### ISSUE TITLE
[BUG]crashes

### ISSUE THREAD

**Issue by master7720** [CCBlueX/LiquidBounce#1044]
### LiquidBounce Build/Version

ba559c1

### Operating System

Linux

### Minecraft Version

1.19.4

### Describe the bug

loading it

### Steps to reproduce

idk

### Client Log

```shell
[23:10:12] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[23:10:13] [main/INFO]: Loading 66 mods:
	- fabric-api 0.80.0+1.19.4
	   |-- fabric-api-base 0.4.25+504944c8f4
	   |-- fabric-api-lookup-api-v1 1.6.26+504944c8f4
	   |-- fabric-biome-api-v1 13.0.8+348a9c64f4
	   |-- fabric-block-api-v1 1.0.7+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.35+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.16+504944c8f4
	   |-- fabric-command-api-v1 1.2.28+f71b366ff4
	   |-- fabric-command-api-v2 2.2.7+504944c8f4
	   |-- fabric-commands-v0 0.2.45+df3654b3f4
	   |-- fabric-containers-v0 0.1.55+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.10+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.2+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.16+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.4.1+504944c8f4
	   |-- fabric-dimensions-v1 2.1.46+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.14+504944c8f4
	   |-- fabric-events-interaction-v0 0.5.0+76ba65ebf4
	   |-- fabric-events-lifecycle-v0 0.2.53+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.34+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.18+504944c8f4
	   |-- fabric-item-group-api-v1 3.0.6+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.34+504944c8f4
	   |-- fabric-keybindings-v0 0.2.32+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.16+504944c8f4
	   |-- fabric-loot-api-v2 1.1.28+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.32+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.2+504944c8f4
	   |-- fabric-mining-level-api-v1 2.1.40+49abcf7ef4
	   |-- fabric-models-v0 0.3.31+504944c8f4
	   |-- fabric-networking-api-v1 1.3.2+504944c8f4
	   |-- fabric-networking-v0 0.3.42+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.4+504944c8f4
	   |-- fabric-particles-v1 1.0.24+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.9+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.2.1+504944c8f4
	   |-- fabric-renderer-api-v1 2.2.6+504944c8f4
	   |-- fabric-renderer-indigo 1.1.2+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.39+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.29+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.22+504944c8f4
	   |-- fabric-rendering-v0 1.1.42+df3654b3f4
	   |-- fabric-rendering-v1 2.1.2+504944c8f4
	   |-- fabric-resource-conditions-api-v1 2.3.2+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.3+1e1fb126f4
	   |-- fabric-screen-api-v1 1.0.46+504944c8f4
	   |-- fabric-screen-handler-api-v1 1.3.21+504944c8f4
	   |-- fabric-sound-api-v1 1.0.10+504944c8f4
	   |-- fabric-transfer-api-v1 3.1.2+504944c8f4
	   \-- fabric-transitive-access-wideners-v1 3.0.4+504944c8f4
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.19.4
[23:10:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/notrocky/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[23:10:13] [main/INFO]: Compatibility level set to JAVA_16
[23:10:13] [main/INFO]: Compatibility level set to JAVA_17
[23:10:13] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[23:10:17] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 74 milliseconds
[23:10:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:10:19] [Render thread/INFO]: Setting user: Master7720
[23:10:19] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[23:10:20] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[23:10:20] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[23:10:20] [Render thread/INFO]: Successfully extracted default theme
[23:10:20] [Render thread/INFO]: Loading heads...
[23:10:22] [Render thread/INFO]: Successfully loaded 956 heads from the database
[23:10:22] [Render thread/INFO]: Found out OpenGL version to be 4.6.
[23:10:22] [Render thread/INFO]: Loading ultralight...
[23:10:22] [Render thread/INFO]: Checking resources...
[23:10:22] [Render thread/INFO]: Loading ultralight natives
[23:10:22] [Render thread/INFO]: Native path: /home/notrocky/.local/share/PrismLauncher/instances/1.19.4(1)/.minecraft/LiquidBounce/ultralight/bin
[23:10:22] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: Can't load library: /home/notrocky/.local/share/PrismLauncher/instances/1.19.4(1)/.minecraft/LiquidBounce/ultralight/bin/libglib-2.0-0.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zlc000$liquidbounce$startClient(class_310.java:6072) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:638) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

### Screenshots

there is none

**Comment by 1zun4secondary** [comment]
Nextgen does not support Linux atm

**Comment by master7720** [comment]
L

**Comment by Aworldc** [comment]
Similar issue - Fedora 38, Gnome 44.3, MultiMC5 0.7.0, Minecraft 1.20.1 with latest LB.
[log.txt](https://github.com/CCBlueX/LiquidBounce/files/12266312/log.txt)

**Comment by ghost** [comment]
> Similar issue - Fedora 38, Gnome 44.3, MultiMC5 0.7.0, Minecraft 1.20.1 with latest LB. [log.txt](https://github.com/CCBlueX/LiquidBounce/files/12266312/log.txt)

Your log shows that it can't locate the `.so` files. Take this with a grain of salt, but try to search and download the requested files and insert them on that directory, which in your case is: `/home/allan/.local/share/applications/MultiMC/instances/1.20 haxed/.minecraft/LiquidBounce/ultralight/bin`.

**Comment by Aworldc** [comment]
> > Similar issue - Fedora 38, Gnome 44.3, MultiMC5 0.7.0, Minecraft 1.20.1 with latest LB. [log.txt](https://github.com/CCBlueX/LiquidBounce/files/12266312/log.txt)
> 
> Your log shows that it can't locate the `.so` files. Take this with a grain of salt, but try to search and download the requested files and insert them on that directory, which in your case is: `/home/allan/.local/share/applications/MultiMC/instances/1.20 haxed/.minecraft/LiquidBounce/ultralight/bin`.

Thank you. Simply needed to `sudo dnf install libpng12`. Works for me now.

Edit: Also needed to do `gsettings set org.gnome.mutter check-alive-timeout 60000` to prevent App not responding dialogs during startup.

**Comment by ghost** [comment]
@master7720 can you also try doing the same? There's a chance yours might work too.

**Comment by master7720** [comment]
> @master7720 can you also try doing the same? There's a chance yours might work too.

yuh it worked fine

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/6602f12d0465f57f8dc2a2f68d39f6840b2b490c
