### ISSUE TITLE
[BUG] Liquidbounce lag on server

### ISSUE THREAD

**Issue by Tsukosky** [CCBlueX/LiquidBounce#1051]
### LiquidBounce Build/Version

b78

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

I take a lot of time to join mini games on servers (like jartex for example), sometimes, especially in bedwars, I get kicked from the server for "unstable connection", "internal server error"  ...

### Steps to reproduce

- go to the jartex server for example
- go to any mini games
- the dirt screen will appear for a long time
- either the game will have started a long time ago when the dirt screen disappears
- either you kicked the server for different reasons

### Client Log

```shell
[14:28:57] [Client thread/INFO]: Applying holder lookups
[14:28:57] [Client thread/INFO]: Holder lookups applied
[14:28:58] [Netty Client IO #3/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:28:58] [Netty Client IO #5/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:29:00] [Netty Client IO #1/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:29:00] [Netty Client IO #0/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:29:00] [Netty Client IO #5/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:29:00] [Netty Client IO #4/INFO]: Attempting connection with missing mods [mcp, FML, Forge, replaymod, custom-crosshair-mod] at SERVER
[14:29:06] [Client thread/INFO]: Connecting to play_jartexnetwork_com.jartex.fun., 25565
[14:29:06] [Netty Epoll Client IO #1/INFO]: Aborting client handshake "VANILLA"
[14:29:06] [Netty Epoll Client IO #1/INFO]: [Netty Epoll Client IO #1] Client side vanilla connection established
[14:29:16] [Client thread/INFO]: [CHAT] LOGIN » Session login
[14:29:17] [Client thread/INFO]: [CHAT] LOGIN » Successful login! Have fun!
[14:29:33] [Client thread/INFO]: [CHAT] ► You have 1 unclaimed Level Reward!
[14:29:33] [Client thread/INFO]: [CHAT] JartexNetwork » You are connected to Lobby3
[14:29:34] [Client thread/INFO]: [CHAT] ➟ Hey! Your email has not been connected!
[14:29:34] [Client thread/INFO]: [CHAT] In order to secure and manage your account you will need to link your email to your account.
[14:29:34] [Client thread/INFO]: [CHAT] To link your email to your account use the /email command
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT]           §fWelcome, §6§lTsuko___§f to §e§lJartex§6§lNetwork
[14:29:34] [Client thread/INFO]: [CHAT]              §fCurrently playing with §e1934 §fplayers!
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT]               §7Click for more JartexNetwork!
[14:29:34] [Client thread/INFO]: [CHAT]           SITE §7▪ STORE §7▪ VOTE §7▪ DISCORD 
[14:29:34] [Client thread/INFO]: [CHAT]                       TWITTER §7▪ INSTA 
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT]           §fPurchase your §branks§f, §6gold§f, and §dmore
[14:29:34] [Client thread/INFO]: [CHAT]                  §fat §estore.jartexnetwork.com
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT] 
[14:29:34] [Client thread/INFO]: [CHAT] Vote ▏ Did you know that you can buy anything from the store by voting?
[14:29:34] [Client thread/INFO]: [CHAT]  ► Vote right now using /vote!
[14:29:34] [Client thread/INFO]: [CHAT]  
[14:29:34] [Client thread/INFO]: [CHAT] 
§e§lJ§6§lN§8 » §a§lJartexNetwork Discord §fClick here to join our discord server to chat with players, read announcements join giveaways § events! §6§njartexnetwork.com/discord

[14:29:34] [Client thread/INFO]: [CHAT] 
§e§lJ§6§lN§8 » §eCheck out our store at §6§nstore.jartexnetwork.com

[14:29:55] [Client thread/INFO]: [CHAT] ► You have 1 unclaimed Level Reward!
[14:29:55] [Client thread/INFO]: [CHAT] JartexNetwork » You are connected to BWLOBBY-k652k-blpt8
[14:29:55] [Client thread/INFO]: [CHAT] ➟ Hey! Your email has not been connected!
[14:29:55] [Client thread/INFO]: [CHAT] In order to secure and manage your account you will need to link your email to your account.
[14:29:55] [Client thread/INFO]: [CHAT] To link your email to your account use the /email command
[14:29:55] [Client thread/INFO]: [CHAT] 
[14:29:55] [Client thread/INFO]: [CHAT] 
[14:29:55] [Client thread/INFO]: [CHAT] Vote ▏ Did you know that you can buy anything from the store by voting?
[14:29:55] [Client thread/INFO]: [CHAT]  ► Vote right now using /vote!
[14:29:55] [Client thread/INFO]: [CHAT]  
[14:30:21] [Client thread/INFO]: [CHAT] ► Bamphodu [15] » aur be chapri
[14:30:34] [Client thread/INFO]: [CHAT] ► Bamphodu [15] » aur be chapri
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ Tsuko___ has joined the game! (7/8)
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ Drexado has joined the game! (8/8)
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 15 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] JartexNetwork » You are connected to BW1-wtn6p-hz6dp
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 10 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 5 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 4 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 3 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 2 seconds.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ The game is going to start in 1 second.
[14:30:59] [Client thread/INFO]: [CHAT] BedWars ❖ You are now in team Aqua.
[14:30:59] [Client thread/INFO]: [CHAT] 
[14:30:59] [Client thread/INFO]: [CHAT]                  --- The game has started! ---
[14:30:59] [Client thread/INFO]: [CHAT]                                GOOD LUCK!
[14:30:59] [Client thread/INFO]: [CHAT] 
[14:30:59] [Client thread/INFO]: [CHAT]         Gather resources from generators on different
[14:30:59] [Client thread/INFO]: [CHAT]           islands to trade them for items and upgrades.
[14:30:59] [Client thread/INFO]: [CHAT]     Break other players' bed, and protect your own to be
[14:30:59] [Client thread/INFO]: [CHAT]                        the last player standing!
[14:30:59] [Client thread/INFO]: [CHAT] 
[14:30:59] [Client thread/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@71bde97b rejected from java.util.concurrent.ThreadPoolExecutor@5cc8705[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 27897]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_202]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_202]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678) ~[?:1.8.0_202]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:204) ~[PacketListener.class:?]
	at com.replaymod.recording.packet.PacketListener.lambda$save$1(PacketListener.java:181) ~[PacketListener.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at net.minecraft.util.Util.func_181617_a(Util.java:19) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:30:59] [Client thread/INFO]: Applying holder lookups
[14:30:59] [Client thread/INFO]: Holder lookups applied
[14:30:59] [Client thread/WARN]: Mixin liquidbounce.forge.mixins.json:gui.MixinGuiButtonExt has multiple constructors, (IIILjava/lang/String;)V was selected
```

**Comment by Tsukosky** [comment]
I specify that sometimes liquidbounce works perfectly without problems, often when I restart my game or my pc etc ... but after a while the bug comes back
