### ISSUE TITLE
[BUG] Client don't starting from Intelij IDEA

### ISSUE THREAD

**Issue by Auerd** [CCBlueX/LiquidBounce#1073]
### LiquidBounce Build/Version

b78

### Operating System

Windows 10

### Minecraft Version

1.19.4

### Describe the bug

When I am trying to run client, the open animation stops on the logo. I think it caused by the missed files in `run`  folder (check log)

### Steps to reproduce

Copy repository by git
In project folder open shell and put `./gradlew genSources`
In IDE open project by selecting `build.gradle`
Build and run `Minecraft Client`

### Client Log

```shell
"D:\Program Files\Eclipse Adoptium\java17.0.7+7\bin\java.exe" -Dfabric.dli.config=D:\Programming\ModsForMinecraftJava\LiquidBounce\.gradle\loom-cache\launch.cfg -Dfabric.dli.env=client -Dfabric.dli.main=net.fabricmc.loader.impl.launch.knot.KnotClient "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\lib\idea_rt.jar=49313:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\bin" -Dfile.encoding=UTF-8 @C:\Users\admin\AppData\Local\Temp\idea_arg_file65285743 net.fabricmc.devlaunchinjector.Main
[18:30:38] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[18:30:39] [main/WARN] (FabricLoader/Resolution) Warnings were found!
 - Mod 'ViaVersion' (viaversion) 4.7.0-23w18a-SNAPSHOT recommends version 0.3.99 or later of viafabric, which is missing!
	 - You should install version 0.3.99 or later of viafabric for the optimal experience.
[18:30:39] [main/INFO] (FabricLoader) Loading 52 mods:
	- fabric-api 0.79.0+1.19.4
	- fabric-api-base 0.4.24+9ff28bcef4
	- fabric-api-lookup-api-v1 1.6.25+49abcf7ef4
	- fabric-biome-api-v1 13.0.7+348a9c64f4
	- fabric-block-api-v1 1.0.6+e022e5d1f4
	- fabric-blockrenderlayer-v1 1.1.34+c2e6f674f4
	- fabric-client-tags-api-v1 1.0.15+1134c5b8f4
	- fabric-command-api-v2 2.2.6+e719b857f4
	- fabric-content-registries-v0 3.5.9+ae0966baf4
	- fabric-convention-tags-v1 1.4.1+9a7c5daaf4
	- fabric-crash-report-info-v1 0.2.15+aeb40ebef4
	- fabric-data-generation-api-v1 11.4.0+6cebf059f4
	- fabric-dimensions-v1 2.1.45+7f87f8faf4
	- fabric-entity-events-v1 1.5.13+e45f7c65f4
	- fabric-events-interaction-v0 0.4.43+a1ccd7bff4
	- fabric-game-rule-api-v1 1.0.33+a1ccd7bff4
	- fabric-gametest-api-v1 1.2.4+ae0966baf4
	- fabric-item-api-v1 2.1.17+09a3510cf4
	- fabric-item-group-api-v1 3.0.5+043f9acff4
	- fabric-key-binding-api-v1 1.0.33+c477957ef4
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	- fabric-lifecycle-events-v1 2.2.15+5da15ca1f4
	- fabric-loot-api-v2 1.1.27+75e98211f4
	- fabric-message-api-v1 5.1.1+1ee8be40f4
	- fabric-mining-level-api-v1 2.1.39+49abcf7ef4
	- fabric-models-v0 0.3.30+11ba9c3bf4
	- fabric-networking-api-v1 1.3.1+a6f3ccfaf4
	- fabric-object-builder-api-v1 7.0.3+63b515f4f4
	- fabric-particles-v1 1.0.23+f1e4495bf4
	- fabric-recipe-api-v1 1.0.8+a1ccd7bff4
	- fabric-registry-sync-v0 2.2.0+670e8ac6f4
	- fabric-renderer-api-v1 2.2.5+81e8c576f4
	- fabric-renderer-indigo 1.1.1+81e8c576f4
	- fabric-rendering-data-attachment-v1 0.3.28+afca2f3ef4
	- fabric-rendering-fluids-v1 3.0.21+f1e4495bf4
	- fabric-rendering-v1 2.1.1+8f878217f4
	- fabric-resource-conditions-api-v1 2.3.1+e6c7d4eef4
	- fabric-resource-loader-v0 0.11.2+1e1fb126f4
	- fabric-screen-api-v1 1.0.45+8c25edb4f4
	- fabric-screen-handler-api-v1 1.3.20+5da15ca1f4
	- fabric-sound-api-v1 1.0.9+75e98211f4
	- fabric-transfer-api-v1 3.1.1+da9bb835f4
	- fabric-transitive-access-wideners-v1 3.0.3+63b515f4f4
	- fabricloader 0.14.19
	- java 17
	- liquidbounce 1.0.0
	- lithium 0.11.1-SNAPSHOT
	- mctester 0.3.3
	- minecraft 1.19.4
	- modmenu 6.2.1
	- sodium 0.4.10+rev.360da2c-dirty
	- viaversion 4.7.0-23w18a-SNAPSHOT
[18:30:39] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/admin/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/e13b4069fe3555969811d4474f78576c707bbe1c/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:30:39] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[18:30:39] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[18:30:40] [main/INFO] (Sodium) Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[18:30:40] [main/INFO] (Lithium) Loaded configuration file for Lithium: 114 options available, 0 override(s) found
[18:30:41] [main/INFO] (McTesterConfig) Loading default config...
[18:30:49] [Datafixer Bootstrap/INFO] (Minecraft) 180 Datafixer optimizations took 235 milliseconds
[18:30:52] [Render thread/INFO] (Sodium) Launching a new process to probe the system configuration!
[18:30:52] [Render thread/INFO] (Sodium) OpenGL Vendor: NVIDIA Corporation
[18:30:52] [Render thread/INFO] (Sodium) OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
[18:30:52] [Render thread/INFO] (Sodium) OpenGL Version: 3.3.0 NVIDIA 512.15
[18:30:52] [Render thread/WARN] (Sodium) Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[18:30:52] [Render thread/WARN] (Sodium) One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[18:30:53] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:30:53] [Render thread/ERROR] (Minecraft) Failed to verify authentication
 com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.18.38.jar:?]
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient.java:712) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:506) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[minecraft-merged-project-root-1.19.4-net.fabricmc.yarn.1_19_4.1.19.4+build.2-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.18.38.jar:?]
	... 9 more
[18:30:53] [Render thread/INFO] (Minecraft) Setting user: Player648
[18:30:54] [Render thread/INFO] (Indigo) [Indigo] Different rendering plugin detected; not applying Indigo.
[18:30:54] [Worker-Main-1/INFO] (Mod Menu/Update Checker) Checking mod updates...
[18:30:54] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.3.1 SNAPSHOT
[18:30:55] [Render thread/WARN] (FabricLoader/Mixin) Static binding violation: PRIVATE @Overwrite method renderBakedItemModel in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[18:30:56] [Render thread/INFO] (LiquidBounce) Launching LiquidBounce v1.0.0 by CCBlueX
[18:30:57] [Render thread/INFO] (LiquidBounce) Successfully extracted default theme
[18:30:57] [Render thread/INFO] (LiquidBounce) Loading heads...
[18:30:59] [Render thread/INFO] (LiquidBounce) Successfully loaded 956 heads from the database
[18:31:02] [Render thread/INFO] (LiquidBounce) Found out OpenGL version to be 3.3.0.
[18:31:02] [Render thread/INFO] (LiquidBounce) Loading ultralight...
[18:31:02] [Render thread/INFO] (LiquidBounce) Checking resources...
[18:31:02] [Render thread/INFO] (LiquidBounce) Loading ultralight natives
[18:31:02] [Render thread/INFO] (LiquidBounce) Native path: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\ultralight\bin
[18:31:03] [Render thread/INFO] (LiquidBounce) Setting up ultralight renderer
[18:31:03] [Render thread/INFO] (LiquidBounce) [Ul] Initializing Ultralight v1.3.0 with the following configuration
    cache_path: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\ultralight\cache
    face_winding: CounterClockwise
    font_hinting: Smooth
    font_gamma: 1.8
    force_repaint: 0
    animation_timer_delay: 0.0166667
    scroll_timer_delay: 0.0166667
    recycle_delay: 4
    memory_cache_size: 64.00 MB
    page_cache_size: 0
    override_ram_size: disabled
    min_large_heap_size: 32.00 MB
    min_small_heap_size: 1.00 MB

[18:31:03] [Render thread/INFO] (LiquidBounce) [Ul] Creating Session with the following configuration:
    id: 2
    is_persistent: 1
    name: default
    is_default: 1
    disk_path: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\ultralight\cache\default (you can adjust this location in Config::cache_path)
[18:31:04] [Render thread/INFO] (LiquidBounce) [Ul] Memory Usage (WebCore): 
    JavaScript:          64.00 KB

[18:31:04] [Render thread/INFO] (LiquidBounce) [Ul] Memory Usage (UltralightCore): 
    Texture Store:        0.00 B, VRAM: 0.00 B
    Render Texture Store: 0.00 B, VRAM: 0.00 B
    Geometry Store:       0.00 B, VRAM: 0.00 B
    Texture Cache:        0.00 B
    Image Cache:          0.00 B
    Path Cache:           0.00 B
    Font Cache:           8.00 B
    Paint Pool:           6.25 KB
    Render Texture Pool:  0.00 B
    Texture Pool:         0.00 B
    Geometry Pool:        0.00 B
    Path Tesselator:      8.00 B

[18:31:04] [Render thread/INFO] (LiquidBounce) Successfully loaded ultralight!
[18:31:05] [Render thread/INFO] (LiquidBounce) [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'enemies'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'modules'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'commands'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'friends'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'proxies'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'chat'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'fonts'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded config 'storage'.
[18:31:06] [Render thread/INFO] (LiquidBounce) Successfully loaded client!
[18:31:06] [IO-Worker-3/INFO] (LiquidBounce) Connecting to LiquidChat...
[18:31:06] [Render thread/INFO] (Minecraft) Reloading ResourceManager: vanilla, Fabric Mods (Fabric Sound API (v1), Fabric Language Kotlin, Fabric Message API (v1), Fabric Registry Sync (v0), MC Tester Mod, Fabric Dimensions API (v1), Fabric Screen Handler API (v1), Fabric Networking API (v1), Fabric Convention Tags, Fabric Key Binding API (v1), Fabric Data Generation API (v1), Fabric Rendering Fluids (v1), Fabric Game Rule API (v1), Fabric Models (v0), Fabric Command API (v2), Fabric Biome API (v1), Sodium, Fabric API Base, Fabric Loader, ViaVersion, Fabric Rendering (v1), Fabric Renderer API (v1), Fabric Lifecycle Events (v1), Fabric API Lookup API (v1), Fabric Block API (v1), Fabric Object Builder API (v1), Fabric Screen API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Crash Report Info (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Resource Conditions API (v1), Fabric API, Fabric Events Interaction (v0), Fabric Item Group API (v1), Fabric Loot API (v2), Fabric Entity Events (v1), LiquidBounce, Lithium, Fabric Mining Level API (v1), Fabric Client Tags, Fabric Game Test API (v1), Fabric Rendering Data Attachment (v1), Fabric Recipe API (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Mod Menu, Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Particles (v1))
[18:31:06] [Render thread/INFO] (LiquidBounce) [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[18:31:06] [Render thread/INFO] (LiquidBounce) [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[18:31:07] [Thread-25/ERROR] (LiquidBounce) [ERROR/FileSystem] Exception while opening D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/hud/build/bundle.css
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: java.nio.file.NoSuchFileException: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\themes\default\hud\build\bundle.css
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[18:31:07] [Thread-25/INFO] (Minecraft) [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
[18:31:07] [Thread-26/ERROR] (LiquidBounce) [ERROR/FileSystem] Exception while opening D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/hud/build/bundle.js
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: java.nio.file.NoSuchFileException: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\themes\default\hud\build\bundle.js
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[18:31:07] [Thread-26/INFO] (Minecraft) [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
[18:31:08] [Thread-32/ERROR] (LiquidBounce) [ERROR/FileSystem] Exception while opening D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/title/build/bundle.css
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: java.nio.file.NoSuchFileException: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\themes\default\title\build\bundle.css
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[18:31:08] [Thread-32/INFO] (Minecraft) [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
[18:31:08] [IO-Worker-3/INFO] (LiquidBounce) Successfully connected to LiquidChat!
[18:31:08] [Thread-33/ERROR] (LiquidBounce) [ERROR/FileSystem] Exception while opening D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/title/build/bundle.js
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: java.nio.file.NoSuchFileException: D:\Programming\ModsForMinecraftJava\LiquidBounce\run\LiquidBounce\themes\default\title\build\bundle.js
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[18:31:08] [Thread-33/INFO] (Minecraft) [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
[18:31:08] [IO-Worker-3/INFO] (LiquidBounce) Requesting to login into Mojang...
[18:31:08] [nioEventLoopGroup-2-1/ERROR] (LiquidBounce) LiquidChat error
 com.mojang.authlib.exceptions.InvalidCredentialsException: null
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:122) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:106) ~[authlib-3.18.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(YggdrasilMinecraftSessionService.java:72) ~[authlib-3.18.38.jar:?]
	at net.ccbluex.liquidbounce.features.chat.Chat.onPacket$liquidbounce(Chat.kt:240) ~[main/:?]
	at net.ccbluex.liquidbounce.features.chat.client.Client.onMessage$liquidbounce(Client.kt:147) ~[main/:?]
	at net.ccbluex.liquidbounce.features.chat.client.ChannelHandler.channelRead0(ChannelHandler.kt:103) ~[main/:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:31:09] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:item.brush.brushing
[18:31:09] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:item.brush.brush_sand_completed
[18:31:09] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:item.goat_horn.play
[18:31:09] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:31:09] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:music.overworld.cherry_grove
[18:31:09] [Render thread/INFO] (Minecraft) OpenAL initialized on device OpenAL Soft on Динамики (Realtek High Definition Audio)
[18:31:09] [Render thread/INFO] (Minecraft) Sound engine started
[18:31:09] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 64x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:31:09] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:31:10] [Render thread/WARN] (Minecraft) Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:31:10] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:31:10] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:31:10] [Render thread/INFO] (Minecraft) Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:31:14] [Render thread/INFO] (LiquidBounce) [MainFrame 3 (file:///D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[18:31:14] [Render thread/INFO] (LiquidBounce) [MainFrame 5 (file:///D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[18:31:14] [Render thread/INFO] (LiquidBounce) [MainFrame 1 (file:///D:/Programming/ModsForMinecraftJava/LiquidBounce/run/LiquidBounce/themes/default/hud/index.html)]: The view finished loading


[18:32:55] [Render thread/INFO] (LiquidBounce) Shutting down client...
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'enemies'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'modules'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'commands'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'friends'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'proxies'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'chat'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'fonts'.
[18:32:55] [Render thread/INFO] (LiquidBounce) Successfully saved config 'storage'.
[18:32:55] [Render thread/INFO] (Minecraft) Stopping!

Process finished with exit code 0
```

### Screenshots

![](https://github.com/CCBlueX/LiquidBounce/assets/81168821/d04a9930-8fd0-42c1-b5d4-8b32d9bbb413)

**Comment by 1zun4secondary** [comment]
Read the requirements:
https://github.com/CCBlueX/LiquidBounce#setting-up-a-workspace
