### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pkcuti** [CCBlueX/LiquidBounce#1092]
### LiquidBounce Build/Version

liquidbounce-fe313ad (I'm sorry, idk which version it is.

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Describe the bug

When I run it, it shows up and then crashes without even accessing the menu.

### Steps to reproduce

Add hack and run the game.

### Client Log

```shell
Picked up _JAVA_OPTIONS: 
[09:59:21] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.21
[09:59:21] [main/INFO]: Loading 58 mods:
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabric-language-kotlin 1.6.3+kotlin.1.5.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.5.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.5.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.21
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.2.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.2.2
	- fabricloader 0.14.21
	- java 16
	- liquidbounce 1.0.0
	- minecraft 1.16.5
[09:59:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/trann/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:59:37] [main/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[09:59:37] [main/INFO]: Setting user: ELisa
[09:59:38] [main/INFO]: [Indigo] Registering Indigo renderer!
[09:59:38] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[09:59:43] [main/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\trann\AppData\Roaming\.tlauncher\legacy\Minecraft\game\.fabric\remappedJars\minecraft-1.16.5-0.14.21\client-intermediary.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[client-intermediary.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.args$zhj000$liquidbounce$setupIcon(class_310.java:5979) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:466) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
[09:59:47] [main/INFO]: Narrator library for x64 successfully loaded
[09:59:47] [main/INFO]: Reloading ResourceManager: Default, pack 1.4.7.zip, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, LiquidBounce)
[09:59:47] [main/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[09:59:48] [main/INFO]: Successfully extracted default theme
[09:59:48] [main/INFO]: Loading heads...
[09:59:49] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[09:59:50] [Worker-Main-8/WARN]: Texture minecraft:item/misc/gottem with size 392x279 limits mip level from 4 to 0
[09:59:50] [Worker-Main-8/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
[09:59:51] [main/INFO]: Successfully loaded 956 heads from the database
[09:59:51] [main/INFO]: Downloading v0.41 natives... (os: win)
[09:59:51] [main/ERROR]: Unable to download natives
java.io.FileNotFoundException: https://cloud.liquidbounce.net/LiquidBounce/natives/0.41/win-x64.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at net.ccbluex.liquidbounce.utils.HttpUtils.download(HttpUtils.java:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.native.Natives.downloadNatives(Natives.java:59) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:84) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:63) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:104) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zhj000$liquidbounce$startClient(class_310.java:5921) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:592) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
```

### Screenshots

![353586818_244123518358297_104195249645176153_n](https://github.com/CCBlueX/LiquidBounce/assets/134672059/f9fe4b52-6a9e-4d92-bb8d-22ce9f33deb5)
<img width="534" alt="583d7bd3-9288-4cf1-a8b7-ecbe0b4b7926" src="https://github.com/CCBlueX/LiquidBounce/assets/134672059/d32e4e77-424c-441a-9ade-f8cd4c166fff">

**Comment by CzechHek** [comment]
1. why 1.16.5
2. why tlauncher

**Comment by 1zun4** [comment]
bruh

**Comment by be4dev** [comment]
> ### LiquidBounce Build/Version
> 
> liquidbounce-fe313ad (I'm sorry, idk which version it is.
> ### Operating System
> 
> Windows 11
> ### Minecraft Version
> 
> 1.16.5
> ### Describe the bug
> 
> When I run it, it shows up and then crashes without even accessing the menu.
> ### Steps to reproduce
> 
> Add hack and run the game.
> ### Client Log
> 
> ```shell
> Picked up _JAVA_OPTIONS: 
> [09:59:21] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.21
> [09:59:21] [main/INFO]: Loading 58 mods:
> 	- fabric 0.42.0+1.16
> 	   |-- fabric-api-base 0.4.0+3cc0f0907d
> 	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
> 	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
> 	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
> 	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
> 	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
> 	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
> 	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
> 	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
> 	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
> 	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
> 	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
> 	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
> 	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
> 	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
> 	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
> 	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
> 	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
> 	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
> 	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
> 	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
> 	   |-- fabric-models-v0 0.3.1+3cc0f0907d
> 	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
> 	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
> 	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
> 	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
> 	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
> 	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
> 	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
> 	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
> 	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
> 	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
> 	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
> 	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
> 	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
> 	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
> 	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
> 	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
> 	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
> 	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
> 	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
> 	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
> 	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
> 	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
> 	- fabric-language-kotlin 1.6.3+kotlin.1.5.21
> 	   |-- org_jetbrains_kotlin_kotlin-reflect 1.5.21
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.5.21
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.21
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.21
> 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.1
> 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.1
> 	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.2.2
> 	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.2.2
> 	- fabricloader 0.14.21
> 	- java 16
> 	- liquidbounce 1.0.0
> 	- minecraft 1.16.5
> [09:59:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/trann/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [09:59:37] [main/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
> [09:59:37] [main/INFO]: Setting user: ELisa
> [09:59:38] [main/INFO]: [Indigo] Registering Indigo renderer!
> [09:59:38] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
> [09:59:43] [main/ERROR]: Unable to load client icons.
> net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\trann\AppData\Roaming\.tlauncher\legacy\Minecraft\game\.fabric\remappedJars\minecraft-1.16.5-0.14.21\client-intermediary.jar'
> 	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1065.method_14416(class_1065.java:35) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3268.method_14405(class_3268.java:85) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.args$zhj000$liquidbounce$setupIcon(class_310.java:5979) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:466) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
> [09:59:47] [main/INFO]: Narrator library for x64 successfully loaded
> [09:59:47] [main/INFO]: Reloading ResourceManager: Default, pack 1.4.7.zip, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, LiquidBounce)
> [09:59:47] [main/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
> [09:59:48] [main/INFO]: Successfully extracted default theme
> [09:59:48] [main/INFO]: Loading heads...
> [09:59:49] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
> [09:59:50] [Worker-Main-8/WARN]: Texture minecraft:item/misc/gottem with size 392x279 limits mip level from 4 to 0
> [09:59:50] [Worker-Main-8/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
> [09:59:51] [main/INFO]: Successfully loaded 956 heads from the database
> [09:59:51] [main/INFO]: Downloading v0.41 natives... (os: win)
> [09:59:51] [main/ERROR]: Unable to download natives
> java.io.FileNotFoundException: https://cloud.liquidbounce.net/LiquidBounce/natives/0.41/win-x64.zip
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981) ~[?:?]
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
> 	at net.ccbluex.liquidbounce.utils.HttpUtils.download(HttpUtils.java:64) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.native.Natives.downloadNatives(Natives.java:59) [liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:84) [liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:63) [liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:104) [liquidbounce.jar:?]
> 	at net.minecraft.class_310.handler$zhj000$liquidbounce$startClient(class_310.java:5921) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:592) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
> ```
> 
> ### Screenshots
> 
> ![353586818_244123518358297_104195249645176153_n](https://user-images.githubusercontent.com/134672059/244909489-f9fe4b52-6a9e-4d92-bb8d-22ce9f33deb5.png) <img alt="583d7bd3-9288-4cf1-a8b7-ecbe0b4b7926" width="534" src="https://user-images.githubusercontent.com/134672059/244909517-d32e4e77-424c-441a-9ade-f8cd4c166fff.png">

could you test with latest version?

**Comment by ghost** [comment]
A version way too old. If this actually still happens make a new issue.
