### ISSUE TITLE
[BUG] Crashes at launch

### ISSUE THREAD

**Issue by EnchantPlus** [CCBlueX/LiquidBounce#1131]
### LiquidBounce Build/Version

Nextgen latest build of the commit 32709e2

### Operating System

Windows 7

### Minecraft Version

1.20.1

### Describe the bug

Just launched for the first time and crashed

### Steps to reproduce

I tried launching from multimc and sklauncher
Crashes at launch
mods i have:
sodium-fabric-mc1.20-0.4.10+build.27.jar
fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
fabric-api-0.84.0+1.20.1.jar
liquidbounce.jar

The window stays open for like 5 seconds

### Client Log

```shell
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [15.235.51.175]

session.minecraft.net resolves to:
    [13.107.246.48, 13.107.213.48]

textures.minecraft.net resolves to:
    [13.107.246.48, 13.107.213.48]

api.mojang.com resolves to:
    [13.107.246.48, 13.107.213.48]


Minecraft folder is:
C:/Programs/UltimMC/instances/LB NEXT/.minecraft


Java path is:
C:/Program Files/Java/jdk-20/bin/javaw.exe


Checking Java version...
Java is version 20, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Programs/UltimMC/instances/LB NEXT/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Programs/UltimMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Programs/UltimMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Programs/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Programs/UltimMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Programs/UltimMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Programs/UltimMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Programs/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Programs/UltimMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Programs/UltimMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Programs/UltimMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Programs/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Programs/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Programs/UltimMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Programs/UltimMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Programs/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Programs/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Programs/UltimMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Programs/UltimMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Programs/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Programs/UltimMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Programs/UltimMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Programs/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Programs/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Programs/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Programs/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Programs/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Programs/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Programs/UltimMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Programs/UltimMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Programs/UltimMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Programs/UltimMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Programs/UltimMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Programs/UltimMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Programs/UltimMC/libraries/net/fabricmc/fabric-loader/0.14.21/fabric-loader-0.14.21.jar
  C:/Programs/UltimMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Programs/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] fabric-api-0.84.0+1.20.1.jar
  [✔️] fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
  [✔️] liquidbounce.jar
  [✔️] sodium-fabric-mc1.20-0.4.10+build.27.jar

Params:
  --username  --version 1.20.1 --gameDir C:/Programs/UltimMC/instances/LB NEXT/.minecraft --assetsDir C:/Programs/UltimMC/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 640 x 400

Java Arguments:
[-javaagent:C:/Programs/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:50957, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 2212


[authlib-injector] [INFO] Logging file: C:\Programs\UltimMC\instances\LB NEXT\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: http://localhost:50957
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[12:43:31] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[12:43:31] [main/INFO]: Loading 67 mods:
	- fabric-api 0.84.0+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.1.0+c154966e77
	   |-- fabric-renderer-indigo 1.4.0+c154966e77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabric-language-kotlin 1.9.6+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- java 20
	- liquidbounce 1.0.0
	- minecraft 1.20.1
	- sodium 0.4.10+build.27
[12:43:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Programs/UltimMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:43:32] [main/INFO]: Compatibility level set to JAVA_16
[12:43:32] [main/INFO]: Compatibility level set to JAVA_17
[12:43:32] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 0 override(s) found
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[12:43:54] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 1017 milliseconds
[12:43:57] [main/WARN]: Unrecognized user type: Local
[12:43:57] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[12:43:57] [Render thread/INFO]: Launching a new process to probe the system configuration!
[12:43:58] [Render thread/INFO]: OpenGL Vendor: VMware, Inc.
[12:43:58] [Render thread/INFO]: OpenGL Renderer: llvmpipe (LLVM 8.0, 128 bits)
[12:43:58] [Render thread/INFO]: OpenGL Version: 3.3 (Core Profile) Mesa 20.1.8
[authlib-injector] [INFO] Httpd is running on port 51079
[authlib-injector] [INFO] Transformed [net.minecraft.class_742] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[12:43:59] [Render thread/INFO]: Environment: authHost='http://localhost:50957/authserver', accountsHost='http://127.0.0.1:51079/https/api.mojang.com', sessionHost='http://127.0.0.1:51079/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:51079/https/api.minecraftservices.com', name='PROD'
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo] with [Yggdrasil Public Key Transformer]
[12:43:59] [Render thread/INFO]: Setting user: <ACCESS TOKEN>
[authlib-injector] [INFO] Transformed [net.minecraft.class_3248] with [Username Character Check Transformer]
[12:43:59] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[12:44:00] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[12:44:01] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[12:44:02] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[12:44:04] [Render thread/INFO]: Successfully extracted default theme
[12:44:04] [Render thread/INFO]: Loading heads...
[12:44:07] [Render thread/INFO]: Successfully loaded 956 heads from the database
[12:44:08] [Render thread/INFO]: Found out OpenGL version to be 3.3.
[12:44:08] [Render thread/INFO]: Loading ultralight...
[12:44:08] [Render thread/INFO]: Checking resources...
[12:44:08] [Render thread/INFO]: Loading ultralight natives
[12:44:08] [Render thread/INFO]: Native path: C:\Programs\UltimMC\instances\LB NEXT\.minecraft\LiquidBounce\ultralight\bin
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[12:44:08] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: C:\Programs\UltimMC\instances\LB NEXT\.minecraft\LiquidBounce\ultralight\bin\gstreamer-full-1.0.dll: Can't find dependent libraries
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:817) ~[?:?]
	at java.lang.System.load(System.java:2015) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:145) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:139) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zml000$liquidbounce$startClient(class_310.java:7077) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 29 Jun 2023 12:44:32 +0530
```

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
