### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by uurcan7** [CCBlueX/LiquidBounce#1161]
### LiquidBounce Build/Version

b80

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

crash

### Steps to reproduce

just start the game

### Client Log

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (LiquidBounce.jar)
  FMLLoadingPlugin (MemoryFix.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 20.07.2023 22:29
Description: Initializing game

java.lang.ExceptionInInitializerError
	at net.minecraft.client.renderer.texture.AbstractTexture.func_110552_b(AbstractTexture.java:63)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:26)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:14)
	at net.ccbluex.liquidbounce.utils.ImageBackground.initBackground(Background.kt:50)
	at net.ccbluex.liquidbounce.utils.Background$Companion.createBackground(Background.kt:32)
	at net.ccbluex.liquidbounce.file.FileManager.loadBackground(FileManager.kt:164)
	at net.ccbluex.liquidbounce.file.FileManager.<clinit>(FileManager.kt:47)
	at net.ccbluex.liquidbounce.LiquidBounce.<clinit>(LiquidBounce.kt:71)
	at net.minecraft.client.Minecraft.handler$createDisplay$zzf000(Minecraft.java:3220)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:556)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:408)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
	at net.minecraft.client.renderer.GlStateManager.func_179146_y(GlStateManager.java:450)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110996_a(TextureUtil.java:37)
	at net.minecraft.client.renderer.texture.AbstractTexture.func_110552_b(AbstractTexture.java:63)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:26)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:27)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.AbstractTexture.func_110552_b(AbstractTexture.java:63)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:26)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:14)
	at net.ccbluex.liquidbounce.utils.ImageBackground.initBackground(Background.kt:50)
	at net.ccbluex.liquidbounce.utils.Background$Companion.createBackground(Background.kt:32)
	at net.ccbluex.liquidbounce.file.FileManager.loadBackground(FileManager.kt:164)
	at net.ccbluex.liquidbounce.file.FileManager.<clinit>(FileManager.kt:47)
	at net.ccbluex.liquidbounce.LiquidBounce.<clinit>(LiquidBounce.kt:71)
	at net.minecraft.client.Minecraft.handler$createDisplay$zzf000(Minecraft.java:3220)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:556)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:408)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_372, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1447732872 bytes (1380 MB) / 1946157056 bytes (1856 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5105M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MixinLoader (LiquidBounce.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
FMLLoadingPlugin (MemoryFix.jar)
  io.prplz.memoryfix.ClassTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 4
```

**Comment by ghost** [comment]
@uurcan7 Try again with the latest versions. Tell us if it still happens.
