### ISSUE TITLE
[BUG] Grim config issue

### ISSUE THREAD

**Issue by Goofydoggo** [CCBlueX/LiquidBounce#1342]
### LiquidBounce Build/Version

b83

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

I was loading up the client and logged onto a server then i did .config load grim it was weirds it didnt show any press tab to automatically then when i did click enter it showed this : 
![Screenshot 2023-09-19 175801](https://github.com/CCBlueX/LiquidBounce/assets/145468647/c5ea6a5f-3b37-401f-ba4b-6956fe1f36c9)

and this:
![image](https://github.com/CCBlueX/LiquidBounce/assets/145468647/ff785489-362c-42f6-9920-eb6a660d825b)

### Steps to reproduce

[18:00:16] [Thread-74/ERROR]: Failed to load settings
java.io.IOException: Server returned HTTP response code: 500 for URL: https://api.liquidbounce.net/api/v1/client/legacy/settings/grim
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_382]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[?:1.8.0_382]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_382]
	at net.ccbluex.liquidboun
ce.utils.misc.HttpUtils.requestStream(HttpUtils.kt:76) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.request(HttpUtils.kt:55) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.textEndpointRequest(ClientApi.kt:95) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.requestSettingsScript(ClientApi.kt:36) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.requestSettingsScript$default(ClientApi.kt:36) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.features.command.commands.AutoSettingsCommand$execute$1.invoke(AutoSettingsCommand.kt:52) [AutoSettingsCommand$execute$1.class:?]
	at net.ccbluex.liquidbounce.features.command.commands.AutoSettingsCommand$execute$1.invoke(AutoSettingsCommand.kt:44) [AutoSettingsCommand$execute$1.class:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [ThreadsKt$thread$t

### Client Log

```shell
[18:00:16] [Thread-74/ERROR]: Failed to load settings
java.io.IOException: Server returned HTTP response code: 500 for URL: https://api.liquidbounce.net/api/v1/client/legacy/settings/grim
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_382]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_382]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[?:1.8.0_382]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_382]
	at net.ccbluex.liquidboun
ce.utils.misc.HttpUtils.requestStream(HttpUtils.kt:76) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.request(HttpUtils.kt:55) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.textEndpointRequest(ClientApi.kt:95) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.requestSettingsScript(ClientApi.kt:36) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.api.ClientApi.requestSettingsScript$default(ClientApi.kt:36) ~[ClientApi.class:?]
	at net.ccbluex.liquidbounce.features.command.commands.AutoSettingsCommand$execute$1.invoke(AutoSettingsCommand.kt:52) [AutoSettingsCommand$execute$1.class:?]
	at net.ccbluex.liquidbounce.features.command.commands.AutoSettingsCommand$execute$1.invoke(AutoSettingsCommand.kt:44) [AutoSettingsCommand$execute$1.class:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [ThreadsKt$thread$t
```

### Screenshots

![Screenshot 2023-09-19 175801](https://github.com/CCBlueX/LiquidBounce/assets/145468647/cb415547-5d20-439b-9ec0-91c2e7904d67)

**Comment by 1zun4** [comment]
Fixed.

**Comment by Goofydoggo** [comment]
Ty the bug was fixed thank for anyone who read the post
