### ISSUE TITLE
[BUG] NEXTGEN'S RESOURCES IS BROKEN (resource.zip) 

### ISSUE THREAD

**Issue by XiaoGanCN** [CCBlueX/LiquidBounce#1376]
### LiquidBounce Build/Version

nextgen 27a2ba7

### Operating System

macOS

### Minecraft Version

1.20.1

### Describe the bug

I'm using a 3rd-party launcher, when I launch the game and the mod will download a .zip file but there are **few file broken**_(see picture below, file size is 0 byte)_ and **libglib-2.0-0.dylib** is **missing**

### Steps to reproduce

see above

### Client Log

```shell
[22:13:24] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[22:13:25] [main/INFO]: Loading 68 mods:
	- fabric-api 0.89.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.0+0883a8d477
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.22
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.20.1
[22:13:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/ganyong/Desktop/liquid%20bounce/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:13:25] [main/INFO]: Compatibility level set to JAVA_16
[22:13:25] [main/INFO]: Compatibility level set to JAVA_17
[22:13:25] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[22:13:30] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 116 milliseconds
[22:13:31] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:13:32] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:733) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 8 more
[22:13:32] [Render thread/INFO]: Setting user: bruh
[22:13:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[22:13:32] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[22:13:33] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[22:13:35] [Render thread/INFO]: Successfully extracted default theme
[22:13:35] [Render thread/INFO]: Loading heads...
[22:13:39] [Render thread/INFO]: Successfully loaded 956 heads from the database
[22:13:39] [Render thread/INFO]: Downloading required font Roboto-Medium.ttf...
[22:13:40] [Render thread/INFO]: Downloading required font Roboto-Bold.ttf...
[22:13:41] [Render thread/INFO]: Found out OpenGL version to be 4.1.
[22:13:41] [Render thread/INFO]: Loading ultralight...
[22:13:41] [Render thread/INFO]: Checking resources...
[22:13:41] [Render thread/INFO]: Downloading vb8daecd_0.4.12 resources... (os: mac)
[22:14:47] [Render thread/INFO]: Extracting resources...
[22:14:48] [Render thread/INFO]: Successfully loaded resources.
[22:14:48] [Render thread/INFO]: Loading ultralight natives
[22:14:48] [Render thread/INFO]: Native path: /Users/ganyong/Desktop/liquid bounce/LiquidBounce/ultralight/bin
[22:14:48] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: Can't load library: /Users/ganyong/Desktop/liquid bounce/LiquidBounce/ultralight/bin/libglib-2.0-0.dylib
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:126) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:88) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:140) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zll000$liquidbounce$startClient(class_310.java:6087) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

### Screenshots

<img width="1225" alt="截屏2023-09-29 23 15 49" src="https://github.com/CCBlueX/LiquidBounce/assets/76635216/8035da5b-0cb2-4ef2-b3fb-dcc4ab95413c">

### I need a non-broken file, thanks.

**Comment by be4dev** [comment]
> ### LiquidBounce Build/Version
> 
> nextgen [27a2ba7](https://github.com/CCBlueX/LiquidBounce/commit/27a2ba73b16216b0378e950414182d6cde8e9fa3)
> ### Operating System
> 
> macOS
> ### Minecraft Version
> 
> 1.20.1
> ### Describe the bug
> 
> I'm using a 3rd-party launcher, when I launch the game and the mod will download a .zip file but there are **few file broken**_(see picture below, file size is 0 byte)_ and **libglib-2.0-0.dylib** is **missing**
> ### Steps to reproduce
> 
> see above
> ### Client Log
> 
> ```shell
> [22:13:24] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
> [22:13:25] [main/INFO]: Loading 68 mods:
> 	- fabric-api 0.89.0+1.20.1
> 	   |-- fabric-api-base 0.4.30+7abfd51577
> 	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
> 	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
> 	   |-- fabric-block-api-v1 1.0.10+92a0d36777
> 	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
> 	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
> 	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
> 	   |-- fabric-command-api-v1 1.2.33+f71b366f77
> 	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
> 	   |-- fabric-commands-v0 0.2.50+df3654b377
> 	   |-- fabric-containers-v0 0.1.63+df3654b377
> 	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
> 	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
> 	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
> 	   |-- fabric-data-generation-api-v1 12.3.0+0883a8d477
> 	   |-- fabric-dimensions-v1 2.1.53+8536527b77
> 	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
> 	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
> 	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
> 	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
> 	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
> 	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
> 	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
> 	   |-- fabric-keybindings-v0 0.2.34+df3654b377
> 	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
> 	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
> 	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
> 	   |-- fabric-message-api-v1 5.1.7+3265161977
> 	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
> 	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
> 	   |-- fabric-models-v0 0.4.1+9386d8a777
> 	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
> 	   |-- fabric-networking-v0 0.3.50+df3654b377
> 	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
> 	   |-- fabric-particles-v1 1.1.1+201a23a077
> 	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
> 	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
> 	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
> 	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
> 	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
> 	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
> 	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
> 	   |-- fabric-rendering-v0 1.1.48+df3654b377
> 	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
> 	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
> 	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
> 	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
> 	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
> 	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
> 	   |-- fabric-transfer-api-v1 3.3.1+195226a777
> 	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
> 	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
> 	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
> 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
> 	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
> 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
> 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
> 	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
> 	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
> 	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
> 	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
> 	- fabricloader 0.14.22
> 	- java 17
> 	- liquidbounce 1.0.0
> 	- minecraft 1.20.1
> [22:13:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/ganyong/Desktop/liquid%20bounce/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [22:13:25] [main/INFO]: Compatibility level set to JAVA_16
> [22:13:25] [main/INFO]: Compatibility level set to JAVA_17
> [22:13:25] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
> [22:13:30] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 116 milliseconds
> [22:13:31] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [22:13:32] [Render thread/ERROR]: Failed to verify authentication
> com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
> 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
> 	at net.minecraft.class_310.method_31382(class_310.java:733) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:442) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
> Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
> 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
> 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
> 	... 8 more
> [22:13:32] [Render thread/INFO]: Setting user: bruh
> [22:13:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
> [22:13:32] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
> [22:13:33] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
> [22:13:35] [Render thread/INFO]: Successfully extracted default theme
> [22:13:35] [Render thread/INFO]: Loading heads...
> [22:13:39] [Render thread/INFO]: Successfully loaded 956 heads from the database
> [22:13:39] [Render thread/INFO]: Downloading required font Roboto-Medium.ttf...
> [22:13:40] [Render thread/INFO]: Downloading required font Roboto-Bold.ttf...
> [22:13:41] [Render thread/INFO]: Found out OpenGL version to be 4.1.
> [22:13:41] [Render thread/INFO]: Loading ultralight...
> [22:13:41] [Render thread/INFO]: Checking resources...
> [22:13:41] [Render thread/INFO]: Downloading vb8daecd_0.4.12 resources... (os: mac)
> [22:14:47] [Render thread/INFO]: Extracting resources...
> [22:14:48] [Render thread/INFO]: Successfully loaded resources.
> [22:14:48] [Render thread/INFO]: Loading ultralight natives
> [22:14:48] [Render thread/INFO]: Native path: /Users/ganyong/Desktop/liquid bounce/LiquidBounce/ultralight/bin
> [22:14:48] [Render thread/ERROR]: Unable to load client.
> java.lang.UnsatisfiedLinkError: Can't load library: /Users/ganyong/Desktop/liquid bounce/LiquidBounce/ultralight/bin/libglib-2.0-0.dylib
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
> 	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
> 	at java.lang.System.load(System.java:1953) ~[?:?]
> 	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:126) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:88) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:140) ~[liquidbounce.jar:?]
> 	at net.minecraft.class_310.handler$zll000$liquidbounce$startClient(class_310.java:6087) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
> ```
> 
> ### Screenshots
> <img alt="截屏2023-09-29 23 15 49" width="1225" src="https://user-images.githubusercontent.com/76635216/271646864-8035da5b-0cb2-4ef2-b3fb-dcc4ab95413c.png">
> ### I need a non-broken file, thanks.

well, nextgen doesn't really support macOS

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
