### ISSUE TITLE
[BUG] Hud Performance

### ISSUE THREAD

**Issue by Aspw-w** [CCBlueX/LiquidBounce#1556]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Describe the bug

There is a huge lag when the Hud module is turned on and other modules are turned on. I also experience a similar lag when opening ClickGui.

### Steps to reproduce

.t clickgui

### Client Log

```shell
[01:45:59] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
[01:45:59] [ForkJoinPool-1-worker-5/WARN]: Mod liquidbounce uses the version nextgen which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'nextgen'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:46:00] [main/INFO]: Loading 76 mods:
	- fabric-api 0.90.7+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.6+d7b148e077
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.2+1bc31aeb77
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.13+kotlin.1.9.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.24
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- liquidbounce nextgen
	- minecraft 1.20.1
	- nvidium 0.2.0-beta
	- sodium 0.5.3
	- viafabricplus 2.8.7
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.9
[01:46:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/0kcab/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:46:00] [main/INFO]: Compatibility level set to JAVA_16
[01:46:00] [main/INFO]: Compatibility level set to JAVA_17
[01:46:00] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 3 override(s) found
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:46:00] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:46:01] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker)
[01:46:01] [main/WARN]: Error loading class: org/anti_ad/mc/ipnext/event/AutoRefillHandler$ItemSlotMonitor (java.lang.ClassNotFoundException: org/anti_ad/mc/ipnext/event/AutoRefillHandler$ItemSlotMonitor)
[01:46:01] [main/INFO]: Searching for graphics cards...
[01:46:01] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 4090, version=DriverVersion=31.0.15.4601]
[01:46:01] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[01:46:01] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[01:46:02] [main/WARN]: No Bedrock account could be found
[01:46:03] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[01:46:03] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[01:46:03] [main/INFO]: Loading translations...
[01:46:03] [main/INFO]: Registering protocols...
[01:46:04] [main/INFO]: Started resource pack HTTP server on http://127.0.0.1:4176/
[01:46:04] [main/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[01:46:04] [main/INFO]: Highest supported version by the proxy: 1.20.2 (764)
[01:46:04] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:46:04] [main/WARN]: Failed to update counter. Error code: 0x800007D5
[01:46:04] [main/WARN]: Disabling further attempts to query Paging File.
[01:46:08] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 105 milliseconds
[01:46:08] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[01:46:09] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:46:10] [Render thread/INFO]: Setting user: As_pw
[01:46:10] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[01:46:10] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] Cached update file detected, using that!
[01:46:10] [Render thread/WARN]: FileSystem for viafabricplus 2.8.7 has been closed unexpectedly, existing root path references may break!
[01:46:10] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[01:46:10] [Render thread/WARN]: Attempting to apply workarounds for the NVIDIA Graphics Driver...
[01:46:10] [Render thread/WARN]: If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues
[01:46:10] [Render thread/INFO]: ... Successfully applied workarounds for the NVIDIA Graphics Driver!
[01:46:11] [Render thread/INFO]: All capabilities met
[01:46:11] [Render thread/INFO]: Enabling Nvidium
[01:46:11] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[01:46:11] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
[01:46:11] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 546.01
[01:46:11] [Render thread/INFO]: Debug functionality is disabled.
[01:46:11] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[01:46:11] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[01:46:11] [Render thread/INFO]: Shaders are disabled
[01:46:11] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:526) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:601) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:513) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:524) ~[client-intermediary.jar:?]
	... 17 more
[01:46:11] [Render thread/WARN]: Missing metadata in pack file/epicpack
[01:46:11] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:526) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:601) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:513) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 30 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:524) ~[client-intermediary.jar:?]
	... 17 more
[01:46:11] [Render thread/WARN]: Missing metadata in pack file/Shadows edit thing
[01:46:11] [Render thread/INFO]: Hardware information:
[01:46:11] [Render thread/INFO]: CPU: 24x Intel(R) Core(TM) i9-14900KF CPU @ 4.40GHz
[01:46:11] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 4090/PCIe/SSE2 (Supports OpenGL 3.3.0 NVIDIA 546.01)
[01:46:11] [Render thread/INFO]: OS: Windows 10 (10.0)
[01:46:11] [Render thread/INFO]: Launching LiquidBounce Nextgen by As_pw
[01:46:12] [Render thread/INFO]: Successfully extracted default theme
[01:46:12] [Render thread/INFO]: Found out OpenGL version to be 3.3.0.
[01:46:12] [Render thread/INFO]: Loading ultralight...
[01:46:12] [Render thread/INFO]: Checking resources...
[01:46:12] [Render thread/INFO]: Loading ultralight natives
[01:46:12] [Render thread/INFO]: Native path: C:\Users\0kcab\AppData\Roaming\.minecraft\versions\fabric-loader-0.14.24-1.20.1\LiquidBounce\ultralight\bin
[01:46:13] [Render thread/INFO]: Setting up ultralight renderer
[01:46:13] [Render thread/INFO]: [Ul] Initializing Ultralight v1.3.0 with the following configuration
    cache_path: C:\Users\0kcab\AppData\Roaming\.minecraft\versions\fabric-loader-0.14.24-1.20.1\LiquidBounce\ultralight\cache
    face_winding: CounterClockwise
    font_hinting: Smooth
    font_gamma: 1.8
    force_repaint: 0
    animation_timer_delay: 0.00694444
    scroll_timer_delay: 0.00694444
    recycle_delay: 4
    memory_cache_size: 64.00 MB
    page_cache_size: 0
    override_ram_size: disabled
    min_large_heap_size: 32.00 MB
    min_small_heap_size: 1.00 MB

[01:46:13] [Render thread/INFO]: [Ul] Creating Session with the following configuration:
    id: 2
    is_persistent: 1
    name: default
    is_default: 1
    disk_path: C:\Users\0kcab\AppData\Roaming\.minecraft\versions\fabric-loader-0.14.24-1.20.1\LiquidBounce\ultralight\cache\default (you can adjust this location in Config::cache_path)
[01:46:13] [Render thread/INFO]: [Ul] Memory Usage (WebCore): 
    JavaScript:          64.00 KB

[01:46:13] [Render thread/INFO]: [Ul] Memory Usage (UltralightCore): 
    Texture Store:        0.00 B, VRAM: 0.00 B
    Render Texture Store: 0.00 B, VRAM: 0.00 B
    Geometry Store:       0.00 B, VRAM: 0.00 B
    Texture Cache:        0.00 B
    Image Cache:          0.00 B
    Path Cache:           0.00 B
    Font Cache:           8.00 B
    Paint Pool:           6.25 KB
    Render Texture Pool:  0.00 B
    Texture Pool:         0.00 B
    Geometry Pool:        0.00 B
    Path Tesselator:      8.00 B

[01:46:13] [Render thread/INFO]: Successfully loaded ultralight!
[01:46:13] [Render thread/INFO]: [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[01:46:13] [Render thread/INFO]: Successfully loaded config 'enemies'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'modules'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'commands'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'friends'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'proxy'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'accounts'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'fonts'.
[01:46:13] [Render thread/INFO]: Successfully loaded config 'storage'.
[01:46:13] [Render thread/INFO]: Refreshing local IP info...
[01:46:14] [Render thread/INFO]: Successfully loaded client!
[01:46:14] [nioEventLoopGroup-3-1/INFO]: Successfully requested IP info 126.77.16.16
[01:46:14] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, liquidbounce, nvidium, sodium, viafabricplus)
[01:46:14] [Render thread/INFO]: [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[01:46:14] [Render thread/INFO]: [Ul] Creating View with the following configuration:
    width: 854
    height: 480
    device scale: 1
    session id: 2
[01:46:14] [Worker-Main-10/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] :2:12: hello
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html:56:20: Splashscreen loaded
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html:59:20: Debugging
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html:60:20: View Var: net.ccbluex.liquidbounce.base.ultralight.ViewOverlay@2fc50143
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html:61:20: Events Var: net.ccbluex.liquidbounce.base.ultralight.js.bindings.UltralightJsEvents@46d5c6e5
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/ERROR] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html:81:26: Error while setting up event listener: Error: on threw an exception
[01:46:14] [Render thread/INFO]: View message: [CONSOLE_API/LOG] :2:12: hello
[01:46:15] [Render thread/INFO]: [MainFrame 3 (file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[01:46:15] [Render thread/INFO]: View message: [CONSOLE_API/LOG] :2:12: hello
[01:46:16] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[01:46:16] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[01:46:16] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on ヘッドホン (Realtek High Definition Audio)
[01:46:16] [Render thread/INFO]: Sound engine started
[01:46:16] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[01:46:16] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[01:46:16] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[01:46:16] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[01:46:16] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[01:46:16] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[01:46:16] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[01:46:16] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[01:46:16] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[01:46:16] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[01:46:16] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[01:46:16] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[01:46:16] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[01:46:16] [Render thread/INFO]: [MainFrame 5 (file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[01:46:16] [Render thread/INFO]: [MainFrame 1 (file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/hud/index.html)]: The view finished loading
[01:46:23] [Render thread/INFO]: [Ul] Creating View with the following configuration:
    width: 1920
    height: 1017
    device scale: 1
    session id: 2
[01:46:23] [Render thread/INFO]: View message: [CONSOLE_API/LOG] :2:12: hello
[01:46:23] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html:210:24: Account List updating...
[01:46:23] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html:213:28: Account 0: Microsoft As_pw
[01:46:23] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html:249:24: 
[01:46:23] [Render thread/INFO]: [MainFrame 7 (file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[01:46:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:46:28] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html:210:24: Account List updating...
[01:46:28] [Render thread/INFO]: View message: [CONSOLE_API/LOG] file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/altmanager/index.html:213:28: Account 0: Microsoft As_pw
[01:46:29] [Render thread/INFO]: [Ul] Creating View with the following configuration:
    width: 1920
    height: 1017
    device scale: 1
    session id: 2
[01:46:29] [Render thread/INFO]: View message: [CONSOLE_API/LOG] :2:12: hello
[01:46:29] [Render thread/INFO]: [MainFrame 9 (file:///C:/Users/0kcab/AppData/Roaming/.minecraft/versions/fabric-loader-0.14.24-1.20.1/LiquidBounce/themes/default/title/index.html)]: The view finished loading
```

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
