### ISSUE TITLE
[BUG] Will not start

### ISSUE THREAD

**Issue by DebugBoard** [CCBlueX/LiquidBounce#1604]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Netgen newest version

### Operating System

Linux

### Minecraft Version

1.20.1

### Describe the bug

Ran the game and keep getting this error
[20:25:43] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: /home/pjr/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1
.invoke(LiquidBounce.kt:145) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:96) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bka000$liquidbounce$startClient(class_310.java:9591) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Failed to launch client: Process exited with non-zero code: 1

### Steps to reproduce

Install on Debian (kali) 
Run game

### Client Log

```shell
[20:25:43] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: /home/pjr/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1
.invoke(LiquidBounce.kt:145) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:96) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bka000$liquidbounce$startClient(class_310.java:9591) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Failed to launch client: Process exited with non-zero code: 1
```

**Comment by be4dev** [comment]
> ### LiquidBounce Branch
> 
> Nextgen
> ### LiquidBounce Build/Version
> 
> Netgen newest version
> ### Operating System
> 
> Linux
> ### Minecraft Version
> 
> 1.20.1
> ### Describe the bug
> 
> Ran the game and keep getting this error [20:25:43] [Render thread/ERROR]: Unable to load client. java.lang.UnsatisfiedLinkError: /home/pjr/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: cannot open shared object file: No such file or directory at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?] at java.lang.Runtime.load0(Unknown Source) ~[?:?] at java.lang.System.load(Unknown Source) ~[?:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?] at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[LiquidBounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1 .invoke(LiquidBounce.kt:145) ~[LiquidBounce.jar:?] at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:96) ~[LiquidBounce.jar:?] at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?] at net.minecraft.class_310.handler$bka000$liquidbounce$startClient(class_310.java:9591) ~[client-intermediary.jar:?] at net.minecraft.class_310.(class_310.java:631) ~[client-intermediary.jar:?] at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?] /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so Failed to launch client: Process exited with non-zero code: 1
> ### Steps to reproduce
> 
> Install on Debian (kali) Run game
> ### Client Log
> 
> ```shell
> [20:25:43] [Render thread/ERROR]: Unable to load client.
> java.lang.UnsatisfiedLinkError: /home/pjr/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: cannot open shared object file: No such file or directory
> 	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
> 	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
> 	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
> 	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
> 	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
> 	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
> 	at java.lang.System.load(Unknown Source) ~[?:?]
> 	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1
> .invoke(LiquidBounce.kt:145) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:96) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
> 	at net.minecraft.class_310.handler$bka000$liquidbounce$startClient(class_310.java:9591) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:631) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.14.24-1.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
> /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
> Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
> Failed to launch client: Process exited with non-zero code: 1
> ```
> 
> ### Screenshots
> 
> _No response_

this issue disappears when using dev environment, not a clean way tho

**Comment by DebugBoard** [comment]
could you tell me fix pls

**Comment by be4dev** [comment]
> could you tell me fix pls

[sadly you will have to do this](https://github.com/CCBlueX/LiquidBounce#setting-up-a-workspace)

**Comment by DebugBoard** [comment]
Fun........ thanks for helping
