### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FlameGrowl-wq** [CCBlueX/LiquidBounce#1643]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Describe the bug

I was playing normaly and it suddently timeouted out of the server it even happens in single player worlds

### Steps to reproduce

it randomly happens

### Client Log

```shell
va.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.noneMatch(Unknown Source) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getSecurePropertyValue(YggdrasilMinecraftSessionService.java:163) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSe
ssionService.java:116) ~[authlib-4.0.43.jar:?]
	at net.minecraft.class_1071.method_4653(class_1071.java:100) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[09:20:12] [Worker-Main-7/ERROR]: Property textures has been tampered with (signature invalid)
[09:20:56] [Render thread/INFO]: Stopping worker threads
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/129600639/2e0b27e3-cc06-4fb2-bf48-fe8d8848204d)

**Comment by FlameGrowl-wq** [comment]
screenshot is more detailed

**Comment by 1zun4** [comment]
Seems not to be an issue with LiquidBounce, but actually something with the mojang authlib not being happy about some signature. If this issue persisits and is reproduceable, let me know, otherwise I close this.

Update to Minecraft 1.20.4 is coming soon too!
