### ISSUE TITLE
[BUG] Launching issue

### ISSUE THREAD

**Issue by SomePythonDeveloper** [CCBlueX/LiquidBounce#1690]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Every single one

### Operating System

Linux

### Minecraft Version

Every single one

### Describe the bug

I am able to launch into the screen, but then it freezes, and then crashes

### Steps to reproduce

Just launch it from liquidlauncher

### Client Log

```shell
[16:31:18] [Render thread/ERROR]: Fatal error
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from /home/schul/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146) ~[LiquidBounce.jar:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:168) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.
handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /home/schul/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary
(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144) ~[LiquidBounce.jar:?]
	... 12 more
zenity: symbol lookup error: /lib/x86_64-linux-gnu/libcairo-script-interpreter.so.2: undefined symbol: cairo_set_hairline
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/153401958/0ba37124-3cbc-441c-9a75-24e223a4d8e1)

**Comment by SomePythonDeveloper** [comment]
Console says:
  2023-12-17T15:34:35.625204Z ERROR liquidlauncher::app::gui: OpenJDK 64-Bit Server VM warning: You have loaded library /home/schul/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

    at src/app/gui.rs:119

  2023-12-17T15:34:35.631162Z  INFO liquidlauncher::app::gui: [16:34:35] [Render thread/ERROR]: Fatal error
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from /home/schul/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146) ~[LiquidBounce.jar:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:168) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.
    at src/app/gui.rs:108

  2023-12-17T15:34:35.631278Z  INFO liquidlauncher::app::gui: handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /home/schul/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary
    at src/app/gui.rs:108

  2023-12-17T15:34:35.631328Z  INFO liquidlauncher::app::gui: (Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144) ~[LiquidBounce.jar:?]
	... 12 more

    at src/app/gui.rs:108

  2023-12-17T15:34:35.726622Z ERROR liquidlauncher::app::gui: zenity: symbol lookup error: /lib/x86_64-linux-gnu/libcairo-script-interpreter.so.2: undefined symbol: cairo_set_hairline

    at src/app/gui.rs:119

  2023-12-17T15:34:36.198599Z DEBUG liquidlauncher::minecraft::java::runtime: Process exited with code: 1
    at src/minecraft/java/runtime.rs:53

  2023-12-17T15:34:36.199301Z ERROR liquidlauncher::app::gui: An error with the client occourd:
Process exited with non-zero exit code: 1.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/1701
