### ISSUE TITLE
[BUG] Missing Ultralightcore files on linux

### ISSUE THREAD

**Issue by twenty48lol** [CCBlueX/LiquidBounce#1701]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest as of this issue

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

It throws an error and when clicked ok crashes

### Steps to reproduce

Launch the client normally on SKLauncher. Multimc is the same as well
mods used: fabric api, fabric language kotlin, liquidbounce, sodium

### Client Log

```shell
[00:23:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[00:23:02] [main/INFO]: Dependencies overridden for lithium, sodium, immediatelyfast, indium
[00:23:03] [main/INFO]: Loading 68 mods:
	- fabric-api 0.91.2+1.20.4
	   |-- fabric-api-base 0.4.35+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-command-api-v2 2.2.19+78d798af4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.27+78d798af4f
	   |-- fabric-events-interaction-v0 0.6.14+78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.29+78d798af4f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.2+78d798af4f
	   |-- fabric-object-builder-api-v1 13.0.7+78d798af4f
	   |-- fabric-particles-v1 1.1.6+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.13+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32+78d798af4f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.15+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabric-language-kotlin 1.10.16+kotlin.1.9.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.20.4
	- sodium 0.5.5
[00:23:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/twenty48/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:23:03] [main/INFO]: Compatibility level set to JAVA_17
[00:23:03] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[00:23:04] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[00:23:05] [main/INFO]: Searching for graphics cards...
[00:23:05] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=unknown, version=unknown]
[00:23:05] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[00:23:08] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[00:23:17] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 676 milliseconds
[00:23:21] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[00:23:21] [Render thread/INFO]: Setting user: EnchantPlus
[00:23:22] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[00:23:22] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[00:23:23] [Render thread/INFO]: OpenGL Vendor: Mesa
[00:23:23] [Render thread/INFO]: OpenGL Renderer: llvmpipe (LLVM 16.0.6, 128 bits)
[00:23:23] [Render thread/INFO]: OpenGL Version: 4.5 (Core Profile) Mesa 23.3.1-arch1.1
[00:23:25] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[00:23:25] [Render thread/INFO]: Successfully extracted default theme
[00:23:25] [Render thread/INFO]: Loading heads...
[00:23:28] [Render thread/INFO]: Successfully loaded 956 heads from the database
[00:23:29] [Render thread/INFO]: Loading ultralight...
[00:23:29] [Render thread/INFO]: Checking resources...
[00:23:29] [Render thread/INFO]: Loading ultralight natives
[00:23:29] [Render thread/INFO]: Native path: /home/twenty48/.minecraft/modpacks/9a7e95c6-1135-3171-9c8a-76b18406e4ee/LiquidBounce/ultralight/bin
[00:23:29] [Render thread/ERROR]: Failed to load library gstreamer-full-1.0
java.lang.UnsatisfiedLinkError: /home/twenty48/.minecraft/modpacks/9a7e95c6-1135-3171-9c8a-76b18406e4ee/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:161) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zop000$liquidbounce$startClient(class_310.java:6845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[00:23:29] [Render thread/ERROR]: Fatal error
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from /home/twenty48/.minecraft/modpacks/9a7e95c6-1135-3171-9c8a-76b18406e4ee/LiquidBounce/ultralight/bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146) ~[liquidbounce.jar:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:168) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zop000$liquidbounce$startClient(class_310.java:6845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /home/twenty48/.minecraft/modpacks/9a7e95c6-1135-3171-9c8a-76b18406e4ee/LiquidBounce/ultralight/bin/libWebCore.so: libpng12.so.0: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144) ~[liquidbounce.jar:?]
	... 12 more
[00:23:35] [Render thread/ERROR]: Couldn't open url 'https://github.com/CCBlueX/LiquidBounce/issues'
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(AccessController.java:573) ~[?:?]
	at net.minecraft.class_156$class_158.method_669(class_156.java:334) ~[client-intermediary.jar:?]
	at net.minecraft.class_156$class_158.method_670(class_156.java:370) ~[client-intermediary.jar:?]
	at net.ccbluex.liquidbounce.utils.client.ClientUtilsKt.browseUrl(ClientUtils.kt:98) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.client.ErrorHandler.fatal(ErrorHandler.kt:68) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:169) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zop000$liquidbounce$startClient(class_310.java:6845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1143) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:594) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:453) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:334) ~[client-intermediary.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	... 15 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:314) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:244) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1110) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:594) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:453) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:334) ~[client-intermediary.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	... 15 more
```

### Screenshots

OS: Arch linux, updated just 15 mins before launching, xfce4.16

**Comment by michael-pfister** [comment]
I have the same issue when installing LiquidBounce next-gen through the provided mod file. Works fine when I launch it with LiquidLauncher. I used Prism Launcher for it to crash. I am on the latest Fedora Linux.

**Comment by michael-pfister** [comment]
I don't understand what's happening here, the file it is looking for `libpng12.so.0` doesn't exist in the liquid launcher installation either, why is the mod installation looking for it?

**Comment by michael-pfister** [comment]
`libpng12.so.0` is part of libpng which is the library for processing PNG files in Linux. It is supposed to be a shared library commonly found under `/usr/lib64/libpng12.so.0`. Ultralight (a performance improvement mod) is trying to find it under `ultralight/bin` where it doesn't exist.

I fixed this issue by copying the library to the directory it is trying to look for it, however this is more of a hacky way to get things running and not a solution.

```bash
# find the ultralight/bin directory where it throws the error
cd <ultralight/bin directory>

# copy the library file into the directory from shared user libraries 
# (you can also install this library with your package manager in case it's missing)
cp /usr/lib64/libpng12.so.0 .
```

This seems to be a problem with Ultralight and not with Liquidbounce. Are we using the latest version?

**Comment by Ell1ott** [comment]
> Ultralight (a performance improvement mod)

Ultralight is more a library than a mod. https://ultralig.ht/. Ultralight makes it possible for liquidbounce to use html/css/js to render the Hud, ClickGUI, etc.

**Comment by michael-pfister** [comment]
@Ell1ott my bad, I didn't know what it was so I searched up 'minecraft ultralight' which leads you to a mod on forge.

**Comment by twenty48lol** [comment]
> I have the same issue when installing LiquidBounce next-gen through the provided mod file. Works fine when I launch it with LiquidLauncher. I used Prism Launcher for it to crash. I am on the latest Fedora Linux.

it crashed even on liquidlauncher....

**Comment by 1zun4** [comment]
Try installing the missing library `libpng12.so.0` yourself. Normally the system already has it installed, so did Manjaro for me, but seems some distributions are lacking the library sometimes. Also the LiquidLauncher bundles quite a few libraries as well due to the fact its an AppImage.

Otherwise wait for https://github.com/CCBlueX/LiquidBounce/pull/1557 to be merged. This discontinues the use of Ultralight and moves to JCEF, which is more compatible.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
