### ISSUE TITLE
[BUG] JumpEffect crashes the game.

### ISSUE THREAD

**Issue by Katinuka** [CCBlueX/LiquidBounce#1722]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

the latest

### Operating System

Windows 10

### Minecraft Version

1.20.4?

### Describe the bug

I was changing Lifetime setting in JumpEffect module and the game crashed.

### Steps to reproduce

- Find the place where you can jump extremely fast because of the low ceiling
- Enable AntiAFK with jumping only
- When it spams circles change "LifeTime" setting in JumpEffect module
- The game crashed

### Client Log

```shell
[18:06:23] [Render thread/INFO] (LiquidBounce) Successfully saved config 'modules'.
[18:06:23] [Render thread/INFO] (LiquidBounce) [MainFrame 9 (file:///D:/Katinuka/LiquidBounce-nextgen/LiquidBounce/run/LiquidBounce/themes/default/clickgui/index.html)]: The view finished loading
[18:06:53] [Render thread/ERROR] (LiquidBounce) Exception while executing handler.
java.lang.IllegalArgumentException: Color parameter outside of expected range: Alpha
	at java.awt.Color.testColorValueRange(Color.java:312) ~[?:?]
	at java.awt.Color.<init>(Color.java:397) ~[?:?]
	at net.ccbluex.liquidbounce.render.engine.Color4b.toRGBA(RenderTasks.kt:150) ~[main/:?]
	at net.ccbluex.liquidbounce.render.RenderShortcutsKt.drawGradientCircle(RenderShortcuts.kt:455) ~[main/:?]
	at net.ccbluex.liquidbounce.render.RenderShortcutsKt.drawGradientCircle$default(RenderShortcuts.kt:432) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1$1$1$1.invoke(ModuleJumpEffect.kt:44) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1$1$1$1.invoke(ModuleJumpEffect.kt:43) ~[main/:?]
	at net.ccbluex.liquidbounce.render.RenderShortcutsKt.withPosition(RenderShortcuts.kt:109) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1$1.invoke(ModuleJumpEffect.kt:43) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1$1.invoke(ModuleJumpEffect.kt:40) ~[main/:?]
	at net.ccbluex.liquidbounce.render.RenderShortcutsKt.renderEnvironmentForWorld(RenderShortcuts.kt:78) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1.invoke(ModuleJumpEffect.kt:40) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleJumpEffect$renderHandler$1.invoke(ModuleJumpEffect.kt:37) ~[main/:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:156) ~[main/:?]
	at net.minecraft.client.render.GameRenderer.handler$bbj000$liquidbounce$hookWorldRender(GameRenderer.java:3166) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1080) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:885) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1204) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:838) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[18:06:53] [Render thread/ERROR] (Minecraft) Unreported exception thrown!
java.lang.IllegalStateException: Already building!
	at net.minecraft.client.render.BufferBuilder.begin(BufferBuilder.java:133) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.gl.Framebuffer.drawInternal(Framebuffer.java:249) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.gl.Framebuffer.draw(Framebuffer.java:218) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.render.WorldRenderer.drawEntityOutlinesFramebuffer(WorldRenderer.java:523) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:887) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1204) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:838) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-merged-b47d5b4754-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[18:06:54] [Server thread/INFO] (Minecraft) Stopping server
[18:06:54] [Server thread/INFO] (Minecraft) Saving players
[18:06:54] [Server thread/INFO] (Minecraft) Saving worlds
[18:06:54] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:06:54] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:06:54] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:06:54] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (New World): All chunks are saved
[18:06:54] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:06:54] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:06:54] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage: All dimensions are saved
```

### Screenshots

https://youtu.be/O1BY5ihORrc

**Comment by Ell1ott** [comment]
Thanks for the bug report, it will be fixed soon.
