### ISSUE TITLE
[BUG] LB Nextgen does not launch on NixOS

### ISSUE THREAD

**Issue by Guanran928** [CCBlueX/LiquidBounce#1744]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

commit 4af14eb

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Client does not launch on non-FHS Linux distributions. In this case, [NixOS](https://nixos.org/).

### Steps to reproduce

1. Run LB Nextgen on NixOS
2. See client crashes, seems to be cause by native dependencies
  Also seems like https://github.com/CCBlueX/LiquidBounce/pull/1557 broke it even more

### Client Log

```shell
###### After https://github.com/CCBlueX/LiquidBounce/pull/1557
       commit 4af14eb

[18:03:02] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[18:03:02] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[18:03:02] [Render thread/INFO]: https://dl.ccbluex.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/linux_amd64.tar.gz.sha256 -> /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/mcef/libraries/linux_amd64.tar.gz.sha256.temp
[18:03:04] [Render thread/INFO]: Checksum matches: true
[18:03:04] [Render thread/INFO]: Platform directory exists: true
[18:03:04] [Render thread/INFO]: Initializing CEF on linux_amd64...
[18:03:04] [Render thread/INFO]: [STDERR]: java.nio.file.NoSuchFileException: /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/mcef/libraries/linux_amd64/jcef_helper
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:277)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2167)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.mcef.CefUtil.setUnixExecutable(CefUtil.java:56)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:68)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:64)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:67)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:156)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:108)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:161)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zme000$liquidbounce$startClient(class_310.java:6348)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:675)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:223)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[18:03:04] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)




###### Before https://github.com/CCBlueX/LiquidBounce/pull/1557
       commit 553fb8f

[17:56:31] [Render thread/INFO]: Loading ultralight natives
[17:56:31] [Render thread/INFO]: Native path: /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/ultralight/bin
[17:56:31] [Render thread/ERROR]: Failed to load library gstreamer-full-1.0
java.lang.UnsatisfiedLinkError: /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libXv.so.1: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:161) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:156) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.minecraft.class_310.handler$zme000$liquidbounce$startClient(class_310.java:6345) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[17:56:31] [Render thread/ERROR]: Fatal error
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/ultralight/bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:168) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:156) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	at net.minecraft.class_310.handler$zme000$liquidbounce$startClient(class_310.java:6345) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /home/USERNAME/.local/share/PrismLauncher/instances/hax nextgen/.minecraft/LiquidBounce/ultralight/bin/libWebCore.so: libXv.so.1: cannot open shared object file: No such file or directory
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144) ~[liquidbounce-53fb8f-before-mcef.jar:?]
	... 15 more
```

**Comment by 1zun4** [comment]
Use the latest version.
