### ISSUE TITLE
[BUG] Parkour does not work properly 

### ISSUE THREAD

**Issue by derech1e** [CCBlueX/LiquidBounce#1927]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b0.1.3 (git-08c2767)

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

The parkour module should normally be able to do 4-block jumps with 99% success rate right away. Currently it can't make these jumps at all.

### Steps to reproduce

1. Enable Sprint Module or hold sprint the whole time
2. Enable parkour
3. Try a 4 Block jump

### Client Log

```shell
2024-01-28T19:00:07.912245Z  INFO liquidlauncher::app::gui: [20:00:07] [Server thread/INFO]: [DerEchte_: Successfully filled 2601 block(s)]

2024-01-28T19:00:07.937300Z  INFO liquidlauncher::app::gui: [20:00:07] [Render thread/INFO]: [CHAT] Successfully filled 2601 block(s)

2024-01-28T19:01:09.380504Z ERROR liquidlauncher::app::gui: [0128/200109.379:INFO:CONSOLE(0)] "Autofocus processing was blocked because a document already has a focused element.", source: http://localhost:15810/default/#/clickgui (0)

2024-01-28T19:01:13.098021Z ERROR liquidlauncher::app::gui: [0128/200113.097:ERROR:menu_runner_views_aura.cc(23)] Window handle is required for default OSR context menu.

2024-01-28T19:01:13.098478Z ERROR liquidlauncher::app::gui: [0128/200113.097:ERROR:menu_manager.cc(199)] Default context menu implementation is not available; canceling the menu

2024-01-28T19:02:36.915393Z  INFO liquidlauncher::app::gui: [20:02:36] [Server thread/INFO]: Saving and pausing game...

2024-01-28T19:02:36.932219Z  INFO liquidlauncher::app::gui: [20:02:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:02:36.943985Z  INFO liquidlauncher::app::gui: [20:02:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:02:36.947345Z  INFO liquidlauncher::app::gui: [20:02:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:02:48.015168Z  INFO liquidlauncher::app::gui: [20:02:48] [Server thread/INFO]: Saving and pausing game...

2024-01-28T19:02:48.030770Z  INFO liquidlauncher::app::gui: [20:02:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:02:48.038237Z  INFO liquidlauncher::app::gui: [20:02:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:02:48.041553Z  INFO liquidlauncher::app::gui: [20:02:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:02:52.614821Z  INFO liquidlauncher::app::gui: [20:02:52] [Server thread/INFO]: Saving and pausing game...

2024-01-28T19:02:52.630811Z  INFO liquidlauncher::app::gui: [20:02:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:02:52.635215Z  INFO liquidlauncher::app::gui: [20:02:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:02:52.635319Z  INFO liquidlauncher::app::gui: [20:02:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:03:41.814541Z  INFO liquidlauncher::app::gui: [20:03:41] [Server thread/INFO]: Saving and pausing game...

2024-01-28T19:03:41.830550Z  INFO liquidlauncher::app::gui: [20:03:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:03:41.838051Z  INFO liquidlauncher::app::gui: [20:03:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:03:41.840832Z  INFO liquidlauncher::app::gui: [20:03:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:03:44.264843Z  INFO liquidlauncher::app::gui: [20:03:44] [Server thread/INFO]: Saving and pausing game...

2024-01-28T19:03:44.279586Z  INFO liquidlauncher::app::gui: [20:03:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:03:44.284682Z  INFO liquidlauncher::app::gui: [20:03:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:03:44.284832Z  INFO liquidlauncher::app::gui: [20:03:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:04:38.155416Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Shutting down client...

2024-01-28T19:04:38.158652Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/ERROR]: Failed to shutdown browser.
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:?]
	at org.cef.CefClient.cleanupBrowser(CefClient.java:515) ~[LiquidBounce.jar:?]
	at org.cef.CefClient.dispose(CefClient.java:83) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.shutdown(CefUtil.java:121) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.shutdown(MCEF.java:164) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.shutdownBrowserBackend(JcefBrowser.kt:78) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.shutdownBrowser-d1pmJ48(BrowserManager.kt:77) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$shutdownHandler$1.invoke(LiquidBounce.kt:258) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$shutdownHandler$1.invoke(LiquidBounce.kt:256
2024-01-28T19:04:38.158798Z  INFO liquidlauncher::app::gui: ) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:169) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bll000$liquidbounce$stopClient(class_310.java:8857) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:281) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]

2024-01-28T19:04:38.159360Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'enemies'.

2024-01-28T19:04:38.164374Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'modules'.

2024-01-28T19:04:38.164912Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'commands'.

2024-01-28T19:04:38.165648Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'friends'.

2024-01-28T19:04:38.166200Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'proxy'.

2024-01-28T19:04:38.168420Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'accounts'.

2024-01-28T19:04:38.168904Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'tabs'.

2024-01-28T19:04:38.169262Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'lang'.

2024-01-28T19:04:38.169612Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'chat'.

2024-01-28T19:04:38.170067Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Successfully saved config 'storage'.

2024-01-28T19:04:38.170170Z  INFO liquidlauncher::app::gui: [20:04:38] [Render thread/INFO]: Stopping!

2024-01-28T19:04:38.229144Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: DerEchte_ lost connection: Disconnected

2024-01-28T19:04:38.229329Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: DerEchte_ left the game

2024-01-28T19:04:38.247435Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: Stopping singleplayer server as player logged out

2024-01-28T19:04:38.267079Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: Stopping server

2024-01-28T19:04:38.267313Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: Saving players

2024-01-28T19:04:38.267516Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: Saving worlds

2024-01-28T19:04:38.757254Z  INFO liquidlauncher::app::gui: [20:04:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

2024-01-28T19:04:39.278407Z  INFO liquidlauncher::app::gui: [20:04:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

2024-01-28T19:04:39.278833Z  INFO liquidlauncher::app::gui: [20:04:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether

2024-01-28T19:04:39.290073Z  INFO liquidlauncher::app::gui: [20:04:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved

2024-01-28T19:04:39.290188Z  INFO liquidlauncher::app::gui: [20:04:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:04:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved

2024-01-28T19:04:39.290324Z  INFO liquidlauncher::app::gui: [20:04:39] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

2024-01-28T19:04:39.319911Z  INFO liquidlauncher::app::gui: [20:04:39] [Render thread/INFO]: Successfully saved config 'modules'.

2024-01-28T19:04:39.320030Z  INFO liquidlauncher::app::gui: [20:04:39] [Render thread/INFO]: Reloading integration browser JcefTab to URL http://localhost:15810/default/

2024-01-28T19:04:39.320830Z  INFO liquidlauncher::app::gui: [20:04:39] [Render thread/INFO]: Stopping worker threads

2024-01-28T19:04:40.186005Z DEBUG liquidlauncher::minecraft::java::runtime: Process exited with code: 0
```

### Screenshots

The first jump I did on my own.
All subsequent jumps are trigger by the parkour module

https://github.com/CCBlueX/LiquidBounce/assets/39240736/b19498d8-20aa-4534-8c5e-3d617f51a77a

**Comment by superblaubeere27** [comment]
The Parkour mod currently uses the analysis methods of the eagle/safe walk features. Those features have great detection when it comes to stopping the player before falling to death, but underdeliver at jump timing.

I was thinking about a new Parkour module for some time now and made an issue for it #1945. I might be able to make it in the next weeks to months.
