### ISSUE TITLE
[BUG] Game crashed

### ISSUE THREAD

**Issue by Fixerintaved** [CCBlueX/LiquidBounce#2046]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.15

### Operating System

Windows 7

### Minecraft Version

1.20.4

### Describe the bug

crashing game.

### Steps to reproduce

launch game insta crash

### Client Log

```shell
[11:43:57] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[11:43:58] [main/INFO]: Loading 68 mods:
	- fabric-api 0.95.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.48+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.12+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.0.2+25e1b4764f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.73+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.31+eabbae364f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.62+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.52+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   |-- fabric-rendering-v0 1.1.55+df3654b34f
	   |-- fabric-rendering-v1 3.1.0+0d29db764f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.9+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- liquidbounce 0.1.5
	- minecraft 1.20.4
[11:43:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/H:/mc/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:43:58] [main/INFO]: Compatibility level set to JAVA_17
[11:43:59] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[11:43:59] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[11:44:00] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[11:44:02] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[11:44:09] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 328 milliseconds
[11:44:12] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:44:12] [Render thread/INFO]: Setting user: Bobux5
[11:44:13] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[11:44:14] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[11:44:15] [Render thread/INFO]: Launching LiquidBounce v0.1.5 by CCBlueX
[11:44:15] [Render thread/INFO]: Loaded language en_us
[11:44:15] [Render thread/INFO]: Loaded language de_de
[11:44:15] [Render thread/INFO]: Loaded language ja_jp
[11:44:15] [Render thread/INFO]: Loaded language zh_cn
[11:44:15] [Render thread/INFO]: Loaded language ru_ru
[11:44:15] [Render thread/INFO]: Loaded language en_pt
[11:44:15] [Render thread/INFO]: Loaded language pt_br
[11:44:16] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[11:44:17] [Render thread/INFO]: Successfully loaded config 'enemies'.
[11:44:17] [Render thread/INFO]: (Chat) 
[11:44:17] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[11:44:17] [Render thread/INFO]: Successfully loaded config 'modules'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'commands'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'friends'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'proxy'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'accounts'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'tabs'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'lang'.
[11:44:17] [Render thread/INFO]: Successfully loaded config 'storage'.
[11:44:17] [netty-websocket/INFO]: Starting Netty server...
[11:44:17] [nioEventLoopGroup-2-1/INFO]: [id: 0x7b41307a] REGISTERED
[11:44:17] [nioEventLoopGroup-2-1/INFO]: [id: 0x7b41307a] BIND: 0.0.0.0/0.0.0.0:15291
[11:44:17] [nioEventLoopGroup-2-1/INFO]: [id: 0x7b41307a, L:/[0:0:0:0:0:0:0:0]:15291] ACTIVE
[11:44:17] [netty-websocket/INFO]: Netty server started on port 15291.
[11:44:18] [Render thread/INFO]: Successfully extracted default theme
[11:44:18] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[11:44:18] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[11:44:18] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> H:\mc\instances\1.20.4\.minecraft\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[11:44:19] [Render thread/INFO]: Checksum matches: true
[11:44:19] [Render thread/INFO]: Platform directory exists: true
[11:44:19] [Render thread/INFO]: Initializing CEF on windows_amd64...
[11:44:19] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: H:\mc\instances\1.20.4\.minecraft\LiquidBounce\mcef\libraries\windows_amd64\chrome_elf.dll: Не найдена указанная процедура
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:444) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znh000$liquidbounce$startClient(class_310.java:6347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/159524665/f6928ab8-f0ed-49c2-9336-de59b53f8706)

**Comment by 1zun4** [comment]
Retry with v0.1.5 nightly.
