### ISSUE TITLE
[BUG] CRASH: java.lang.IllegalStateException: Choice GrimCollide not found

### ISSUE THREAD

**Issue by Snowiiii** [CCBlueX/LiquidBounce#2065]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest (30e3781)

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Client Crash

### Steps to reproduce

Run Client

### Client Log

```shell
[Info: 2024-02-11 12:39:22.741063444: MinecraftJavaLoggingContext.cpp(65)] Game/LiquidBounce (Render thread) Error Unable to deserialize choice GrimCollide
java.lang.IllegalStateException: Choice GrimCollide not found
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:246)
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:256)
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:208)
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:206)
	at net.ccbluex.liquidbounce.config.ConfigSystem.load(ConfigSystem.kt:149)
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:157)
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111)
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170)
	at net.minecraft.class_310.handler$bac000$liquidbounce$startClient(class_310.java:5847)
	at net.minecraft.class_310.<init>(class_310.java:675)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
```

**Comment by 1zun4** [comment]
I cannot reproduce this error.

**Comment by Snowiiii** [comment]
bro, i can't reproduce it either...., yesterday it crashed all day long, today it works fine, The JVM is an fucking mystery box, Sorry for your time
