### ISSUE TITLE
[BUG] Game Crash 

### ISSUE THREAD

**Issue by runtimefailure** [CCBlueX/LiquidBounce#2066]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-61 (latest at the website)

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

when i launch the game and it  downloaded the required shit it does not launch

### Steps to reproduce

start game

### Client Log

```shell
[18:38:44] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> C:\Users\Alan\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[18:38:02] [Render thread/INFO]: Checksum matches: true
[18:38:02] [Render thread/INFO]: Platform directory exists: true
[18:38:02] [Render thread/INFO]: Initializing CEF on windows_amd64...
[18:38:03] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\user\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\windows_amd64\libGLESv2.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.cef.CefApp.startup(CefApp.java:442)
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94)
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73)
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66)
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66)
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63)
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166)
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112)
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170)
	at net.minecraft.class_310.handler$zba000$liquidbounce$startClient(class_310.java:3347)
	at net.minecraft.class_310.<init>(class_310.java:675)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Here I am!
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/91615271/7db4481d-33df-42cb-a7f5-e09014f945ed)

**Comment by runtimefailure** [comment]
ok i fixed it i needed to delete the "mcef" folder inside liquidbounce
