### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cxh06** [CCBlueX/LiquidBounce#2084]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

nextgen

### Operating System

Windows 8.1

### Minecraft Version

1.20.4

### Describe the bug

crashing when opening nextgen

### Steps to reproduce

dont know

### Client Log

```shell
[16:16:07] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[16:16:08] [ForkJoinPool-1-worker-3/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[16:16:08] [main/INFO]: Loading 97 mods:
	- baritone 1.10.2
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- fabric-api 0.91.3+1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14+78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-object-builder-api-v1 13.0.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32+78d798af4f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- liquidbounce 0.1.4
	- minecraft 1.20.4
	- moddetectionpreventer 1.0.0
	- modmenu 9.0.0-pre.1
	- nochatreports 1.20.4-v2.5.0
	- sodium 0.5.5
	- viafabricplus 3.0.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-23w51b-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-23w51b-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-lifecycle-events-v1 2.2.30+78d798af4f
	   |-- fabric-networking-api-v1 3.1.5+b7e146354f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.16+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.16+78d798af4f
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.1.0
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[16:16:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/User/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:16:09] [main/INFO]: Compatibility level set to JAVA_17
[16:16:10] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[16:16:13] [main/INFO]: Searching for graphics cards...
[16:16:15] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics Family, version=DriverVersion=10.18.14.4414]
[16:16:15] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon HD 8670M, version=DriverVersion=13.151.0.0]
[16:16:15] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[16:16:20] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[16:16:38] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 3046 milliseconds
[16:16:46] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:16:46] [Render thread/INFO]: Setting user: dvxdvdx
[16:16:48] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[16:16:48] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[16:16:49] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[16:16:49] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[16:16:49] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[16:16:49] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:16:50] [Render thread/WARN]: ClothConfig API not found, cannot provide config screen factory.
[16:16:50] [Worker-Main-1/INFO]: Checking mod updates...
[16:16:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[16:16:52] [Render thread/INFO]: OpenGL Vendor: Intel
[16:16:52] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 4400
[16:16:52] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 10.18.14.4414
[16:16:55] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:50805/
[16:16:56] [Render thread/INFO]: Launching LiquidBounce v0.1.4 by CCBlueX
[16:16:56] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[16:16:56] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 23w51b (766)
[16:16:56] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:16:57] [Render thread/INFO]: Loaded language en_us
[16:16:57] [Render thread/INFO]: Loaded language de_de
[16:16:57] [Render thread/INFO]: Loaded language ja_jp
[16:16:57] [Render thread/INFO]: Loaded language zh_cn
[16:16:57] [Render thread/INFO]: Loaded language ru_ru
[16:16:57] [Render thread/INFO]: Loaded language en_pt
[16:16:57] [Render thread/INFO]: Loaded language pt_br
[16:16:59] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[16:17:00] [Render thread/INFO]: Successfully loaded config 'enemies'.
[16:17:00] [Render thread/INFO]: (Chat) 
[16:17:00] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[16:17:00] [Render thread/INFO]: Successfully loaded config 'modules'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'commands'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'friends'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'proxy'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'accounts'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'tabs'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'lang'.
[16:17:00] [Render thread/INFO]: Successfully loaded config 'storage'.
[16:17:01] [netty-websocket/INFO]: Starting Netty server...
[16:17:01] [nioEventLoopGroup-3-1/INFO]: [id: 0xd899e09f] REGISTERED
[16:17:01] [nioEventLoopGroup-3-1/INFO]: [id: 0xd899e09f] BIND: 0.0.0.0/0.0.0.0:15432
[16:17:01] [nioEventLoopGroup-3-1/INFO]: [id: 0xd899e09f, L:/[0:0:0:0:0:0:0:0]:15432] ACTIVE
[16:17:01] [netty-websocket/INFO]: Netty server started on port 15432.
[16:17:04] [Render thread/INFO]: Successfully extracted default theme
[16:17:04] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[16:17:04] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[16:17:04] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> C:\Users\User\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[16:17:05] [Render thread/INFO]: Checksum matches: true
[16:17:05] [Render thread/INFO]: Platform directory exists: true
[16:17:05] [Render thread/INFO]: Initializing CEF on windows_amd64...
[16:17:05] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\User\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries\windows_amd64\libcef.dll: The specified procedure could not be found
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:445) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bmh000$liquidbounce$startClient(class_310.java:9347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
```

**Comment by 1zun4** [comment]
Try deleting C:\Users\User\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries
