### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1Ecko** [CCBlueX/LiquidBounce#2098]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I was launching the game thro lunar fabric but it crashed
![image](https://github.com/CCBlueX/LiquidBounce/assets/35502409/4a3fab56-a399-4bc7-bf37-3ef652202f7b)

### Steps to reproduce

Launching the game basically

### Client Log

```shell
[2024-02-16 00:02:52.137] [error] NOTE: Picked up JDK_JAVA_OPTIONS: -XX:+DisableAttachMechanism
[2024-02-16 00:02:52.140] [error] Picked up JAVA_TOOL_OPTIONS: -XX:+DisableAttachMechanism
[2024-02-16 00:02:52.140] [error] Picked up _JAVA_OPTIONS: -XX:+DisableAttachMechanism
[2024-02-16 00:02:53.089] [info]  [00:02:53] [
[2024-02-16 00:02:53.090] [info]  Genesis/main/INFO] Found external file: Fabric-API-v1_20_4-0.91.2.jar
[2024-02-16 00:02:53.097] [info]  [00:02:53] [Genesis/
[2024-02-16 00:02:53.098] [info]  main/INFO] Found external file: ReplayMod-v1_20_4-2.6.14.jar
[2024-02-16 00:02:53.099] [info]  [00:02:53] [Genesis/main/INFO] Found external file: Sodium-v1_20_4-0.5.5.jar
[2024-02-16 00:02:53.100] [info]  [00:02:53] [Genesis/main/INFO] Found external file: Iris-v1_20_4-1.6.14.jar
[2024-02-16 00:02:53.655] [info]  [
[2024-02-16 00:02:53.657] [info]  00:02:53] [Genesis/main/INFO] Found classpath URL: common-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 3d1ce015144d9e8c67afb6c7bea44d465088760f
[2024-02-16 00:02:53.657] [info]  
[2024-02-16 00:02:53.662] [info]  [00:02:53] [Genesis/main/
[2024-02-16 00:02:53.663] [info]  INFO] Found classpath URL: lunar-fabric-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 94164c1704be54f96056099ac3fd3ed60293393e
[2024-02-16 00:02:53.792] [info]  [00:02:53] [
[2024-02-16 00:02:53.792] [info]  Genesis/main/INFO] Found classpath URL: genesis-0.1.0-SNAPSHOT-all.jar with SHA-1 hash f4fe0763ee5612babf600ff896c2fcb2817bb441
[2024-02-16 00:02:53.798] [info]  [00:02:53] [Genesis/main/INFO
[2024-02-16 00:02:53.798] [info]  ] Found classpath URL: lunar-lang.jar with SHA-1 hash 8ac3190e3564dd237aa2e33e9da303b906319101
[2024-02-16 00:02:53.800] [info]  [00:02:53] [Genesis/main/INFO] Found classpath URL: lunar-emote.jar with SHA-1 hash b04f3ee8f5e43fa3b162981b50bb72fe1acabb33
[2024-02-16 00:02:54.276] [info]  [00:02:54] [Genesis
[2024-02-16 00:02:54.277] [info]  /main/INFO] Found classpath URL: lunar.jar with SHA-1 hash c4bf1454c42c8bb098a3d81ccd4c98f7f137c6f8
[2024-02-16 00:02:54.527] [info]  [00:02:54] [Genesis/main
[2024-02-16 00:02:54.528] [info]  /INFO] Found classpath URL: modern-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 31afdbd14da884a90c94f2f456c116e4ec7bc576
[2024-02-16 00:02:54.532] [info]  [00:02:54] [Genesis/main
[2024-02-16 00:02:54.532] [info]  /INFO] Found classpath URL: lunar-replaymod-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash e035258e9e3d271ea3fbfddc86f0b103c768f1c3
[2024-02-16 00:02:54.552] [info]  [
[2024-02-16 00:02:54.555] [info]  00:02:54] [Genesis/main/
[2024-02-16 00:02:54.556] [info]  INFO] Found classpath URL: lunar-sodium-mixins-0.1.0-SNAPSHOT-all.jar with SHA-1 hash 9c427deb82d9d88df3ef97715ae534daca1ebbfb
[2024-02-16 00:02:57.388] [info]  [00:02:57] [
[2024-02-16 00:02:57.389] [info]  Genesis
[2024-02-16 00:02:57.390] [info]  /main/INFO] Adding pre-launch library to game classpath: .\.ichor\ichormodule-libs\net_fabricmc_fabric_loader_0_15_6-lunar-0.1.0.jar
[2024-02-16 00:02:57.768] [info]  [
[2024-02-16 00:02:57.769] [info]  00:02:57
[2024-02-16 00:02:57.770] [info]  ] [
[2024-02-16 00:02:57.771] [info]  Genesis/GameBootstrap
[2024-02-16 00:02:57.772] [info]  /
[2024-02-16 00:02:57.773] [info]  main
[2024-02-16 00:02:57.774] [info]  /INFO
[2024-02-16 00:02:57.777] [info]  ] 
[2024-02-16 00:02:57.778] [info]  Launching Minecraft 1.20.4 v1_20_4 (parsed from 1.20.4)
[2024-02-16 00:02:57.780] [info]  
[2024-02-16 00:03:06.216] [info]  [
[2024-02-16 00:03:06.217] [info]  00:03:06] [Ichor/main/WARN] Fabric Mod indium is missing an external file!
[2024-02-16 00:03:06.393] [info]  LUNARCLIENT_STATUS_PREINIT
[2024-02-16 00:03:06.395] [info]  [00:03:06] [Genesis/GameBootstrap/main/INFO] Starting game!
[2024-02-16 00:03:08.866] [info]  [00:03:08] [IchorPipeline/main/INFO] Built mapping set for com.moonsworth.lunar.ichor.ORCOOCHOHOIOCCCHROHROCRHI.RCICCIHHORIHRRIOICRCOIHRR.ORCOOCHOHOIOCCCHROHROCRHI.OCRCOOCCIRIOHOCIIIHCCORCO 1745ms on thread main
[2024-02-16 00:03:08.869] [info]  
[2024-02-16 00:03:10.770] [info]  [00:03:10] [IchorPipeline/main/
[2024-02-16 00:03:10.771] [info]  INFO] Built mapping set for com.moonsworth.RCICCIHHORIHRRIOICRCOIHRR.RCICCIHHORIHRRIOICRCOIHRR.RROORRROHCICHHRRCROOIRIRR.RCICCIHHORIHRRIOICRCOIHRR 523ms on thread main
[2024-02-16 00:03:10.782] [info]  [00:03:10] [IchorPipeline/main
[2024-02-16 00:03:10.783] [info]  /INFO] Loading Mixin runtime for META_MIXIN
[2024-02-16 00:03:11.531] [info]  [00:03:11] [Ichor/mixin(META_MIXIN)/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=Unknown Service=Ichor Env=CLIENT
[2024-02-16 00:03:13.419] [info]  [
[2024-02-16 00:03:13.420] [info]  00:03:13] [IchorPipeline
[2024-02-16 00:03:13.421] [info]  /main/INFO
[2024-02-16 00:03:13.421] [info]  ] 
[2024-02-16 00:03:13.422] [info]  Loading Mixin runtime for MIXIN
[2024-02-16 00:03:13.424] [info]  
[2024-02-16 00:03:13.831] [info]  [00:03:13] [Ichor/mixin(MIXIN)/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=Unknown Service=Ichor Env=CLIENT
[2024-02-16 00:03:14.464] [info]  [
[2024-02-16 00:03:14.465] [info]  00:03:14
[2024-02-16 00:03:14.466] [info]  ] [IchorPipeline/main/INFO] Done loading Mixin runtimes in 3680ms
[2024-02-16 00:03:14.467] [info]  [00:03:14] [IchorPipeline/main/INFO] 
[2024-02-16 00:03:14.468] [info]  Setting up mixins for META_MIXIN
[2024-02-16 00:03:14.469] [info]  
[2024-02-16 00:03:14.730] [info]  [
[2024-02-16 00:03:14.732] [info]  00:03:14] [IchorPipeline/main/INFO] Setting up mixins for MIXIN
[2024-02-16 00:03:14.734] [info]  [00:03:14] [Ichor/main
[2024-02-16 00:03:14.736] [info]  /INFO] Mixin config mixins.modern.json doesn't exist in IchorClassLoader(MIXIN)
[2024-02-16 00:03:14.737] [info]  [00:03:14] [Ichor/main/INFO] Mixin config mixins.modern_lunar.json doesn't exist in IchorClassLoader(MIXIN)
[2024-02-16 00:03:15.390] [info]  [00:03:15] [IchorPipeline/main/INFO] Done registering Mixins in 923ms
[2024-02-16 00:03:15.391] [info]  [00:03:15] [IchorPipeline/main/INFO] Going to default mixins stage for META_MIXIN
[2024-02-16 00:03:20.391] [info]  [00:03:20] [IchorPipeline/main/INFO] Going to default mixins stage for MIXIN
[2024-02-16 00:03:20.420] [info]  [00:03:20] [Ichor/MixinExtras|Service(META_MIXIN)/INFO] Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-beta.10).
[2024-02-16 00:03:24.825] [info]  [00:03:24] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[2024-02-16 00:03:53.870] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Catching java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for net/optifine/render/ChunkVisibility (checked [net.optifine.render.ChunkVisibility]).
[2024-02-16 00:03:53.871] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for net/optifine/render/ChunkVisibility (checked [net.optifine.render.ChunkVisibility]).)
[2024-02-16 00:03:53.872] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Catching java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for shadersmod/client/ShadersRender (checked [shadersmod.client.ShadersRender]).
[2024-02-16 00:03:53.873] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for shadersmod/client/ShadersRender (checked [shadersmod.client.ShadersRender]).)
[2024-02-16 00:03:53.874] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Catching java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for net/optifine/shaders/ShadersRender (checked [net.optifine.shaders.ShadersRender]).
[2024-02-16 00:03:53.874] [info]  [00:03:53] [Ichor/mixin(MIXIN)/WARN] Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for net/optifine/shaders/ShadersRender (checked [net.optifine.shaders.ShadersRender]).)
[2024-02-16 00:04:03.571] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.578] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.580] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.584] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.590] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.661] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.664] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[2024-02-16 00:04:03.667] [info]  [00:04:03] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[2024-02-16 00:04:05.570] [info]  [00:04:05] [Ichor/mixin(MIXIN)/WARN] Catching java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (checked [com.viaversion.viaversion.protocol.packet.PacketWrapperImpl]).
[2024-02-16 00:04:05.570] [info]  [00:04:05] [Ichor/mixin(MIXIN)/WARN] Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: IchorClassLoader(MIXIN) couldn't find class bytes for com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (checked [com.viaversion.viaversion.protocol.packet.PacketWrapperImpl]).)
[2024-02-16 00:04:07.240] [info]  [00:04:07] [IchorPipeline/main/INFO] Mixin runtimes prepared in 51849ms
[2024-02-16 00:04:07.241] [info]  [00:04:07] [IchorPipeline/main/INFO] Initialized Mixin in 56458ms
[2024-02-16 00:04:07.247] [info]  [00:04:07] [Ichor/MixinExtras|Service(MIXIN)/INFO] Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0-beta.10).
[2024-02-16 00:04:09.420] [info]  [Bridge] Setting Bridge Implementation to com.moonsworth.lunar.OHIIOROIOICOOCHCORHOIRIRO.IOHHIIRCOCOHOHRIRHCORIOCI
[2024-02-16 00:04:11.314] [info]  [00:04:11] [Ichor/mixin(MIXIN)/INFO] liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod (unknown)->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/network/syncher/EntityDataAccessor; should be static as its target is
[2024-02-16 00:04:15.533] [info]  [Bridge] Found textures dir: C:\Users\Hayan\.lunarclient\textures
[2024-02-16 00:04:15.589] [info]  [00:04:15] [main/INFO]: Completely ignored arguments: [--workingDirectory, ., --webosrDir, C:\Users\Hayan\.lunarclient\offline\multiver\natives, --classpathDir, ., --ichorExternalFiles, Fabric-API-v1_20_4-0.91.2.jar,ReplayMod-v1_20_4-2.6.14.jar,Sodium-v1_20_4-0.5.5.jar,Iris-v1_20_4-1.6.14.jar, --ichorClassPath, common-0.1.0-SNAPSHOT-all.jar,lunar-fabric-mixins-0.1.0-SNAPSHOT-all.jar,genesis-0.1.0-SNAPSHOT-all.jar,lunar-lang.jar,lunar-emote.jar,lunar.jar,modern-0.1.0-SNAPSHOT-all.jar,lunar-replaymod-mixins-0.1.0-SNAPSHOT-all.jar,lunar-sodium-mixins-0.1.0-SNAPSHOT-all.jar, --uiDir, C:\Users\Hayan\.lunarclient\ui]
[2024-02-16 00:04:35.363] [info]  [00:04:35] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 495 milliseconds
[2024-02-16 00:04:45.097] [info]  [00:04:45] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[2024-02-16 00:04:45.189] [info]  [00:04:45] [Render thread/INFO]: Setting user: Player204
[2024-02-16 00:04:45.289] [info]  [
[2024-02-16 00:04:45.290] [info]  00:04:45] [IchorPipeline/Render thread/INFO] Launching main ModInitializer
[2024-02-16 00:04:45.291] [info]  [00:04:45] [IchorPipeline/Render thread/INFO] Launching Entrypoint(main) in Genesis
[2024-02-16 00:04:46.462] [info]  [00:04:46] [Download-2/ERROR]: Failed to fetch user properties
[2024-02-16 00:04:46.463] [info]  com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
[2024-02-16 00:04:46.463] [info]  	at Genesis/com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[?:?]
[2024-02-16 00:04:46.463] [info]  	at Genesis/com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[?:?]
[2024-02-16 00:04:46.464] [info]  	at Genesis/net.minecraft.client.Minecraft.lambda$new$2(SourceFile:467) ~[?:?]
[2024-02-16 00:04:46.464] [info]  	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
[2024-02-16 00:04:46.465] [info]  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
[2024-02-16 00:04:46.465] [info]  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
[2024-02-16 00:04:46.466] [info]  	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[2024-02-16 00:04:46.466] [info]  Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
[2024-02-16 00:04:46.467] [info]  	at Genesis/com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[?:?]
[2024-02-16 00:04:46.467] [info]  	at Genesis/com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[?:?]
[2024-02-16 00:04:46.468] [info]  	at Genesis/com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[?:?]
[2024-02-16 00:04:46.468] [info]  	... 5 more
[2024-02-16 00:04:46.907] [info]  [
[2024-02-16 00:04:46.908] [info]  00:04:46
[2024-02-16 00:04:46.909] [info]  ] [Ichor/Render thread
[2024-02-16 00:04:46.910] [info]  /INFO] Found entrypoint net.fabricmc.fabric.impl.networking.CommonPacketsImpl::init()
[2024-02-16 00:04:46.952] [info]  [
[2024-02-16 00:04:46.953] [info]  00:04:46] [IchorPipeline/Render thread
[2024-02-16 00:04:46.954] [info]  /INFO] Entrypoint(main) had 8 invokes.
[2024-02-16 00:04:46.955] [info]  [00:04:46] [IchorPipeline/Render thread/INFO] Launching client ClientModInitializer
[2024-02-16 00:04:46.956] [info]  [00:04:46] [IchorPipeline/Render thread/INFO] Launching Entrypoint(client) in Genesis
[2024-02-16 00:04:48.458] [info]  [00:04:48] [Render thread/INFO]: [STDOUT]: ReplayModBackendMixin_v1_19.onInitializeClient: initializing ReplayMod
[2024-02-16 00:04:49.132] [info]  [00:04:49] [Ichor/Render thread/INFO] Found entrypoint net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl::init()
[2024-02-16 00:04:49.230] [info]  [00:04:49] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[2024-02-16 00:04:49.233] [info]  [00:04:49] [Ichor/Render thread/INFO] Found entrypoint net.fabricmc.fabric.impl.networking.client.ClientNetworkingImpl::clientInit()
[2024-02-16 00:04:49.360] [info]  [00:04:49] [IchorPipeline/Render thread/INFO] Entrypoint(client) had 11 invokes.
[2024-02-16 00:04:49.448] [info]  [00:04:49] [Ichor/mixin(MIXIN)/WARN] Method overwrite conflict for bridge$isFancyGraphics in mixins.modern_bridge_combined.json:RROORRROHCICHHRRCROOIRIRR.HOROOOOOCCCRHOIICIIIOCHHC.RCROHRIHRCRRRCHCOCCCCIHOR from mod (unknown), previously written by com.moonsworth.lunar.OHIIOROIOICOOCHCORHOIRIRO.RCROHRIHRCRRRCHCOCCCCIHOR.RROORRROHCICHHRRCROOIRIRR.HOROOOOOCCCRHOIICIIIOCHHC.IOHHIIRCOCOHOHRIRHCORIOCI. Skipping method.
[2024-02-16 00:04:49.449] [info]  [00:04:49] [Ichor/mixin(MIXIN)/WARN] Method overwrite conflict for bridge$setFrameRateLimit in mixins.modern_bridge_combined.json:RROORRROHCICHHRRCROOIRIRR.HOROOOOOCCCRHOIICIIIOCHHC.RCROHRIHRCRRRCHCOCCCCIHOR from mod (unknown), previously written by com.moonsworth.lunar.OHIIOROIOICOOCHCORHOIRIRO.RCROHRIHRCRRRCHCOCCCCIHOR.RROORRROHCICHHRRCROOIRIRR.HOROOOOOCCCRHOIICIIIOCHHC.IOHHIIRCOCOHOHRIRHCORIOCI. Skipping method.
[2024-02-16 00:04:49.805] [info]  [00:04:49] [Render thread/INFO]: [LC] Loaded File: Options
[2024-02-16 00:04:50.545] [info]  [00:04:50] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[2024-02-16 00:04:51.325] [info]  [00:04:51] [Render thread/INFO]: OpenGL Vendor: Intel
[2024-02-16 00:04:51.326] [info]  [00:04:51] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 5500
[2024-02-16 00:04:51.327] [info]  [00:04:51] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 20.19.15.4835
[2024-02-16 00:04:51.761] [info]  [00:04:51] [Render thread/INFO]: [STDOUT]: LUNARCLIENT_STATUS_INIT
[2024-02-16 00:04:52.899] [info]  [00:04:52] [Render thread/INFO]: Debug functionality is disabled.
[2024-02-16 00:04:52.925] [info]  [00:04:52] [Render thread/INFO]: DSA support not detected.
[2024-02-16 00:04:53.014] [info]  [00:04:53] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[2024-02-16 00:04:53.015] [info]  [00:04:53] [Render thread/INFO]: Shaders are disabled
[2024-02-16 00:04:53.547] [info]  [00:04:53] [Render thread/WARN]: Missing metadata in pack file/64 !        �3Bedwars x Amaranth Revamp �8[�f32x�8].zip
[2024-02-16 00:04:56.281] [info]  [00:04:56] [Render thread/INFO]: Hardware information:
[2024-02-16 00:04:56.283] [info]  [00:04:56] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
[2024-02-16 00:04:56.284] [info]  [00:04:56] [Render thread/INFO]: GPU: Intel(R) HD Graphics 5500 (Supports OpenGL 3.3.0 - Build 20.19.15.4835)
[2024-02-16 00:04:56.285] [info]  [00:04:56] [Render thread/INFO]: OS: Windows 11 (10.0)
[2024-02-16 00:04:58.376] [info]  [00:04:58] [Render thread/INFO]: Launching LiquidBounce v0.1.4 by CCBlueX
[2024-02-16 00:04:59.265] [info]  [00:04:59] [Render thread/INFO]: Loaded language en_us
[2024-02-16 00:04:59.268] [info]  [00:04:59] [Render thread/INFO]: Loaded language de_de
[2024-02-16 00:04:59.274] [info]  [00:04:59] [Render thread/INFO]: Loaded language ja_jp
[2024-02-16 00:04:59.286] [info]  [00:04:59] [Render thread/INFO]: Loaded language zh_cn
[2024-02-16 00:04:59.291] [info]  [00:04:59] [Render thread/INFO]: Loaded language ru_ru
[2024-02-16 00:04:59.301] [info]  [00:04:59] [Render thread/INFO]: Loaded language en_pt
[2024-02-16 00:04:59.305] [info]  [00:04:59] [Render thread/INFO]: Loaded language pt_br
[2024-02-16 00:05:02.213] [info]  [00:05:02] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[2024-02-16 00:05:05.296] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'enemies'.
[2024-02-16 00:05:05.313] [info]  [00:05:05] [Render thread/INFO]: (Chat) 
[2024-02-16 00:05:05.315] [info]  [00:05:05] [Render thread/INFO]: (Chat) �f�lLiquid�9�lBounce �8? �7Auto ConfigAuto Config
[2024-02-16 00:05:05.341] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'modules'.
[2024-02-16 00:05:05.342] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'commands'.
[2024-02-16 00:05:05.344] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'friends'.
[2024-02-16 00:05:05.354] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'proxy'.
[2024-02-16 00:05:05.356] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'accounts'.
[2024-02-16 00:05:05.357] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'tabs'.
[2024-02-16 00:05:05.358] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'lang'.
[2024-02-16 00:05:05.360] [info]  [00:05:05] [Render thread/INFO]: Successfully loaded config 'storage'.
[2024-02-16 00:05:05.860] [info]  [00:05:05] [netty-websocket/INFO]: Starting Netty server...
[2024-02-16 00:05:06.427] [info]  [00:05:06] [nioEventLoopGroup-2-1/INFO]: [id: 0x9ef7d001] REGISTERED
[2024-02-16 00:05:06.431] [info]  [00:05:06] [nioEventLoopGroup-2-1/INFO]: [id: 0x9ef7d001] BIND: 0.0.0.0/0.0.0.0:15610
[2024-02-16 00:05:06.436] [info]  [00:05:06] [netty-websocket/INFO]: Netty server started on port 15610.
[2024-02-16 00:05:06.438] [info]  [00:05:06] [nioEventLoopGroup-2-1/INFO]: [id: 0x9ef7d001, L:/[0:0:0:0:0:0:0:0]:15610] ACTIVE
[2024-02-16 00:05:07.094] [info]  [00:05:07] [Render thread/INFO]: Successfully extracted default theme
[2024-02-16 00:05:07.227] [info]  [00:05:07] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[2024-02-16 00:05:07.239] [info]  [00:05:07] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[2024-02-16 00:05:07.241] [info]  [00:05:07] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> C:\Users\Hayan\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[2024-02-16 00:05:08.055] [info]  [00:05:08] [Render thread/INFO]: Checksum matches: true
[2024-02-16 00:05:08.056] [info]  [00:05:08] [Render thread/INFO]: Platform directory exists: true
[2024-02-16 00:05:08.057] [info]  [00:05:08] [Render thread/INFO]: Initializing CEF on windows_amd64...
[2024-02-16 00:05:08.609] [info]  [00:05:08] [Render thread/ERROR]: Fatal error
[2024-02-16 00:05:08.610] [info]  java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Hayan\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\windows_amd64\libGLESv2.dll
[2024-02-16 00:05:08.610] [info]  	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.611] [info]  	at java.base/java.lang.Runtime.load0(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.611] [info]  	at java.base/java.lang.System.load(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.612] [info]  	at Genesis/org.cef.CefApp.startup(CefApp.java:442) ~[?:?]
[2024-02-16 00:05:08.612] [info]  	at Genesis/net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[?:?]
[2024-02-16 00:05:08.613] [info]  	at Genesis/net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[?:?]
[2024-02-16 00:05:08.613] [info]  	at Genesis/net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[?:?]
[2024-02-16 00:05:08.614] [info]  	at Genesis/net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) [?:?]
[2024-02-16 00:05:08.615] [info]  	at Genesis/net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) [?:?]
[2024-02-16 00:05:08.615] [info]  	at Genesis/net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) [?:?]
[2024-02-16 00:05:08.616] [info]  	at Genesis/net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) [?:?]
[2024-02-16 00:05:08.617] [info]  	at Genesis/net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) [?:?]
[2024-02-16 00:05:08.617] [info]  	at Genesis/net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) [?:?]
[2024-02-16 00:05:08.618] [info]  	at Genesis/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) [?:?]
[2024-02-16 00:05:08.618] [info]  	at Genesis/net.minecraft.client.Minecraft.handler$ceo000$startClient(SourceFile:13474) [?:?]
[2024-02-16 00:05:08.619] [info]  	at Genesis/net.minecraft.client.Minecraft.<init>(SourceFile:675) [?:?]
[2024-02-16 00:05:08.619] [info]  	at Genesis/net.minecraft.client.main.Main.redirect$zbd000$impl$main$minecraft(SourceFile:639) [?:?]
[2024-02-16 00:05:08.620] [info]  	at Genesis/net.minecraft.client.main.Main.main(SourceFile:223) [?:?]
[2024-02-16 00:05:08.620] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[2024-02-16 00:05:08.621] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.621] [info]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.622] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.622] [info]  	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-02-16 00:05:08.623] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[2024-02-16 00:05:08.624] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.625] [info]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.626] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
[2024-02-16 00:05:08.626] [info]  	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.RCICCIHHORIHRRIOICRCOIHRR(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-02-16 00:05:08.627] [info]  	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-02-16 00:05:08.628] [info]  	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/35502409/36dac202-e2bf-4699-9722-f3fc84ea8b19)

**Comment by 1zun4** [comment]
Try deleting %appdata%\CCBlueX\LiquidLauncher\data\gameDir\nextgen\LiquidBounce\mcef\libraries

**Comment by 1Ecko** [comment]
i think it worked tysm!
