### ISSUE TITLE
[BUG] fix cant run on pojavlaucher

### ISSUE THREAD

**Issue by GuruTransfer** [CCBlueX/LiquidBounce#2099]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

Please fix the error that it cannot run and crashes used renderer 3.0+

### Steps to reproduce

Install all required mods, select fabric, click edit, select renderer zink or else render click play when half loaded then crash

### Client Log

```shell
[10:00:12] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[10:00:13] [ForkJoinPool-1-worker-4/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:00:14] [main/INFO]: Loading 93 mods:
	- fabric-api 0.96.1+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.13+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.1+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.63+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.0+d74054c14f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.10+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- liquidbounce 0.1.4
	- minecraft 1.20.4
	- sodium 0.5.8+mc1.20.4
	- viafabricplus 3.0.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-23w51b-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-23w51b-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.1.0
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[10:00:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:00:15] [main/INFO]: Compatibility level set to JAVA_17
[10:00:17] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[10:00:21] [main/INFO]: Searching for graphics cards...
[10:00:22] [main/WARN]: No graphics cards were found. Either you have no hardware devices supporting 3D acceleration, or something has gone terribly wrong!
[10:00:22] [main/WARN]: Unable to determine desktop session type because the environment variable XDG_SESSION_TYPE is not set! Your user session may not be configured correctly.
[10:00:22] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[10:00:25] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[10:00:25] [main/WARN]: File not found or not readable: /proc/stat
[10:00:25] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[10:00:28] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[10:00:47] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 1173 milliseconds
[10:00:59] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:00:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10:00:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:01:00] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:01:00] [Render thread/INFO]: Setting user: GuruVN
[10:01:02] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[10:01:03] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[10:01:03] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[10:01:04] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[10:01:04] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[10:01:05] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[10:01:05] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[10:01:07] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[10:01:08] [Render thread/INFO]: OpenGL Vendor: PojavLauncherTeam & ptitSeb
[10:01:08] [Render thread/INFO]: OpenGL Renderer: Adreno (TM) 610
[10:01:08] [Render thread/INFO]: OpenGL Version: 2.1 gl4es wrapper 1.1.5
[10:01:08] [Render thread/WARN]: Detected presence of environment variable POJAV_LAUNCHER, which seems to indicate we are running on Android
[10:01:08] [Render thread/ERROR]: It appears that PojavLauncher is being used with an OpenGL compatibility layer. This will likely cause severe performance issues, graphical issues, and crashes when used with Sodium. This configuration is not supported -- you are on your own!
[10:01:16] [Render thread/INFO]: Launching LiquidBounce v0.1.4 by CCBlueX
[10:01:16] [ForkJoinPool.commonPool-worker-1/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 76:54:3a:ce:87:ba:5d:a9
[10:01:17] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:37271/
[10:01:19] [Render thread/INFO]: Loaded language en_us
[10:01:19] [Render thread/INFO]: Loaded language de_de
[10:01:19] [Render thread/INFO]: Loaded language ja_jp
[10:01:19] [Render thread/INFO]: Loaded language zh_cn
[10:01:19] [Render thread/INFO]: Loaded language ru_ru
[10:01:19] [Render thread/INFO]: Loaded language en_pt
[10:01:19] [Render thread/INFO]: Loaded language pt_br
[10:01:20] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[10:01:20] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 23w51b (766)
[10:01:20] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:01:23] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[10:01:27] [Render thread/INFO]: Successfully loaded config 'enemies'.
[10:01:27] [Render thread/INFO]: (Chat) 
[10:01:27] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[10:01:27] [Render thread/INFO]: Successfully loaded config 'modules'.
[10:01:27] [Render thread/INFO]: Successfully loaded config 'commands'.
[10:01:27] [Render thread/INFO]: Successfully loaded config 'friends'.
[10:01:27] [Render thread/INFO]: Successfully loaded config 'proxy'.
[10:01:28] [Render thread/INFO]: Successfully loaded config 'accounts'.
[10:01:28] [Render thread/INFO]: Successfully loaded config 'tabs'.
[10:01:28] [Render thread/INFO]: Successfully loaded config 'lang'.
[10:01:28] [Render thread/INFO]: Successfully loaded config 'storage'.
[10:01:28] [netty-websocket/INFO]: Starting Netty server...
[10:01:28] [nioEventLoopGroup-3-1/INFO]: [id: 0xaf2f57eb] REGISTERED
[10:01:28] [nioEventLoopGroup-3-1/INFO]: [id: 0xaf2f57eb] BIND: 0.0.0.0/0.0.0.0:15538
[10:01:28] [nioEventLoopGroup-3-1/INFO]: [id: 0xaf2f57eb, L:/0.0.0.0:15538] ACTIVE
[10:01:28] [netty-websocket/INFO]: Netty server started on port 15538.
[10:01:33] [Render thread/INFO]: Successfully extracted default theme
[10:01:33] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[10:01:33] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[10:01:33] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/linux_arm64.tar.gz.sha256 -> /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/LiquidBounce/mcef/libraries/linux_arm64.tar.gz.sha256.temp
[10:01:35] [Render thread/INFO]: Checksum matches: true
[10:01:35] [Render thread/INFO]: Platform directory exists: true
[10:01:35] [Render thread/INFO]: Initializing CEF on linux_arm64...
[10:01:35] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/LiquidBounce/mcef/libraries/linux_arm64/libcef.so: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/LiquidBounce/mcef/libraries/linux_arm64/libcef.so" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace" (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:452) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$blh000$liquidbounce$startClient(class_310.java:7847) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
```

**Comment by Razzy52** [comment]
Nextgen will most likely never be supported for pojav launcher.
Either use legacy with Viaforge or buy a computer.
pretty sure this can be closed

**Comment by Aworldc** [comment]
grrrr
