### ISSUE TITLE
[BUG] Affected items

### ISSUE THREAD

**Issue by deanqkhanhcoder** [CCBlueX/LiquidBounce#2100]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

release: 0.1.4	

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

rat report from antivirus!!

### Steps to reproduce

run client
rat report!

### Client Log

```shell
[17:52:34] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[17:52:35] [ForkJoinPool-1-worker-6/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:52:48] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.6.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\toanpq\AppData\Roaming\.sklaucher\mods\liquidbounce.jar]: java.io.FileNotFoundException: C:\Users\toanpq\AppData\Roaming\.sklaucher\mods\liquidbounce.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.6.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\toanpq\AppData\Roaming\.sklaucher\mods\liquidbounce.jar]: java.io.FileNotFoundException: C:\Users\toanpq\AppData\Roaming\.sklaucher\mods\liquidbounce.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.6.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.FileNotFoundException: C:\Users\toanpq\AppData\Roaming\.sklaucher\mods\liquidbounce.jar (Operation did not complete successfully because the file contains a virus or potentially unwanted software)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1442) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1407) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:250) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:179) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:193) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.6.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### Screenshots

![Untitled](https://github.com/CCBlueX/LiquidBounce/assets/146457695/0b68b595-9005-4512-a32b-73396a18f839)

**Comment by 1zun4** [comment]
Report to Microsoft.

I already did in the past, but seems it either gets flagged again or your AV definition is outdated. Since I am a Linux user I cannot report this myself.
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/3dc36e7c-2138-444b-a940-205e12c8b4fa)
