### ISSUE TITLE
[BUG] liquidbounce gui being laggy

### ISSUE THREAD

**Issue by Solibex** [CCBlueX/LiquidBounce#2120]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-5170bcc (lastest nightly build), git-63c6b3e (lastest build)

### Operating System

Windows 10

### Minecraft Version

1.19.4

### Describe the bug

Liquidbounce main menu, client menu was laggy and unresponsive, the vanilla menu isn't laggy though.
The log would be spammed with thousands of error message every tick with the Fail to load outline shader message
Windowed mode would sometimes fix the lag problem?
(2 minutes > 294MB log file) [Couldn't send the original logs]
I was running on 300fps so it wasn't specs problem

### Steps to reproduce

Don't know 🤷 

### Client Log

```shell
[22:23:37] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[22:23:37] [main/INFO]: Loading 17 mods:
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.1.5
	- minecraft 1.20.4
[22:23:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/mcrenndjn/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:23:37] [main/INFO]: Compatibility level set to JAVA_17
[22:23:37] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[22:23:37] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[22:23:37] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[22:23:38] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[22:23:38] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[22:23:38] [main/WARN]: Disabling further attempts to query Paging File.
[22:23:39] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[22:23:39] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[22:23:42] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 101 milliseconds
[22:23:43] [main/ERROR]: FabricAPI is not installed, please install it to use the page buttons in the creative inventory
[22:23:43] [Render thread/INFO]: Environment: Environment[sessionHost=https://0.0.0.0, servicesHost=https://0.0.0.0, name=properties]
[22:23:43] [Render thread/INFO]: Setting user: hardcorelOL
[22:23:43] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[22:23:44] [Render thread/INFO]: Launching LiquidBounce v0.1.5 by CCBlueX
[22:23:44] [Render thread/INFO]: Loaded language en_us
[22:23:44] [Render thread/INFO]: Loaded language de_de
[22:23:44] [Render thread/INFO]: Loaded language ja_jp
[22:23:44] [Render thread/INFO]: Loaded language zh_cn
[22:23:44] [Render thread/INFO]: Loaded language ru_ru
[22:23:44] [Render thread/INFO]: Loaded language en_pt
[22:23:44] [Render thread/INFO]: Loaded language pt_br
[22:23:45] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[22:23:45] [Render thread/INFO]: Successfully loaded config 'enemies'.
[22:23:45] [Render thread/INFO]: (Chat) 
[22:23:45] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[22:23:45] [Render thread/INFO]: Successfully loaded config 'modules'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'commands'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'friends'.
[22:23:45] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:208) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:264) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:208) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:206) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.load(ConfigSystem.kt:149) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:157) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:173) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zba000$liquidbounce$startClient(class_310.java:3347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 17 more
[22:23:45] [Render thread/INFO]: Successfully loaded config 'proxy'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'accounts'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'tabs'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'lang'.
[22:23:45] [Render thread/INFO]: Successfully loaded config 'storage'.
[22:23:45] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.exceptions.MinecraftClientException.toAuthenticationException(MinecraftClientException.java:29) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:154) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:23:45] [Download-1/WARN]: Couldn't look up profile properties for 8c253552-1b5d-3523-b5ee-ca9dc834ede0
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://0.0.0.0/session/minecraft/profile/8c2535521b5d3523b5eeca9dc834ede0?unsigned=false due to Connection refused: no further information
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_53464(class_310.java:463) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
	... 8 more
[22:23:45] [Yggdrasil Key Fetcher/ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://0.0.0.0/publickeys due to Connection refused: no further information
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.52.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
	... 9 more
[22:23:45] [netty-websocket/INFO]: Starting Netty server...
[22:23:46] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071] REGISTERED
[22:23:46] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071] BIND: 0.0.0.0/0.0.0.0:15466
[22:23:46] [netty-websocket/INFO]: Netty server started on port 15466.
[22:23:46] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] ACTIVE
[22:23:46] [Render thread/INFO]: Successfully extracted default theme
[22:23:46] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[22:23:46] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[22:23:46] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> C:\Users\mcrenndjn\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[22:23:47] [Render thread/INFO]: Checksum matches: true
[22:23:47] [Render thread/INFO]: Platform directory exists: true
[22:23:47] [Render thread/INFO]: Initializing CEF on windows_amd64...
[22:23:47] [Render thread/INFO]: [STDOUT]: initialize on Thread[Render thread,5,main] with library path C:\Users\mcrenndjn\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\windows_amd64
[22:23:47] [Render thread/INFO]: Chromium Embedded Framework initialized
[22:23:47] [Render thread/INFO]: Browser is ready.
[22:23:47] [Render thread/INFO]: Successfully loaded client!
[22:23:47] [Render thread/INFO]: Reloading ResourceManager: vanilla
[22:23:47] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x1fd1e50c, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11226]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ COMPLETE
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x56bec8cc, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11228]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ COMPLETE
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x27c27ed3, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11229]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0xd36ceff9, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11230]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x3da4919a, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11231]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ COMPLETE
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x7f8549ab, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11232]
[22:23:48] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ COMPLETE
[22:23:48] [Render thread/INFO]: Loading Discord IPC configuration...
[22:23:48] [IO-Worker-1/INFO]: Requesting to login into Mojang...
[22:23:49] [Render thread/INFO]: Successfully connected to Discord RPC.
[22:23:49] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[22:23:49] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[22:23:49] [Render thread/WARN]: Missing sound for event: minecraft:entity.generic.wind_burst
[22:23:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[22:23:49] [Render thread/INFO]: Sound engine started
[22:23:49] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22:23:49] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[22:23:49] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:23:49] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:23:49] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[22:23:49] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:23:49] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[22:23:49] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:23:49] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:23:49] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[22:23:49] [Render thread/ERROR]: Failed to load outline shader
java.io.FileNotFoundException: liquidbounce:shaders/post/outline_shader.json
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1256(class_279.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at net.ccbluex.liquidbounce.render.engine.MinecraftFramebufferShader.load(MinecraftFramebufferShader.kt:38) ~[liquidbounce.jar:?]
	at net.minecraft.class_761.handler$zdo000$liquidbounce$onLoadEntityOutlineShader(class_761.java:3201) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3296(class_761.java:523) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_14491(class_761.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
[22:23:49] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[22:23:49] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:23:49] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:23:49] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[22:23:49] [Render thread/INFO]: Loading fonts...
[22:23:49] [Render thread/INFO]: Loading queued font Montserrat
[22:23:49] [Render thread/INFO]: Loaded fonts successfully!
[22:23:50] [Render thread/INFO]: Loaded Discord IPC configuration.
[22:23:50] [Render thread/INFO]: Refreshing local IP info...
[22:23:50] [Render thread/INFO]: Loading heads...
[22:23:50] [nioEventLoopGroup-5-1/INFO]: IP Info [VN, AS45543 SaiGon Tourist cable Televition Company]
[22:23:52] [Render thread/INFO]: Successfully loaded 956 heads from the database
[22:23:52] [Render thread/INFO]: Loading settings list from API...
[22:23:52] [Render thread/INFO]: Loaded 24 settings from API.
[22:23:52] [Render thread/INFO]: Successfully loaded 232 cape carriers.
[22:23:52] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7UI desync detected, it should now be fixed!UI desync detected, it should now be fixed!
[22:23:52] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@21f6b0d5, url=http://localhost:15466/default/#/)
[22:23:52] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ: [id: 0x04c961db, L:/[0:0:0:0:0:0:0:1]:15466 - R:/[0:0:0:0:0:0:0:1]:11245]
[22:23:52] [nioEventLoopGroup-2-1/INFO]: [id: 0xde745071, L:/[0:0:0:0:0:0:0:0]:15466] READ COMPLETE
[22:23:55] [Render thread/ERROR]: ########## GL ERROR ##########
[22:23:55] [Render thread/ERROR]: @ Render
[22:23:55] [Render thread/ERROR]: 65539: Invalid standard cursor 0x00000000
[22:23:59] [Render thread/INFO]: Shutting down client...
[22:23:59] [Render thread/INFO]: Successfully shutdown browser.
[22:23:59] [Render thread/INFO]: Successfully saved config 'enemies'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'modules'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'commands'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'friends'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'proxy'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'accounts'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'tabs'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'lang'.
[22:23:59] [Render thread/INFO]: Successfully saved config 'storage'.
[22:23:59] [Render thread/INFO]: Stopping!
[22:23:59] [Render thread/INFO]: Successfully saved config 'modules'.
```

### Screenshots

https://github.com/CCBlueX/LiquidBounce/assets/92078408/f4126d34-35b7-439e-9062-2f301f7334d1

**Comment by larryngton** [comment]
try restarting (lmao) or running .client integration reset (it fixes most gui issues)

**Comment by Solibex** [comment]
Already tried restarting for a few times.
.client integration reset does nothing at all
Probably some issue with drivers?

**Comment by superblaubeere27** [comment]
> Already tried restarting for a few times. .client integration reset does nothing at all Probably some issue with drivers?

Hmm, that is odd because we just run a chromium process under the hood.

If you open chrome normally (on the same drive as the .minecraft folder) does it lag?

**Comment by Solibex** [comment]
Chrome works fine for me no delays

**Comment by rusian85** [comment]
i had the same problem but it in 1.20.4 (latest build) and i had good pc (rtx 4060ti & ryzen 7 7700x)

**Comment by superblaubeere27** [comment]
> i had the same problem but it in 1.20.4 (latest build) and i had good pc (rtx 4060ti & ryzen 7 7700x)

how is the cpu/memory usage in the task manager?

**Comment by 1zun4** [comment]
I will close this issue since even my AMD Ryzen 7 5700U iGPU can handle the GUI with 150fps+ and zero delay, as well as a new Theme Implementation was pushed (which might have fixes this issue). If this issue persists try creating a new issue, but honestly there is not much to change to the fact that Minecraft and JCEF requires performance and if you are running a potato or bad drivers, there is nothing we can do.
