### ISSUE TITLE
LiquidBounce Crashing After Launching. Failed to load font Montserrat

### ISSUE THREAD

**Issue by Blazebreaker0** [CCBlueX/LiquidBounce#2150]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

macOS

### Minecraft Version

1.20.4

### Describe the bug

I press LaunchBounce and it takes me to the loading screen of Minecraft and then it crashes. 

### Steps to reproduce

-Go to LiquidBounce Launcher
-Press Launch LiquidBounce
-Minecraft with LiquidBounce will start loading
-Game crashes

### Client Log

```shell
ethod_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0
.15.1.jar:?]
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

### Screenshots

![tempImagexk4m2T](https://github.com/CCBlueX/LiquidBounce/assets/161091649/38302648-6215-45d4-9a68-5b47bf86ac23)
![tempImagewcDg39](https://github.com/CCBlueX/LiquidBounce/assets/161091649/3648c26a-b8bc-4818-946b-67d08f6f97ca)

**Comment by Blazebreaker0** [comment]
Is there anyway I can fix this

**Comment by 1zun4** [comment]
Yes figure out what is blocking the download connection.

**Comment by superblaubeere27** [comment]
and maybe delete LiquidBounce's font folder

**Comment by Pxttyy** [comment]
> Is there anyway I can fix this

I have the same issue, Did yo figure out what's causing it?

**Comment by Blazebreaker0** [comment]
I don't really know how to check what's blocking the internet so I need to figure that out first. I am on a Mac so it's a little more difficult to figure this stuff out.

**Comment by Fedoba** [comment]
Got it guys! It was the firewall which was blocking the connection. Just allow LiquidLaucher in the Windows Firewall Settings (MAKE SURE BOTH PUBLIC AND PRIVATE ARE CHECKED!). Enjoy!
![image_2024-02-27_220806738](https://github.com/CCBlueX/LiquidBounce/assets/156590137/901078ce-fac6-4fb7-9e21-1a2ccee34076)

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/2178
