### ISSUE TITLE
[BUG] Game crashes for no reason

### ISSUE THREAD

**Issue by Nesndnnensn** [CCBlueX/LiquidBounce#2160]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b88

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Every few random times, my game keeps crashing when I do things that doesn't usually cause crashes. 

### Steps to reproduce

Not sure how to reproduce. 

### Client Log

```shell
[18:27:53] [Client thread/INFO]: Setting user: ThisIsARobbery
[18:28:02] [Client thread/WARN]: Skipping bad option: streamPreferredServer:
[18:28:03] [Client thread/INFO]: LWJGL Version: 3.3.1 SNAPSHOT
[18:28:03] [Client thread/INFO]: [STDOUT]: LWJGLX: GL caps init
[18:28:04] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[18:28:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.Pointer$Default.<init>(Pointer.java:88)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.CustomBuffer.<init>(CustomBuffer.java:25)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.StructBuffer.<init>(StructBuffer.java:20)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWImage$Buffer.<init>(GLFWImage.java:294)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.setIcon(Display.java:946)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at bhz.av(SourceFile:661)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at bhz.aq(SourceFile:456)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at bhz.a(SourceFile:404)
[18:28:04] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:28:04] [Client thread/INFO]: [STDOUT]: LWJGLX: ready-handle context created
[18:28:05] [Client thread/INFO]: [STDOUT]: Grab: false
[18:28:06] [Client thread/WARN]: Removed selected resource pack !  §3Penguin §7[§f16x§7].zip because it's no longer compatible
[18:28:06] [Client thread/WARN]: Removed selected resource pack Grass Colormap Overlay because it's no longer compatible
[18:28:06] [Client thread/INFO]: Reloading ResourceManager: Default
[18:28:07] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:28:08] [Thread-2/INFO]: Initializing LWJGL OpenAL
[18:28:08] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:28:08] [Thread-2/INFO]: OpenAL initialized.
[18:28:08] [Sound Library Loader/INFO]: Sound engine started
[18:28:32] [Client thread/INFO]: Created: 1024x512 textures-atlas
[18:28:45] [Client thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':
dlopen failed: library "libfliteWrapper.so" not found
dlopen failed: library "libfliteWrapper.so" not found
Native library (linux-aarch64/libfliteWrapper.so) not found in resource path ([file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.12/1.12.jar])
[18:28:47] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:28:55] [Client thread/INFO]: Stopping!
[18:28:55] [Client thread/INFO]: SoundSystem shutting down...
[18:28:55] [Client thread/ERROR]: Error in class 'SoundSystem'
[18:28:55] [Client thread/ERROR]: Problem during Library.cleanup()!
[18:28:55] [Client thread/INFO]: Ignoring errors... continuing clean-up.
[18:28:55] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
```

**Comment by EclipsesDev** [comment]
wait ur using it on pojav? welp I've never use pojav before, but this is most likely memory allocation issues, also does it only happen on this specific version or older version too?

**Comment by 1zun4** [comment]
uses pojav. "for no reason", never seen this error either.

**Comment by Nesndnnensn** [comment]
> wait ur using it on pojav? welp I've never use pojav before, but this is most likely memory allocation issues, also does it only happen on this specific version or older version too?

It's the most latest of pojav

**Comment by Nesndnnensn** [comment]
But memory might be right, it's at like 1740MB

**Comment by EclipsesDev** [comment]
Not sure with this kind of error, since I never use lb pojav version

**Comment by EclipsesDev** [comment]
> > wait ur using it on pojav? welp I've never use pojav before, but this is most likely memory allocation issues, also does it only happen on this specific version or older version too?
> 
> It's the most latest of pojav

Maybe try lowering the version, see if that help
