### ISSUE TITLE
[BUG] Cant load library.

### ISSUE THREAD

**Issue by corzyy** [CCBlueX/LiquidBounce#2172]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5 (git-06b8f4b) 

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

when i start liquidbounce via the liquidlauncher, it cant load a libary and it crashes.

![image](https://github.com/CCBlueX/LiquidBounce/assets/96943942/c064c3ff-e042-4148-8a37-25b3b43dd966)

### Steps to reproduce

Start Liquidbounce

https://github.com/CCBlueX/LiquidBounce/assets/96943942/f4e3aab5-b31f-4d51-b6cc-c78fc89ddc36

### Client Log

```shell
dbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:168) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:174) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bmi000$liquidbounce$startClient(class_310.java:9347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launc
h(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

**Comment by 1zun4** [comment]
Delete the LiquidBounce folder and try again. Might use a VPN to resolve connection issues.
