### ISSUE TITLE
Launching Liquid Bounce on my mac didn't work[BUG]

### ISSUE THREAD

**Issue by Gradyruan** [CCBlueX/LiquidBounce#2173]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

macOS

### Minecraft Version

1.20.4

### Describe the bug

When I launched Liquid Bounce it opened "Java" and when it was just about to load in, it crashed and gave me an error on the Liquid Launcher.

### Steps to reproduce

Please fix

### Client Log

```shell
[10:09:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[10:09:02] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:09:02] [main/INFO]: Loading 97 mods:
	- baritone 1.10.2
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- fabric-api 0.91.3+1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14+78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.
```

### Screenshots

<img width="2048" alt="Screenshot 2024-02-25 at 10 10 02 AM" src="https://github.com/CCBlueX/LiquidBounce/assets/124465586/d186b58b-7871-495a-9dfd-958d86f516ab">
<img width="2048" alt="Screenshot 2024-02-25 at 10 09 43 AM" src="https://github.com/CCBlueX/LiquidBounce/assets/124465586/bfd7692b-1af1-4484-9a1b-2b946b8fbd4a">

**Comment by Gradyruan** [comment]
ethod_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0
.15.1.jar:?]
An error with the client occourd:
Process exited with non-zero exit code: 1.

**Comment by 1zun4** [comment]
use a vpn or smth, your download is being blocked.
