### ISSUE TITLE
[BUG] NOT FOUND libGLESv2.dll 

### ISSUE THREAD

**Issue by ArroySigma1** [CCBlueX/LiquidBounce#2203]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 10

### Minecraft Version

1.20.4 Fabric

### Describe the bug

Then i was Luanch liquidBounce NextGen then 1 error comming

### Steps to reproduce

open tlegancy click on version selecet 1.20.4 fabric go to game directory click on mods past there liquidbounce nextgen.jar and close the window and go to tl legancy and click on start then liquidbounce open you seee error witch is i give the screenshot 

Thankyou.

### Client Log

```shell
[08:59:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[08:59:02] [main/INFO]: Loading 68 mods:
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.1.4
	- minecraft 1.20.4
[08:59:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Users/Laptop/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:59:03] [main/INFO]: Compatibility level set to JAVA_17
[08:59:05] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[08:59:05] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[08:59:06] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08:59:11] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[08:59:28] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 1657 milliseconds
[08:59:34] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services]
[08:59:34] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[08:59:34] [Render thread/INFO]: Setting user: HorizonYT5
[08:59:36] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[08:59:37] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[08:59:39] [Render thread/INFO]: Launching LiquidBounce v0.1.4 by CCBlueX
[08:59:40] [Render thread/INFO]: Loaded language en_us
[08:59:40] [Render thread/INFO]: Loaded language de_de
[08:59:40] [Render thread/INFO]: Loaded language ja_jp
[08:59:40] [Render thread/INFO]: Loaded language zh_cn
[08:59:40] [Render thread/INFO]: Loaded language ru_ru
[08:59:40] [Render thread/INFO]: Loaded language en_pt
[08:59:40] [Render thread/INFO]: Loaded language pt_br
[08:59:41] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[08:59:42] [Render thread/INFO]: Successfully loaded config 'enemies'.
[08:59:42] [Render thread/INFO]: (Chat) 
[08:59:42] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[08:59:42] [Render thread/INFO]: Successfully loaded config 'modules'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'commands'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'friends'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'proxy'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'accounts'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'tabs'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'lang'.
[08:59:42] [Render thread/INFO]: Successfully loaded config 'storage'.
[08:59:43] [netty-websocket/INFO]: Starting Netty server...
[08:59:43] [nioEventLoopGroup-2-1/INFO]: [id: 0xdfdf4334] REGISTERED
[08:59:43] [nioEventLoopGroup-2-1/INFO]: [id: 0xdfdf4334] BIND: 0.0.0.0/0.0.0.0:15841
[08:59:43] [nioEventLoopGroup-2-1/INFO]: [id: 0xdfdf4334, L:/[0:0:0:0:0:0:0:0]:15841] ACTIVE
[08:59:43] [netty-websocket/INFO]: Netty server started on port 15841.
[08:59:44] [Render thread/INFO]: Successfully extracted default theme
[08:59:44] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[08:59:44] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[08:59:44] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/windows_amd64.tar.gz.sha256 -> D:\Users\Laptop\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\windows_amd64.tar.gz.sha256.temp
[08:59:46] [Render thread/INFO]: Checksum matches: true
[08:59:46] [Render thread/INFO]: Platform directory exists: true
[08:59:46] [Render thread/INFO]: Initializing CEF on windows_amd64...
[08:59:46] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: D:\Users\Laptop\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\windows_amd64\libGLESv2.dll: Can't find dependent libraries
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:442) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znk000$liquidbounce$startClient(class_310.java:6347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
```

### Screenshots

![Screenshot 2024-03-01 090015](https://github.com/CCBlueX/LiquidBounce/assets/160377560/d6446082-62cb-4075-8412-f82b53459581)

**Comment by 1zun4** [comment]
Try deleting `D:\Users\Laptop\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\windows_amd64` and repeat... Your download has failed.

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/pull/2178
