### ISSUE TITLE
[BUG] WE CANT JOIN THE GAME!!!!!!

### ISSUE THREAD

**Issue by NickSuengMin** [CCBlueX/LiquidBounce#2231]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.3

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I Dont Know

### Steps to reproduce

I Dont Know

### Client Log

```shell
ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:165) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:111) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bbg000$liquidbounce$startClient(class_310.java:8347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.kn
ot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

**Comment by 1zun4** [comment]
0.1.3? Outdated version. Also post full log.
