### ISSUE TITLE
[BUG] Sorry is second and help 

### ISSUE THREAD

**Issue by NickSuengMin** [CCBlueX/LiquidBounce#2236]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.4

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

how pls

### Steps to reproduce

I dont know

### Client Log

```shell
ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$bmh000$liquidbounce$startClient(class_310.java:9347) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.kn
ot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[12:08:05] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

### Screenshots

![Screenshot (75)](https://github.com/CCBlueX/LiquidBounce/assets/162038804/e6a01f3e-48cd-41f3-b333-26cee400c6dc)

**Comment by 1zun4** [comment]
Delete the folder that it shows in message and try again. Might check if your Windows firewall is blocking connections.

**Comment by NickSuengMin** [comment]
where

**Comment by NickSuengMin** [comment]
> Delete the folder that it shows in message and try again. Might check if your Windows firewall is blocking connections.

what folder

**Comment by NickSuengMin** [comment]
> Delete the folder that it shows in message and try again. Might check if your Windows firewall is blocking connections.

hey

**Comment by NickSuengMin** [comment]
> Delete the folder that it shows in message and try again. Might check if your Windows firewall is blocking connections.

**Comment by NickSuengMin** [comment]
óiayfaiof

**Comment by superblaubeere27** [comment]
sdfghjklbndsfgjm ,g

**Comment by superblaubeere27** [comment]
> > Delete the folder that it shows in message and try again. Might check if your Windows firewall is blocking connections.
> 
> what folder

**Comment by superblaubeere27** [comment]
The folder is `%appdata%/.minecraft/LiquidBounce/mcef`. Try to delete it.

Btw, we see your issue and are working on it when we have time, no need to push your issue for the 5th time. One time is okay if you think we forgot about you, but holy fuck

**Comment by 1zun4** [comment]
We gave you different ways to solve this issue. I will consider this as closed now.
