### ISSUE TITLE
[BUG] liquidbounce next gen on iOS doesnt work

### ISSUE THREAD

**Issue by Repo2i** [CCBlueX/LiquidBounce#2247]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Latest comit

### Operating System

macOS

### Minecraft Version

1.20.4

### Describe the bug

When launching and error -1

### Steps to reproduce

Well just place liquidbounc and their dependencies

### Client Log

```shell
[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 3.0-development
[Pre-Init] Commit: b92f438 (feat/modpack)
[Pre-Init] Device: iPad (8th generation)
[Pre-Init] iPadOS 16.1.1 (20B101) (TrollStore)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: YES
* com.apple.developer.kernel.increased-memory-limit: YES
* com.apple.private.security.no-sandbox: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (soal)
[Pre-Init] Beginning migration for file "overrideargs.txt"
[Pre-Init] File "overrideargs.txt" was already migrated
[Pre-Init] Beginning migration for file "custom_env.txt"
[Pre-Init] File "custom_env.txt" was already migrated
2024-03-05 14:01:51.833 PojavLauncher[2169:167079] -[UIPickerView setFrame:]: invalid size {320, 216} pinned to {320, 216} 
[VersionList] Got 736 versions
Discovering servers...
[MCDL] insertSafety: how to insert assetIndex?
[MCDL] insertSafety: how to insert assets?
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-x86
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-linux
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos-arm64
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-arm64
[MDCL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-x86
[MCDL] Unknown artifact object for org.ow2.asm:asm:9.6, attempting to generate one
[MCDL] Unknown artifact object for org.ow2.asm:asm-analysis:9.6, attempting to generate one
[MCDL] Unknown artifact object for org.ow2.asm:asm-commons:9.6, attempting to generate one
[MCDL] Unknown artifact object for org.ow2.asm:asm-tree:9.6, attempting to generate one
[MCDL] Unknown artifact object for org.ow2.asm:asm-util:9.6, attempting to generate one
[MCDL] Unknown artifact object for net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5, attempting to generate one
[MCDL] Unknown artifact object for net.fabricmc:intermediary:1.20.4, attempting to generate one
[MCDL] Unknown artifact object for net.fabricmc:fabric-loader:0.15.7, attempting to generate one
Stopped discovering servers.
Discovering servers...
Successfully set Jetsam task limit
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Reading custom environment variables
[JavaLauncher] Warning: skipped empty value custom env variable: 
[JavaLauncher] RENDERER is set to libgl4es_114.dylib
[JavaLauncher] Looking for Java 17 or later
[JavaLauncher] JAVA_HOME has been set to /private/var/containers/Bundle/Application/359E0C8F-292A-4C42-9FC7-50945853C97A/PojavLauncher.app/java_runtimes/java-17-openjdk
[JavaLauncher] Max RAM allocation is set to 1026 MB
[JavaLauncher] Reading custom JVM flags
[Init] Found JLI lib
[Init] Calling JLI_Launch
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Launching Minecraft fabric-loader-0.15.7-1.20.4
Args init finished. Now starting game
2024-03-05 14:01:57,547 main ERROR appender Console has no parameter that matches element Policies
[14:01:57] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[14:01:57] [ForkJoinPool-1-worker-5/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:01:58] [main/INFO]: Loading 94 mods:
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.1.4
	- lithium 0.12.1
	- minecraft 1.20.4
	- sodium 0.5.8+mc1.20.4
	- viafabricplus 3.0.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-23w51b-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-23w51b-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.1.0
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[14:01:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:01:58] [main/INFO]: Compatibility level set to JAVA_17
[14:01:58] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[14:01:58] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[14:02:00] [main/INFO]: Searching for graphics cards...
[14:02:00] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[14:02:00] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=UNKNOWN, name=unknown, version=unknown]
[14:02:01] [main/WARN]: Failed sysctl call: hw.packages, Error code: 1
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
[14:02:01] [main/WARN]: Failed sysctl call: vm.swapusage, Error code: 1
[14:02:02] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[14:02:08] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 445 milliseconds
[14:02:11] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:02:11] [Render thread/INFO]: Setting user: _____4_______19
[14:02:12] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[14:02:12] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[14:02:12] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[14:02:13] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[14:02:13] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[14:02:13] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jul 26 2023 14:23:23
LIBGL: Using GLES 2.0 backend
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Subtract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_shader_texture_lod detected and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Extension GL_OES_get_program_binary  detected and used
LIBGL: Number of supported Program Binary Format: 1
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 31
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Hardware vendor is Google Inc. (Apple)
LIBGL: GLSL 300 es supported and used
LIBGL: Max Color Attachments: 8 / Draw buffers: 8
LIBGL: Targeting OpenGL 2.1
LIBGL: No hack in shader converter to define overloaded function with int
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: Force normals to be normalized on FPE shaders
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal
EGLBridge: Binding to OpenGL ES
[14:02:13] [Render thread/INFO]: OpenGL Vendor: PojavLauncherTeam & ptitSeb
[14:02:13] [Render thread/INFO]: OpenGL Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple A12 GPU, Version 16.1.1 (Build 20B101))
[14:02:13] [Render thread/INFO]: OpenGL Version: 2.1 gl4es wrapper 1.1.5
[14:02:13] [Render thread/WARN]: Detected presence of environment variable POJAV_LAUNCHER, which seems to indicate we are running on Android
[14:02:13] [Render thread/ERROR]: It appears that PojavLauncher is being used with an OpenGL compatibility layer. This will likely cause severe performance issues, graphical issues, and crashes when used with Sodium. This configuration is not supported -- you are on your own!
[14:02:14] [Render thread/WARN]: Failed sysctl call: hw.packages, Error code: 1
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[14:02:14] [Render thread/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
[14:02:15] [Render thread/INFO]: Launching LiquidBounce v0.1.4 by CCBlueX
[14:02:15] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:49608/
[14:02:16] [Render thread/INFO]: Loaded language en_us
[14:02:16] [Render thread/INFO]: Loaded language de_de
[14:02:16] [Render thread/INFO]: Loaded language ja_jp
[14:02:16] [Render thread/INFO]: Loaded language zh_cn
[14:02:16] [Render thread/INFO]: Loaded language ru_ru
[14:02:16] [Render thread/INFO]: Loaded language en_pt
[14:02:16] [Render thread/INFO]: Loaded language pt_br
[14:02:16] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[14:02:16] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 23w51b (766)
[14:02:16] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:02:16] [Render thread/WARN]: KeepSprint is missing fallback description key liquidbounce.module.keepSprint.description
[14:02:17] [Render thread/INFO]: Successfully loaded config 'enemies'.
[14:02:17] [Render thread/INFO]: (Chat) 
[14:02:17] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[14:02:17] [Render thread/INFO]: Successfully loaded config 'modules'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'commands'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'friends'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'proxy'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'accounts'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'tabs'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'lang'.
[14:02:17] [Render thread/INFO]: Successfully loaded config 'storage'.
[14:02:17] [netty-websocket/INFO]: Starting Netty server...
[14:02:17] [nioEventLoopGroup-3-1/INFO]: [id: 0x27e76a41] REGISTERED
[14:02:17] [nioEventLoopGroup-3-1/INFO]: [id: 0x27e76a41] BIND: 0.0.0.0/0.0.0.0:15924
[14:02:17] [nioEventLoopGroup-3-1/INFO]: [id: 0x27e76a41, L:/[0:0:0:0:0:0:0:0]:15924] ACTIVE
[14:02:17] [netty-websocket/INFO]: Netty server started on port 15924.
[14:02:18] [Render thread/INFO]: Successfully extracted default theme
[14:02:18] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[14:02:18] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[14:02:18] [Render thread/INFO]: https://dl.liquidbounce.net/resources/java-cef-builds/e91a133673f9524c5f7db9bdbad1aff61b3887d7/macos_arm64.tar.gz.sha256 -> /private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64.tar.gz.sha256.temp
[14:02:19] [Render thread/INFO]: Checksum matches: true
[14:02:19] [Render thread/INFO]: Platform directory exists: true
[14:02:19] [Render thread/INFO]: Initializing CEF on macos_arm64...
[14:02:19] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: /private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib: dlopen(/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib, 0x0001): tried: '/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib' (mach-o file (/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib), but incompatible platform (have 'macOS', need 'iOS')), '/private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/lib
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:449) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.CefUtil.init(CefUtil.java:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:73) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:66) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:166) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:170) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$cde000$liquidbounce$startClient(class_310.java:7847) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:76) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:105) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:54) ~[launcher.jar:?]


missing software! (we will try basic console input)
 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed)
or xterm + bash (opens console for basic input)
or existing console for basic input


LiquidBounce Nextgen

LiquidBounce Nextgen has encountered an error!
Please report this issue to the developers on GitHub.

Include the following information:
OS: Mac OS X (aarch64)
Java: 17.0.11-internal
Client Version: 0.1.4 (git-63c6b3e)

Error: /private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib: dlopen(/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib, 0x0001): tried: /private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib (mach-o file (/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/libraries/macos_arm64/jcef_app.app/Contents/Java/libjcef.dylib), but incompatible platform (have macOS, need iOS)), /private/preboot/Cryptexes/OS/private/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/LiquidBounce/mcef/lib
Error Type: java.lang.UnsatisfiedLinkError

Include your game log, which can be found at:
/var/mobile/Containers/Data/Application/E03A1DE4-9363-46DC-82F3-AB511BBC692C/Documents/instances/soal/logs/latest.log

press enter to continue 

exit(1) called
Stopped discovering servers.
Discovering servers...
Stopped discovering servers.
Discovering servers...
```

**Comment by 1zun4** [comment]
No support.

**Comment by Repo2i** [comment]
Well iOS is similar to macOS

**Comment by 1zun4** [comment]
No it is not.
