### ISSUE TITLE
[BUG] LiquidBounce can't create a Minecraft Window on Linux. 

### ISSUE THREAD

**Issue by Paindeluxe** [CCBlueX/LiquidBounce#2346]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5 commit 0d9bda9

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

I tried starting LiquidBounce 0.1.5 on Minecraft 1.20.4 with Fabric Language Kotlin as the other loaded mod.
I ended up received an Error about missing "X server" or "$DISPLAY"

I am using the latest Mesa Drivers with Wayland and my Minecraft Launcher is Prism Launcher 8.2.

### Steps to reproduce

1. Install LiquidBounce 0.1.5 commit 0d9bda9 with Fabric Language Kotlin.
2. Start Minecraft 1.20.4.
3. Crash.

### Client Log

```shell
[18:06:25] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[18:06:25] [main/INFO]: Loading 17 mods:
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.1.5
	- minecraft 1.20.4
[18:06:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/pain/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:06:25] [main/INFO]: Compatibility level set to JAVA_17
[18:06:25] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[18:06:25] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[18:06:26] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[18:06:26] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[18:06:28] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 105 milliseconds
[18:06:29] [main/ERROR]: FabricAPI is not installed, please install it to use the page buttons in the creative inventory
[18:06:30] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:06:30] [Render thread/INFO]: Setting user: Pain_deluxe
[18:06:30] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[18:06:30] [Render thread/WARN]: Removed resource pack fabric from options because it doesn't seem to exist anymore
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
[18:06:31] [Render thread/INFO]: Launching LiquidBounce v0.1.5 by CCBlueX
[18:06:31] [Render thread/INFO]: Loaded language en_us
[18:06:31] [Render thread/INFO]: Loaded language de_de
[18:06:31] [Render thread/INFO]: Loaded language ja_jp
[18:06:31] [Render thread/INFO]: Loaded language zh_cn
[18:06:31] [Render thread/INFO]: Loaded language ru_ru
[18:06:31] [Render thread/INFO]: Loaded language en_pt
[18:06:31] [Render thread/INFO]: Loaded language pt_br
[18:06:31] [Render thread/WARN]: SmartEat is missing fallback description key liquidbounce.module.smartEat.description
[18:06:31] [Render thread/INFO]: Successfully extracted default theme
[18:06:31] [Render thread/INFO]: Inserted 9 components
[18:06:31] [Render thread/INFO]: Successfully loaded config 'enemies'.
[18:06:31] [Render thread/INFO]: (Chat) 
[18:06:31] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[18:06:31] [Render thread/INFO]: Successfully loaded config 'modules'.
[18:06:31] [Render thread/INFO]: Successfully loaded config 'commands'.
[18:06:31] [Render thread/INFO]: Successfully loaded config 'friends'.
[18:06:31] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:218) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:273) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:228) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:201) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.load(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zbc000$liquidbounce$startClient(class_310.java:3351) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 21 more
[18:06:32] [Render thread/INFO]: Successfully loaded config 'proxy'.
[18:06:32] [Render thread/INFO]: Successfully loaded config 'accounts'.
[18:06:32] [Render thread/INFO]: Successfully loaded config 'tabs'.
[18:06:32] [Render thread/INFO]: Successfully loaded config 'lang'.
[18:06:32] [Render thread/INFO]: Successfully loaded config 'storage'.
[18:06:32] [Render thread/INFO]: Successfully loaded config 'theme'.
[18:06:32] [netty-websocket/INFO]: Starting Netty server...
[18:06:32] [epollEventLoopGroup-2-1/INFO]: [id: 0x24b78fa3] REGISTERED
[18:06:32] [epollEventLoopGroup-2-1/INFO]: [id: 0x24b78fa3] BIND: 0.0.0.0/0.0.0.0:15742
[18:06:32] [netty-websocket/INFO]: Netty server started on port 15742.
[18:06:32] [epollEventLoopGroup-2-1/INFO]: [id: 0x24b78fa3, L:/[0:0:0:0:0:0:0:0%0]:15742] ACTIVE
[18:06:33] [Render thread/INFO]: java-cef commit: e91a133673f9524c5f7db9bdbad1aff61b3887d7
[18:06:33] [Render thread/INFO]: Task: Downloading Checksum with progress 0.0 %
[18:06:34] [Render thread/INFO]: Checksum matches: true
[18:06:34] [Render thread/INFO]: Platform directory exists: true
[18:06:34] [Render thread/INFO]: Initializing CEF on linux_amd64...
[18:06:34] [Render thread/INFO]: [STDOUT]: initialize on Thread[Render thread,5,main] with library path /home/pain/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.20.4/.minecraft/LiquidBounce/mcef/libraries/linux_amd64
[0311/180635.019523:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[0311/180635.019565:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
Process was killed by user.
```

**Comment by 1zun4** [comment]
No idea.

**Comment by Paindeluxe** [comment]
I think it's important to say that I have had similar issues with older versions of minecraft before.
So it could be a me problem...

**Comment by dudethis** [comment]
It might be a permissions problem, you could try running it as admin

**Comment by Paindeluxe** [comment]
As of commit [6a13995](https://github.com/CCBlueX/LiquidBounce/commit/6a13995d04bd1e72719ae5fe5cc40153e9e485b8) my issue disappeared. I have not tested any other nightly builds, but I am glad to be able to use LiquidBounce again.

PS: I have no idea what fixed my issue

**Comment by be4dev** [comment]
> As of commit [6a13995](https://github.com/CCBlueX/LiquidBounce/commit/6a13995d04bd1e72719ae5fe5cc40153e9e485b8) my issue disappeared. I have not tested any other nightly builds, but I am glad to be able to use LiquidBounce again.
> 
> PS: I have no idea what fixed my issue

it is most likely your wayland issue (may be you forgot to export some value)
