### ISSUE TITLE
Cannot Use baritone Forge 1.12.14 with lb 1.12.2

### ISSUE THREAD

**Issue by AiryXV** [CCBlueX/LiquidBounce#239]
**Describe the bug**
THe BUg is that we cannot use baritone 1.2.14 with liquid bounce , I tried to load it as a forge mod and also checked the logs.
logs are at the end of the msg

**To Reproduce**
1. Download Baritone 1.2.14
2.Drag it into the mods folder 
3.Load Minecraft
4.The Game should return error code : 1 

**Screenshots**
none

**Additional information:**
 - OS: WIndows 10 Insiders 
 - latest 1.12.2 version
 - 1.12.2
![Screenshot 2020-10-04 184316](https://user-images.githubusercontent.com/66723772/95016586-7c374480-0671-11eb-9cb2-e4c6fda2a0d0.png)

Last 15 lines for errors from the logs:
`18:41:57.900
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
18:41:57.900
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
18:41:57.900
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
18:41:57.900
at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
18:41:57.900
... 6 more
18:41:57.902
Exception in thread "main" [18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
18:41:57.967
[18:41:57] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
18:41:58.004
Process crashed with exit code 1`

**Comment by yorik100** [comment]
Baritone tututututututu

**Comment by E404NNF** [comment]
can confirm on latest LB b73 1.12.2 (from 9 days ago), https://paste.ee/p/1kpmQ here's a log

**Comment by superblaubeere27** [comment]
Baritone isn't suppose to work with LiquidBounce.
