### ISSUE TITLE
[BUG] Game crashes

### ISSUE THREAD

**Issue by YoMamaAH21** [CCBlueX/LiquidBounce#2487]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b2f

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I downloaded Kotlin Fabric Language, Fabric API Mod, and ViaFabricPlus, and added them to my Mods folder (all 1.20.4), and when I tried to launch the game I got this Error.

Note: I used Feather Launcher, because my Minecraft Launcher does not work.

### Steps to reproduce

Not sure...

### Client Log

```shell
info: CONNECTING TO SERVER undefined
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start::bindings] server: None
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Loading version
info: {"versionSize":221922400,"state":{"VersionLoading":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":0}
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished loading version
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished moving mods
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Preparing assets
[2024-03-16T20:00:37Z INFO  rust_launcher::start] Preparing JRE
info: {"versionSize":221922400,"state":{"Downloading":["Libraries","Mods","Assets","Jre"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":75439}
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Preparing libraries
info: {"versionSize":221922400,"state":{"Downloading":["Libraries","Mods","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":43223320}
info: {"versionSize":221922400,"state":{"Downloading":["Libraries","Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":43223320}
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Preparing mods
[2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished preparing mods
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished preparing libraries
info: {"versionSize":221922400,"state":{"Downloading":["Assets"]},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":548948538}
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished preparing assets
[2024-03-16T20:00:37Z INFO  rust_launcher::start] Preparing registry
info: {"versionSize":221922400,"state":{"Jvm":true},"currentDownloadRate":0,"expectedTasks":6,"downloadSpeed":0,"downloaded":875479952}
info: [2024-03-16T20:00:37Z INFO  rust_launcher::start] Finished preparing registry
info: [2024-03-16T20:00:37Z INFO  rust_launcher::common::launch] starting JVM with arguments: ["-Djava.library.path=libraries/native\\net/digitalingot/fcef-windows/0.0.9\\extracted/;libraries/native\\net/digitalingot/fwebp-windows/0.0.2\\extracted/;libraries/native\\net/digitalingot/favif-windows/0.0.1\\extracted/;libraries/native\\com/discord/discord-game-sdk/3.2.1\\extracted/;libraries/native\\net/digitalingot/fdiscord/0.0.1\\extracted/;libraries/native\\net/digitalingot/fjni/0.0.1\\extracted/;libraries/native\\org/jitsi/jnopus/1.0\\extracted/;libraries/native\\org/lwjgl/lwjgl/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-jemalloc/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-openal/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-opengl/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-glfw/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-stb/3.3.2\\extracted/;libraries/native\\org/lwjgl/lwjgl-tinyfd/3.3.2\\extracted/", "--add-opens=java.desktop/java.awt.event=ALL-UNNAMED", "--add-opens=java.desktop/java.awt.color=ALL-UNNAMED", "--add-opens=java.desktop/java.awt=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-Xmx2048M", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseG1GC", "-XX:G1NewSizePercent=20", "-XX:G1ReservePercent=20", "-XX:MaxGCPauseMillis=50", "-XX:G1HeapRegionSize=32M", "-Dlog4j2.formatMsgNoLookups=true", "-XX:ErrorFile=feather/java_error.log", "-Djavax.accessibility.assistive_technologies=", "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT", "-cp", "libraries\\java\\net/minecraft/client/1.20.4/minecraft-1.20.4.jar;libraries\\java\\net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar;libraries\\java\\org/ow2/asm/asm/9.6/asm-9.6.jar;libraries\\java\\org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar;libraries\\java\\org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar;libraries\\java\\org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar;libraries\\java\\org/ow2/asm/asm-util/9.6/asm-util-9.6.jar;libraries\\java\\net/fabricmc/intermediary/1.20.4/intermediary-1.20.4.jar;libraries/java\\net/fabricmc/fabric-loader/0.15.7/fabric-loader-0.15.7.jar;libraries\\java\\net/digitalingot/fjni/0.0.1/fjni-0.0.1.jar;libraries\\java\\net/digitalingot/fdiscord/0.0.1/fdiscord-0.0.1.jar;libraries\\java\\software/bernie/geckolib/geckolib-fabric-1.20-3.4.1.jar;libraries\\java\\net/digitalingot/rust-extension/1.0.7/rust-extension-1.0.7.jar;libraries\\java\\net/digitalingot/fcef/0.0.9/fcef-0.0.9.jar;libraries\\java\\net/digitalingot/fwebp/0.0.1/fwebp-0.0.1.jar;libraries\\java\\net/digitalingot/favif/0.0.1/favif-0.0.1.jar;libraries\\java\\net/digitalingot/feather-server-api/messaging/0.0.4/messaging-0.0.4-SNAPSHOT.jar;libraries\\java\\org/jitsi/libjitsi-opus/1.1-32-g2a5a8171/libjitsi-opus-1.1-32-g2a5a8171.jar;libraries\\java\\org/capnproto/runtime/0.1.10/runtime-0.1.10.jar;libraries\\java\\com/google/inject/guice/5.1.0/guice-vendored-5.1.0.jar;libraries\\java\\javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar;libraries\\java\\io/netty/netty-codec-http/4.1.97.Final/netty-codec-http-4.1.97.Final.jar;libraries\\java\\com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar;libraries\\java\\com/google/code/gson/gson/2.10.1/gson-2.10.1.jar;libraries\\java\\com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar;libraries\\java\\com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar;libraries\\java\\com/ibm/icu/icu4j/73.2/icu4j-73.2.jar;libraries\\java\\com/mojang/authlib/6.0.52/authlib-6.0.52.jar;libraries\\java\\com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar;libraries\\java\\com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar;libraries\\java\\com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar;libraries\\java\\com/mojang/logging/1.1.1/logging-1.1.1.jar;libraries\\java\\com/mojang/patchy/2.2.10/patchy-2.2.10.jar;libraries\\java\\com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar;libraries\\java\\commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar;libraries\\java\\commons-io/commons-io/2.13.0/commons-io-2.13.0.jar;libraries\\java\\commons-logging/commons-logging/1.2/commons-logging-1.2.jar;libraries\\java\\io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar;libraries\\java\\io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar;libraries\\java\\io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar;libraries\\java\\io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar;libraries\\java\\io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar;libraries\\java\\io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar;libraries\\java\\it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar;libraries\\java\\net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar;libraries\\java\\net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar;libraries\\java\\net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;libraries\\java\\org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar;libraries\\java\\org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar;libraries\\java\\org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar;libraries\\java\\org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar;libraries\\java\\org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar;libraries\\java\\org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar;libraries\\java\\org/joml/joml/1.10.5/joml-1.10.5.jar;libraries\\java\\org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar;libraries\\java\\org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar;libraries\\java\\org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar", "-DFabricMcEmu= net.minecraft.client.main.Main ", "net.digitalingot.rustextension.ProxiedStart", "net.fabricmc.loader.launch.knot.KnotClient", "--username", "GameChair", "--version", "1.20.4-feather", "--gameDir", "C:\\Users\\DBrit\\AppData\\Roaming/.minecraft", "--assetsDir", "assets", "--assetIndex", "1.20.4-feather-game", "--uuid", "a355fcf881664148afe95528be06affe", "--accessToken", "<hidden>", "--userType", "msa", "--versionType", "feather"]
info: sending javaw pid
info: starting cleanup
info: [16:00:39] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
info: [16:00:39] [ForkJoinPool-1-worker-4/WARN]: Mod feather uses the version release/7544889f which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'release/7544889f'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
info: [16:00:39] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
info: [16:00:39] [main/INFO]: Loading 94 mods:
	- fabric-api 0.95.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.48+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.12+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.0.2+25e1b4764f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.73+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.62+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.52+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   |-- fabric-rendering-v0 1.1.55+df3654b34f
	   |-- fabric-rendering-v1 3.1.0+0d29db764f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.9+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- feather release/7544889f
	- java 17
	- liquidbounce 0.1.9
	- minecraft 1.20.4
	- viafabricplus 3.1.0
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-24w09a-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-24w09a-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.2
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- io_jsonwebtoken_jjwt-api 0.12.5
	   |-- io_jsonwebtoken_jjwt-gson 0.12.5
	   |-- io_jsonwebtoken_jjwt-impl 0.12.5
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.4.1
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.2
	   |-- net_raphimc_minecraftauth 4.0.0-SNAPSHOT
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.5-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
info: [16:00:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/DBrit/AppData/Roaming/.minecraft/libraries/java/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
info: [16:00:39] [main/INFO]: Compatibility level set to JAVA_17
info: [16:00:40] [main/INFO]: Feather: Optifine dectected? false
info: [16:00:40] [main/INFO]: [Feather::EssentialMod] Installed: false
info: [16:00:40] [main/WARN]: Error loading class: com/terraformersmc/modmenu/config/option/EnumConfigOption (java.lang.ClassNotFoundException: com/terraformersmc/modmenu/config/option/EnumConfigOption)
info: [16:00:41] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
info: [16:00:41] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
info: [16:00:42] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
info: [16:00:43] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
info: [16:00:44] [main/WARN]: @ModifyConstant conflict. Skipping mixins.feather.json:DcuoN from mod feather->@ModifyConstant::Whkjl(I)I with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.client.MixinMinecraftClient from mod liquidbounce->@ModifyConstant::getFramerateLimit(I)I with priority 1337
info: [16:00:44] [main/WARN]: @Redirect conflict. Skipping mixins.feather.json:xbRIA from mod feather->@Redirect::okmNU(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIIIFFIIII)V with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.gui.MixinSplashOverlay from mod liquidbounce->@Redirect::drawTexture(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIIIFFIIII)V with priority 1337
info: [16:00:44] [main/WARN]: @Redirect conflict. Skipping mixins.feather.json:xbRIA from mod feather->@Redirect::okmNU(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIIIFFIIII)V with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.gui.MixinSplashOverlay from mod liquidbounce->@Redirect::drawTexture(Lnet/minecraft/class_332;Lnet/minecraft/class_2960;IIIIFFIIII)V with priority 1337
info: [16:00:44] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
info: [16:00:44] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) ~[rust-extension-1.0.7.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[minecraft-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[minecraft-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;Lcom/llamalad7/mixinextras/sugar/ref/LocalFloatRef;)Z in viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.doPostInject(InjectorWrapperImpl.java:79) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.doPostInject(SugarWrapperImpl.java:84) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.postInject(WrapperInjectionInfo.java:78) ~[mixinextras-0.3.5-63e25e1b0e82f847.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[minecraft-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 7 more
info: [2024-03-16T20:00:44Z INFO  rust_launcher::start::bindings] launch stalled
```

**Comment by liquidsquid1** [comment]
I don’t believe LiquidBounce supports Feather Client. Please use another launcher like Prism.

**Comment by mumy-255** [comment]
> I don’t believe LiquidBounce supports Feather Client. Please use another launcher like Prism.

Duplicate of [#2466](https://github.com/CCBlueX/LiquidBounce/issues/2466), try downgrading ViaFabricPlus to version 3.0.6.

**Comment by YoMamaAH21** [comment]
> > I don’t believe LiquidBounce supports Feather Client. Please use another launcher like Prism.
> 
> Duplicate of [#2466](https://github.com/CCBlueX/LiquidBounce/issues/2466), try downgrading ViaFabricPlus to version 3.0.6.

When I try and do this, it opens but automatically closes a couple seconds after.

**Comment by SenkJu** [comment]
Could you try using LiquidLauncher? Also, is there an error message?
