### ISSUE TITLE
JCEF unsatisfied link error

### ISSUE THREAD

**Issue by gsaf5a** [CCBlueX/LiquidBounce#2492]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

lastet

### Operating System

Windows 8.1

### Minecraft Version

1.16.5

### Describe the bug

AFTER STARTING THE INSTALLATION OF THE BIBLE LIBRARY AND WHEN THEY ARE UNPACKED, THE MAINCRAFT CRUSHES (I NOT ENGLISH)

### Steps to reproduce

AFTER STARTING THE INSTALLATION OF THE BIBLE LIBRARY AND WHEN THEY ARE UNPACKED, THE MAINCRAFT CRUSHES (I NOT ENGLISH)

### Client Log

```shell
uidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:77) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:70) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:171) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$zmh000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:
?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/137874441/86ad7cad-4c59-4cf4-8069-10ce22640e0e)

**Comment by gsaf5a** [comment]
but file have 
![image](https://github.com/CCBlueX/LiquidBounce/assets/137874441/9c760a80-f251-48b8-98d4-2b06f3b6a93f)

**Comment by gsaf5a** [comment]
how to fix?

**Comment by 1zun4** [comment]
No idea. Check if your AV is blocking anything or might try to re-download the files.

**Comment by be4dev** [comment]
> ### LiquidBounce Branch
> 
> Nextgen
> ### LiquidBounce Build/Version
> 
> lastet
> ### Operating System
> 
> Windows 8.1
> ### Minecraft Version
> 
> 1.16.5
> ### Describe the bug
> 
> AFTER STARTING THE INSTALLATION OF THE BIBLE LIBRARY AND WHEN THEY ARE UNPACKED, THE MAINCRAFT CRUSHES (I NOT ENGLISH)
> ### Steps to reproduce
> 
> AFTER STARTING THE INSTALLATION OF THE BIBLE LIBRARY AND WHEN THEY ARE UNPACKED, THE MAINCRAFT CRUSHES (I NOT ENGLISH)
> ### Client Log
> 
> ```shell
> uidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:77) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:66) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:70) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:171) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[LiquidBounce.jar:?]
> 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[LiquidBounce.jar:?]
> 	at net.minecraft.class_310.handler$zmh000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:
> ?]
> 	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
> An error with the client occourd:
> Process exited with non-zero exit code: 1.
> ```
> 
> ### Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/137874441/313451468-86ad7cad-4c59-4cf4-8069-10ce22640e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTk1MjMsIm5iZiI6MTcxMDc5OTIyMywicGF0aCI6Ii8xMzc4NzQ0NDEvMzEzNDUxNDY4LTg2YWQ3Y2FkLTRjNTktNGNmNC04MDY5LTEwY2UyMjY0MGUwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQyMjAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmMzZDQ5ZTFjODYxZTRlOTdjMjc4ZmUzZDI4YjIwZGIwYTM1MWI3ZTBjN2ZlZWIwOTE0NDZkNTJhMTgwNzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uIShlQzw_Dvc4-KzDSWT51SyHJtQ_rBsLotL5aWLE58)

загрузи полные логи, а не только последние 2 строчки

**Comment by dudethis** [comment]
you should show more of your crash log. sometimes unsatisfied link error can mean your hardware might not be supported.

**Comment by 1zun4** [comment]
Windows 8 is not supported.
