### ISSUE TITLE
[BUG] The NPE issue in LiquidWalk (git-a3dead3)

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2551]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0 git-a3dead3

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When starting the game, if LiquidWalk is enabled, it throws an NPE in the log.

### Steps to reproduce

1. Enable LiquidWalk.
2. Restart the game.

### Client Log

```shell
[02:06:49] [Render thread/INFO]: Successfully saved config 'modules'.
[02:06:49] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@61ffec81, url=http://127.0.0.1:15110/default/#/)
[02:06:49] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.832 ms
[02:06:49] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[02:06:49] [Server thread/INFO]: Generating keypair
[02:06:50] [nioEventLoopGroup-3-1/INFO]: [id: 0x35d596fb, L:/[0:0:0:0:0:0:0:0]:15110] READ: [id: 0xfbed9144, L:/127.0.0.1:15110 - R:/127.0.0.1:2731]
[02:06:50] [nioEventLoopGroup-3-1/INFO]: [id: 0x35d596fb, L:/[0:0:0:0:0:0:0:0]:15110] READ COMPLETE
[02:06:50] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[02:06:50] [Server thread/WARN]: Method overwrite conflict for removeIf in modernfix-common.mixins.json:bugfix.paper_chunk_patches.SortedArraySetMixin from mod modernfix, previously written by me.jellysquid.mods.lithium.mixin.world.chunk_tickets.SortedArraySetMixin. Skipping method.
[02:06:50] [Render thread/INFO]: 准备生成区域中：0%
[02:06:50] [Render thread/INFO]: 准备生成区域中：0%
[02:06:51] [Render thread/INFO]: Time elapsed: 880 ms
[02:06:51] [Server thread/INFO]: Changing view distance to 16, from 10
[02:06:51] [Server thread/INFO]: Changing simulation distance to 12, from 0
[02:06:51] [Server thread/INFO]: mumy_[local:E:be86240a] logged in with entity id 126 at (-6.49900888194764, -59.0, -3.3069847992605315)
[02:06:51] [Render thread/INFO]: New minimap session initialized!
[02:06:51] [Server thread/INFO]: mumy_加入了游戏
[02:06:51] [Render thread/INFO]: Successfully saved config 'modules'.
[02:06:51] [Render thread/ERROR]: Exception while executing handler.
java.lang.NullPointerException: null
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleHoleESP.updateScanRegion(ModuleHoleESP.kt:376) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleHoleESP.enable(ModuleHoleESP.kt:309) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.Module$onWorldChange$1.invoke(Module.kt:219) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.Module$onWorldChange$1.invoke(Module.kt:216) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$dcp000$liquidbounce$hookWorldChangeEvent(class_310.java:17995) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2257) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[02:06:51] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@61ffec81, url=http://127.0.0.1:15110/default/#/)
[02:06:51] [Render thread/INFO]: Started 2 worker threads
[02:06:51] [Server thread/ERROR]: Exception while executing handler.
java.lang.NullPointerException: Cannot read field "field_3903" because "net.minecraft.class_310.method_1551().field_1724.field_3913" is null
	at net.ccbluex.liquidbounce.features.module.modules.movement.liquidwalk.modes.LiquidWalkVanilla$shapeHandler$1.invoke(LiquidWalkVanilla.kt:52) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.movement.liquidwalk.modes.LiquidWalkVanilla$shapeHandler$1.invoke(LiquidWalkVanilla.kt:51) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_4970.handler$dbp000$liquidbounce$hookCollisionShape(class_4970.java:1604) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:1129) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.getCollisionShapeBelowEntity(LithiumEntityCollisions.java:199) ~[lithium-fabric-mc1.20.4-0.12.1.jar:?]
	at net.minecraft.class_1297.lithiumCollideMultiAxisMovement(class_1297.java:8903) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.redirect$bdd000$lithium$adjustMovementForCollisionsGetEntitiesLater(class_1297.java:8881) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_17835(class_1297.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:707) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2339) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2259) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6091(class_1657.java:1620) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_6091(class_3222.java:1128) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2743) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:582) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2446) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:257) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:06:51] [Server thread/ERROR]: Exception while executing handler.
java.lang.NullPointerException: Cannot read field "field_3903" because "net.minecraft.class_310.method_1551().field_1724.field_3913" is null
	at net.ccbluex.liquidbounce.features.module.modules.movement.liquidwalk.modes.LiquidWalkVanilla$shapeHandler$1.invoke(LiquidWalkVanilla.kt:52) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.movement.liquidwalk.modes.LiquidWalkVanilla$shapeHandler$1.invoke(LiquidWalkVanilla.kt:51) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_4970.handler$dbp000$liquidbounce$hookCollisionShape(class_4970.java:1604) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:1129) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:219) ~[lithium-fabric-mc1.20.4-0.12.1.jar:?]
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:32) ~[lithium-fabric-mc1.20.4-0.12.1.jar:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-32.1.2-jre.jar:?]
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.collectAll(ChunkAwareBlockCollisionSweeper.java:301) ~[lithium-fabric-mc1.20.4-0.12.1.jar:?]
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.getBlockCollisions(LithiumEntityCollisions.java:40) ~[lithium-fabric-mc1.20.4-0.12.1.jar:?]
	at net.minecraft.class_1297.lithiumCollideMultiAxisMovement(class_1297.java:8919) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.redirect$bdd000$lithium$adjustMovementForCollisionsGetEntitiesLater(class_1297.java:8881) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_17835(class_1297.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:707) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2339) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2259) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6091(class_1657.java:1620) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_6091(class_3222.java:1128) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2743) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:582) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2446) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:257) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

(loop...)
```

**Comment by 1zun4** [comment]
To be fair, this might be rather related to Lithium Mod.

In the stacktrace it can be found: "LithiumEntityCollisions"

**Comment by 1zun4** [comment]
I cannot reproduce it - might really be just related to Lithium Mod, but can be ignored anyway. It will not affect anything.
