### ISSUE TITLE
[BUG] IllegalStateException issue thrown in ConfigSystem

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2552]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0 git-a3dead3

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When starting LiquidBounce, ConfigSystem throws an exception.

### Steps to reproduce

1. Upgrade LiquidBounce from 0.1.9 to 0.2.0 git-a3dead3.
2. Launch the game.

### Client Log

```shell
[02:05:06] [Render thread/INFO]: Launching LiquidBounce v0.2.0 by CCBlueX
[02:05:06] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[02:05:06] [Render thread/INFO]: Intermediary environment detected.
[02:05:06] [Render thread/INFO]: Loaded language en_us
[02:05:06] [Render thread/INFO]: Loaded language de_de
[02:05:06] [Render thread/INFO]: Loaded language ja_jp
[02:05:06] [Render thread/INFO]: Loaded language zh_cn
[02:05:06] [Render thread/INFO]: Loaded language ru_ru
[02:05:06] [Render thread/INFO]: Loaded language en_pt
[02:05:06] [Render thread/INFO]: Loaded language pt_br
[02:05:08] [Render thread/WARN]: Unable to find main.js or main.mjs inside the directory lib.
[02:05:11] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyExtraCore 0.1.js'.
[02:05:11] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyLogFilter 0.1.js'.
[02:05:11] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyPacketDebugger 0.3.js'.
[02:05:11] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyStrongholdFinder 0.1.js'.
[02:05:11] [Render thread/WARN]: mumyAutoTotem is missing fallback description key liquidbounce.module.mumyAutoTotem.description
[02:05:11] [Render thread/WARN]: mumyAntiBlind is missing fallback description key liquidbounce.module.mumyAntiBlind.description
[02:05:11] [Render thread/WARN]: mumyLogFilter is missing fallback description key liquidbounce.module.mumyLogFilter.description
[02:05:11] [Render thread/WARN]: mumyPacketDebugger is missing fallback description key liquidbounce.module.mumyPacketDebugger.description
[02:05:11] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[02:05:12] [Render thread/WARN]: mumyStrongholdFinder is missing fallback description key liquidbounce.module.mumyStrongholdFinder.description
[02:05:13] [Render thread/INFO]: Successfully extracted default theme
[02:05:13] [Render thread/INFO]: Inserted 9 components
[02:05:13] [Render thread/INFO]: Successfully loaded config 'enemies'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'enemies'.
[02:05:13] [Render thread/INFO]: (Chat) 
[02:05:13] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[02:05:13] [Render thread/ERROR]: Unable to deserialize choice Vulcan277
java.lang.IllegalStateException: Choice Vulcan277 not found
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:255) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:265) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$dcp000$liquidbounce$startClient(class_310.java:17850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[02:05:13] [Render thread/ERROR]: Unable to deserialize choice Vulcan286-113
java.lang.IllegalStateException: Choice Vulcan286-113 not found
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:255) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:265) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$dcp000$liquidbounce$startClient(class_310.java:17850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[02:05:13] [Render thread/ERROR]: Unable to deserialize choice Grim2859-V
java.lang.IllegalStateException: Choice Grim2859-V not found
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:255) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:265) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$dcp000$liquidbounce$startClient(class_310.java:17850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[02:05:13] [Render thread/INFO]: Successfully loaded config 'modules'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'modules'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'commands'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'commands'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'friends'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'friends'.
[02:05:13] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:224) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:275) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$dcp000$liquidbounce$startClient(class_310.java:17850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 24 more
[02:05:13] [Render thread/INFO]: Successfully loaded config 'proxy'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'proxy'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'accounts'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'accounts'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'tabs'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'tabs'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'lang'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'lang'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'storage'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'storage'.
[02:05:13] [Render thread/INFO]: Successfully loaded config 'theme'.
[02:05:13] [Render thread/INFO]: Successfully saved config 'theme'.
[02:05:13] [netty-websocket/INFO]: Starting Netty server...
[02:05:13] [nioEventLoopGroup-3-1/INFO]: [id: 0x35d596fb] REGISTERED
[02:05:13] [nioEventLoopGroup-3-1/INFO]: [id: 0x35d596fb] BIND: 0.0.0.0/0.0.0.0:15110
[02:05:13] [nioEventLoopGroup-3-1/INFO]: [id: 0x35d596fb, L:/[0:0:0:0:0:0:0:0]:15110] ACTIVE
[02:05:13] [netty-websocket/INFO]: Netty server started on port 15110.
[02:05:14] [Render thread/INFO]: Refresh Rate: 75 Hz
[02:05:14] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[02:05:15] [Render thread/INFO]: [Downloading Checksum] Started task
[02:05:16] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[02:05:16] [Render thread/INFO]: Checksum matches: true
[02:05:16] [Render thread/INFO]: Platform directory exists: true
[02:05:16] [Render thread/INFO]: Initializing CEF on windows_amd64...
[02:05:16] [Render thread/INFO]: [STDOUT]: initialize on Thread[Render thread,5,main] with library path H:\Games\Play2\.minecraft\versions\1.20.4-Fabric 0.15.7\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64
[02:05:16] [Render thread/INFO]: Chromium Embedded Framework initialized
[02:05:16] [Render thread/INFO]: Browser is ready.
[02:05:16] [Render thread/INFO]: Successfully loaded client!
[02:05:17] [Render thread/INFO]: Loaded background image for theme default
```

**Comment by 1zun4** [comment]
This is not a bug. This "error" is displayed when serialising a mode that no longer exists.
The only relevant part is: `Choice Vulcan286-113 not found` - which is an error we throw ourselves and can therefore be ignored.
