### ISSUE TITLE
cant start the game on nextgen [BUG]

### ISSUE THREAD

**Issue by bever2020** [CCBlueX/LiquidBounce#2557]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.2.0

### Operating System

Windows 11

### Minecraft Version

1.7-1.20.4

### Describe the bug

i tried to launch the game from the liquidlauncher and it didn't work game version was 1.7  -  1.20.4

### Steps to reproduce

branch nextgen enable all the mods and then launch and see

### Client Log

```shell
~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$cdk000$liquidbounce$startClient(class_310.java:10850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at java.lang.invoke.LambdaForm$DMH/0x000002671024c800.invokeStaticInit(LambdaForm$DMH) ~[?:?]
	at java.lang.invoke.LambdaForm$MH/0x00000267102a8000.invokeExact_MT(LambdaForm$MH) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
[09:21:10] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
An error occourd:

Process exited with non-zero exit code: 1.
```

### Screenshots

![Screenshot 2024-03-23 092254](https://github.com/CCBlueX/LiquidBounce/assets/164615219/71ad5910-18ab-4a21-95ec-a39ffdc65d1d)
![Screenshot 2024-03-23 092316](https://github.com/CCBlueX/LiquidBounce/assets/164615219/4eb94366-a970-4e5c-871e-256808d3eca5)
![Screenshot 2024-03-23 092329](https://github.com/CCBlueX/LiquidBounce/assets/164615219/72766a08-7d46-49fb-90d0-4e6982cdef54)

**Comment by bever2020** [comment]
![Screenshot 2024-03-23 092813](https://github.com/CCBlueX/LiquidBounce/assets/164615219/e40aa8b4-67ba-4fc9-a064-2549c78dd9c7)

**Comment by SenkJu** [comment]
You're running out of memory. How much RAM does your PC have? I will close this for now as its likely not a LiquidBounce issue. Feel free to comment.
