### ISSUE TITLE
[BUG] Liquidbounce Nextgen Crashes

### ISSUE THREAD

**Issue by raalo** [CCBlueX/LiquidBounce#2566]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Nextgen

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When i open liquidbounce from the TLauncher the client crash after 5 seconds.

### Steps to reproduce

- Open TLauncher
- Select fabric-loader-0.15.7-1.20.4
- Open the game
- The game crashes

### Client Log

```shell
[11:18:18] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[11:18:18] [main/INFO]: Loading 68 mods:
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.1.9
	- minecraft 1.20.4
[11:18:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/REDA%c3%87%c3%83O/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:18:19] [main/INFO]: Compatibility level set to JAVA_17
[11:18:20] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[11:18:20] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[11:18:21] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[11:18:21] [main/INFO]: Completely ignored arguments: [-noverify]
[11:18:24] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[11:18:30] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 382 milliseconds
[11:18:36] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:18:36] [Render thread/INFO]: Setting user: r1nite167
[11:18:38] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[11:18:38] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[11:18:39] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[11:18:40] [Render thread/INFO]: Found non-pack entry 'C:\Users\REDAÇÃO\AppData\Roaming\.minecraft\resourcepacks\! CopaMushMC.rar', ignoring
[11:18:41] [Render thread/INFO]: Launching LiquidBounce v0.1.9 by CCBlueX
[11:18:42] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[11:18:42] [Render thread/INFO]: Intermediary environment detected.
[11:18:42] [Render thread/INFO]: Loaded language en_us
[11:18:42] [Render thread/INFO]: Loaded language de_de
[11:18:42] [Render thread/INFO]: Loaded language ja_jp
[11:18:42] [Render thread/INFO]: Loaded language zh_cn
[11:18:42] [Render thread/INFO]: Loaded language ru_ru
[11:18:42] [Render thread/INFO]: Loaded language en_pt
[11:18:42] [Render thread/INFO]: Loaded language pt_br
[11:18:45] [Render thread/INFO]: Successfully extracted default theme
[11:18:45] [Render thread/INFO]: Inserted 9 components
[11:18:45] [Render thread/INFO]: Successfully loaded config 'enemies'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'enemies'.
[11:18:45] [Render thread/INFO]: (Chat) 
[11:18:45] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[11:18:45] [Render thread/INFO]: Successfully loaded config 'modules'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'modules'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'commands'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'commands'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'friends'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'friends'.
[11:18:45] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:224) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:275) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:203) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:162) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znn000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 18 more
[11:18:45] [Render thread/INFO]: Successfully loaded config 'proxy'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'proxy'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'accounts'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'accounts'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'tabs'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'tabs'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'lang'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'lang'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'storage'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'storage'.
[11:18:45] [Render thread/INFO]: Successfully loaded config 'theme'.
[11:18:45] [Render thread/INFO]: Successfully saved config 'theme'.
[11:18:46] [netty-websocket/INFO]: Starting Netty server...
[11:18:47] [Render thread/INFO]: Refresh Rate: 75 Hz
[11:18:47] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[11:18:47] [Render thread/ERROR]: Fatal error
java.lang.RuntimeException: Unsupported platform: windows 10 x86
	at net.ccbluex.liquidbounce.mcef.MCEFPlatform.getPlatform(MCEFPlatform.java:74) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.newResourceManager(MCEFResourceManager.java:79) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.newResourceManager(MCEF.java:65) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:59) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:171) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znn000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
[11:18:48] [nioEventLoopGroup-2-1/INFO]: [id: 0x740acabc] REGISTERED
[11:18:48] [nioEventLoopGroup-2-1/INFO]: [id: 0x740acabc] BIND: 0.0.0.0/0.0.0.0:16693
[11:18:48] [netty-websocket/INFO]: Netty server started on port 16693.
[11:18:48] [nioEventLoopGroup-2-1/INFO]: [id: 0x740acabc, L:/0.0.0.0:16693] ACTIVE
```

### Screenshots

![lb error](https://github.com/CCBlueX/LiquidBounce/assets/164646275/499ca632-f668-45b6-ba23-94abcf296a71)

**Comment by EclipsesDev** [comment]
I think thats because u have outdated windows (I'm not sure)

**Comment by SenkJu** [comment]
You're running 32-bit Windows which is not supported. Please upgrade to a 64-bit installation. If your CPU was produced within the last 10 years, it should be compatible.
