### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cutiegin** [CCBlueX/LiquidBounce#2609]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

c402a08

### Operating System

Windows 7

### Minecraft Version

1.20.4

### Describe the bug

i just started minecraft and liquidbounce nextgen got crashed

### Steps to reproduce

click start game

### Client Log

```shell
[20:31:46] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[20:31:47] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:31:48] [main/INFO]: Loading 93 mods:
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.2.0
	- minecraft 1.20.4
	- viafabricplus 3.1.0
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-24w09a-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-24w09a-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.2
	   |-- io_jsonwebtoken_jjwt-api 0.12.5
	   |-- io_jsonwebtoken_jjwt-gson 0.12.5
	   |-- io_jsonwebtoken_jjwt-impl 0.12.5
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.4.1
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.2
	   |-- net_raphimc_minecraftauth 4.0.0-SNAPSHOT
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.5-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[20:31:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/cutiegin/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:31:48] [main/INFO]: Compatibility level set to JAVA_17
[20:31:52] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[20:31:52] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[20:32:00] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[20:32:20] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 1093 milliseconds
[20:32:29] [Render thread/INFO]: Environment: Environment[sessionHost=https://0.0.0.0, servicesHost=https://0.0.0.0, name=properties]
[20:32:29] [Render thread/INFO]: Setting user: testlrofla
[20:32:32] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.exceptions.MinecraftClientException.toAuthenticationException(MinecraftClientException.java:29) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:154) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[20:32:32] [Download-1/WARN]: Couldn't look up profile properties for 9fd2da94-5ec6-3a6b-8cc2-c69eb94191a5
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://0.0.0.0/session/minecraft/profile/9fd2da945ec63a6b8cc2c69eb94191a5?unsigned=false due to Connection refused: no further information
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_53464(class_310.java:463) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
	... 8 more
[20:32:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[20:32:32] [Yggdrasil Key Fetcher/ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://0.0.0.0/publickeys due to Connection refused: no further information
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.52.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
	... 9 more
[20:32:37] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[20:32:39] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[20:32:39] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[20:32:44] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[20:32:44] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[20:32:49] [Render thread/INFO]: Launching LiquidBounce v0.2.0 by CCBlueX
[20:32:51] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[20:32:51] [Render thread/INFO]: Intermediary environment detected.
[20:32:52] [Render thread/INFO]: Loaded language en_us
[20:32:52] [Render thread/INFO]: Loaded language de_de
[20:32:52] [Render thread/INFO]: Loaded language ja_jp
[20:32:52] [Render thread/INFO]: Loaded language zh_cn
[20:32:52] [Render thread/INFO]: Loaded language ru_ru
[20:32:52] [Render thread/INFO]: Loaded language en_pt
[20:32:52] [Render thread/INFO]: Loaded language pt_br
[20:32:59] [Render thread/WARN]: AutoQueue is missing fallback description key liquidbounce.module.autoQueue.description
[20:33:05] [Render thread/INFO]: Successfully extracted default theme
[20:33:06] [Render thread/INFO]: Inserted 9 components
[20:33:06] [Render thread/INFO]: Successfully loaded config 'enemies'.
[20:33:06] [Render thread/INFO]: Successfully saved config 'enemies'.
[20:33:06] [Render thread/INFO]: (Chat) 
[20:33:06] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[20:33:06] [Render thread/INFO]: Successfully loaded config 'modules'.
[20:33:07] [Render thread/INFO]: Successfully saved config 'modules'.
[20:33:07] [Render thread/INFO]: Successfully loaded config 'commands'.
[20:33:07] [Render thread/INFO]: Successfully saved config 'commands'.
[20:33:07] [Render thread/INFO]: Successfully loaded config 'friends'.
[20:33:07] [Render thread/INFO]: Successfully saved config 'friends'.
[20:33:07] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:223) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:275) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:207) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:146) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:164) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$bja000$liquidbounce$startClient(class_310.java:7350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 18 more
[20:33:08] [Render thread/INFO]: Successfully loaded config 'proxy'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'proxy'.
[20:33:08] [Render thread/INFO]: Successfully loaded config 'accounts'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'accounts'.
[20:33:08] [Render thread/INFO]: Successfully loaded config 'tabs'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'tabs'.
[20:33:08] [Render thread/INFO]: Successfully loaded config 'lang'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'lang'.
[20:33:08] [Render thread/INFO]: Successfully loaded config 'storage'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'storage'.
[20:33:08] [Render thread/INFO]: Successfully loaded config 'theme'.
[20:33:08] [Render thread/INFO]: Successfully saved config 'theme'.
[20:33:10] [netty-websocket/INFO]: Starting Netty server...
[20:33:11] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:61664/
[20:33:11] [nioEventLoopGroup-3-1/INFO]: [id: 0x349a9d0c] REGISTERED
[20:33:11] [nioEventLoopGroup-3-1/INFO]: [id: 0x349a9d0c] BIND: 0.0.0.0/0.0.0.0:16690
[20:33:11] [nioEventLoopGroup-3-1/INFO]: [id: 0x349a9d0c, L:/[0:0:0:0:0:0:0:0]:16690] ACTIVE
[20:33:11] [netty-websocket/INFO]: Netty server started on port 16690.
[20:33:13] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: c0.0.15a-1 (0)
[20:33:13] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 24w09a (766)
[20:33:13] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://0.0.0.0, servicesHost=https://0.0.0.0, name=properties]
[20:33:13] [Render thread/INFO]: Refresh Rate: 60 Hz
[20:33:14] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[20:33:14] [Yggdrasil Key Fetcher/ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://0.0.0.0/publickeys due to Connection refused: no further information
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.52.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
	... 9 more
[20:33:32] [Render thread/INFO]: [Downloading Checksum] Started task
[20:33:32] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[20:33:32] [Render thread/INFO]: Checksum matches: true
[20:33:32] [Render thread/INFO]: Platform directory exists: true
[20:33:32] [Render thread/INFO]: Initializing CEF on windows_amd64...
[20:33:32] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\cutiegin\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\chrome_elf.dll: Не найдена указанная процедура
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:454) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:77) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:67) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$bja000$liquidbounce$startClient(class_310.java:7350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
[20:33:42] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/115403340/be9dcfea-7e15-49d7-84c2-a48dec35b560)

**Comment by superblaubeere27** [comment]
Try deleting `C:\Users\cutiegin\AppData\Roaming\.minecraft\LiquidBounce\mcef`

**Comment by iLoveLBnextgen** [comment]
> Try deleting `C:\Users\cutiegin\AppData\Roaming\.minecraft\LiquidBounce\mcef`

Still crash

**Comment by norp1xxx** [comment]
> > Try deleting `C:\Users\cutiegin\AppData\Roaming\.minecraft\LiquidBounce\mcef`
> 
> Still crash

do u find a fix? (можешь ответить и на русском)

**Comment by 1zun4** [comment]
Windows 7 is not supported.
