### ISSUE TITLE
IDK[BUG]

### ISSUE THREAD

**Issue by Gabizeir** [CCBlueX/LiquidBounce#2616]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

Every of next gen

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I doed everything ok but If everytime get this bug,idk If its not compatible im pojav launcher or If i do something wrong

### Steps to reproduce

...

### Client Log

```shell
[20:30:17] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[20:30:18] [main/INFO]: Loading 68 mods:
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- liquidbounce 0.1.8
	- minecraft 1.20.4
[20:30:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:30:19] [main/INFO]: Compatibility level set to JAVA_17
[20:30:23] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[20:30:23] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[20:30:25] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[20:30:26] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[20:30:26] [main/WARN]: File not found or not readable: /proc/stat
[20:30:27] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[20:30:30] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[20:30:47] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 1395 milliseconds
[20:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[20:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[20:30:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[20:31:01] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:31:01] [Render thread/INFO]: Setting user: TOILETGABISJAG
[20:31:03] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[20:31:03] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[20:31:05] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[20:31:05] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[20:31:06] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[20:31:08] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[20:31:09] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[20:31:09] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[20:31:10] [Render thread/INFO]: Launching LiquidBounce v0.1.8 by CCBlueX
[20:31:11] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[20:31:11] [Render thread/INFO]: Intermediary environment detected.
[20:31:11] [Render thread/INFO]: Loaded language en_us
[20:31:11] [Render thread/INFO]: Loaded language de_de
[20:31:11] [Render thread/INFO]: Loaded language ja_jp
[20:31:11] [Render thread/INFO]: Loaded language zh_cn
[20:31:11] [Render thread/INFO]: Loaded language ru_ru
[20:31:11] [Render thread/INFO]: Loaded language en_pt
[20:31:11] [Render thread/INFO]: Loaded language pt_br
[20:31:15] [Render thread/INFO]: Successfully extracted default theme
[20:31:15] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[20:31:15] [Render thread/INFO]: Inserted 9 components
[20:31:15] [Render thread/INFO]: Successfully loaded config 'enemies'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'enemies'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'modules'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'modules'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'commands'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'commands'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'friends'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'friends'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'proxy'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'proxy'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'accounts'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'accounts'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'tabs'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'tabs'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'lang'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'lang'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'storage'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'storage'.
[20:31:15] [Render thread/INFO]: Successfully loaded config 'theme'.
[20:31:15] [Render thread/INFO]: Successfully saved config 'theme'.
[20:31:16] [netty-websocket/INFO]: Starting Netty server...
[20:31:16] [netty-websocket/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 97:c7:d2:63:59:a3:a8:1f
[20:31:16] [nioEventLoopGroup-2-1/INFO]: [id: 0x87ae8ff5] REGISTERED
[20:31:16] [nioEventLoopGroup-2-1/INFO]: [id: 0x87ae8ff5] BIND: 0.0.0.0/0.0.0.0:16837
[20:31:16] [netty-websocket/INFO]: Netty server started on port 16837.
[20:31:16] [nioEventLoopGroup-2-1/INFO]: [id: 0x87ae8ff5, L:/0.0.0.0:16837] ACTIVE
[20:31:17] [Render thread/INFO]: Refresh Rate: 60 Hz
[20:31:17] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[20:31:17] [Render thread/INFO]: [Downloading Checksum] Started task
[20:31:18] [Render thread/ERROR]: Fatal error
java.lang.RuntimeException: Error writing to file from input stream
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:256) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.compareChecksum(MCEFResourceManager.java:190) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.requiresDownload(MCEFResourceManager.java:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:62) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:63) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:171) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:112) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:183) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znn000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/LiquidBounce/mcef/libraries/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/linux_arm64.tar.gz.sha256.temp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(Unknown Source) ~[?:?]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:?]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:244) ~[liquidbounce.jar:?]
	... 13 more
```

### Screenshots

....

**Comment by 1zun4** [comment]
Pojavlauncher is of course not supported.
