### ISSUE TITLE
Liquidlauncher crashes with lifesteal mod

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#2661]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.9

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I got the mods Lifesteal By LoxiGoose, and fabric api for 1.20.2 to join an Aternos server with the mod and I did not know how to switch from 1.20.4 to 1.20.2 so I tried it and I get an error message and I was able to once get in the minecraft and the server but now I can't get it to even load minecraft. If someone could reply and tell me how to change the liquid bounce version from 1.20.4 to 1.20.2. I would appreciate it.

### Steps to reproduce

Download Lifesteal By Loxigoose into the liquid bounce and also Fabric Api for 1.20.2 and try and load minecraft 

### Client Log

```shell
(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotCl
assLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	... 2 more
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by liquidsquid1** [comment]
Don't use Lifesteal mod :p
I don't think there will be compatibility soon as LiquidBounce injects alot of funni stuff.

Can you close this?

**Comment by ghost** [comment]
I want to beat up my cheater friends on our lifesteal server 😈😈😈😈😈

**Comment by Razzy52** [comment]
Contact the developer of the lifesteal mod or make the changes necessary to make it compatible yourself.

**Comment by 1zun4** [comment]
1.20.2, yeah no

**Comment by ghost** [comment]
You can just join the server without the mods but it doesn't show any custom items or blocks
