### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fluorescentl** [CCBlueX/LiquidBounce#2736]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

liquidbounce crashes when l open the game

### Steps to reproduce

...

### Client Log

```shell
[14:23:30] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.3
[14:23:30] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:23:30] [main/INFO]: Loading 106 mods:
	- baritone 1.10.2
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- fabric-api 0.91.3+1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14+78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-object-builder-api-v1 13.0.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- ferritecore 6.0.3
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- liquidbounce 0.2.0
	- lithium 0.12.1
	- minecraft 1.20.4
	- modmenu 9.0.0
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   \-- fabric-screen-api-v1 2.0.16+78d798af4f
	- nochatreports 1.20.4-v2.5.0
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- sodium 0.5.8+mc1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   \-- fabric-resource-loader-v0 0.11.17+707e4d1b4f
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- viafabricplus 3.0.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-23w51b-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-23w51b-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-lifecycle-events-v1 2.2.30+78d798af4f
	   |-- fabric-networking-api-v1 3.1.5+b7e146354f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.16+78d798af4f
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.1.0
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[14:23:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Administrator/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:23:30] [main/INFO]: Compatibility level set to JAVA_17
[14:23:31] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 1 override(s) found
[14:23:31] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[14:23:31] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[14:23:31] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[14:23:32] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[14:23:32] [main/INFO]: Searching for graphics cards...
[14:23:32] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[14:23:33] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 3060 Laptop GPU, version=DriverVersion=31.0.15.4617]
[14:23:33] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[14:23:33] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[14:23:35] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[14:23:40] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 298 milliseconds
[14:23:44] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:23:45] [Render thread/INFO]: Setting user: huanghun_
[14:23:45] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[14:23:45] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[14:23:45] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[14:23:46] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[14:23:46] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[14:23:46] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[14:23:46] [Render thread/WARN]: ClothConfig API not found, cannot provide config screen factory.
[14:23:46] [Worker-Main-1/INFO]: Checking mod updates...
[14:23:47] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[14:23:47] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[14:23:48] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[14:23:48] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
[14:23:48] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 546.17
[14:23:48] [Render thread/INFO]: Debug functionality is disabled.
[14:23:48] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[14:23:48] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[14:23:48] [Render thread/INFO]: Shaders are disabled
[14:23:49] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:59585/
[14:23:49] [Worker-Main-1/INFO]: Update available for 'viafabricplus@3.0.6', (-> 3.1.0)
[14:23:49] [Worker-Main-1/INFO]: Update available for 'modmenu@9.0.0', (-> 9.1.0-beta.1)
[14:23:49] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.10.17+kotlin.1.9.22', (-> 1.10.19+kotlin.1.9.23)
[14:23:49] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.91.3+1.20.4', (-> 0.96.11+1.20.4)
[14:23:49] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[14:23:49] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 23w51b (766)
[14:23:49] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:23:49] [Render thread/INFO]: Hardware information:
[14:23:49] [Render thread/INFO]: CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H
[14:23:49] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 (Supports OpenGL 3.3.0 NVIDIA 546.17)
[14:23:49] [Render thread/INFO]: OS: Windows 11 (10.0)
[14:23:51] [Render thread/INFO]: Launching LiquidBounce v0.2.0 by CCBlueX
[14:23:51] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[14:23:51] [Render thread/INFO]: Intermediary environment detected.
[14:23:51] [Render thread/INFO]: Loaded language en_us
[14:23:51] [Render thread/INFO]: Loaded language de_de
[14:23:51] [Render thread/INFO]: Loaded language ja_jp
[14:23:51] [Render thread/INFO]: Loaded language zh_cn
[14:23:51] [Render thread/INFO]: Loaded language ru_ru
[14:23:51] [Render thread/INFO]: Loaded language en_pt
[14:23:51] [Render thread/INFO]: Loaded language pt_br
[14:23:54] [Render thread/INFO]: Successfully extracted default theme
[14:23:54] [Render thread/INFO]: Inserted 9 components
[14:23:54] [Render thread/INFO]: Successfully loaded config 'enemies'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'enemies'.
[14:23:54] [Render thread/INFO]: (Chat) 
[14:23:54] [Render thread/INFO]: (Chat)   f  lLiquid  9  lBounce   8?   7Auto ConfigAuto Config
[14:23:54] [Render thread/INFO]: Successfully loaded config 'modules'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'modules'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'commands'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'commands'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'friends'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'friends'.
[14:23:54] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:223) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:275) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:207) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:205) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:146) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:164) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:184) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$coi000$liquidbounce$startClient(class_310.java:11850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 18 more
[14:23:54] [Render thread/INFO]: Successfully loaded config 'proxy'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'proxy'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'accounts'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'accounts'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'tabs'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'tabs'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'lang'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'lang'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'storage'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'storage'.
[14:23:54] [Render thread/INFO]: Successfully loaded config 'theme'.
[14:23:54] [Render thread/INFO]: Successfully saved config 'theme'.
[14:23:55] [netty-websocket/INFO]: Starting Netty server...
[14:23:55] [nioEventLoopGroup-3-1/INFO]: [id: 0x6c35ae40] REGISTERED
[14:23:55] [nioEventLoopGroup-3-1/INFO]: [id: 0x6c35ae40] BIND: 0.0.0.0/0.0.0.0:15150
[14:23:55] [nioEventLoopGroup-3-1/INFO]: [id: 0x6c35ae40, L:/[0:0:0:0:0:0:0:0]:15150] ACTIVE
[14:23:55] [netty-websocket/INFO]: Netty server started on port 15150.
[14:23:56] [Render thread/INFO]: Refresh Rate: 144 Hz
[14:23:56] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[14:23:57] [Render thread/INFO]: [Downloading Checksum] Started task
[14:23:57] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[14:24:00] [ForkJoinPool.commonPool-worker-2/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[14:24:18] [Render thread/ERROR]: Fatal error
java.lang.RuntimeException: Error connecting to https://dl.liquidbounce.net/resources/java-cef-builds/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/windows_amd64.tar.gz.sha256
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:261) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.compareChecksum(MCEFResourceManager.java:190) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.requiresDownload(MCEFResourceManager.java:94) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:62) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:184) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$coi000$liquidbounce$startClient(class_310.java:11850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:233) ~[LiquidBounce.jar:?]
	... 13 more
```

### Screenshots

![1712385145450](https://github.com/CCBlueX/LiquidBounce/assets/151549675/3f7886e3-5254-4506-815a-66d613992d5d)

**Comment by liquidsquid1** [comment]
Your internet connection may be too slow or the CEF download URL may be blocked in your area.

**Comment by Fluorescentl** [comment]
> 您的互联网连接速度可能太慢，或者您所在地区的 CEF 下载 URL 可能被阻止。

thank

**Comment by liquidsquid1** [comment]
You can always use a VPN to access the download for LiquidBounce

**Comment by Fluorescentl** [comment]
> 您可以随时使用 VPN 访问 LiquidBounce 的下载

Okay, I turned off the VPN and it's ready

**Comment by 1zun4** [comment]
So it is solved?

**Comment by liquidsquid1** [comment]
> So it is solved?

I would consider it solved, they can now use the client so 🤷‍♂️
