### ISSUE TITLE
[BUG] JCEF Process Priority

### ISSUE THREAD

**Issue by mumy-255** [CCBlueX/LiquidBounce#2766]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.0.1-0.2.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

Due to the process priority of JCEF, when running NextGen on my PC, Minecraft usually consumes all GPU resources, leaving little to none for JCEF, resulting in UI lag or even errors.

Initially, I tried using vertical synchronization to attempt to alleviate this issue, but it made my gaming experience worse. 
Limiting FPS also leads to similar problems (and on my PC, restricting FPS to above 100 makes JCEF run less smoothly, causing lag).

Later, I tried updating my graphics card drivers, but there was no change; Minecraft still monopolized GPU resources. 
Therefore, this issue remains unresolved.

### Steps to reproduce

...

### Client Log

```shell
[21:31:55] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[21:31:55] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_krlite_pierced uses the version v1.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:31:55] [ForkJoinPool-1-worker-4/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:31:55] [main/INFO]: Loading 181 mods:
	- appleskin 2.5.1+mc1.20.3
	- badoptimizations 2.1.0
	- betterbeds 1.3.0
	- bettermounthud 1.2.2
	- betterpingdisplay 1.1.1
	- betterstats 3.9.5+fabric-1.20.4
	   \-- tcdcommons 3.9.4+fabric-1.20.4
	- bookshelf 23.0.6
	- bugjump 1.2.0-1.20.1
	- carpet 1.4.128+v231205
	- carpet-extra 1.4.128
	- carpet-fixes 1.20-1.17.0
	   |-- conditional-mixin 0.3.1
	   \-- mixinextras 0.3.5
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.4+1.20.2
	- cull-less-leaves 1.3.0
	- cupboard 1.20.1-2.6
	- customskinloader 14.19.1
	- debugify 1.20.4+1.1
	- disable_custom_worlds_advice 5.0
	- experimentalperformance 0.1.1
	   |-- io_github_classgraph_classgraph 4.8.162
	   \-- org_openjdk_jol_jol-core 0.17
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- farsight 1.20.2-4.1
	   \-- org_jctools_jctools-core 4.0.1
	- faster_entity_animations 1.6
	- fastipping 1.0.1
	- fastquit 3.0.0+1.20.4
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- ibeeditor 2.2.8
	- icterine 1.3.0
	- immediatelyfast 1.2.11+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- indium 1.0.30+mc1.20.4
	- java 21
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- ksyxis 1.2.2
	- lambdabettergrass 1.5.2+1.20.1
	- lambdynlights 2.3.4+1.20.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.3+1.20.2
	- languagereload 1.5.10+1.20.3
	- lazydfu 0.1.3
	- liquidbounce 0.2.0
	- lithium 0.12.1
	- logical_zoom 0.0.22
	- malilib 0.18.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.4
	- modelfix 1.14
	- modernfix 5.15.0+mc1.20.4
	- modmenu 9.0.0
	- morechathistory 1.3.0
	- nbt_ac 1.2
	- nbttooltips 0.1.4-1.20.x
	- nochatreports 1.20.4-v2.5.0
	- noxesium 1.2.0+669ccb7
	   \-- com_noxcrew_noxesium_api_ 1.2.0+669ccb7
	- packetfixer 1.2.4
	- particletweaks 1.1.3-Fabric+1.20.2-unstable
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- shulkerboxtooltip 4.0.8+1.20.4
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sspb 3.2.1
	- starlight 1.1.3+fabric.f5dcd1a
	- stendhal 1.4.1-1.20.2
	   \-- libgui 9.0.0+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- toolstats 19.0.3
	- tooltipfix 1.1.1-1.20
	- tweakeroo 0.19.1
	- viafabricplus 3.1.1-SNAPSHOT
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-24w09a-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-24w09a-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.2
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- io_jsonwebtoken_jjwt-api 0.12.5
	   |-- io_jsonwebtoken_jjwt-gson 0.12.5
	   |-- io_jsonwebtoken_jjwt-impl 0.12.5
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.4.1
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.2
	   |-- net_raphimc_minecraftauth 4.0.0-SNAPSHOT
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.6-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
	- videotape 1.2.1
	   \-- com_github_krlite_pierced v1.2
	- xaerominimap 24.0.3
	- yet_another_config_lib_v3 3.3.2+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
[21:31:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/H:/Games/Play2/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:31:56] [main/INFO]: Compatibility level set to JAVA_17

[21:32:12] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[21:32:13] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[21:32:13] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[21:32:13] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
[21:32:13] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 537.58
[21:32:13] [Render thread/INFO]: Initializing ImmediatelyFast 1.2.11+1.20.4 on NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (NVIDIA Corporation) with OpenGL 3.3.0 NVIDIA 537.58
[21:32:14] [Render thread/INFO]: [LambdaBetterGrass] Rebuilding resources...
[21:32:15] [Render thread/INFO]: Launching LiquidBounce v0.2.0 by CCBlueX
[21:32:15] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[21:32:15] [Render thread/INFO]: Intermediary environment detected.
[21:32:15] [Render thread/INFO]: Loaded language en_us
[21:32:15] [Render thread/INFO]: Loaded language de_de
[21:32:15] [Render thread/INFO]: Loaded language ja_jp
[21:32:15] [Render thread/INFO]: Loaded language zh_cn
[21:32:15] [Render thread/INFO]: Loaded language ru_ru
[21:32:15] [Render thread/INFO]: Loaded language en_pt
[21:32:15] [Render thread/INFO]: Loaded language pt_br
[21:32:16] [Worker-Main-1/INFO]: Update available for 'bookshelf@23.0.6', (-> 23.0.8)
[21:32:16] [Worker-Main-1/INFO]: Update available for 'betterstats@3.9.5+fabric-1.20.4', (-> 3.9.7+fabric-1.20.4)
[21:32:16] [Worker-Main-1/INFO]: Update available for 'modmenu@9.0.0', (-> 9.1.0-beta.1)
[21:32:16] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.96.4+1.20.4', (-> 0.97.0+1.20.4)
[21:32:16] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.10.18+kotlin.1.9.22', (-> 1.10.19+kotlin.1.9.23)
[21:32:17] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[21:32:19] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'BlocksMCCriticals.js'.
[21:32:19] [Render thread/WARN]: Unable to find main.js or main.mjs inside the directory lib.
[21:32:19] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyExtraCore 0.1.js'.
[21:32:19] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyLogFilter 0.2.js'.
[21:32:19] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyPacketDebugger 0.3.js'.
[21:32:19] [Render thread/INFO]: [ScriptAPI] Successfully loaded script 'mumyStrongholdFinder 0.1.js'.
[21:32:19] [Render thread/WARN]: BlocksMCCriticals is missing fallback description key liquidbounce.module.blocksMCCriticals.description
[21:32:19] [Render thread/WARN]: mumyAntiBlind is missing fallback description key liquidbounce.module.mumyAntiBlind.description
[21:32:19] [Render thread/WARN]: mumyAntiDrop is missing fallback description key liquidbounce.module.mumyAntiDrop.description
[21:32:19] [Render thread/WARN]: mumyFreePlace is missing fallback description key liquidbounce.module.mumyFreePlace.description
[21:32:19] [Render thread/WARN]: mumyCalculateDamage is missing fallback description key liquidbounce.module.mumyCalculateDamage.description
[21:32:19] [Render thread/WARN]: mumyPacketAdjuster is missing fallback description key liquidbounce.module.mumyPacketAdjuster.description
[21:32:19] [Render thread/WARN]: mumyLogFilter is missing fallback description key liquidbounce.module.mumyLogFilter.description
[21:32:19] [Render thread/WARN]: mumyPacketDebugger is missing fallback description key liquidbounce.module.mumyPacketDebugger.description
[21:32:19] [Render thread/WARN]: mumyStrongholdFinder is missing fallback description key liquidbounce.module.mumyStrongholdFinder.description
[21:32:20] [Render thread/INFO]: Successfully extracted default theme
[21:32:20] [Render thread/INFO]: Inserted 9 components
[21:32:20] [Render thread/INFO]: Successfully loaded config 'enemies'.
[21:32:20] [Render thread/INFO]: Successfully saved config 'enemies'.
[21:32:20] [Render thread/INFO]: (Chat) 
[21:32:20] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[21:32:21] [Render thread/INFO]: Successfully loaded config 'modules'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'modules'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'commands'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'commands'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'friends'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'friends'.
[21:32:21] [Render thread/ERROR]: Unable to deserialize value proxy
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at net.ccbluex.liquidbounce.config.Value.deserializeFrom(Value.kt:223) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeValue(ConfigSystem.kt:275) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:230) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable(ConfigSystem.kt:207) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.deserializeConfigurable$default(ConfigSystem.kt:205) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ConfigSystem.loadAll(ConfigSystem.kt:146) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:164) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:184) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$gga000$liquidbounce$startClient(class_310.java:26350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	... 24 more
[21:32:21] [Render thread/INFO]: Successfully loaded config 'proxy'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'proxy'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'accounts'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'accounts'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'tabs'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'tabs'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'lang'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'lang'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'storage'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'storage'.
[21:32:21] [Render thread/INFO]: Successfully loaded config 'theme'.
[21:32:21] [Render thread/INFO]: Successfully saved config 'theme'.
[21:32:21] [netty-websocket/INFO]: Starting Netty server...
[21:32:21] [nioEventLoopGroup-3-1/INFO]: [id: 0x7e4bd995] REGISTERED
[21:32:21] [nioEventLoopGroup-3-1/INFO]: [id: 0x7e4bd995] BIND: 0.0.0.0/0.0.0.0:16483
[21:32:21] [nioEventLoopGroup-3-1/INFO]: [id: 0x7e4bd995, L:/[0:0:0:0:0:0:0:0]:16483] ACTIVE
[21:32:21] [netty-websocket/INFO]: Netty server started on port 16483.
[21:32:21] [Render thread/INFO]: Refresh Rate: 75 Hz
[21:32:21] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[21:32:22] [Render thread/INFO]: [Downloading Checksum] Started task
[21:32:23] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[21:32:23] [Render thread/INFO]: Checksum matches: true
[21:32:23] [Render thread/INFO]: Platform directory exists: true
[21:32:23] [Render thread/INFO]: Initializing CEF on windows_amd64...
[21:32:23] [Render thread/INFO]: [STDOUT]: initialize on Thread[#1,Render thread,5,main] with library path H:\Games\Play2\.minecraft\versions\1.20.4-Fabric 0.15.7\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64
[21:32:24] [Render thread/INFO]: Chromium Embedded Framework initialized
[21:32:24] [Render thread/INFO]: Browser is ready.
[21:32:24] [Render thread/INFO]: Successfully loaded client!
[21:32:24] [Render thread/INFO]: Loaded background image for theme default
[21:32:24] [Render thread/INFO]: Invalidating pack caches
```

**Comment by SenkJu** [comment]
Hm, is that something we can control? @superblaubeere27
