### ISSUE TITLE
[BUG] LiquidBounce crashes when trying to login to hypixel

### ISSUE THREAD

**Issue by fuckusfm** [CCBlueX/LiquidBounce#2797]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.2.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was trying to hop on hypixel and when i connected with no problems i crashed before displaying the world

### Steps to reproduce

Launch liquidbounce (every recommended mods enabled)
Hop on hypixel

### Client Log

```shell
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:23] [pool-11-thread-1/INFO]: [STDERR]: java.lang.NullPointerException
[12:17:25] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26227()" because the return value of "net.minecraft.class_2841.method_12321(int, int, int)" is null
	at net.minecraft.class_2826.method_12255(class_2826.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12234(class_2818.java:754) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_8316(class_2818.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8316(class_1937.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_2943(class_638.java:388) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_2941(class_638.java:362) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310
```

**Comment by 1zun4** [comment]
Do you have like the full complete log? This seems very weird...

**Comment by 1zun4** [comment]
The issue was caused by Baritone. We have removed Baritone for the time being.

**Comment by 1zun4** [comment]
It is caused by ViaFabricPlus 3.1.0. Baritone was not the direct cause, it simply made it worse by trying to scan the world.
