### ISSUE TITLE
join server crash

### ISSUE THREAD

**Issue by susmonke12** [CCBlueX/LiquidBounce#2856]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

4164187 nextgen

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

I was trying to join cubecraft, (also happens with any other server) but it just crashes and tells me exit code -1

### Steps to reproduce

join any server.

### Client Log

```shell
from minecraft launcher:
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4597.getBuffer(net.minecraft.class_1921)" because "$$4" is null

crash report:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-04-19 18:10:36
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4597.getBuffer(net.minecraft.class_1921)" because "$$4" is null
	at net.minecraft.class_922.method_4054(class_922.java:137)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.handler$zeg000$liquidbounce$injectOutlineESP(class_761.java:3271)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_922.method_4054(class_922.java:137)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.handler$zeg000$liquidbounce$injectOutlineESP(class_761.java:3271)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_745)
	Entity ID: 5788
	Entity Name: BeSleepy
	Entity's Exact location: 454.50, 56.00, -404.50
	Entity's Block location: World: (454,56,-405), Section: (at 6,8,11 in 28,3,-26; chunk contains blocks 448,-64,-416 to 463,319,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.handler$zeg000$liquidbounce$injectOutlineESP(class_761.java:3271)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@364a139a
	Location: 5.00,-2.80,-3.00 - World: (5,-3,-3), Section: (at 5,13,13 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: -180.0
	Delta: 0.43979454
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.handler$zeg000$liquidbounce$injectOutlineESP(class_761.java:3271)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 74.839s
	Wall uptime: 67.289s
	High-res time: 66.957s
	Client ticks: 1117 ticks / 55.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 20 total; [class_746['wauudahhdrinker'/53948, l='ClientLevel', x=449.50, y=57.18, z=-401.50], class_745['Gideman'/12724, l='ClientLevel', x=453.50, y=56.00, z=-399.50], class_745['ItzayselSleep'/53763, l='ClientLevel', x=454.50, y=56.00, z=-401.50], class_745['BeSleepy'/5788, l='ClientLevel', x=454.50, y=56.00, z=-404.50], class_745['Sandalek'/47235, l='ClientLevel', x=450.50, y=56.00, z=-399.50], class_745['Hedgwig'/53633, l='ClientLevel', x=450.50, y=56.00, z=-403.15], class_745['ib20'/53369, l='ClientLevel', x=454.62, y=55.00, z=-409.44], class_745['juleczkak'/44321, l='ClientLevel', x=450.50, y=56.00, z=-403.50], class_745['TomSon_Ajax'/46309, l='ClientLevel', x=456.46, y=55.00, z=-396.48], class_745['Jxmand'/48107, l='ClientLevel', x=466.55, y=55.00, z=-400.16], class_745['WolfWizard86'/28365, l='ClientLevel', x=424.00, y=55.00, z=-406.07], class_745['vojtxx1_CZ'/50317, l='ClientLevel', x=431.55, y=54.00, z=-397.89], class_745['Mango0tje_'/5787, l='ClientLevel', x=454.50, y=56.00, z=-399.50], class_745['YSQ_'/52995, l='ClientLevel', x=451.12, y=56.00, z=-402.51], class_745['_EliteMay'/5789, l='ClientLevel', x=451.50, y=56.00, z=-401.50], class_745['Minkuhhh'/52032, l='ClientLevel', x=471.57, y=54.50, z=-408.99], class_745['jestem_bot'/53464, l='ClientLevel', x=454.50, y=56.00, z=-398.50], class_745['gunabol'/53947, l='ClientLevel', x=449.50, y=56.00, z=-398.50], class_745['mdurn'/5242, l='ClientLevel', x=452.50, y=56.00, z=-400.50], class_745['Teaman1917'/39861, l='ClientLevel', x=452.50, y=56.00, z=-398.50]]
	Chunk stats: 841, 275
	Level dimension: minecraft:overworld
	Level spawn location: World: (449,56,-405), Section: (at 1,8,11 in 28,3,-26; chunk contains blocks 448,-64,-416 to 463,319,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 14210214 game time, 460000 day time
	Server brand: BungeeCraft (c75f153)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 276

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: vanilla, server/00000000/cdfc6a3e-013d-352f-88b4-e22cd03796bb
```

### Screenshots

![Screenshot 2024-04-19 181710](https://github.com/CCBlueX/LiquidBounce/assets/149056268/48d4d464-9cb9-4577-9a65-a4a9fb367cf7)

**Comment by Razzy52** [comment]
Try a viafabricplus version 3.06 or lower

**Comment by 1zun4** [comment]
Switch OutlineShader to Glow Shader instead.
