### ISSUE TITLE
liquidbounce-nextgen always crash when loading[BUG]

### ISSUE THREAD

**Issue by liquidbounce-thebestclient** [CCBlueX/LiquidBounce#2864]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.3.0

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

i was try to launch nextgen with the launcher(liquidbounce launcher) and other luncher with this mod , but when loading , it's always crash with message timeout , so i restart the client and launcher , but no any fixs , my luncher is least , what can i do now ?

**[crash with liquidbounce-nextgen]**

![image](https://github.com/CCBlueX/LiquidBounce/assets/167439424/a6476737-e54c-4499-9e5d-2aeb4c529ed0)

### Steps to reproduce

i did delete the liquidbounce folder in minecraft , just want a blank config so i want to made a new , but it crash next time

### Client Log

```shell
Loading minecraft version manifest...
Loading version profile...
Downloading inherited version 1.20.4...
Launching 416418728dae109af790c3db42f1350e159cd07f...
Determined OS to be windows 10.0.22621
Checking for JRE...
Java binary: "C:\\Users\\86180\\AppData\\Roaming\\CCBlueX\\LiquidLauncher\\data\\runtimes\\temurin_17\\jdk-17.0.10+7-jre\\bin\\javaw.exe"
An error occourd:

(os error 5)
```

**Comment by liquidbounce-thebestclient** [comment]
help me pls

**Comment by liquidbounce-thebestclient** [comment]
new crash log!

:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.download(HttpClient.kt:112) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.downloadFont(Fonts.kt:115) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce(Fonts.kt:77) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce$default(Fonts.kt:70) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$QueuedFont.loadNow(Fonts.kt:159) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadQueuedFonts(Fonts.kt:55) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$
ClientResourceReloader.method_14491(LiquidBounce.kt:207) ~[LiquidBounce.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.
java:265) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

**Comment by 1zun4** [comment]
This looks like something is blocking your connection.

Please try following https://liquidbounce.net/docs/Tutorials/Fixing%20LiquidLauncher "Fixing issues with the system's hosts file"
or check if any of your Windows FW or AV settings block something. Also try changing your DNS.
