### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NickSuengMin** [CCBlueX/LiquidBounce#2945]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.41

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was playing Liquid and clicked on launch. Wait a minute I see an error

### Steps to reproduce

i wont know

### Client Log

```shell
~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$cnj000$liquidbounce$startClient(class_310.java:10850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.3-1.20.4.jar:?]
	at java.lang.invoke.LambdaForm$DMH/0x000001cf12258400.invokeStaticInit(LambdaForm$DMH) ~[?:?]
	at java.lang.invoke.LambdaForm$MH/0x000001cf122b4000.invokeExact_MT(LambdaForm$MH) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by 1zun4** [comment]
Missing most of the log. Post full log.
