### ISSUE TITLE
[BUG][CRASH]

### ISSUE THREAD

**Issue by ShubhamPrakash2** [CCBlueX/LiquidBounce#2973]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

liquidbounce- 7e0dba8    0.4.1 / 1.20.4

### Operating System

Windows 8.1

### Minecraft Version

1.20.4

### Describe the bug

MC crashed after extracting file

### Steps to reproduce

Just start the game u will get the error

### Client Log

```shell
[22:49:54] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[22:49:55] [main/INFO]: Loading 74 mods:
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.4.1
	- lithium 0.12.1
	- minecraft 1.20.4
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
[22:49:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Shubham_Prakash/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:49:56] [main/INFO]: Compatibility level set to JAVA_17
[22:49:57] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[22:49:57] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[22:49:57] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[22:50:04] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[22:50:06] [main/INFO]: Searching for graphics cards...
[22:50:06] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[22:50:07] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics Family, version=DriverVersion=10.18.10.3960]
[22:50:13] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[22:50:32] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 519 milliseconds
[22:50:42] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:50:42] [Render thread/INFO]: Setting user: shubhamshivam
[22:50:44] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[22:50:45] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[22:50:45] [Render thread/INFO]: OpenGL Vendor: Intel
[22:50:45] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 4400
[22:50:45] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 10.18.10.3960
[22:50:49] [Render thread/INFO]: Launching LiquidBounce v0.4.1 by CCBlueX
[22:50:50] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[22:50:50] [Render thread/INFO]: Intermediary environment detected.
[22:50:50] [Render thread/INFO]: Loaded language en_us
[22:50:50] [Render thread/INFO]: Loaded language de_de
[22:50:50] [Render thread/INFO]: Loaded language ja_jp
[22:50:50] [Render thread/INFO]: Loaded language zh_cn
[22:50:50] [Render thread/INFO]: Loaded language ru_ru
[22:50:50] [Render thread/INFO]: Loaded language en_pt
[22:50:50] [Render thread/INFO]: Loaded language pt_br
[22:50:53] [Render thread/INFO]: Successfully extracted default theme
[22:50:54] [Render thread/INFO]: Inserted 10 components
[22:50:54] [Render thread/INFO]: Successfully loaded config 'enemies'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'enemies'.
[22:50:54] [Render thread/INFO]: (Chat) 
[22:50:54] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[22:50:54] [Render thread/INFO]: Successfully loaded config 'modules'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'modules'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'commands'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'commands'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'friends'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'friends'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'proxy'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'proxy'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'accounts'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'accounts'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'tabs'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'tabs'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'lang'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'lang'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'storage'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'storage'.
[22:50:54] [Render thread/INFO]: Successfully loaded config 'theme'.
[22:50:54] [Render thread/INFO]: Successfully saved config 'theme'.
[22:50:54] [netty-websocket/INFO]: Default port 15000 available.
[22:50:55] [netty-websocket/INFO]: Starting Netty server...
[22:50:55] [nioEventLoopGroup-2-1/INFO]: [id: 0xaa25da38] REGISTERED
[22:50:55] [nioEventLoopGroup-2-1/INFO]: [id: 0xaa25da38] BIND: 0.0.0.0/0.0.0.0:15000
[22:50:55] [netty-websocket/INFO]: Netty server started on port 15000.
[22:50:55] [nioEventLoopGroup-2-1/INFO]: [id: 0xaa25da38, L:/0.0.0.0:15000] ACTIVE
[22:50:56] [Render thread/INFO]: Refresh Rate: 60 Hz
[22:50:56] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[22:51:08] [Render thread/INFO]: [Downloading Checksum] Started task
[22:51:09] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[22:51:09] [Render thread/INFO]: Checksum matches: true
[22:51:09] [Render thread/INFO]: Platform directory exists: true
[22:51:09] [Render thread/INFO]: Initializing CEF on windows_amd64...
[22:51:09] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\Shubham_Prakash\AppData\Roaming\.minecraft\versions\Bounce\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\libcef.dll: The specified procedure could not be found
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:455) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:67) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$blj000$liquidbounce$startClient(class_310.java:7350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Bounce.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[22:51:26] [Render thread/ERROR]: Fatal error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_333.method_1791()" because the return value of "net.minecraft.class_310.method_44713()" is null
	at net.minecraft.class_309.method_1466(class_309.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:492) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.util.tinyfd.TinyFileDialogs.ntinyfd_messageBox(Native Method) ~[lwjgl-tinyfd-3.3.2.jar:?]
	at org.lwjgl.util.tinyfd.TinyFileDialogs.tinyfd_messageBox(TinyFileDialogs.java:307) ~[lwjgl-tinyfd-3.3.2.jar:?]
	at net.ccbluex.liquidbounce.utils.client.ErrorHandler.fatal(ErrorHandler.kt:58) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.client.ErrorHandler.fatal$default(ErrorHandler.kt:39) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$blj000$liquidbounce$startClient(class_310.java:7350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Bounce.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
```

### Screenshots

![ss2](https://github.com/CCBlueX/LiquidBounce/assets/168987454/2e7e0c78-4ed9-4c56-a386-936ca9105cb6)

**Comment by ShubhamPrakash2** [comment]
PLS SOLVE THIS ISSUE

**Comment by N0tHorizon** [comment]
Based on the error message you provided, the issue seems to be related to the libcef.dll file, which is a part of the Chromium Embedded Framework (CEF) used by LiquidBounce for web-related functionality. Since the error specifically mentions that a procedure in libcef.dll could not be found, the problem likely lies within this file or its dependencies.

Here's what you can do:

    Verify the Integrity of libcef.dll: Ensure that the libcef.dll file is present in the specified location (C:\Users\Shubham_Prakash\AppData\Roaming\.minecraft\versions\Bounce\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\) and that it's not corrupted. You can try re-downloading the LiquidBounce client or reinstalling it to make sure all required files are intact.

    Check for Compatibility Issues: Make sure that the version of libcef.dll you have is compatible with your system (Windows 8.1) and Java version (Java 17). Sometimes, compatibility issues can arise if the library was built for a different platform or architecture.

    Update or Reinstall CEF: If you suspect that libcef.dll is outdated or incompatible, you can try updating it to a newer version. Alternatively, you can reinstall the LiquidBounce client, which may include a newer version of CEF with the necessary fixes.

    Review Dependencies: Check if there are any other dependencies or configuration files related to CEF that may be causing the issue. Sometimes, missing or misconfigured dependencies can lead to DLL loading errors.

**Comment by N0tHorizon** [comment]
If the issue persists try updating your java binary or LiquidBounce. If liquid is at its latest update try a earlier version or try uninstalling and reinstalling. I have reviewed the libcef.dll file and found issue of why you are crashing, I will fix the issue that you are experiencing

**Comment by 1zun4** [comment]
@TWS-Python Try deleting your LiquidBounce folder and restart.

**Comment by ShubhamPrakash2** [comment]
@TWS-Python 
Statement 1:
Ok I have tried 1st step deleted many time, reinstall many time, even restarted my PC ,tried older versions but issue persists...
Statement 2:
How can I check that.
I have tried to download that DLL file from internet but it failed. Also it has great size difference internet_dll=50MB lb_dll=200MB
Statement 3:
How can I update that DLL.
Statement 4:
If there is other dependencies it must get downloaded with liquidbounce package.

BTW What to do with issue #2999.(I am new to GitHub, just joined GitHub for this issue only)
Thanks for your comment

**Comment by 1zun4** [comment]
Windows 8 is not supported.
