### ISSUE TITLE
0.1.0 crashing for no reason (i have administrator on)

### ISSUE THREAD

**Issue by talonfrost** [CCBlueX/LiquidBounce#2974]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

I was just going to play on 0.1.0 to see if it has aac but when i could get a chance to load it crashed :sad

### Steps to reproduce

turn all downloads to on

### Client Log

```shell
Loading minecraft version manifest...Downloading recommended mod LiquidBounceDownloading recommended mod Fabric APIDownloading recommended mod Fabric KotlinDownloading recommended mod ImmediatelyFastDownloading recommended mod IrisDownloading recommended mod LithiumDownloading recommended mod Mod MenuDownloading recommended mod No Chat ReportsDownloading recommended mod Reese's Sodium OptionsDownloading recommended mod Sodium ExtraDownloading recommended mod SodiumDownloading recommended mod ViaFabricPlusLoading version profile...Downloading inherited version 1.20.4...Launching 034fcd07b9c9326e51417d2933c4544dcc0c5724...Setting up...Determined OS to be windows 10.0.19045Checking for JRE...Java Path: "C:\\Users\\Talon Edward Frost\\AppData\\Roaming\\CCBlueX\\LiquidLauncher\\data\\runtimes\\temurin_17\\jdk-17.0.11 9-jre\\bin\\javaw.exe"Client JAR local hash: fd19469fed4a4b4c15b2d5133985f0e3e7816a8a, remote: fd19469fed4a4b4c15b2d5133985f0e3e7816a8aChecking libraries...Library com.github.oshi:oshi-core:6.4.5 already exists and SHA1 matches.Library com.google.code.gson:gson:2.10.1 already exists and SHA1 matches.Library org.ow2.asm:asm:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-analysis:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-commons:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-tree:9.6 already exists and SHA1 matches.Library org.ow2.asm:asm-util:9.6 already exists and SHA1 matches.Library net.fabricmc:sponge-mixin:0.12.5 mixin.0.8.5 already exists and SHA1 matches.Library net.fabricmc:intermediary:1.20.4 already exists and SHA1 matches.Library net.fabricmc:fabric-loader:0.15.1 already exists and SHA1 matches.Library com.google.guava:failureaccess:1.0.1 already exists and SHA1 matches.Library com.ibm.icu:icu4j:73.2 already exists and SHA1 matches.Library com.google.guava:guava:32.1.2-jre already exists and SHA1 matches.Library com.mojang:authlib:6.0.52 already exists and SHA1 matches.Library com.mojang:blocklist:1.0.10 already exists and SHA1 matches.Library com.mojang:brigadier:1.2.9 already exists and SHA1 matches.Library com.mojang:datafixerupper:6.0.8 already exists and SHA1 matches.Library com.mojang:logging:1.1.1 already exists and SHA1 matches.Library com.mojang:patchy:2.2.10 already exists and SHA1 matches.Library com.mojang:text2speech:1.17.9 already exists and SHA1 matches.Library commons-codec:commons-codec:1.16.0 already exists and SHA1 matches.Library commons-logging:commons-logging:1.2 already exists and SHA1 matches.Library commons-io:commons-io:2.13.0 already exists and SHA1 matches.Library io.netty:netty-codec:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-buffer:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-common:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-handler:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-resolver:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-transport-classes-epoll:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-transport-native-unix-common:4.1.97.Final already exists and SHA1 matches.Library io.netty:netty-transport:4.1.97.Final already exists and SHA1 matches.Library net.java.dev.jna:jna:5.13.0 already exists and SHA1 matches.Library net.java.dev.jna:jna-platform:5.13.0 already exists and SHA1 matches.Library org.apache.commons:commons-lang3:3.13.0 already exists and SHA1 matches.Library org.apache.commons:commons-compress:1.22 already exists and SHA1 matches.Library net.sf.jopt-simple:jopt-simple:5.0.4 already exists and SHA1 matches.Library org.apache.httpcomponents:httpclient:4.5.13 already exists and SHA1 matches.Library it.unimi.dsi:fastutil:8.5.12 already exists and SHA1 matches.Library org.apache.httpcomponents:httpcore:4.4.16 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-api:2.19.0 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-core:2.19.0 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0 already exists and SHA1 matches.Library org.joml:joml:1.10.5 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.slf4j:slf4j-api:2.0.7 already exists and SHA1 matches.Checking assets...Launching...Running...[21:53:15] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[21:53:15] [ForkJoinPool-1-worker-1/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[21:53:15] [main/INFO]: Loading 104 mods:
	- fabric-api 0.91.3 1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.45 78d798af4f
	   |-- fabric-biome-api-v1 13.0.15 78d798af4f
	   |-- fabric-block-api-v1 1.0.14 78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45 78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6 78d798af4f
	   |-- fabric-command-api-v1 1.2.40 f71b366f4f
	   |-- fabric-commands-v0 0.2.57 df3654b34f
	   |-- fabric-containers-v0 0.1.81 df3654b34f
	   |-- fabric-content-registries-v0 5.0.9 78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9 78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22 78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17 78d798af4f
	   |-- fabric-dimensions-v1 2.1.60 78d798af4f
	   |-- fabric-entity-events-v1 1.5.28 4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14 78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71 df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45 78d798af4f
	   |-- fabric-item-api-v1 2.1.34 78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20 78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40 78d798af4f
	   |-- fabric-keybindings-v0 0.2.38 df3654b34f
	   |-- fabric-loot-api-v2 2.1.4 78d798af4f
	   |-- fabric-message-api-v1 6.0.4 78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59 78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7 78d798af4f
	   |-- fabric-models-v0 0.4.6 9386d8a74f
	   |-- fabric-object-builder-api-v1 13.0.7 78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15 78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3 78d798af4f
	   |-- fabric-renderer-indigo 1.5.3 78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50 df3654b34f
	   |-- fabric-rendering-v0 1.1.53 df3654b34f
	   |-- fabric-rendering-v1 3.0.12 78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13 78d798af4f
	   |-- fabric-screen-api-v1 2.0.16 78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50 78d798af4f
	   |-- fabric-sound-api-v1 1.0.16 78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6 78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13 78d798af4f
	- fabric-language-kotlin 1.9.4 kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- liquidbounce 0.1.0
	- lithium 0.12.1
	- minecraft 1.20.4
	- modmenu 9.0.0
	   |-- fabric-key-binding-api-v1 1.0.40 78d798af4f
	   \-- fabric-screen-api-v1 2.0.16 78d798af4f
	- nochatreports 1.20.4-v2.5.0
	- reeses-sodium-options 1.7.2 mc1.20.4-build.102
	- sodium 0.5.8 mc1.20.4
	   |-- fabric-api-base 0.4.36 78d798af4f
	   |-- fabric-block-view-api-v2 1.0.4 78d798af4f
	   |-- fabric-rendering-data-attachment-v1 0.3.42 73761d2e4f
	   \-- fabric-rendering-fluids-v1 3.0.33 78d798af4f
	- sodium-extra 0.5.4 mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0 1.17
	   \-- crowdin-translate 1.4 1.19.3
	- viafabricplus 3.1.0
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-24w09a-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-24w09a-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.2
	   |-- fabric-command-api-v2 2.2.20 78d798af4f
	   |-- fabric-lifecycle-events-v1 2.3.0 a67ffb5d4f
	   |-- fabric-networking-api-v1 3.1.7 2e5ac5484f
	   |-- fabric-particles-v1 1.1.7 78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18 78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18 b66dcf784f
	   |-- io_jsonwebtoken_jjwt-api 0.12.5
	   |-- io_jsonwebtoken_jjwt-gson 0.12.5
	   |-- io_jsonwebtoken_jjwt-impl 0.12.5
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.4.1
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.2
	   |-- net_raphimc_minecraftauth 4.0.0-SNAPSHOT
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.5-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[21:53:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Talon Edward Frost/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:53:16] [main/INFO]: Compatibility level set to JAVA_17
[21:53:16] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[21:53:16] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[21:53:16] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:53:17] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:53:17] [main/INFO]: Searching for graphics cards...
[21:53:17] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[21:53:18] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon HD 7600 Series, version=DriverVersion=15.201.1151.1008]
[21:53:21] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
[21:53:21] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
[21:53:21] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;Lcom/llamalad7/mixinextras/sugar/ref/LocalFloatRef;)Z in viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.doPostInject(InjectorWrapperImpl.java:79) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.doPostInject(SugarWrapperImpl.java:84) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.postInject(WrapperInjectionInfo.java:78) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by Razzy52** [comment]
why are you using such an old version?

**Comment by 1zun4** [comment]
Update to newest version...
