### ISSUE TITLE
[BUG] CRASH

### ISSUE THREAD

**Issue by weks1dev** [CCBlueX/LiquidBounce#3013]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

liquidbounce- 7e0dba8 0.4.1 / 1.20.4

### Operating System

Windows 7

### Minecraft Version

1.20.4

### Describe the bug

When  start the game, it crashes, I tried to update java and nothing happened

### Steps to reproduce

When starting the game, the following error appears

### Client Log

```shell
[11:50:46] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[11:50:46] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[11:50:47] [main/INFO]: Loading 98 mods:
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- liquidbounce 0.4.1
	- minecraft 1.20.4
	- modmenu 9.2.0-beta.2
	- sodium 0.5.8+mc1.20.4
	- tlskincape 1.33
	- viafabricplus 3.0.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0-23w51b-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.10.0-23w51b-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.1.0
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
	- worldtools 1.2.4
[11:50:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:50:47] [main/INFO]: Compatibility level set to JAVA_17
[11:50:48] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[11:50:49] [main/INFO]: Searching for graphics cards...
[11:50:51] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GT 640, version=DriverVersion=26.21.14.4187]
[11:50:51] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[11:50:51] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[11:50:51] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[11:50:54] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[11:51:02] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 537 milliseconds
[11:51:07] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:51:07] [Render thread/INFO]: Setting user: weks1dev
[11:51:09] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[11:51:09] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[11:51:09] [Render thread/INFO]: Checking mod updates...
[11:51:09] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[11:51:09] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[11:51:10] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[11:51:10] [Update Checker/Fabric Loader/INFO]: Update available for 'fabricloader@0.15.7'
[11:51:11] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.10.18+kotlin.1.9.22', (-> 1.10.20+kotlin.1.9.24)
[11:51:11] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.96.4+1.20.4', (-> 0.97.0+1.20.4)
[11:51:11] [Worker-Main-1/INFO]: Update available for 'modmenu@9.2.0-beta.2', (-> 9.0.0)
[11:51:11] [Worker-Main-1/INFO]: Update available for 'viafabricplus@3.0.6', (-> 3.1.1)
[11:51:11] [Render thread/INFO]: Initializing WorldTools 1.2.4
[11:51:11] [Render thread/INFO]: WorldTools Fabric initialized
[11:51:12] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[11:51:12] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[11:51:13] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[11:51:13] [Render thread/INFO]: OpenGL Renderer: GeForce GT 640/PCIe/SSE2
[11:51:13] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 441.87
[11:51:13] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:59973/
[11:51:13] [Render thread/WARN]: Missing metadata in pack file/by fullsidee.zip
[11:51:13] [Render thread/INFO]: Found non-pack entry 'C:\Users\User\AppData\Roaming\.minecraft\resourcepacks\DJHWHDLJHKWBDJWDBWHDB.rar', ignoring
[11:51:13] [Render thread/ERROR]: Failed to open pack C:\Users\User\AppData\Roaming\.minecraft\resourcepacks\open_this_and_move_all files_inside_color_variants_folder_to_your_resourcepack_folder.zip
java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1763) ~[?:?]
	at java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1244) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1702) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1442) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:252) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:181) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:195) ~[?:?]
	at net.minecraft.class_3258$class_8616.method_52426(class_3258.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14391(class_3258.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14410(class_3258.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:76) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
[11:51:14] [Render thread/WARN]: Missing metadata in pack file/open_this_and_move_all files_inside_color_variants_folder_to_your_resourcepack_folder.zip
[11:51:14] [Render thread/WARN]: Removed resource pack minecraft:supporteatinganimation from options because it doesn't seem to exist anymore
[11:51:15] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[11:51:15] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 23w51b (766)
[11:51:15] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:51:15] [Render thread/INFO]: Launching LiquidBounce v0.4.1 by CCBlueX
[11:51:16] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[11:51:16] [Render thread/INFO]: Intermediary environment detected.
[11:51:16] [Render thread/INFO]: Loaded language en_us
[11:51:16] [Render thread/INFO]: Loaded language de_de
[11:51:16] [Render thread/INFO]: Loaded language ja_jp
[11:51:16] [Render thread/INFO]: Loaded language zh_cn
[11:51:16] [Render thread/INFO]: Loaded language ru_ru
[11:51:16] [Render thread/INFO]: Loaded language en_pt
[11:51:16] [Render thread/INFO]: Loaded language pt_br
[11:51:19] [Render thread/INFO]: Successfully extracted default theme
[11:51:19] [Render thread/INFO]: Inserted 10 components
[11:51:19] [Render thread/INFO]: Successfully loaded config 'enemies'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'enemies'.
[11:51:19] [Render thread/INFO]: (Chat) 
[11:51:19] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8? §7Auto ConfigAuto Config
[11:51:19] [Render thread/INFO]: Successfully loaded config 'modules'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'modules'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'commands'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'commands'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'friends'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'friends'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'proxy'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'proxy'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'accounts'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'accounts'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'tabs'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'tabs'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'lang'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'lang'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'storage'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'storage'.
[11:51:19] [Render thread/INFO]: Successfully loaded config 'theme'.
[11:51:19] [Render thread/INFO]: Successfully saved config 'theme'.
[11:51:19] [Render thread/INFO]: Refresh Rate: 60 Hz
[11:51:20] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[11:51:20] [netty-websocket/INFO]: Default port 15000 available.
[11:51:20] [netty-websocket/INFO]: Starting Netty server...
[11:51:20] [nioEventLoopGroup-3-1/INFO]: [id: 0x59550f3f] REGISTERED
[11:51:20] [nioEventLoopGroup-3-1/INFO]: [id: 0x59550f3f] BIND: 0.0.0.0/0.0.0.0:15000
[11:51:20] [nioEventLoopGroup-3-1/INFO]: [id: 0x59550f3f, L:/0.0.0.0:15000] ACTIVE
[11:51:20] [netty-websocket/INFO]: Netty server started on port 15000.
[11:51:27] [Render thread/INFO]: [Downloading Checksum] Started task
[11:51:27] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[11:51:27] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[11:51:27] [Render thread/INFO]: Checksum matches: true
[11:51:27] [Render thread/INFO]: Platform directory exists: true
[11:51:27] [Render thread/INFO]: Initializing CEF on windows_amd64...
[11:51:27] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\User\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\chrome_elf.dll: Не найдена указанная процедура
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1957) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:454) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:67) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$bmi000$liquidbounce$startClient(class_310.java:7850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
```

### Screenshots

![Screenshot_2](https://github.com/CCBlueX/LiquidBounce/assets/169652609/e721175b-eaf7-47e0-82dd-c3069a3392fc)

**Comment by 1zun4** [comment]
Update your Windows. Windows 7 is not supported.
