### ISSUE TITLE
[BUG] my liquidbounce keeps crashing when i lauch it but it says run with admin and i tried that and it still crashed

### ISSUE THREAD

**Issue by justinedds** [CCBlueX/LiquidBounce#3051]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.5.1

### Operating System

Windows 11

### Minecraft Version

1.20.6

### Describe the bug

i launched liquidbounce then pressed lauch then it just crashed

### Steps to reproduce

i launched liquidbounce then i pressed play for error 1

### Client Log

```shell
e.mcef.cef.CefHelper.init(CefHelper.java:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:67) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:72) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) [LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.c
allEvent(EventManager.kt:186) [LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$cgi000$liquidbounce$startClient(class_310.java:10320) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:674) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by 1zun4** [comment]
We need the full crash log. But if you are using LiquidLauncher, might try to use the "Clear data" button in the settings and try again.

**Comment by justinedds** [comment]
ok
