### ISSUE TITLE
[BUG] liquidbounce-ui/vite fails to build when running in a symlinked folder

### ISSUE THREAD

**Issue by pp0236** [CCBlueX/LiquidBounce#3107]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b4f013685c14d7dcc27064541eaf0a5a5c66c35b

### Operating System

Windows 10

### Minecraft Version

\-

### Describe the bug

```
C:\Users\kaury\Desktop\dev\LiquidBounce\src-theme>npm run build

> liquidbounce-ui@0.0.0 build
> vite build

7:28:50 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

@jhubbardsf/svelte-sortablejs@1.1.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
vite v5.1.7 building for production...
✓ 308 modules transformed.
x Build failed in 11.69s
error during build:
RollupError: [vite:build-html] The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths, received "D:/another-tf2-paste/LiquidBounce/src-theme/index.html".
    at error (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at FileEmitter.emitFile (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/rollup/dist/es/shared/node-entry.js:18235:24)
    at Object.generateBundle (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:30958:22)
    at async Bundle.generate (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/rollup/dist/es/shared/node-entry.js:17096:9)
    at async file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/rollup/dist/es/shared/node-entry.js:19645:27
    at async catchUnfinishedHookActions (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/rollup/dist/es/shared/node-entry.js:19075:16)
    at async build (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:67051:22)
    at async CAC.<anonymous> (file:///D:/another-tf2-paste/LiquidBounce/src-theme/node_modules/vite/dist/node/cli.js:842:9)

C:\Users\kaury\Desktop\dev\LiquidBounce\src-theme>
```

fix: https://stackoverflow.com/a/77705155

### Steps to reproduce

- mklink /d C:\\....Desktop\workspace\LiquidBounce D:\\workspace\....\LiquidBounce 
- building from workspace on the desktop

### Client Log

```shell
-
```

**Comment by 1zun4** [comment]
Sorry but at this point you can fix the issue yourself.
