### ISSUE TITLE
[BUG] Crash Error: Java heap space Error Type: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Prepkitty** [CCBlueX/LiquidBounce#3189]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.6.0

### Operating System

Windows 11

### Minecraft Version

1.7-1.20.6

### Describe the bug

every time i open it liquidlauncher and click launch that screen comes

### Steps to reproduce

open liquid launcher then click launch

### Client Log

```shell
LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:193) [LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$cgl000$liquidbounce$startClient(class_310.java:10320) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:674) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) [client-intermediary.jar:?]
	at java.base/java.lang.invoke.LambdaForm$DMH/0x000001d510284000.invokeStaticInit(LambdaForm$DMH) ~[?:?]
	at java.base/java.lang.invoke.LambdaForm$MH/0x000001d510260800.invokeExact_MT(LambdaForm$MH) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
An error occourd:

Process exited with non-zero exit code: 1.
```

### Screenshots

![image_2024-06-04_145030460](https://github.com/CCBlueX/LiquidBounce/assets/171693900/59ab9323-edaa-4f4c-abfd-087753c25282)

**Comment by 1zun4** [comment]
How much memory does your PC have? Try going into the LiquidLauncher settings and increase the maximum memory usage.

**Comment by Prepkitty** [comment]
1 gb over and i put 100% memory

**Comment by Prepkitty** [comment]
> How much memory does your PC have? Try going into the LiquidLauncher settings and increase the maximum memory usage.

i use laptop if that matters

**Comment by 1zun4** [comment]
1gb is not enough. It will not run on your hardware.

**Comment by Prepkitty** [comment]
how do i get more memory?

**Comment by Prepkitty** [comment]
wait never mind i have 30gb

**Comment by 1zun4** [comment]
We are not talking about disk space, but RAM, which is random access memory that can only be increased by plugging in more Memory Sticks. Sometimes these are not expandable on laptops, especially on low-power or Chromebook-like laptops.

You can check your RAM in the Task Manager:
![image](https://github.com/CCBlueX/LiquidBounce/assets/12410754/f42082d7-86ee-4389-910b-2507519289e1)

**Comment by Prepkitty** [comment]
wait i got more than you does that mean i can run?
