### ISSUE TITLE
[BUG] lb crash PLS help [idk the log is really long and idk If It fully fits]

### ISSUE THREAD

**Issue by GHOTY-Glitch** [CCBlueX/LiquidBounce#3273]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.6.0

### Operating System

Linux

### Minecraft Version

1.20.6

### Describe the bug

I started lb NextGen, It IS my First time getting this client, and It crash when the loading bar IS almost fully complete

What i use:
Fabric API
Kotlin Launguages Fabric

OS:Linux
Java: 21.0.1
Version: 1.20.6

### Steps to reproduce

Launch lb

### Client Log

```shell
--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: realme RMX3830
Info: API version: 33
Info: Selected Minecraft version: fabric-loader-0.15.11-1.20.6
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1600
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~6olB4g7uC7_D21TU29C6cw==/net.kdt.pojavlaunch-_GmonYkHli1f1zJ5UF4FkA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~6olB4g7uC7_D21TU29C6cw==/net.kdt.pojavlaunch-_GmonYkHli1f1zJ5UF4FkA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 64), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (16807): dlopen libgl4es_114.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success

I/jrelog  (16807): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libinstrument.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjdwp.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjsig.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/liblcms.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsyslookup.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libextnet.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libzip.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjimage.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libprefs.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjaas.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/librmi.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2gss.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success
I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjawt.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsctp.so success

I/jrelog  (16807): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (16807): dlopen /data/app/~~6olB4g7uC7_D21TU29C6cw==/net.kdt.pojavlaunch-_GmonYkHli1f1zJ5UF4FkA==/lib/arm64/libopenal.so success

I/jrelog  (16807): Done processing args

I/jrelog  (16807): Found JLI lib
I/jrelog  (16807): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[15:50:19] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[15:50:20] [main/INFO]: Loading 66 mods:
	- fabric-api 0.100.2+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51b0
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bb0
	   |-- fabric-biome-api-v1 13.0.25+be5d88beb0
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bb0
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51b0
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51b0
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bb0
	   |-- fabric-command-api-v1 1.2.45+f71b366fb0
	   |-- fabric-command-api-v2 2.2.24+80f8cf51b0
	   |-- fabric-commands-v0 0.2.62+df3654b3b0
	   |-- fabric-content-registries-v0 8.0.6+b82b2392b0
	   |-- fabric-convention-tags-v1 2.0.7+7f945d5bb0
	   |-- fabric-convention-tags-v2 2.1.3+f4bfb622b0
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51b0
	   |-- fabric-data-attachment-api-v1 1.1.17+2a2c66b6b0
	   |-- fabric-data-generation-api-v1 19.2.3+a5d5299db0
	   |-- fabric-dimensions-v1 2.1.68+94793913b0
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bb0
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3b0
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51b0
	   |-- fabric-item-api-v1 8.2.3+6e5bbc4ab0
	   |-- fabric-item-group-api-v1 4.1.1+f4bfb622b0
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51b0
	   |-- fabric-keybindings-v0 0.2.43+df3654b3b0
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3b0
	   |-- fabric-loot-api-v2 3.0.6+97f703dab0
	   |-- fabric-message-api-v1 6.0.11+a7dc0e41b0
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51b0
	   |-- fabric-models-v0 0.4.11+9386d8a7b0
	   |-- fabric-networking-api-v1 4.2.0+a916f7c5b0
	   |-- fabric-object-builder-api-v1 15.1.5+c5fc38b3b0
	   |-- fabric-particles-v1 4.0.0+c5fc38b3b0
	   |-- fabric-recipe-api-v1 5.0.5+c5fc38b3b0
	   |-- fabric-registry-sync-v0 5.0.18+a916f7c5b0
	   |-- fabric-renderer-api-v1 3.2.12+97f703dab0
	   |-- fabric-renderer-indigo 1.5.14+41791025b0
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3b0
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb0
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb0
	   |-- fabric-rendering-v0 1.1.64+df3654b3b0
	   |-- fabric-rendering-v1 4.2.4+b21c00cbb0
	   |-- fabric-resource-conditions-api-v1 4.2.0+a5d5299db0
	   |-- fabric-resource-loader-v0 1.1.1+f4bfb622b0
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8ab0
	   |-- fabric-screen-handler-api-v1 1.3.75+8c7b71c2b0
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3b0
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3b0
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560b0
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- liquidbounce 0.6.0
	- minecraft 1.20.6
[15:50:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:50:21] [main/INFO]: Compatibility level set to JAVA_17
[15:50:24] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[15:50:24] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[15:50:25] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[15:50:27] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~6olB4g7uC7_D21TU29C6cw==/net.kdt.pojavlaunch-_GmonYkHli1f1zJ5UF4FkA==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:?]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:?]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) [client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) [client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) [client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[15:50:27] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:?]
	at net.minecraft.class_6396.method_37133(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) [client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) [client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) [client-intermediary.jar:?]
	at net.minecraft
```

**Comment by liquidsquid1** [comment]
Pojav Launcher is not supported by the LiquidBounce client. Please use a PC **(do not use legacy, nextgen is the better client)**

**Comment by EclipsesDev** [comment]
well if the question was how to use lb in pojav, well only legacy is supported there.. but for laptop/pc you can use both nextgen & legacy 👍

**Comment by GHOTY-Glitch** [comment]
> well if the question was how to use lb in pojav, well only legacy is supported there.. but for laptop/pc you can use both nextgen & legacy 👍

But when Will you guys add Support😭im poor to buy pc

**Comment by liquidsquid1** [comment]
> > well if the question was how to use lb in pojav, well only legacy is supported there.. but for laptop/pc you can use both nextgen & legacy 👍
> 
> But when Will you guys add Support😭im poor to buy pc

Probably never.
