### ISSUE TITLE
[BUG] issue while launching

### ISSUE THREAD

**Issue by HYPERIONxEND** [CCBlueX/LiquidBounce#3314]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.4.1 (git-7e0dba8)

### Operating System

Windows 7

### Minecraft Version

1.20.4

### Describe the bug

I tried liquid launcher but it shows issue so i tried downloading manually but this issue came and destroy my excitement :skull

### Steps to reproduce

I saw some issue and tried but they didn,t worked

### Client Log

```shell
[10:58:33] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[10:58:34] [main/INFO]: Loading 68 mods:
	- fabric-api 0.95.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.48+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.12+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.0.2+25e1b4764f
	   |-- fabric-data-generation-api-v1 13.2.1+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.73+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.23+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.31+eabbae364f
	   |-- fabric-loot-api-v2 2.1.7+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.62+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.11+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.52+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   |-- fabric-rendering-v0 1.1.55+df3654b34f
	   |-- fabric-rendering-v1 3.1.0+0d29db764f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.18+b66dcf784f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.9+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.20+kotlin.1.9.24
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.24
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.24
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.24
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.24
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 20
	- liquidbounce 0.4.1
	- minecraft 1.20.4
[10:58:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/MAGSI/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:58:36] [main/INFO]: Compatibility level set to JAVA_17
[10:58:41] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[10:58:42] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[10:58:45] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[10:58:55] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[10:59:13] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 531 milliseconds
[10:59:27] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:59:27] [Render thread/INFO]: Setting user: HYPERIONxEND
[10:59:29] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[10:59:31] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[10:59:37] [Render thread/INFO]: Launching LiquidBounce v0.4.1 by CCBlueX
[10:59:38] [Render thread/INFO]: Probing environment... (official: evi, intermediary: net.minecraft.class_310)
[10:59:38] [Render thread/INFO]: Intermediary environment detected.
[10:59:38] [Render thread/INFO]: Loaded language en_us
[10:59:38] [Render thread/INFO]: Loaded language de_de
[10:59:38] [Render thread/INFO]: Loaded language ja_jp
[10:59:38] [Render thread/INFO]: Loaded language zh_cn
[10:59:38] [Render thread/INFO]: Loaded language ru_ru
[10:59:38] [Render thread/INFO]: Loaded language en_pt
[10:59:38] [Render thread/INFO]: Loaded language pt_br
[10:59:42] [Render thread/INFO]: Successfully extracted default theme
[10:59:43] [Render thread/INFO]: Inserted 10 components
[10:59:43] [Render thread/INFO]: Successfully loaded config 'enemies'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'enemies'.
[10:59:43] [Render thread/INFO]: (Chat) 
[10:59:43] [Render thread/INFO]: (Chat) §f§lLiquid§9§lBounce §8▸ §7Auto ConfigAuto Config
[10:59:43] [Render thread/INFO]: Successfully loaded config 'modules'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'modules'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'commands'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'commands'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'friends'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'friends'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'proxy'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'proxy'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'accounts'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'accounts'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'tabs'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'tabs'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'lang'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'lang'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'storage'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'storage'.
[10:59:43] [Render thread/INFO]: Successfully loaded config 'theme'.
[10:59:43] [Render thread/INFO]: Successfully saved config 'theme'.
[10:59:44] [netty-websocket/INFO]: Default port 15000 available.
[10:59:45] [Render thread/INFO]: Refresh Rate: 60 Hz
[10:59:45] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[10:59:45] [netty-websocket/INFO]: Starting Netty server...
[10:59:47] [nioEventLoopGroup-2-1/INFO]: [id: 0xfbadf060] REGISTERED
[10:59:47] [nioEventLoopGroup-2-1/INFO]: [id: 0xfbadf060] BIND: 0.0.0.0/0.0.0.0:15000
[10:59:47] [netty-websocket/INFO]: Netty server started on port 15000.
[10:59:47] [nioEventLoopGroup-2-1/INFO]: [id: 0xfbadf060, L:/[0:0:0:0:0:0:0:0]:15000] ACTIVE
[10:59:58] [Render thread/INFO]: [Downloading Checksum] Started task
[10:59:59] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[10:59:59] [Render thread/INFO]: Checksum matches: true
[10:59:59] [Render thread/INFO]: Platform directory exists: true
[10:59:59] [Render thread/INFO]: Initializing CEF on windows_amd64...
[10:59:59] [Render thread/ERROR]: Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\MAGSI\AppData\Roaming\.tlauncher\legacy\Minecraft\game\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\chrome_elf.dll: The specified procedure could not be found
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:817) ~[?:?]
	at java.lang.System.load(System.java:2015) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:454) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:67) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager$initBrowser$1.invoke(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:72) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:114) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:186) ~[liquidbounce.jar:?]
	at net.minecraft.class_310.handler$znk000$liquidbounce$startClient(class_310.java:6350) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
```

### Screenshots

![PROBLEM](https://github.com/CCBlueX/LiquidBounce/assets/173659098/27cd9451-1159-4704-a335-cbdc84cd98db)

**Comment by HYPERIONxEND** [comment]
I also removed mods and tried without mods but it doesn,t works at all

**Comment by FatMolePanda** [comment]
"Windows 7"

**Comment by 1zun4** [comment]
Update your windows. Windows 7 is not supported.

**Comment by 1zun4** [comment]
Yes. LiquidBounce would not have run well on this hardware anyway.
