### ISSUE TITLE
[BUG] crashes on 3rd file download

### ISSUE THREAD

**Issue by sappy30430** [CCBlueX/LiquidBounce#3344]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

7.1

### Operating System

Windows 10

### Minecraft Version

1.21

### Describe the bug

opening it downloads 'required files' and give me error 61928751. not sure if its a problem with my gpu being gtx 1060.

### Steps to reproduce

install liquidbounce 7.1 start 3rd file install crash

### Client Log
java.io.IOException: Failed to delete existing platform directory
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadJcef(MCEFResourceManager.java:125) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable$lambda$4(JcefBrowser.kt:67) ~[LiquidBounce.jar:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]

```


### Screenshots

_No response_

**Comment by 1zun4** [comment]
restart computer and try again

**Comment by sappy30430** [comment]
alright thanks ill try this

**Comment by CallsignReaper714** [comment]
im having this issue aswell, restarted my pc an everything

**Comment by MukjepScarlet** [comment]
The code of this part was totally rewritten.
