### ISSUE TITLE
[BUG] kotlin.NotImplementedError on launch/Installation instructions?

### ISSUE THREAD

**Issue by solonovamax** [CCBlueX/LiquidBounce#343]
**Describe the bug**
This is kind of a two in one, but whatever.

First, there are no easy to follow installation instructions. I can figure out how to build from source, but it seems this mod has dependencies, which seem to be listed nowhere. So it's hard to figure out what to install.

It should probably be listed that you need to install the fabric-language-kotlin mod.
I built the mod with `gradle genSources; gradle build`, and then copied the non dev jar to my mods folder.

This produced the following error. The only problem is, given that there are no installation instructions, I'm not sure if this is because I didn't install it correctly, or because of something else. (If it's not because of how I installed it, I'll rename the issue & move the installation instructions part to another issue)

(I've removed all the irrelevant stuff)
```
[20:58:10] [main/INFO]: Loading heads...
[20:58:10] [main/ERROR]: Unable to load heads database
kotlin.NotImplementedError: An operation is not implemented: not done yet
	at net.ccbluex.liquidbounce.features.tabs.Tabs.<clinit>(Tabs.java:84) [liquidbounce-1.0.0.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce.start(LiquidBounce.java:88) [liquidbounce-1.0.0.jar:?]
	at net.minecraft.class_310.handler$zgg000$startClient(class_310.java:4925) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:592) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-minecraft-1.16.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:58:10] [main/INFO]: Loading ultralight...
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2021-02-14, 8:58 p.m.
Description: Initializing game

java.lang.NoClassDefFoundError: com/labymedia/ultralight/UltralightJava
	at net.ccbluex.liquidbounce.renderer.ultralight.WebPlatform.<clinit>(WebPlatform.java:75)
	at net.ccbluex.liquidbounce.LiquidBounce.start(LiquidBounce.java:91)
	at net.minecraft.client.MinecraftClient.handler$zgg000$startClient(MinecraftClient:4925)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:592)
	at net.minecraft.client.main.Main.main(Main:177)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.labymedia.ultralight.UltralightJava
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ccbluex.liquidbounce.renderer.ultralight.WebPlatform.<clinit>(WebPlatform.java:75)
	at net.ccbluex.liquidbounce.LiquidBounce.start(LiquidBounce.java:91)
	at net.minecraft.class_310.handler$zgg000$startClient(class_310.java:4925)
	at net.minecraft.class_310.<init>(class_310.java:592)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.10.16-arch1-1
	Java Version: 15.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 946121360 bytes (902 MB) / 1342177280 bytes (1280 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:-UseAdaptiveSizePolicy -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Xms512m -Xmx3072m
	Fabric Mods: 
		barium: Barium 0.1-SNAPSHOT
		carpet: Carpet Mod in Fabric 1.4.14
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.7.0-unstable
		cr3stal: Cr³stal 1.0.0
		fabric: Fabric API 0.23.0+build.410-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c6fa
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5fa
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5ffa
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.2+3c53fe3395
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.11.1
		fiber: fiber 0.23.0-2
		io_sentry_sentry: sentry 3.1.0
		itemscroller: Item Scroller 0.15.0-dev.20200912.221805
		java: OpenJDK 64-Bit Server VM 15
		liquidbounce: LiquidBounce 1.0.0
		litematica: Litematica 0.0.0-dev.20200920.161640
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.4
		minihud: MiniHUD 0.19.0-dev.20201027.145441
		modmenu: Mod Menu 1.14.6+build.31
		okzoomer: Ok Zoomer 4.0.0+1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		phosphor: Phosphor 0.6.0+build.7
		replaymod: Replay Mod 1.16.3-2.4.5
		sodium: Sodium 0.1.0
		tweakeroo: Tweakeroo 0.10.0-dev.20201004.191811
		worldedit: WorldEdit 7.2.0+a51fa43
		wurst: Wurst Client v7.7.2-MC1.16.4
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.39, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
Process exited with code 255.
```

Env:
- 1.16.4
- multimc
- java 15
- LWJGL 3.2.2
- fabric 0.11.1
- other mods listed in the crash report

**Comment by SenkJu** [comment]
The nextgen branch of this repository contains a recode of LiquidBounce that is still very much in an early development phase. The readme and compilation instructions/dependencies will be updated along the way.

**Comment by kawaiinekololi** [comment]
It is not supposed to be used in a launcher yet.

**Comment by solonovamax** [comment]
> It is not supposed to be used in a launcher yet.

pain

I mean, it'd be nice if you could try and get something kind of working for running it in a launcher.
You'd be able to get a lot more testing results and find bugs quicker with a few beta testers. Just make sure everyone understands that this is in beta/alpha, so it's not stable in the slightest and would be prone to lots of crashes/etc.

Just use a 0.* version to indicate that and append `BETA` to the version.

*(I also happen to have a nice version class utility for a kotlin buildscript if you want, which complies with the SemVer specification. I've attached both a groovy and kotlin version here. The groovy one *might* not be the best, because I prefer kotlin buildscripts, so I only just translated it to groovy. Here's a few example outputs for it: `0.1.23-BETA+abcd123`, `2.2.0-BETA+8cf60f6`, `4.0.0` <-- non beta version, etc. Also, just assume that code is under MIT, so use it however you want. Feel free to relicense it under GPL, but I've used it in a few MIT projects. Use it if you feel like it, but you don't have to.)*

<details> 
<summary>Kotlin version</summary>

```kotlin
// example usage
val versionObj = Version("0", "1", "23", true) // semver version "0.1.23", and has the word BETA + the git hash appended to the version name.
version = versionObj

/**
 * Version class that does version stuff.
 */
@Suppress("MemberVisibilityCanBePrivate")
class Version(val major: String, val minor: String, val revision: String, val preRelease: Boolean = false) {

    override fun toString(): String {
        return if (!preRelease)
            "$major.$minor.$revision"
        else //Only use git hash if it's a prerelease. Feel free to remove the `gteGitHash()` call if you don't want that functionality. Note: requires a git repo to compile. Cannot compile without `git` installed, or if sources were downloaded instead of git repo.
            "$major.$minor.$revision-BETA+${getGitHash()}"
    }
}

/**
 * Uses black magic to get the git hash of the latest commit.
 */
fun getGitHash(): String {
    val stdout = java.io.ByteArrayOutputStream()
    val result = exec {
        isIgnoreExitValue = true
        commandLine = mutableListOf("git", "rev-parse", "--short", "HEAD")
        standardOutput = stdout
    }
    when (result.exitValue) { // you can remove this block if you don't want to help people who might accidentally stumble upon this.
        128 -> {
            project.logger.error("You must git clone the repository. You cannot build from a zip/tarball of the sources.")
            result.rethrowFailure().assertNormalExitValue()
        }
        127 -> {
            project.logger.error("Could not find git executable. Please install git. https://git-scm.com/downloads")
            result.rethrowFailure().assertNormalExitValue()
        }
        0 -> { // do nothing
        }
        else -> {
            project.logger.error("An error may or may not have occurred. The exit code was not zero.")
            result.rethrowFailure().assertNormalExitValue()
        }
    }
    return stdout.toString().trim()
}
```
</details>

<details> 
<summary>Groovy version</summary>

```groovy
// example usage
def versionObj = Version("0", "1", "23", true) // semver version "0.1.23", and has the word BETA + the git hash appended to the version name.
version = versionObj

String getGitHash() {
    def stdout = new ByteArrayOutputStream()
    def result = exec {
        ignoreExitValue true
        println(isIgnoreExitValue())
        commandLine = ["git", "rev-parse", "--short", "HEAD"]
        standardOutput = stdout
    }
    switch (result.exitValue) { // you can remove this block if you don't want to help people who might accidentally stumble upon this.
        case 128:
            project.logger.error("You must git clone the repository. You cannot build from a zip/tarball of the sources.")
            result.rethrowFailure().assertNormalExitValue()
            break
        case 127:
            project.logger.error("Could not find git executable. Please install git. https://git-scm.com/downloads")
            result.rethrowFailure().assertNormalExitValue()
            break
        case 0: // do nothing
            break
        default: // other errors?
            project.logger.warn("An error may or may not have occured. The exit code was not 0.")
            result.rethrowFailure().assertNormalExitValue()
            break
    }
    return stdout.toString().trim()
}

Project.metaClass.static.getGitHash = getGitHash() // I hate groovy.

/**
 * Version class that does version stuff.
 */
class Version {
    String major
    String minor
    String revision
    boolean preRelease

    /**
     * Constructor for version class.
     * <p>
     * The {@link #preRelease} parameter defaults to false, so you can omit it if you don't need it.
     */
    Version(String major, String minor, String revision, boolean preRelease = false) {
        this.major = major
        this.minor = minor
        this.revision = revision
        this.preRelease = preRelease
    }

    @Override
    String toString() {
        return !preRelease ? "$major.$minor.$revision" : "$major.$minor.$revision-BETA+${Project.getGitHash()}" //Only use git hash if it's a prerelease. Feel free to remove the `gteGitHash()` call if you don't want that functionality. Note: requires a git repo to compile. Cannot compile without `git` installed, or if sources were downloaded instead of git repo.
    }
}
```
</details>
