### ISSUE TITLE
I CAN'T start the Client.

### ISSUE THREAD

**Issue by MapleLoves** [CCBlueX/LiquidBounce#3464]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.8.0

### Operating System

Windows 10

### Minecraft Version

1.21

### Describe the bug

I was starting the client but suddenly the client Crashed

### Steps to reproduce

Go To the Liquid Launcher and Click the"Launch Liquidbounce"buttom

### Client Log

```
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
at java.base/java.net.Socket.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:233) ~[LiquidBounce.jar:?]
	... 12 more
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by Wanfeng114** [comment]
omg It Can't show the Client log Completely

**Comment by Wanfeng114** [comment]
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)~[?:?]
	at java.base/java.net.Socket.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Sour
ce) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:233) ~[LiquidBounce.jar:?]
	... 12 more
An error occourd:

Process exited with non-zero exit code: 1.

**Comment by ion1x** [comment]
send a full log

**Comment by MapleLoves** [comment]
> send a full log

here https://paste.ccbluex.net/c3750b7ab

**Comment by 1zun4** [comment]
Use a VPN such as Cloudflare Warp

**Comment by MapleLoves** [comment]
> Use a VPN such as Cloudflare Warp

okay thanks
