### ISSUE TITLE
[BUG] Dont start

### ISSUE THREAD

**Issue by TheFirstPlaceCoder** [CCBlueX/LiquidBounce#3540]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.8.0

### Operating System

Windows 7

### Minecraft Version

1.21

### Describe the bug

Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\Администратор\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\chrome_elf.dll: Не найдена указанная процедура
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at org.cef.CefApp.startup(CefApp.java:454)
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95)
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79)
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser$lambda$4(BrowserManager.kt:67)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable$lambda$4$lambda$3$lambda$2(JcefBrowser.kt:68)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:174)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Steps to reproduce

- install fabric 1.21
- move fabric api 1.21 to mods folder
- move liquid jar to mods folder
- launch minecraft

### Client Log

```shell
Fatal error
java.lang.UnsatisfiedLinkError: C:\Users\Администратор\AppData\Roaming\.minecraft\LiquidBounce\mcef\libraries\0e837c94ea090b6eb4b9bc65428ec28fd75d1d72\windows_amd64\chrome_elf.dll: Не найдена указанная процедура
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at org.cef.CefApp.startup(CefApp.java:454)
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95)
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:79)
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser$lambda$4(BrowserManager.kt:67)
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable$lambda$4$lambda$3$lambda$2(JcefBrowser.kt:68)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:174)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Screenshots

![изображение](https://github.com/user-attachments/assets/7c7bd56f-6137-4cc7-93c9-872d58cca614)

**Comment by masterBeans990** [comment]
windows 7??? dude update ur windows 😭

**Comment by 1zun4** [comment]
Windows 7 is not compatible.
