### ISSUE TITLE
[BUG] Version 0.9.1 does not launch on NixOS

### ISSUE THREAD

**Issue by TheDeafCreeper** [CCBlueX/LiquidBounce#3549]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

e982523 (0.9.1)

### Operating System

Linux

### Minecraft Version

1.21

### Describe the bug

LB Fails to find the `libnss3` library and crashes.
Potentially related to #1744.

### Steps to reproduce

Download NixOS and Minecraft
Attempt to use LiquidBounce

### Client Log

```shell
java.lang.UnsatisfiedLinkError: /home/thedeafcreeper/.local/share/PrismLauncher/instances/Liquid Bounce/.minecraft/LiquidBounce/mcef/libraries/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/linux_amd64/libcef.so: libnss3.so: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[?:?]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418) ~[?:?]
	at java.base/java.lang.Runtime.load0(Runtime.java:852) ~[?:?]
	at java.base/java.lang.System.load(System.java:2025) ~[?:?]
	at org.cef.CefApp.startup(CefApp.java:462) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.cef.CefHelper.init(CefHelper.java:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.mcef.MCEF.initialize(MCEF.java:71) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.initBrowserBackend(JcefBrowser.kt:80) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser$lambda$4(BrowserManager.kt:67) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:73) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.web.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce.startHandler$lambda$4(LiquidBounce.kt:179) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:195) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$ddp000$liquidbounce$startClient(class_310.java:20256) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:668) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```
```


### Screenshots

_No response_

**Comment by TheDeafCreeper** [comment]
Also happens on latest nightly build ([ddea34e](https://github.com/CCBlueX/LiquidBounce/commit/ddea34e392b16c217fa9569c0f32fd2c8e82d4ef) at time of writing).

**Comment by 1zun4** [comment]
No idea. Missing library it seems.

**Comment by superblaubeere27** [comment]
`libnss3` is missing! Just install it

**Comment by TheDeafCreeper** [comment]
It's not that the library is missing, just that the way nixos is setup means that the way Liquidbounce tries to access it doesn't work.

What does work however is running Minecraft via `steam-run` (not related to steam at all).

For prisim launcher as an example that just means putting "stream-run" in the wrapper command.

**Comment by DarkReaperBoy** [comment]
> It's not that the library is missing, just that the way nixos is setup means that the way Liquidbounce tries to access it doesn't work.
> 
> What does work however is running Minecraft via `steam-run` (not related to steam at all).
> 
> For prisim launcher as an example that just means putting "stream-run" in the wrapper command.

@TheDeafCreeper 

![Image](https://github.com/user-attachments/assets/1b5e280d-7af9-4c8e-9b38-99b33ca41c46)
