### ISSUE TITLE
[BUG] Can't load script with lunar client

### ISSUE THREAD

**Issue by RedDragon0293** [CCBlueX/LiquidBounce#3558]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.9.1

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

Title
LiquidBounce nextgen 0.9.1 with Lunar Client 3.2.11-master.4022
Full log: [7eb52b73-3273-4c95-a226-2b4ac943ddb9-master.txt](https://forum.liquidbounce.net/assets/uploads/files/1722084341408-7eb52b73-3273-4c95-a226-2b4ac943ddb9-master.txt) 
Script file: [AutoFish.js](https://forum.liquidbounce.net/assets/uploads/files/1722084421268-autofish.js)

### Steps to reproduce

- Add a script
- Launch
- Error

### Client Log

```shell
[2024-07-27 20:34:35.090] [info]  [20:34:35] [Render thread/ERROR]: Unable to load script main.js.
[2024-07-27 20:34:35.090] [info]  org.graalvm.polyglot.PolyglotException: TypeError: Access to host class net.minecraft.item.FishingRodItem is not allowed or does not exist.
[2024-07-27 20:34:35.091] [info]  	at <js>.:program(main.js:1) ~[?:?]
[2024-07-27 20:34:35.091] [info]  	at Genesis/org.graalvm.polyglot.Context.eval(Context.java:403) ~[liquidbounce.jar:?]
[2024-07-27 20:34:35.091] [info]  	at Genesis/net.ccbluex.liquidbounce.script.Script.initScript(Script.kt:90) ~[?:?]
[2024-07-27 20:34:35.092] [info]  	at Genesis/net.ccbluex.liquidbounce.script.ScriptManager.loadScript(ScriptManager.kt:86) ~[?:?]
[2024-07-27 20:34:35.092] [info]  	at Genesis/net.ccbluex.liquidbounce.script.ScriptManager.loadSafely(ScriptManager.kt:76) ~[?:?]
[2024-07-27 20:34:35.092] [info]  	at Genesis/net.ccbluex.liquidbounce.script.ScriptManager.loadScripts(ScriptManager.kt:53) ~[?:?]
[2024-07-27 20:34:35.093] [info]  	at Genesis/net.ccbluex.liquidbounce.LiquidBounce.startHandler$lambda$4(LiquidBounce.kt:163) ~[?:?]
[2024-07-27 20:34:35.093] [info]  	at Genesis/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:195) [?:?]
[2024-07-27 20:34:35.093] [info]  	at Genesis/net.minecraft.client.Minecraft.handler$cdp000$startClient(SourceFile:10952) [?:?]
[2024-07-27 20:34:35.094] [info]  	at Genesis/net.minecraft.client.Minecraft.<init>(SourceFile:668) [?:?]
[2024-07-27 20:34:35.094] [info]  	at Genesis/net.minecraft.client.main.Main.redirect$zbf000$impl$main$minecraft(SourceFile:656) [?:?]
[2024-07-27 20:34:35.094] [info]  	at Genesis/net.minecraft.client.main.Main.main(SourceFile:239) [?:?]
[2024-07-27 20:34:35.095] [info]  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
[2024-07-27 20:34:35.095] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
[2024-07-27 20:34:35.095] [info]  	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-07-27 20:34:35.096] [info]  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
[2024-07-27 20:34:35.096] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
[2024-07-27 20:34:35.096] [info]  	at com.moonsworth.lunar.genesis.HHICHIHIOCHHHICIOOOIHRCOHIICOC.IRICHRRHICCCHRHOICIHCCHHCOICIC(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-07-27 20:34:35.097] [info]  	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
[2024-07-27 20:34:35.097] [info]  	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
```

**Comment by 1zun4** [comment]
Cannot be fixed. Do not use Lunar client.
