### ISSUE TITLE
[BUG] Game Crashed When Open Player's Inv

### ISSUE THREAD

**Issue by Kizure1337** [CCBlueX/LiquidBounce#3605]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.9.1 e982523

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

I just enabled the InventoryMove module when i was in creative mode.When i tried to open the player's inv, the game crashed because a refect exception.

### Steps to reproduce

1.Enable InventoryMove Module
2.Make sure player is in creative mode
3.open the player's inventory.
4.crashed.

### Client Log

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-08-05 09:33:42
Description: Ticking entity

java.lang.IllegalAccessError: class net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove tried to access private field net.minecraft.class_7706.field_40200 (net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove and net.minecraft.class_7706 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @224edc67)
	at net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove.isInCreativeSearchField(ModuleInventoryMove.kt:88)
	at net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove.shouldHandleInputs(ModuleInventoryMove.kt:82)
	at net.minecraft.class_743.redirect$bmk000$liquidbounce$hookInventoryMove(class_743.java:1060)
	at net.minecraft.class_743.method_3129(class_743.java:22)
	at net.minecraft.class_746.method_6007(class_746.java:705)
	at net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at net.minecraft.class_1657.method_5773(class_1657.java:312)
	at net.minecraft.class_742.method_5773(class_742.java:59)
	at net.minecraft.class_746.method_5773(class_746.java:221)
	at net.minecraft.class_638.method_18646(class_638.java:1158)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)
	at net.minecraft.class_310.method_1574(class_310.java:1956)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove.isInCreativeSearchField(ModuleInventoryMove.kt:88)
	at net.ccbluex.liquidbounce.features.module.modules.movement.ModuleInventoryMove.shouldHandleInputs(ModuleInventoryMove.kt:82)
	at net.minecraft.class_743.redirect$bmk000$liquidbounce$hookInventoryMove(class_743.java:1060)
	at net.minecraft.class_743.method_3129(class_743.java:22)
	at net.minecraft.class_746.method_6007(class_746.java:705)
	at net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at net.minecraft.class_1657.method_5773(class_1657.java:312)
	at net.minecraft.class_742.method_5773(class_742.java:59)
	at net.minecraft.class_746.method_5773(class_746.java:221)
	at net.minecraft.class_638.method_18646(class_638.java:1158)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 1621
	Entity Name: Kizure8964
	Entity's Exact location: 128334.28, 71.18, -53669.66
	Entity's Block location: World: (128334,71,-53670), Section: (at 14,7,10 in 8020,4,-3355; chunk contains blocks 128320,0,-53680 to 128335,255,-53665), Region: (250,-105; contains chunks 8000,-3360 to 8031,-3329, blocks 128000,0,-53760 to 128511,255,-53249)
	Entity's Momentum: -0.07, -0.15, 0.24
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)
	at net.minecraft.class_310.method_1574(class_310.java:1956)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 284.394s
	Wall uptime: 250.771s
	High-res time: 248.142s
	Client ticks: 4354 ticks / 217.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kizure8964'/1621, l='ClientLevel', x=128334.28, y=71.18, z=-53669.66]]
	Chunk stats: 65536, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-134,123,109), Section: (at 10,11,13 in -9,7,6; chunk contains blocks -144,0,96 to -129,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 116967 game time, 1000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
	Tracked entity count: 25

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, fabric-api-base, fabric-block-view-api-v2, fabric-command-api-v2, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-networking-api-v1, fabric-particles-v1, fabric-registry-sync-v0, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, liquidbounce, lithium, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, sodium, viafabricplus

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 678829928 bytes (647 MiB) / 1308622848 bytes (1248 MiB) up to 2684354560 bytes (2560 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics 
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 39270.34
	Virtual memory used (MiB): 17276.36
	Swap memory total (MiB): 29091.80
	Swap memory used (MiB): 2859.25
	Space in storage for jna.tmpdir (MiB): available: 99659.78, total: 159364.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 99659.78, total: 159364.31
	Space in storage for io.netty.native.workdir (MiB): available: 99659.78, total: 159364.31
	Space in storage for java.io.tmpdir (MiB): available: 91879.58, total: 328705.00
	Space in storage for workdir (MiB): available: 99659.78, total: 159364.31
	JVM Flags: 11 total; -Xmx2560m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.21
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Vega 8 Graphics  GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, fabric, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, fabric-api-base, fabric-block-view-api-v2, fabric-command-api-v2, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-networking-api-v1, fabric-particles-v1, fabric-registry-sync-v0, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, liquidbounce, lithium, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, sodium, viafabricplus
	Current Language: zh_cn
	Locale: zh_CN
	System encoding: GBK
	File encoding: GB18030
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
```

**Comment by 1zun4** [comment]
I cannot seem to replicate it on the newest nightly. I consider it as fixed.
