### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nicer4596** [CCBlueX/LiquidBounce#3725]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

ab555af

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

Failed to load the font Montserrat

### Steps to reproduce

Fail to load Montserrat font

### Client Log

```shell
[18:31:10] [Render thread/ERROR]: Failed to load font Montserrat
java.lang.IllegalStateException: Failed to load font from folder /storage/emulated/0/FCL/.minecraft/LiquidBounce/fonts/Montserrat
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.createFontFromFolder(Fonts.kt:140) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce(Fonts.kt:85) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce(Fonts.kt:92) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce$default(Fonts.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$QueuedFont.loadNow(Fonts.kt:159) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadQueuedFonts(Fonts.kt:55) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$ClientResourceReloader.method_14491(LiquidBounce.kt:211) ~[liquidbounce.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
Caused by: java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source) ~[?:?]
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(Unknown Source) ~[?:?]
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(Unknown Source) ~[?:?]
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.render.engine.font.GlyphPage$Companion.renderAtlas(GlyphPage.kt:286) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.font.GlyphPage$Companion.create(GlyphPage.kt:169) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.font.GlyphPage$Companion.createAscii(GlyphPage.kt:129) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.createFontFromFolder(Fonts.kt:135) ~[liquidbounce.jar:?]
	... 23 more
[18:31:10] [Render thread/ERROR]: Fatal error
java.lang.IllegalStateException: Failed to load font Montserrat
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce(Fonts.kt:95) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce(Fonts.kt:92) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontInfo.load$liquidbounce$default(Fonts.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$QueuedFont.loadNow(Fonts.kt:159) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadQueuedFonts(Fonts.kt:55) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$ClientResourceReloader.method_14491(LiquidBounce.kt:211) ~[liquidbounce.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]
[18:31:11] [mcef-downloader/INFO]: [Downloading JCEF] Progress 25%
```

**Comment by 1zun4** [comment]
`/storage/emulated/0/FCL/.minecraft/LiquidBounce/fonts/Montserrat`, is this Android?

**Comment by nicer4596** [comment]
erm it's emulated minecraft java on android

-------- Original Message --------
