### ISSUE TITLE
NullPointerException in minimap

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#3772]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0375f700918f442efe23bd39431fcfc65a678e04

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

error (no crash)

### Steps to reproduce

not sure, I think it happened during a world change

### Client Log

```shell
[16:38:26] [Thread-517/INFO]: [STDERR]: java.lang.NullPointerException
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.ChunkRenderer$MinimapChunkUpdateSubscriber.getColor(ChunkRenderer.kt:91)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.ChunkRenderer$MinimapChunkUpdateSubscriber.chunkUpdate$lambda$4(ChunkRenderer.kt:178)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.MinimapTextureAtlasManager.editChunk(MinimapTextureAtlasManager.kt:117)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.ChunkRenderer$MinimapChunkUpdateSubscriber.chunkUpdate(ChunkRenderer.kt:173)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.utils.block.ChunkScanner$ChunkScannerThread.scanChunk(ChunkScanner.kt:173)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.utils.block.ChunkScanner$ChunkScannerThread.thread$lambda$1(ChunkScanner.kt:127)
[16:38:26] [Thread-517/INFO]: [STDERR]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by MukjepScarlet** [comment]
`mc.world == null` because of world change
The ChunkScanner called the method of Listeners when this variable was changing

**Comment by superblaubeere27** [comment]
> `mc.world == null` because of world change The ChunkScanner called the method of Listeners when this variable was changing

I see. The ChunkScanner infrastructure needs a rewrite...

**Comment by MukjepScarlet** [comment]
> > `mc.world == null` because of world change The ChunkScanner called the method of Listeners when this variable was changing
> 
> I see. The ChunkScanner infrastructure needs a rewrite...

I don't meet this with the latest commit. Maybe we should add null check in each subscriber. This should be an exception because we do check mc.world before calling scan methods...

**Comment by MukjepScarlet** [comment]
I plan to rewrite the HoleESP, meanwhile I'll review the ChunkScanner to avoid bugs.
