### ISSUE TITLE
[BUG] java.lang.NullPointerException on disable Vulcan286-113 fly

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#3785]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0375f700918f442efe23bd39431fcfc65a678e04

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

error prevents fly from being disabled

### Steps to reproduce

1. enable fly with "Vulcan286-113" as the mode
2. right click on the ground
3. disable fly

### Client Log

```shell
[17:29:14] [Render thread/ERROR]: Failed to set Enabled from true to false
java.lang.NullPointerException: null
	at net.ccbluex.liquidbounce.features.module.modules.movement.fly.modes.vulcan.FlyVulcan286.disable(FlyVulcan286.kt:69) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.ChoiceConfigurable.newState(ConditionalConfigurables.kt:90) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.Module.enabled_delegate$lambda$7(Module.kt:138) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.Value.set(Value.kt:173) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.Value.set(Value.kt:166) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.config.Value.setValue(Value.kt:105) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.Module.setEnabled(Module.kt:91) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.ModuleManager.keyHandler$lambda$2(ModuleManager.kt:88) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:197) ~[liquidbounce.jar:?]
	at net.minecraft.class_309.handler$cac000$liquidbounce$hookKeyboardKey(class_309.java:1147) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:361) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:499) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by be4dev** [comment]
> ### LiquidBounce Branch
> 
> Nextgen
> ### LiquidBounce Build/Version
> 
> [0375f70](https://github.com/CCBlueX/LiquidBounce/commit/0375f700918f442efe23bd39431fcfc65a678e04)
> ### Operating System
> 
> Windows 10
> ### Minecraft Version
> 
> 1.21.1
> ### Describe the bug
> 
> error prevents fly from being disabled
> ### Steps to reproduce
> 
>     1. enable fly with "Vulcan286-113" as the mode
> 
>     2. right click on the ground
> 
>     3. disable fly
> 
> 
> ### Client Log
> 
> ```shell
> [17:29:14] [Render thread/ERROR]: Failed to set Enabled from true to false
> java.lang.NullPointerException: null
> 	at net.ccbluex.liquidbounce.features.module.modules.movement.fly.modes.vulcan.FlyVulcan286.disable(FlyVulcan286.kt:69) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.config.ChoiceConfigurable.newState(ConditionalConfigurables.kt:90) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.features.module.Module.enabled_delegate$lambda$7(Module.kt:138) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.config.Value.set(Value.kt:173) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.config.Value.set(Value.kt:166) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.config.Value.setValue(Value.kt:105) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.features.module.Module.setEnabled(Module.kt:91) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.features.module.ModuleManager.keyHandler$lambda$2(ModuleManager.kt:88) ~[liquidbounce.jar:?]
> 	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:197) ~[liquidbounce.jar:?]
> 	at net.minecraft.class_309.handler$cac000$liquidbounce$hookKeyboardKey(class_309.java:1147) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_309.method_1466(class_309.java:361) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_309.method_22678(class_309.java:499) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_309.method_22676(class_309.java:499) ~[client-intermediary.jar:?]
> 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) [lwjgl-glfw-3.3.3.jar:?]
> 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
> 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
> 	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
> ```
> 
> ### Screenshots
> 
> _No response_

made pr https://github.com/CCBlueX/LiquidBounce/pull/3791
