### ISSUE TITLE
[BUG] load error

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#3787]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0375f700918f442efe23bd39431fcfc65a678e04

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

error (no crash)

### Steps to reproduce

load game

mods: (slightly tweaked [Adrenaline](https://modrinth.com/modpack/adrenaline))
- BadOptimizations-2.1.4-1.21
- cloth-config-15.0.130-fabric
- CullLessLeaves-1.3.0
- fabric-api-0.102.1+1.21.1
- fabric-language-kotlin-1.12.0+kotlin.2.0.10
- ferritecore-7.0.0-fabric
- indium-1.0.35+mc1.21
- liquidbounce
- lithium-fabric-mc1.21.1-0.13.0
- modernfix-fabric-5.19.0+mc1.21
- sodium-fabric-0.5.11+mc1.21
- threadtweak-fabric-1.20.6-0.1.3
- ViaFabricPlus-3.4.5
- WI-Zoom-1.5-MC1.21.1
- YetAnotherConfigLib-3.5.0+1.21-fabric

### Client Log

```shell
[17:54:27] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[17:54:27] [Render thread/WARN]: Shader ui_blur could not find uniform named BlurDir in the specified shader program.
[17:54:27] [Render thread/ERROR]: Failed to load outline shader
net.minecraft.class_2973: Invalid shaders/program/outline_shader.json (liquidbounce): Couldn't compile fragment program (liquidbounce, outline_shader) : Fragment shader failed to compile with the following errors:
ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.<init>(class_280.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_283.<init>(class_283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1262(class_279.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1257(class_279.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1256(class_279.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at net.ccbluex.liquidbounce.render.engine.MinecraftFramebufferShader.load(MinecraftFramebufferShader.kt:44) ~[liquidbounce.jar:?]
	at net.minecraft.class_761.handler$cpl000$liquidbounce$onLoadEntityOutlineShader(class_761.java:7709) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3296(class_761.java:532) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_14491(class_761.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.io.IOException: Couldn't compile fragment program (liquidbounce, outline_shader) : Fragment shader failed to compile with the following errors:
ERROR: error(#271) Explicit version number 120 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated
	at net.minecraft.class_281.method_34416(class_281.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_5937.method_34415(class_5937.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.method_16036(class_280.java:170) ~[client-intermediary.jar:?]
	at net.minecraft.class_280.<init>(class_280.java:137) ~[client-intermediary.jar:?]
	... 26 more
```

**Comment by MukjepScarlet** [comment]
GLSL issue. Should be fixed.
