### ISSUE TITLE
[BUG] ConcurrentModificationException in AutoFarm

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#3806]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b58a402ad2c568c09908bcc683fcff3d873dd1b6

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

error

### Steps to reproduce

use AutoFarm

### Client Log

```shell
[12:08:41] [Render thread/ERROR]: Exception while executing handler.
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
	at net.ccbluex.liquidbounce.features.module.modules.world.autofarm.AutoFarmVisualizer$Blocks.renderHandler$lambda$6$lambda$5(AutoFarmVisualizer.kt:96) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.RenderShortcutsKt.renderEnvironmentForWorld(RenderShortcuts.kt:91) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.world.autofarm.AutoFarmVisualizer$Blocks.renderHandler$lambda$6(AutoFarmVisualizer.kt:94) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:197) [liquidbounce.jar:?]
	at net.minecraft.class_757.handler$cpc000$liquidbounce$hookWorldRender(class_757.java:5689) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1112) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by MukjepScarlet** [comment]
This should be fixed because we are now using ConcurrentMap. #4081

**Comment by MukjepScarlet** [comment]
I think this is fixed. Did you try it with newer versions?

**Comment by ManInMyVan** [comment]
not yet
