### ISSUE TITLE
[BUG] IllegalStateException in minimap

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#3810]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

b58a402ad2c568c09908bcc683fcff3d873dd1b6

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

errors

### Steps to reproduce

unsure, happened after dying in singleplayer

### Client Log

```shell
[13:52:03] [Thread-639/INFO]: [STDERR]: java.lang.IllegalStateException: No more space in the texture atlas!
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.MinimapTextureAtlasManager.allocate(MinimapTextureAtlasManager.kt:73)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.MinimapTextureAtlasManager.getOrAllocate(MinimapTextureAtlasManager.kt:101)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.MinimapTextureAtlasManager.editChunk(MinimapTextureAtlasManager.kt:110)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.web.theme.component.types.minimap.ChunkRenderer$MinimapChunkUpdateSubscriber.chunkUpdate(ChunkRenderer.kt:160)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.utils.block.ChunkScanner$ChunkScannerThread.scanChunk(ChunkScanner.kt:173)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.utils.block.ChunkScanner$ChunkScannerThread.thread$lambda$1(ChunkScanner.kt:127)
[13:52:03] [Thread-639/INFO]: [STDERR]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by superblaubeere27** [comment]
Minimap seems to be buggy at the moment. I will try to fix it. Maybe those fixes will fix this too.

**Comment by MukjepScarlet** [comment]
Is it still there?
