### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stpidgamers** [CCBlueX/LiquidBounce#388]
Hello,When i try running the game it loads and there's no error but when I go into a world my console spams this

```
[00:03:33] [main/ERROR] (LiquidBounce) Exception while executing handler.
 kotlin.UninitializedPropertyAccessException: lateinit property webView has not been initialized
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleHud$renderHandler$1.invoke(ModuleHud.kt:39) ~[main/:?]
	at net.ccbluex.liquidbounce.features.module.modules.render.ModuleHud$renderHandler$1.invoke(ModuleHud.kt:38) ~[main/:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:104) [main/:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$zeb000$hookRenderEvent(InGameHud.java:1345) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:264) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:597) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1048) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.5-v2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2@net.fabricmc.yarn.1_16_5.1.16.5+build.5-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```
	
Any Fix?

**Comment by superblaubeere27** [comment]
The natives propably failed to load. Please send the full log

**Comment by stpidgamers** [comment]
The full console ?

**Comment by stpidgamers** [comment]
Hi, for some reason i reloaded intellij and it fixed itself i guess

**Comment by stpidgamers** [comment]
I have a question tho, does clickgui work? if no then its not working for me lma

**Comment by 1zuna-chan** [comment]
clickgui works.

**Comment by stpidgamers** [comment]
so lb is suppost to stop responding ?

**Comment by mems01** [comment]
Buddy, it's in early development. That of course means it will have some unexpected stuff kicking in while playing.

**Comment by 1zuna-chan** [comment]
@stpidgamers What are you expecting from something you have to build yourself while it's on active development?
