### ISSUE TITLE
[BUG] Wierd keystrokes when using REI

### ISSUE THREAD

**Issue by MrFrog222** [CCBlueX/LiquidBounce#3897]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.13.0

### Operating System

Arch Linux

### Minecraft Version

1.21.1

### Describe the bug

When installing Roughly Enough Items alongside Liquidbounce the keystrokes feature becomes bugged and says key.keyboard.w for w, key.keyboard.a for a, etc. To clarify, i've already tested and made sure REI's dependencys Cloth Config API and Architectury API are not causing the issue as using Liquidbounce with those two installed but without REI works perfectly fine.

### Steps to reproduce

- Install Liquidbounce, Fabric API, Cloth Config API, Architectury API, Fabric Language Kotlin, and REI
- Activate the Keystrokes feature within the HUD module

### Client Log

```shell
[21:48:07] [Server thread/INFO]: Starting integrated minecraft server version 1.21.1
[21:48:07] [Server thread/INFO]: Generating keypair
[21:48:07] [Server thread/INFO]: Enforcing safe world random access
[21:48:07] [Server thread/INFO]: Using TheSpeedyObjectFactory with Unsafe
[21:48:08] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:48:08] [Render thread/INFO]: Preparing spawn area: 2%
[21:48:08] [Render thread/INFO]: Time elapsed: 435 ms
[21:48:08] [Server thread/INFO]: Changing view distance to 12, from 10
[21:48:08] [Server thread/INFO]: Changing simulation distance to 12, from 0
[21:48:09] [Render thread/INFO]: Joined server with c2me:ext_render_distance_v1 support
[21:48:09] [Server thread/INFO]: MrFrog222[local:E:473932ce] logged in with entity id 1 at (-8.5, -60.0, -5.5)
[21:48:09] [Server thread/INFO]: MrFrog222 joined the game
[21:48:09] [Render thread/INFO]: New Xaero hud session initialized!
[21:48:09] [Render thread/WARN]: Method overwrite conflict for getChunks in betterf3.mixins.json:chunk.ClientChunkMapMixin from mod betterf3, previously written by baritone.launch.mixins.MixinChunkArray. Skipping method.
[21:48:09] [Render thread/INFO]: Reloading pipeline on dimension change: null => minecraft:overworld
[21:48:09] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[21:48:09] [Render thread/INFO]: Successfully saved config 'modules'.
[21:48:09] [Render thread/INFO]: Reloading integration browser JcefTab to Route(theme=net.ccbluex.liquidbounce.web.theme.Theme@2cb3ac3b, url=http://127.0.0.1:15000/default/#/)
[21:48:09] [Render thread/INFO]: Started 6 worker threads
[21:48:09] [Render thread/INFO]: [STDOUT]: Baritone world data dir: /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384
[21:48:09] [Render thread/INFO]: [STDOUT]: Cached world directory: /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/cache
[21:48:09] [Render thread/INFO]: [STDOUT]: Would save waypoints to /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/waypoints
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, storage] and [calc, expression] with inputs: [storage]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, storage, timesHopperSpeed] and [calc, storage, itemsperhour] with inputs: [0, -123, 123]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, storage, help] and [calc, storage, itemsperhour] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, nether] and [calc, expression] with inputs: [nether]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, overworld] and [calc, expression] with inputs: [overworld]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, sbtoitem] and [calc, expression] with inputs: [sbtoitem]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, sbtoitem, 16s] and [calc, sbtoitem, numberofsbs] with inputs: [16s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, sbtoitem, 1s] and [calc, sbtoitem, numberofsbs] with inputs: [1s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, sbtoitem, help] and [calc, sbtoitem, numberofsbs] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtosb] and [calc, expression] with inputs: [itemtosb]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtosb, 16s] and [calc, itemtosb, numberofitems] with inputs: [16s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtosb, 1s] and [calc, itemtosb, numberofitems] with inputs: [1s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtosb, help] and [calc, itemtosb, numberofitems] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, secondstohopperclock] and [calc, expression] with inputs: [secondstohopperclock]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, secondstohopperclock, help] and [calc, secondstohopperclock, seconds] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, secondstorepeater] and [calc, expression] with inputs: [secondstorepeater]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, secondstorepeater, help] and [calc, secondstorepeater, seconds] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtostack] and [calc, expression] with inputs: [itemtostack]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtostack, 16s] and [calc, itemtostack, numberofitems] with inputs: [16s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtostack, 1s] and [calc, itemtostack, numberofitems] with inputs: [1s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, itemtostack, help] and [calc, itemtostack, numberofitems] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, stacktoitem] and [calc, expression] with inputs: [stacktoitem]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, stacktoitem, 16s] and [calc, stacktoitem, numberofstacks] with inputs: [16s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, stacktoitem, 1s] and [calc, stacktoitem, numberofstacks] with inputs: [1s]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, stacktoitem, help] and [calc, stacktoitem, numberofstacks] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, rates] and [calc, expression] with inputs: [rates]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, rates, help] and [calc, rates, numberofitems] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, allaystorage] and [calc, expression] with inputs: [allaystorage]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, allaystorage, help] and [calc, allaystorage, itemsperhour] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, random] and [calc, expression] with inputs: [random]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, random, minmax] and [calc, random, max] with inputs: [minmax]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, random, help] and [calc, random, max] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, craft] and [calc, expression] with inputs: [craft]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, craft, item, depth] and [calc, craft, item, amount] with inputs: [depth]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, craft, help] and [calc, craft, item] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, signaltoitems] and [calc, expression] with inputs: [signaltoitems]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, signaltoitems, help] and [calc, signaltoitems, container] with inputs: [help]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, barter] and [calc, expression] with inputs: [barter]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, custom] and [calc, expression] with inputs: [custom]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, variables] and [calc, expression] with inputs: [variables]
[21:48:09] [Render thread/WARN]: Ambiguity between arguments [calc, help] and [calc, expression] with inputs: [help]
[21:48:09] [Render thread/INFO]: Joined server with c2me:ext_render_distance_v1 support
[21:48:09] [Render thread/INFO]: [ShulkerBoxTooltip] Server integration enabled, attempting handshake...
[21:48:09] [Server thread/INFO]: [ShulkerBoxTooltip] MrFrog222: protocol version: 2.0
[21:48:09] [Server thread/INFO]: [ShulkerBoxTooltip Plugins] Loading 1 plugin: shulkerboxtooltip
[21:48:09] [Server thread/INFO]: [ShulkerBoxTooltip] overriding preview provider shulkerboxtooltip:trapped_chest with shulkerboxtooltip:chest for item minecraft:chest
[21:48:09] [Server thread/INFO]: [ShulkerBoxTooltip Plugins] Registered 31 providers for mod shulkerboxtooltip
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] ========================================
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] ========================================
[21:48:09] [Render thread/INFO]: Loaded 2 advancements
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[21:48:09] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[21:48:09] [Render thread/INFO]: [ShulkerBoxTooltip Plugins] Registered 19 color keys for mod shulkerboxtooltip
[21:48:09] [Render thread/INFO]: Received config from the server: 
[21:48:09] [Render thread/INFO]: Changing view distance to 12 (play stage)
[21:48:09] [Render thread/INFO]: [ShulkerBoxTooltip] Handshake succeeded
[21:48:09] [Render thread/INFO]: [ShulkerBoxTooltip] Server protocol version: 2.0
[21:48:10] [Render thread/INFO]: Minimap updated server level id: 1679888644 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[21:48:10] [Render thread/WARN]: Shader clouds could not find uniform named FogStart in the specified shader program.
[21:48:10] [Render thread/WARN]: Shader clouds could not find uniform named FogEnd in the specified shader program.
[21:48:10] [Render thread/INFO]: Reloading entity icon resources...
[21:48:10] [Render thread/INFO]: Reloaded entity icon resources!
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 5.088 ms, totaling 44.79 ms.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 2.036 ms, totaling 733.4 ms.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 486.4 μs, totaling 3.920 ms.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ========================================
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[21:48:10] [REI-ReloadPlugins/INFO]: [REI] ========================================
[21:48:11] [Render thread/WARN]: Failed to load texture: minecraft:hud/hotbar
java.io.FileNotFoundException: minecraft:hud/hotbar
	at net.minecraft.class_5912.method_43043(class_5912.java:23) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at software.bernie.geckolib.cache.texture.AnimatableTexture.method_4625(AnimatableTexture.java:40) ~[geckolib-fabric-1.21.1-4.6.3.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.wrapOperation$bno000$geckolib$replaceAnimatableTexture(class_1060.java:2031) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:117) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:761) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:754) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.handler$dha000$slotted_armor_hud$renderArmorHud(class_329.java:3171) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_55805(class_329.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) [client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55809(class_9080.java:29) [client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:218) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.4.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[21:48:11] [Render thread/WARN]: Failed to load texture: minecraft:hud/hotbar
java.io.FileNotFoundException: minecraft:hud/hotbar
	at net.minecraft.class_5912.method_43043(class_5912.java:23) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:761) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:754) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.handler$dha000$slotted_armor_hud$renderArmorHud(class_329.java:3171) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_55805(class_329.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) [client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55809(class_9080.java:29) [client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:218) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.4.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[21:48:11] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.'
[21:48:11] [Render thread/WARN]: Time from main menu to in-game was 4.6084557 seconds
[21:48:11] [Render thread/WARN]: Total time to load game and open world was 23.220455 seconds
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[21:48:11] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[21:48:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[21:48:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 919.8 μs, totaling 41.23 ms.
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 891.9 μs, totaling 1.169 s.
[21:48:11] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 459.1 μs, totaling 12.64 ms.
[0907/214812.119865:INFO:CONSOLE(4)] "Connecting to server at:  ws://127.0.0.1:15000", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (4)
[21:48:12] [epollEventLoopGroup-3-1/INFO]: [id: 0x7c572d1b, L:/[0:0:0:0:0:0:0:0%0]:15000] READ: [id: 0xbab2db9b, L:/127.0.0.1:15000 - R:/127.0.0.1:52556]
[21:48:12] [epollEventLoopGroup-3-1/INFO]: [id: 0x7c572d1b, L:/[0:0:0:0:0:0:0:0%0]:15000] READ COMPLETE
[0907/214812.163354:INFO:CONSOLE(4)] "[WS] Connected to server", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (4)
[0907/214812.195569:INFO:CONSOLE(4)] "[WS] Cleaned up event listeners", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (4)
[0907/214812.195661:INFO:CONSOLE(76)] "[Router] Redirecting to none", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (76)
[0907/214812.196717:INFO:CONSOLE(4)] "Connecting to server at:  ws://127.0.0.1:15000", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (4)
[21:48:12] [epollEventLoopGroup-3-1/INFO]: [id: 0x7c572d1b, L:/[0:0:0:0:0:0:0:0%0]:15000] READ: [id: 0x00cadd75, L:/127.0.0.1:15000 - R:/127.0.0.1:52572]
[21:48:12] [epollEventLoopGroup-3-1/INFO]: [id: 0x7c572d1b, L:/[0:0:0:0:0:0:0:0%0]:15000] READ COMPLETE
[0907/214812.275248:INFO:CONSOLE(4)] "[WS] Connected to server", source: http://127.0.0.1:15000/default/assets/index-CeH7XCTe.js (4)
[21:48:16] [Server thread/INFO]: Saving and pausing game...
[21:48:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:48:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:48:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[0907/214817.346409:WARNING:keyboard_code_conversion_x.cc(1462)] Unknown keycode:0
[0907/214817.443195:WARNING:keyboard_code_conversion_x.cc(1462)] Unknown keycode:0
[21:48:39] [ForkJoinPool.commonPool-worker-9/INFO]: [STDOUT]: Saving region 0,-1 to disk /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/cache
[21:48:39] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region -1,-1 to disk /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/cache
[21:48:39] [ForkJoinPool.commonPool-worker-4/INFO]: [STDOUT]: Saving region 0,0 to disk /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/cache
[21:48:39] [pool-11-thread-2/INFO]: [STDOUT]: Saving region -1,0 to disk /home/mrfrog222/.local/share/PrismLauncher/instances/1.21.1 LiquidBounce/.minecraft/saves/New World/./baritone/minecraft/overworld_384/cache
[21:48:39] [ForkJoinPool.commonPool-worker-9/INFO]: [STDOUT]: Saved region successfully
[21:48:39] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[21:48:39] [ForkJoinPool.commonPool-worker-4/INFO]: [STDOUT]: Saved region successfully
[21:48:39] [pool-11-thread-2/INFO]: [STDOUT]: Saved region successfully
[21:48:39] [pool-11-thread-2/INFO]: [STDOUT]: World save took 45ms

```

### Screenshots

![2024-09-07_21 42 39](https://github.com/user-attachments/assets/6ee2aa9a-4edb-45b0-bc8f-d1b320e75e0c)

**Comment by MrFrog222** [comment]
As you may see in the screenshot i also have other mods installed. But i also verified that neither of those is the culprit either.
