### ISSUE TITLE
[QUESTION] How can i use "nextgen" LiquidBounce?

### ISSUE THREAD

**Issue by Aleaf-Egemen** [CCBlueX/LiquidBounce#392]
![image](https://user-images.githubusercontent.com/45121448/113706737-b4cede00-96e7-11eb-9770-26d55f4b95b4.png)
![image](https://user-images.githubusercontent.com/45121448/113706757-bac4bf00-96e7-11eb-9d31-9dd2bec8de49.png)

im launching game like that but it crashes

**Comment by superblaubeere27** [comment]
ok. Can you send us the log?

**Comment by Aleaf-Egemen** [comment]
[latest.log](https://github.com/CCBlueX/LiquidBounce/files/6265088/latest.log) @superblaubeere27

**Comment by superblaubeere27** [comment]
Can you try it without optifine?

**Comment by Aleaf-Egemen** [comment]
it still crashes
[latest.log](https://github.com/CCBlueX/LiquidBounce/files/6265142/latest.log)

**Comment by Aplicat0r** [comment]
I have the same problem. When i start the game it says exit code:0

**Comment by 1zuna-chan** [comment]
It seems this is a issue caused by Mixins, because the obf naming of the field 'yaw' is not included in the refmap.
@superblaubeere27

**Comment by Aplicat0r** [comment]
soo how do we fix it

**Comment by 1zuna-chan** [comment]
Not sure. It works for me, so I can't really tell why it causes issues for you.

**Comment by Aplicat0r** [comment]
okay i reinstalled java and now it works

**Comment by Aplicat0r** [comment]
what version of fabric do u have

**Comment by 1zuna-chan** [comment]
'fabric-loader-0.11.3-1.16.5'
![](https://encrypting.host/T4F1CCtuLT.png?key=znnAXHIqJmROlS)

**Comment by Aplicat0r** [comment]
its the same for me but it sill crashes. I tryed reinstalling java and fabric, but it sill dose that. Maybe if i reinstall Minecraft, idk. I will try

**Comment by 1zuna-chan** [comment]
I don't think so. Could you try using this version:
https://dl.ccbluex.net/skip/Z8mETelcui

**Comment by Aplicat0r** [comment]
ill try

**Comment by Aplicat0r** [comment]
okay that works.

**Comment by 1zuna-chan** [comment]
Can you send me your log?

**Comment by Aplicat0r** [comment]
uhhh how xD

**Comment by 1zuna-chan** [comment]
from .minecraft/logs/latest.log

**Comment by Aplicat0r** [comment]
oof the file is too big.

**Comment by Aplicat0r** [comment]
ok here https://justpaste.it/5flkd

**Comment by 1zuna-chan** [comment]
oh god hell, I can't read this.
Please post it on https://paste.ccbluex.net/

**Comment by Aplicat0r** [comment]
when i try to paste it the tab just freezes

**Comment by Aplicat0r** [comment]
can i share the file with mega and then u can download it

**Comment by benjarobbi** [comment]
there you go: https://img.l1.si/e4dc0438-ba36-4c44-8ace-b4e9aea57424.html

**Comment by Aplicat0r** [comment]
on what site did u paste it

**Comment by benjarobbi** [comment]
I simply downloaded your justpaste - did some regex foo to get an HTML file out of it and uploaded it on a public ShareX file uploader.

**Comment by Aplicat0r** [comment]
ohh i didnt think of that

**Comment by benjarobbi** [comment]
I'd just recommend using a simple file drop service the next time for sharing bigger log files. Avoid services, which don't offer proper formatting such as justpaste or stick, if possible, to [the CCBlueX paste service](https://paste.ccbluex.net/).

**Comment by Aplicat0r** [comment]
The problem wat that the file was too big for github and when I tryed to paste the log on ccbluex paste service my pc almost crashed.

**Comment by benjarobbi** [comment]
I have been able to upload the 4 MB log file to GitHub, as the limit for [file uploads within issues is 25 MB for files](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests). How big is your local log file?

**Comment by Aplicat0r** [comment]
174mb

**Comment by benjarobbi** [comment]
Alright. Well then this could be the issue, why most services didn't let you upload your insanely big log file. JustPaste has obviously only managed it by truncating your log file at 4 MB. Still, I would guess that the information we received out of the 4 MB should be sufficient for further analysis. 

For further bug reporting you maybe should just select a specific part of the file to share in an issue to speed-up file sharing and to avoid unnecessary resource usage.

**Comment by 1zuna-chan** [comment]
```
[17:44:31] [Thread-20/INFO]: Loading ultralight...
[17:44:31] [Thread-20/INFO]: [STDERR]: java.lang.RuntimeException: Task failed execution
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:53)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:42)
[17:44:31] [Thread-20/INFO]: [STDERR]: at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[17:44:31] [Thread-20/INFO]: [STDERR]: Caused by: com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency UltralightCore (tried to load from C:\Users\PC\AppData\Roaming\.minecraft\LiquidBounce\natives\UltralightCore.dll)
[17:44:31] [Thread-20/INFO]: [STDERR]: at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146)
[17:44:31] [Thread-20/INFO]: [STDERR]: at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.renderer.ultralight.WebPlatform$init$1.invoke(WebPlatform.java:84)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.renderer.ultralight.WebPlatform$init$1.invoke(WebPlatform.java:79)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:51)
[17:44:31] [Thread-20/INFO]: [STDERR]: ... 2 more
[17:44:31] [Thread-20/INFO]: [STDERR]: Caused by: java.lang.UnsatisfiedLinkError: C:\Users\PC\AppData\Roaming\.minecraft\LiquidBounce\natives\UltralightCore.dll: The process cannot access the file because it is being used by another process
[17:44:31] [Thread-20/INFO]: [STDERR]: at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[17:44:31] [Thread-20/INFO]: [STDERR]: at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
[17:44:31] [Thread-20/INFO]: [STDERR]: at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
[17:44:31] [Thread-20/INFO]: [STDERR]: at java.lang.Runtime.load0(Runtime.java:809)
[17:44:31] [Thread-20/INFO]: [STDERR]: at java.lang.System.load(System.java:1086)
[17:44:31] [Thread-20/INFO]: [STDERR]: at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144)
[17:44:31] [Thread-20/INFO]: [STDERR]: ... 6 more
[17:44:31] [Thread-20/INFO]: [STDERR]: java.lang.RuntimeException: Task failed execution
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:53)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:42)
[17:44:31] [Thread-20/INFO]: [STDERR]: at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[17:44:31] [Thread-20/INFO]: [STDERR]: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property renderer has not been initialized
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.renderer.ultralight.WebPlatform.getRenderer(WebPlatform.java:73)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.renderer.ultralight.WebView$1.invoke(WebView.java:133)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.renderer.ultralight.WebView$1.invoke(WebView.java:129)
[17:44:31] [Thread-20/INFO]: [STDERR]: at net.ccbluex.liquidbounce.utils.SingleThreadTaskScheduler$1.invoke(SingleThreadTaskScheduler.java:51)
[17:44:31] [Thread-20/INFO]: [STDERR]: ... 2 more
```

the main reasion is this.

**Comment by Aplicat0r** [comment]
and what is this?

**Comment by Aplicat0r** [comment]
okay i fix the half of the problem. i had to load the fabric api. now the modules are working but the hud is broken LOL

**Comment by 1zuna-chan** [comment]
the hud is probably broken because the bundled css, js is missing from the nightly builds because of some problems with the gradle building and npm builds.

**Comment by Aplicat0r** [comment]
where can i get the css file

**Comment by 1zuna-chan** [comment]
Can you please just wait until we're done solving these issues?

**Comment by Aplicat0r** [comment]
yeah

**Comment by 1zuna-chan** [comment]
![4yt2iXTEXk](https://user-images.githubusercontent.com/69533520/114185172-b72e7380-9945-11eb-84ea-4d5ed8ba26bd.png)
