### ISSUE TITLE
[BUG] Game rendering freeze when joing loyisa

### ISSUE THREAD

**Issue by commandblock2** [CCBlueX/LiquidBounce#3943]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-2aa367e

### Operating System

Linux

### Minecraft Version

1.21.1

### Describe the bug

When I joined the loyisa server I see my game rendering freeze but the chat(log) and the sound works. This does not reliably reproduce and sometime it's after you have a few normal frames in the server already but other time it stucks in the loading terrain ui. Happens like 80% of the time for me, I am on KDE/wayland/mesa/intel, also tested with proprietary nvidia driviers.
Oddly enough, loyisa is the only server had this happening for me

### Steps to reproduce

- Modify build.gradle to include viafabricplus to include the mod in launch
- Launch LiquidBounce with Intellij idea
- Join `mc.loyisa.cn` if it doesn't reproduce then join another server and comeback and join mc.loyisa.cn

### Client Log

```shell
Github says the comment can't be longer than 65536 so I put it here instead,
https://privatebin.net/?6e9f22e9a7e93e76#2q1NtJMS6gFiwo3NNMg6Tjp1UsbUgtipUhZiuiF3HtNh
```

### Screenshots

https://github.com/user-attachments/assets/08eeff6a-7fc2-43b9-8871-3917f992ce2a

Listen to the audio in this attachment.

**Comment by commandblock2** [comment]
I put a log point `Breakpoint reached at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1166)` (the start of the `render` function, line 1214 after genSources) here, this log point can be reached when I am in other servers, but when I am in loyisa's setting server it's not reached.

**Comment by commandblock2** [comment]
It maybe is a bit of misleading to say that the break point can not be reached at all, it is actually somehow stuck in the `render` function executing a task (looks like a StorageESP one), here is the thread dump,
```
"Render thread@1" tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at net.ccbluex.liquidbounce.features.module.modules.render.ModuleStorageESP$StorageScanner.invalidateChunk(ModuleStorageESP.kt:234)
	  at net.ccbluex.liquidbounce.utils.block.WorldChangeNotifier.chunkDeltaUpdateHandler$lambda$3$lambda$2(WorldChangeNotifier.kt:43)
	  at net.ccbluex.liquidbounce.utils.block.WorldChangeNotifier$$Lambda/0x00007fad09744cc0.invoke(Unknown Source:-1)
	  at net.ccbluex.liquidbounce.utils.block.WorldChangeNotifier.notifyAllSubscribers(WorldChangeNotifier.kt:76)
	  - locked <0x8b85> (a java.util.ArrayList)
	  at net.ccbluex.liquidbounce.utils.block.WorldChangeNotifier.chunkDeltaUpdateHandler$lambda$3(WorldChangeNotifier.kt:42)
	  at net.ccbluex.liquidbounce.utils.block.WorldChangeNotifier$$Lambda/0x00007fad091b4298.invoke(Unknown Source:-1)
	  at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:197)
	  at net.minecraft.client.network.ClientPlayNetworkHandler.handler$bpm000$liquidbounce$onChunkDeltaUpdateEnd(MixinClientPlayNetworkHandler.java:78)
	  at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkDeltaUpdate(ClientPlayNetworkHandler.java:701)
	  at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket.java:77)
	  at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket.java:36)
	  at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27)
	  at net.minecraft.network.NetworkThreadUtils$$Lambda/0x00007fad0962c9c8.run(Unknown Source:-1)
	  at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:140)
	  at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:24)
	  at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:114)
	  at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:103)
	  at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1233)
	  at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:885)
	  at net.minecraft.client.main.Main.main(Main.java:228)
	  at java.lang.invoke.LambdaForm$DMH/0x00007fad08294000.invokeStaticInit(LambdaForm$DMH:-1)
	  at java.lang.invoke.LambdaForm$MH/0x00007fad08009400.invokeExact_MT(LambdaForm$MH:-1)
	  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	  at java.lang.invoke.LambdaForm$DMH/0x00007fad08005c00.invokeStatic(LambdaForm$DMH:-1)
	  at java.lang.invoke.LambdaForm$MH/0x00007fad08009400.invokeExact_MT(LambdaForm$MH:-1)
	  at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

```

**Comment by commandblock2** [comment]
If I change https://github.com/CCBlueX/LiquidBounce/blob/4fde9b10b5f58d99b8977559f1b1edc4b9631a3f/src/main/kotlin/net/ccbluex/liquidbounce/utils/block/ChunkScanner.kt#L112 to `        private val chunkUpdateQueue = ArrayBlockingQueue<UpdateRequest>(6000)` the game will freeze after a few minutes of playing. Putting log points here https://github.com/CCBlueX/LiquidBounce/blob/4fde9b10b5f58d99b8977559f1b1edc4b9631a3f/src/main/kotlin/net/ccbluex/liquidbounce/utils/block/ChunkScanner.kt#L152-L154 does indicate that it keeps growing and the game freezes when it reaches 6000, it's some times do decrease to 5999 but it is probably because of the ChunkScannerThread cannot keep up with this update request

**Comment by commandblock2** [comment]
Looks like this is happening because loyisa puts way too many beds in it's map and the `ModuleBedPlates` listens for block changes and this part is called when doing the chunk scan. The visualvm profile is attached, look for the `ChunkScannerThread`, which might be a bit difficult to find
[snapshot-1726583221997.nps.zip](https://github.com/user-attachments/files/17029916/snapshot-1726583221997.nps.zip)

**Comment by MukjepScarlet** [comment]
I refactored this feature with Kotlin coroutines. (#4081) Could you test once again with the latest commit? I haven't encountered it for now.

**Comment by commandblock2** [comment]
Checked out this commit and the previous one, can confirm this https://github.com/CCBlueX/LiquidBounce/pull/4081 fixes the problem
