### ISSUE TITLE
[BUG] crashing game

### ISSUE THREAD

**Issue by sh0tzik** [CCBlueX/LiquidBounce#4352]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.16.0

### Operating System

macOS

### Minecraft Version

1.21.1

### Describe the bug

I launched the client, I wait until it starts, and when it starts, an error occurs and the client crashes

### Steps to reproduce

я не знаю

### Client Log

```shell
cket.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.h
ttp.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadFile(MCEFResourceManager.java:233) ~[LiquidBounce.jar:?]
	... 12 more
An error occourd:

Process exited with non-zero exit code: 1.
```

**Comment by 1zun4** [comment]
Use a VPN such as Cloudflare Warp.
