### ISSUE TITLE
[BUG] liquidbounce doesnt load

### ISSUE THREAD

**Issue by ENDER1355** [CCBlueX/LiquidBounce#444]
loading screen appears, but then it crashes

Crash log:

[17:28:05] [main/INFO]: Loading for game Minecraft 1.16.5
[17:28:06] [main/INFO]: [FabricLoader] Loading 58 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, multiconnect-api@1.3.36, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, liquidbounce@1.0.0, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.33.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.6.0+2868a2287d, fabric-key-binding-api-v1@1.0.4+9354966b7d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.6+2868a2287d, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-object-builders-v0@0.7.2+ca58154a7d
[17:28:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Ali/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:28:17] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:28:18] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:625) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:409) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[17:28:18] [main/INFO]: Setting user: maxpower097
[17:28:19] [main/INFO]: [Indigo] Registering Indigo renderer!
[17:28:20] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:28:24] [main/INFO]: Narrator library for x64 successfully loaded
[17:28:24] [main/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[17:28:25] [main/INFO]: Successfully extracted default theme
[17:28:25] [main/INFO]: Loading heads...
[17:28:25] [main/ERROR]: Unable to load heads database
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_51]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request(HttpClient.java:53) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request$default(HttpClient.java:50) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.get(HttpClient.java:62) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.tabs.Tabs.<clinit>(Tabs.java:86) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:85) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:64) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zeb000$startClient(class_310.java:4921) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:574) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[17:28:25] [main/ERROR]: Unable to load font Roboto-Medium.ttf. Falling back to default.
java.awt.FontFormatException: java.nio.BufferUnderflowException
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:569) ~[?:1.8.0_51]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:191) ~[?:1.8.0_51]
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2461) ~[?:1.8.0_51]
	at java.awt.Font.<init>(Font.java:615) ~[?:1.8.0_51]
	at java.awt.Font.createFont0(Font.java:969) ~[?:1.8.0_51]
	at java.awt.Font.createFont(Font.java:877) ~[?:1.8.0_51]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.getAwtFont(Fonts.java:96) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.loadFont(Fonts.java:82) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadFonts(Fonts.java:68) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.RenderEngine.init(RenderEngine.java:125) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:89) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:64) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zeb000$startClient(class_310.java:4921) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:574) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[17:28:25] [main/ERROR]: Unable to load font Roboto-Bold.ttf. Falling back to default.
java.awt.FontFormatException: java.nio.BufferUnderflowException
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:569) ~[?:1.8.0_51]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:191) ~[?:1.8.0_51]
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2461) ~[?:1.8.0_51]
	at java.awt.Font.<init>(Font.java:615) ~[?:1.8.0_51]
	at java.awt.Font.createFont0(Font.java:969) ~[?:1.8.0_51]
	at java.awt.Font.createFont(Font.java:877) ~[?:1.8.0_51]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.getAwtFont(Fonts.java:96) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.loadFont(Fonts.java:82) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadFonts(Fonts.java:68) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.RenderEngine.init(RenderEngine.java:125) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:89) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:64) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zeb000$startClient(class_310.java:4921) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:574) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[17:28:26] [main/INFO]: Found out OpenGL version to be 4.6.14760. Using backend for OpenGL 4.3+ (Multi rendering)
[17:28:26] [main/INFO]: Loading ultralight...
[17:28:26] [main/INFO]: Checking resources...
[17:28:26] [main/INFO]: Downloading v0.43 resources... (os: win)
[17:28:27] [main/ERROR]: Unable to download resources
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_51]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.download(HttpClient.java:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.ultralight.UltralightResources.downloadResources(UltralightResources.java:84) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.init(UltralightEngine.java:85) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:92) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.java:64) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zeb000$startClient(class_310.java:4921) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:574) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]

**Comment by 1zun4** [comment]
It seems something is wrong with your internet connection. Might check if you can access: https://cloud.liquidbounce.net/

**Comment by ENDER1355** [comment]
cloud site works, but it still doesn't load

**Comment by 1zun4** [comment]
Not sure what causes the SSL handshake issues.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Sorry. I can't really help you out right now.

**Comment by 1zun4** [comment]
Oh. I think I might know why.
https://github.com/CCBlueX/LiquidBounce/issues/445

You are modifying the Djavax.net.ssl.trustStore which might causes all other SSL handhshakes to break.

**Comment by ENDER1355** [comment]
thank you for helping, does easymc need a public API in order to make account manager of them?

**Comment by ENDER1355** [comment]
@1zun4 can u lock this? cuz someone found out my name and i don't want ppl spamming here OMG HIS REAL NAME
