### ISSUE TITLE
[BUG]Shader crash

### ISSUE THREAD

**Issue by MTW6wQ** [CCBlueX/LiquidBounce#4627]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.18 and 0.19

### Operating System

macOS

### Minecraft Version

1.21.1

### Describe the bug

when I click "toggle shaders" it crashes 
same thing happens on 0.19 and 0.18
when opening the client again it crashes

### Steps to reproduce

-  click toggle shaders
- crashes

### Client Log

```shell
[13:33:03] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[13:33:03] [main/INFO]: Loading 56 mods:
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- liquidbounce 0.19.0
	   |-- com_github_ccbluex_discordipc 4.0.0
	   |-- com_github_ccbluex_mc-authlib 1.4.1
	   |-- com_github_ccbluex_netty-httpserver 2.1.0
	   |-- com_google_code_gson_gson 2.10.1
	   |-- com_kohlschutter_junixsocket_junixsocket-common 2.8.3
	   |-- com_kohlschutter_junixsocket_junixsocket-native-common 2.8.3
	   |-- com_thealtening_api_api 4.1.0
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- commons-io_commons-io 2.15.1
	   |-- io_netty_netty-codec 4.1.114
	   |-- io_netty_netty-codec-http 4.1.114
	   |-- io_netty_netty-codec-socks 4.1.114
	   |-- io_netty_netty-handler 4.1.114
	   |-- io_netty_netty-handler-proxy 4.1.114
	   |-- io_netty_netty-resolver 4.1.114
	   |-- io_netty_netty-transport-native-unix-common 4.1.114
	   |-- mcef 1.2.0-1.21.1
	   |-- net_fabricmc_tiny-mappings-parser 0.3.0+build.17
	   |-- net_lenni0451_reflect 1.3.2
	   |-- org_apache_commons_commons-exec 1.3
	   |-- org_apache_commons_commons-lang3 3.12.0
	   |-- org_apache_logging_log4j_log4j-api 2.23.1
	   |-- org_apache_logging_log4j_log4j-core 2.23.1
	   |-- org_apache_tika_tika-core 2.9.2
	   |-- org_graalvm_js_js-language 24.0.2
	   |-- org_graalvm_polyglot_polyglot 24.0.2
	   |-- org_graalvm_regex_regex 24.0.2
	   |-- org_graalvm_sdk_collections 24.0.2
	   |-- org_graalvm_sdk_jniutils 24.0.2
	   |-- org_graalvm_sdk_nativeimage 24.0.2
	   |-- org_graalvm_sdk_word 24.0.2
	   |-- org_graalvm_shadowed_icu4j 24.0.2
	   |-- org_graalvm_truffle_truffle-api 24.0.2
	   |-- org_graalvm_truffle_truffle-compiler 24.0.2
	   |-- org_graalvm_truffle_truffle-runtime 24.0.2
	   |-- org_jetbrains_annotations 13.0
	   \-- org_slf4j_slf4j-api 2.0.10
	- minecraft 1.21.1
[13:33:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/Users/{COMPUTER_USERNAME}/Library/Application%20Support/ModrinthApp/meta/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[13:33:03] [main/INFO]: Compatibility level set to JAVA_17
[13:33:04] [main/WARN]: Error loading class: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl (java.lang.ClassNotFoundException: com/viaversion/viaversion/protocol/packet/PacketWrapperImpl)
[13:33:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[13:33:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/model/light/data/LightDataAccess (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/model/light/data/LightDataAccess)
[13:33:04] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[13:33:04] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 145 milliseconds
[13:33:07] [main/ERROR]: FabricAPI is not installed, please install it to use the page buttons in the creative inventory
[13:33:07] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:33:07] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[13:33:07] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[13:33:08] [Render thread/INFO]: Launching LiquidBounce v0.19.0 by CCBlueX
[13:33:08] [Render thread/INFO]: Probing environment...
[13:33:08] [Render thread/INFO]: Intermediary environment detected.
[13:33:08] [Render thread/INFO]: Loaded language en_us
[13:33:08] [Render thread/INFO]: [ScriptAPI] Engine Version: Development Build, Supported languages: [ js ]
[13:33:09] [Render thread/INFO]: Successfully extracted default theme
[13:33:09] [Render thread/INFO]: Inserted 12 components
[13:33:09] [Render thread/INFO]: Successfully loaded config 'combattargets'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'combattargets'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'visualtargets'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'visualtargets'.
[13:33:09] [Render thread/INFO]: (Chat) 
[13:33:09] [Render thread/INFO]: (Chat) LiquidBounce ▸ Auto ConfigLiquidBounce ▸ Auto Config
[13:33:09] [Render thread/INFO]: Successfully loaded config 'modules'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'modules'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'commands'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'commands'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'friends'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'friends'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'proxy'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'proxy'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'accounts'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'accounts'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'tabs'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'tabs'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'lang'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'lang'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'account'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'account'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'storage'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'storage'.
[13:33:09] [Render thread/INFO]: Successfully loaded config 'theme'.
[13:33:09] [Render thread/INFO]: Successfully saved config 'theme'.
[13:33:09] [Render thread/INFO]: Default port 15000 available.
[13:33:09] [Render thread/INFO]: Refresh Rate: 60 Hz
[13:33:09] [Render thread/INFO]: JCEF Commit: 0e837c94ea090b6eb4b9bc65428ec28fd75d1d72
[13:33:09] [netty-websocket/INFO]: Starting Netty server...
[13:33:09] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d] REGISTERED
[13:33:09] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d] BIND: 0.0.0.0/0.0.0.0:15000
[13:33:09] [netty-websocket/INFO]: Netty server started on port 15000.
[13:33:09] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] ACTIVE
[13:33:10] [Render thread/INFO]: [Downloading Checksum] Started task
[13:33:10] [Rich Presence Updater/INFO]: Loading Discord IPC configuration...
[13:33:10] [Render thread/INFO]: [Downloading Checksum] Progress 100%
[13:33:10] [Rich Presence Updater/INFO]: Successfully connected to Discord RPC.
[13:33:10] [Render thread/INFO]: Checksum matches: true
[13:33:10] [Render thread/INFO]: Platform directory exists: true
[13:33:10] [Render thread/INFO]: Initializing CEF on macos_arm64...
[13:33:10] [Render thread/INFO]: [STDOUT]: initialize on Thread[#1,Render thread,5,main] with library path /Users/{COMPUTER_USERNAME}/Library/Application Support/ModrinthApp/profiles/LB Plain/LiquidBounce/mcef/libraries/0e837c94ea090b6eb4b9bc65428ec28fd75d1d72/macos_arm64/jcef_app.app/Contents/Java
[13:33:10] [Render thread/INFO]: Chromium Embedded Framework initialized
[13:33:10] [Render thread/INFO]: Browser is ready.
[13:33:10] [Render thread/INFO]: Successfully loaded client!
[13:33:11] [Render thread/INFO]: Loaded background image for theme default
[13:33:11] [Render thread/INFO]: Reloading ResourceManager: vanilla
[13:33:11] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x6408e127, L:/127.0.0.1:15000 - R:/127.0.0.1:63883]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:11] [Worker-Main-4/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0xaf0979fa, L:/127.0.0.1:15000 - R:/127.0.0.1:63884]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x1242a308, L:/127.0.0.1:15000 - R:/127.0.0.1:63885]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x8f9363cc, L:/127.0.0.1:15000 - R:/127.0.0.1:63886]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x3dda092c, L:/127.0.0.1:15000 - R:/127.0.0.1:63887]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0xdac87dfa, L:/127.0.0.1:15000 - R:/127.0.0.1:63888]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x388ab167, L:/127.0.0.1:15000 - R:/127.0.0.1:63889]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x75d0ed33, L:/127.0.0.1:15000 - R:/127.0.0.1:63890]
[13:33:11] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:11] [Render thread/ERROR]: ########## GL ERROR ##########
[13:33:11] [Render thread/ERROR]: @ Render
[13:33:11] [Render thread/ERROR]: 65539: Invalid standard cursor 0x00000000
[13:33:12] [IO-Worker-1/INFO]: Requesting to login into Mojang...
[13:33:12] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:33:12] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:33:12] [Render thread/INFO]: OpenAL initialized on device Gemoo Speaker
[13:33:12] [Render thread/INFO]: Sound engine started
[13:33:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[13:33:12] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:33:12] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[13:33:12] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:33:12] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[13:33:12] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:33:12] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:33:12] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[13:33:12] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[13:33:12] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:33:12] [Render thread/ERROR]: Failed to load UI blur shader
java.io.FileNotFoundException: liquidbounce:shaders/post/ui_blur.json
	at knot/net.minecraft.class_5912.method_43043(class_5912.java:23) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at knot/net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_279.method_1256(class_279.java:61) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.handler$zec000$liquidbounce$hookUIBlurLoad(class_757.java:1760) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:547) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
[13:33:12] [Render thread/ERROR]: Failed to load outline shader
java.io.FileNotFoundException: liquidbounce:shaders/post/outline_shader.json
	at knot/net.minecraft.class_5912.method_43043(class_5912.java:23) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at knot/net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_279.method_1256(class_279.java:61) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_279.<init>(class_279.java:57) ~[client-intermediary.jar:?]
	at knot/net.ccbluex.liquidbounce.render.engine.MinecraftFramebufferShader.load(MinecraftFramebufferShader.kt:44) ~[liquidbounce.jar:?]
	at knot/net.minecraft.class_761.handler$zek000$liquidbounce$onLoadEntityOutlineShader(class_761.java:3211) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_761.method_3296(class_761.java:532) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_761.method_14491(class_761.java:508) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
[13:33:12] [Render thread/INFO]: Loading fonts...
[13:33:12] [Render thread/INFO]: Loading queued font Montserrat
[13:33:13] [Render thread/INFO]: Loaded fonts successfully!
[13:33:13] [Render thread/INFO]: Loaded Discord IPC configuration.
[13:33:13] [Render thread/INFO]: Refreshing local IP info...
[13:33:14] [Render thread/INFO]: Loading heads...
[13:33:16] [Render thread/INFO]: Successfully loaded 956 heads from the database
[13:33:16] [Render thread/INFO]: Loading settings list from API...
[13:33:16] [Render thread/INFO]: Loaded 22 settings from API.
[13:33:16] [Render thread/INFO]: Disabled conflicting options.
[13:33:16] [Render thread/INFO]: Successfully loaded 346 cosmetics carriers.
[13:33:19] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ: [id: 0x2fa4744d, L:/127.0.0.1:15000 - R:/127.0.0.1:63903]
[13:33:19] [nioEventLoopGroup-2-1/INFO]: [id: 0xddd6e50d, L:/[0:0:0:0:0:0:0:0]:15000] READ COMPLETE
[13:33:29] [nioEventLoopGroup-3-2/INFO]: Successfully saved config 'theme'.
[13:33:29] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Filed to compile shader! Caused by: ERROR: 0:1: '' :  version '120' is not supported
ERROR: 0:2: '' :  #version required and missing.

	at knot/net.ccbluex.liquidbounce.render.shader.Shader.compileShader(Shader.kt:95) ~[liquidbounce.jar:?]
	at knot/net.ccbluex.liquidbounce.render.shader.Shader.<init>(Shader.kt:45) ~[liquidbounce.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.theme.Theme.compileShader(ThemeManager.kt:216) ~[liquidbounce.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.theme.ThemeManager.shaderEnabled_delegate$lambda$1$lambda$0(ThemeManager.kt:61) ~[liquidbounce.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:174) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.
Time: 2024-11-23 13:33:30
Description: Unexpected error
java.lang.IllegalStateException: Filed to compile shader! Caused by: ERROR: 0:1: '' : version '120' is not supported
ERROR: 0:2: '' : #version required and missing.
at knot//net.ccbluex.liquidbounce.render.shader.Shader.compileShader(Shader.kt:95)
at knot//net.ccbluex.liquidbounce.render.shader.Shader.<init>(Shader.kt:45)
at knot//net.ccbluex.liquidbounce.integration.theme.Theme.compileShader(ThemeManager.kt:216)
at knot//net.ccbluex.liquidbounce.integration.theme.ThemeManager.shaderEnabled_delegate$lambda$1$lambda$0(ThemeManager.kt:61)
at knot//com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:174)
at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162)
at knot//net.minecraft.class_1041.method_15998(class_1041.java:303)
at knot//net.minecraft.class_310.method_1523(class_310.java:1307)
at knot//net.minecraft.class_310.method_1514(class_310.java:882)
at knot//net.minecraft.client.main.Main.main(Main.java:256)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
at knot//net.ccbluex.liquidbounce.render.shader.Shader.compileShader(Shader.kt:95)
at knot//net.ccbluex.liquidbounce.render.shader.Shader.<init>(Shader.kt:45)
at knot//net.ccbluex.liquidbounce.integration.theme.Theme.compileShader(ThemeManager.kt:216)
at knot//net.ccbluex.liquidbounce.integration.theme.ThemeManager.shaderEnabled_delegate$lambda$1$lambda$0(ThemeManager.kt:61)
at knot//com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:174)
at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:162)
-- Uptime --
Details:
JVM uptime: 27.142s
Wall uptime: 22.594s
High-res time: 22.336s
Client ticks: 307 ticks / 15.350s
Stacktrace:
at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
at knot//net.minecraft.class_310.method_54580(class_310.java:949)
at knot//net.minecraft.class_310.method_1514(class_310.java:905)
at knot//net.minecraft.client.main.Main.main(Main.java:256)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: vanilla
Java Version: 21.0.4, Azul Systems, Inc.
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
Memory: 115916752 bytes (110 MiB) / 550502400 bytes (525 MiB) up to 2147483648 bytes (2048 MiB)
CPUs: 8
Processor Vendor: Apple Inc.
Processor Name: Apple M2
Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
Microarchitecture: ARM64 SoC: Avalanche + Blizzard
Frequency (GHz): 3.50
Number of physical packages: 1
Number of physical CPUs: 8
Number of logical CPUs: 8
Graphics card #0 name: Apple M2
Graphics card #0 vendor: Apple (0x106b)
Graphics card #0 VRAM (MiB): 0.00
Graphics card #0 deviceId: unknown
Graphics card #0 versionInfo: unknown
Memory slot #0 capacity (MiB): 0.00
Memory slot #0 clockSpeed (GHz): 0.00
Memory slot #0 type: unknown

```

**Comment by 1zun4** [comment]
I hope this fixes your issue. I cannot tell if 330 is high enough to be supported on macOS. Please try to use the nightly version to try it out and let me know if it works.

![image](https://github.com/user-attachments/assets/75c958ae-3c10-4091-895b-296a9b350693)

**Comment by MTW6wQ** [comment]
> I hope this fixes your issue. I cannot tell if 330 is high enough to be supported on macOS. Please try to use the nightly version to try it out and let me know if it works.
> 
> ![image](https://github.com/user-attachments/assets/75c958ae-3c10-4091-895b-296a9b350693)
>  
 Fixed
