### ISSUE TITLE
[BUG] 1.21 not supported what

### ISSUE THREAD

**Issue by VitzS7ven** [CCBlueX/LiquidBounce#4646]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.19.0

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

i put on my mods file and start

### Steps to reproduce

- put on mods folder
- start
- copy error on fabric screen

### Client Log

```shell
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'LiquidBounce' (liquidbounce) 0.19.0 with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'LiquidBounce' (liquidbounce) 0.19.0 requires version 1.21.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by ghost** [comment]
Can you read at this point? It tells you it needs 1.21.1 and not 1.21 to run the client.

**Comment by kefteme2110-eng** [comment]
cghjkl
