### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce#466]
latest nextgen crashing :p 

testing with clean .minecraft

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/117331628-9f440400-ae9f-11eb-9174-34fa50dd1de2.png)

**Comment by Teals53** [comment]
![Uploading image.png…]()

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/117331766-bd116900-ae9f-11eb-9962-ef3da03f8722.png)

**Comment by Teals53** [comment]
[19:17:28] [main/INFO]: Loading for game Minecraft 1.16.5
[19:17:29] [main/INFO]: [FabricLoader] Loading 57 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, liquidbounce@1.0.0, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.34.1+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, fabric-entity-events-v1@1.1.0+c88702897d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.6+2868a2287d, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.2+d6244c6d7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[19:17:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Pc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

**Comment by ghost** [comment]
You don't need fabric-api, just fabric kotlin.

1. Go to this site: https://fabricmc.net/use/
2. Download Installer for Windows
3. Run the file, install you know
4. Done. Now you simply go to your preferred Launcher, find fabric-loader-0.11.3-1.16.5 and load it.
5. Make sure you have LiquidBounce.jar and the fabric kotlin file on the mods folder.

**Comment by Teals53** [comment]
well u already telling me what i do before

**Comment by Teals53** [comment]
lol thats not helpful

**Comment by Teals53** [comment]
maybe u reply without looking the photos ? xd

**Comment by ghost** [comment]
Delete your `LiquidBounce` folder.

**Comment by Teals53** [comment]
there is no liquidbounce folder xd

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/117337157-b1c13c00-aea5-11eb-9140-fb769edc76b2.png)

**Comment by Teals53** [comment]
im testing with clean .mc folder i just install fabric and put required mods in mods folder did i need to do any other stuff ?

**Comment by ghost** [comment]
Did you install the fabric installer?

**Comment by Teals53** [comment]
yeap

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/117337380-f8af3180-aea5-11eb-9f81-10b82e97b558.png)
how can i see this without install fabric ?

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/117337412-01a00300-aea6-11eb-90a1-a2bdb1a8bd04.png)
and how it can be come without install fabric

**Comment by 1zun4secondary** [comment]
> [19:17:28] [main/INFO]: Loading for game Minecraft 1.16.5
> [19:17:29] [main/INFO]: [FabricLoader] Loading 57 mods: fabric-renderer-api-v1@0.4.2+2868a2287d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, liquidbounce@1.0.0, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.34.1+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, fabric-entity-events-v1@1.1.0+c88702897d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.6+2868a2287d, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.2+d6244c6d7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
> [19:17:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Pc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

always post the full crash log ... not just a piece of it.

and probably same reason like:
https://github.com/CCBlueX/LiquidBounce/issues/467

**Comment by Teals53** [comment]
i already post full log ? xd

**Comment by 1zun4secondary** [comment]
No. You did not.

**Comment by Teals53** [comment]
im not lying let me send a video

**Comment by Teals53** [comment]
https://user-images.githubusercontent.com/13446881/117353425-c529d280-aeb8-11eb-9e42-1ce132edb26d.mp4

**Comment by Teals53** [comment]
xd

**Comment by ghost** [comment]
You didn't install fabric-loader properly.

EDIT: You are missing the `native` folder. Re-install it.

**Comment by SenkJu** [comment]
The log you posted doesn't even contain an error. Make sure you can even launch the game without LiquidBounce.

**Comment by Teals53** [comment]
i can start game without mods

**Comment by Teals53** [comment]
[23:08:11] [main/INFO]: Loading for game Minecraft 1.16.5
[23:08:12] [main/INFO]: [FabricLoader] Loading 12 mods: org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, minecraft@1.16.5, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, java@8, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabricloader@0.11.3, fabric-language-kotlin@1.5.0+kotlin.1.4.31, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2
[23:08:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Pc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[23:08:18] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:08:19] [main/INFO]: Setting user: Teals53
[23:08:19] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[23:08:23] [main/INFO]: Narrator library for x64 successfully loaded
[23:08:23] [main/INFO]: Reloading ResourceManager: Default
[23:08:29] [main/INFO]: OpenAL initialized.
[23:08:29] [main/INFO]: Sound engine started
[23:08:30] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:08:30] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:08:30] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:08:30] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:08:30] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:08:30] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:08:30] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:08:32] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[23:08:32] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:08:32] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[23:08:51] [main/INFO]: Stopping!

**Comment by Teals53** [comment]
i can start without lb mod

**Comment by SenkJu** [comment]
That's still not a full log. Enable the option that opens a log windows as soon as you launch the game.

**Comment by Teals53** [comment]
23:11:48.880
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Pc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
23:11:50.241

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458$$Lambda$186/256346753.get(Unknown Source)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at net.minecraft.class_5458$$Lambda$194/712410791.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookStrideGround(Lnet/minecraft/class_1657;)Z in liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap liquidbounce-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more
23:11:50.241
Process crashed with exit code 1

**Comment by 1zun4secondary** [comment]
Exact same issue like: https://github.com/CCBlueX/LiquidBounce/issues/467

**Comment by Teals53** [comment]
so current version is broken kk
