### ISSUE TITLE
[BUG] com.jagrosh.discordipc.exceptions.NoDiscordClientException: No Valid Discord Client was found for this Instance

### ISSUE THREAD

**Issue by ManInMyVan** [CCBlueX/LiquidBounce#4665]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

4ea45ba

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

error

### Steps to reproduce

load client with discord closed

### Client Log

```shell
[12:09:28] [DefaultDispatcher-worker-2/ERROR]: Failed to connect to Discord RPC.
com.jagrosh.discordipc.exceptions.NoDiscordClientException: No Valid Discord Client was found for this Instance
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:163) ~[com_github_ccbluex_discordipc-4.0.0-e5ca8b6597c4be2b.jar:?]
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:375) ~[com_github_ccbluex_discordipc-4.0.0-e5ca8b6597c4be2b.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.client.ModuleRichPresence.connectIpc(ModuleRichPresence.kt:92) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.client.ModuleRichPresence.access$connectIpc(ModuleRichPresence.kt:60) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.module.modules.client.ModuleRichPresence$updateCycle$1$1.invokeSuspend(ModuleRichPresence.kt:141) [liquidbounce.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.0.21-6301f741d3f6049d.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) [org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
```

**Comment by 1zun4** [comment]
Not a bug.

**Comment by ManInMyVan** [comment]
make the error silent or a warning?
