### ISSUE TITLE
[BUG]Pink Glitch

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#4721]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.20.1

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

Colors went all weird

### Steps to reproduce

idk

### Client Log

```shell
https://mclo.gs/RIy31Ql
```

### Screenshots

![image](https://github.com/user-attachments/assets/3b5e6687-9ef2-420c-87e0-c436b1e59168)

**Comment by DataM0del** [comment]
> ### LiquidBounce Branch
> 
> Nextgen
> ### LiquidBounce Build/Version
> 
> 0.20.1
> ### Operating System
> 
> Windows 11
> ### Minecraft Version
> 
> 1.21.1
> ### Describe the bug
> 
> Colors went all weird
> ### Steps to reproduce
> 
> idk
> ### Client Log
> 
> ```shell
> https://mclo.gs/RIy31Ql
> ```
> 
> ### Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/88818265/390225283-3b5e6687-9ef2-420c-87e0-c436b1e59168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzkyNDIsIm5iZiI6MTczMjY3ODk0MiwicGF0aCI6Ii84ODgxODI2NS8zOTAyMjUyODMtM2I1ZTY2ODctOWVmMi00MjBjLTg3ZTAtYzQzNmIxZTU5MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAzNDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OTVhNzYyNDlhOGJmYzJmYmM0MTBlNTM5YWM0OTNlMzgxM2U3NjMyYzNkYjY5NmI3YzhiNDJjZmViMzljMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tfYTf4h30xjA8crgl9P0n2B8eyHWNgOR0AC8pHzdyUQ)

Either:
- Your device is out of memory (too bad, Java ate your RAM, 99.99999999999% usage, only 1 MB left for OS)
- He must've ported RenderDragon to this
- your texture pack doesn't have the texture for something (shouldn't happen)

**Comment by DataM0del** [comment]
> [21:05:32] [Render thread/WARN]: Failed to load texture: minecraft:textures/atlas/blocks.png
java.io.FileNotFoundException: minecraft:textures/atlas/blocks.png
	at knot/net.minecraft.class_5912.method_43043(class_5912.java:23) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at knot/net.minecraft.class_5912.getResourceOrThrow(class_5912.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4668$class_4683.method_23563(class_4668.java:241) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at knot/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1109) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1921.method_60895(class_1921.java:894) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_60893(class_4597.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_22994(class_4597.java:85) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4597$class_4598.method_22993(class_4597.java:78) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51452(class_332.java:130) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51425(class_332.java:583) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51424(class_332.java:564) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_332.method_51423(class_332.java:560) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_1762(class_329.java:1293) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_1759(class_329.java:588) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_55805(class_329.java:529) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) [client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55809(class_9080.java:29) [client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_1753(class_329.java:218) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

your resource pack / texture pack doesn't have the textures, skill issue.

**Comment by 1zun4** [comment]
Restart your game. Unlikely a LiquidBounce bug.
