### ISSUE TITLE
[BUG] just another crash report

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce#475]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12.05.2021 01:25
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:100)
	at net.minecraft.class_309.handler$zzf000$hookKey(class_309.java:577)
	at net.minecraft.class_309.method_1466(class_309.java:357)
	at net.minecraft.class_309.method_22678(class_309.java:433)
	at net.minecraft.class_309$$Lambda$3783/1508292228.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:433)
	at net.minecraft.class_309$$Lambda$2400/226911589.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.java:100)
	at net.minecraft.class_309.handler$zzf000$hookKey(class_309.java:577)
	at net.minecraft.class_309.method_1466(class_309.java:357)
	at net.minecraft.class_309.method_22678(class_309.java:433)
	at net.minecraft.class_309$$Lambda$3783/1508292228.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:433)
	at net.minecraft.class_309$$Lambda$2400/226911589.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 10 total; [class_746['Ofet'/26573, l='ClientLevel', x=-6.28, y=63.00, z=-34.79], class_745['§a§lYakında..'/154, l='ClientLevel', x=-16.50, y=64.00, z=-48.50], class_745['CIT-ad1c30fd08de'/165, l='ClientLevel', x=-19.50, y=64.00, z=-40.50], class_745['§e'/169, l='ClientLevel', x=-8.50, y=64.00, z=-53.50], class_745['§e'/172, l='ClientLevel', x=-0.50, y=64.00, z=-53.50], class_745['§e'/175, l='ClientLevel', x=-4.50, y=64.00, z=-53.50], class_745['§e'/178, l='ClientLevel', x=-12.50, y=64.00, z=-51.50], class_745['§a§lYakında..'/186, l='ClientLevel', x=7.50, y=64.00, z=-48.50], class_745['§e'/189, l='ClientLevel', x=3.50, y=64.00, z=-51.50], class_745['§e§lÖdül Bekçisi'/192, l='ClientLevel', x=10.50, y=64.00, z=-40.50]]
	Chunk stats: Client Chunk Cache: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-5,63,-28), Chunk: (at 11,3,4 in -1,-2; contains blocks -16,0,-32 to -1,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 123515 game time, 1291416 day time
	Server brand: §c§l<3§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6796383000 bytes (6481 MB) / 8489271296 bytes (8096 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 730/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: Türkçe (Türkiye)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

%99 percent its know issue

**Comment by Teals53** [comment]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 12.05.2021 16:47
Description: Initializing game

kotlin.UninitializedPropertyAccessException: lateinit property lockedOnThread has not been initialized
	at net.ccbluex.liquidbounce.utils.client.ThreadLock.get(ThreadLock.java:27)
	at net.ccbluex.liquidbounce.render.ultralight.View.<init>(View.java:57)
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.newSplashView(UltralightEngine.java:152)
	at net.minecraft.class_425.handler$zbc000$hookSplashInit(class_425.java:556)
	at net.minecraft.class_425.<init>(class_425.java:53)
	at net.minecraft.class_310.<init>(class_310.java:585)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ccbluex.liquidbounce.utils.client.ThreadLock.get(ThreadLock.java:27)
	at net.ccbluex.liquidbounce.render.ultralight.View.<init>(View.java:57)
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.newSplashView(UltralightEngine.java:152)
	at net.minecraft.class_425.handler$zbc000$hookSplashInit(class_425.java:556)
	at net.minecraft.class_425.<init>(class_425.java:53)
	at net.minecraft.class_310.<init>(class_310.java:585)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7311932648 bytes (6973 MB) / 8086618112 bytes (7712 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 730/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

now again for not launchable

**Comment by ENDER1355** [comment]
did you put it in another directory? it may not work if you do so

**Comment by Teals53** [comment]
yeah why not lol

**Comment by ENDER1355** [comment]
hmmm, what are jvm arguments

**Comment by Teals53** [comment]
default

**Comment by ENDER1355** [comment]
hmm, i think i know, just remove natives folder from versions of fabric

**Comment by ENDER1355** [comment]
add -noverify maybe

**Comment by ENDER1355** [comment]
this was happening to me too

**Comment by ENDER1355** [comment]
remove everything except for json and jar in the fabric-loader-0.11.3-1.16.5 folder

**Comment by Teals53** [comment]
its not a crash about starting its a crash ingame xd

**Comment by Teals53** [comment]
just try to open hud or other modules and boom

**Comment by ENDER1355** [comment]
update your windows and java then, since liquidbounce and minecraft are in java and gui is in html

**Comment by Teals53** [comment]
its just becasue of nextgen nothing about me kk ?

**Comment by ENDER1355** [comment]
ive tried it and it worked, but clickgui didnt work (or because it doesnt exist?)

**Comment by Teals53** [comment]
no its exist set keybind or open it on tabgui

**Comment by ENDER1355** [comment]
change language maybe

**Comment by ENDER1355** [comment]
invalid?
