### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kosei9987aaa** [CCBlueX/LiquidBounce#4804]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

idk

### Operating System

Windows 11

### Minecraft Version

0.21.0

### Describe the bug

idk i added mod and it got cooked

### Steps to reproduce

add mod,
"webdisplay,and mcef "
start
cooked

### Client Log

```shell
[19:03:47] [Render thread/ERROR]: Fatal error
java.lang.NoClassDefFoundError: net/ccbluex/liquidbounce/mcef/MCEF
	at knot/net.ccbluex.liquidbounce.integration.browser.supports.JcefBrowser.makeDependenciesAvailable(JcefBrowser.kt:60) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.browser.BrowserManager.initBrowser(BrowserManager.kt:64) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.LiquidBounce.startHandler$lambda$4(LiquidBounce.kt:185) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:210) [LiquidBounce.jar:?]
	at knot/net.minecraft.class_310.handler$ccf000$liquidbounce$startClient(class_310.java:11276) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.<init>(class_310.java:668) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader
-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.ClassNotFoundException: net.ccbluex.liquidbounce.mcef.MCEF
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 10 more
[19:03:47] [netty-websocket/INFO]: Starting Netty server...
[19:03:47] [nioEventLoopGroup-3-1/INFO]: [id: 0xc4ce91e5] REGISTERED
[19:03:47] [nioEventLoopGroup-3-1/INFO]: [id: 0xc4ce91e5] BIND: 0.0.0.0/0.0.0.0:15000
[19:03:47] [nioEventLoopGroup-3-1/INFO]: [id: 0xc4ce91e5, L:/[0:0:0:0:0:0:0:0]:15000] ACTIVE
[19:03:47] [netty-websocket/INFO]: Netty server started on port 15000.
An error occured:

Process exited with non-zero exit code: 1.
```

**Comment by SuicidalEeper** [comment]
Maybe don't do that

**Comment by 1zun4** [comment]
Do not add WebDisplay or MCEF. We use MCEF for our client UI, but we have a heavily modified version of it, adding the old version of it yourself will cause the client to not work.
