### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xaersaw** [CCBlueX/LiquidBounce#4935]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

1.0

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

It didn't launch.

### Steps to reproduce

Go to LB 1.0 and launch.

### Client Log

```shell
matches.Library org.lwjgl:lwjgl-glfw:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.2:natives-windows-x86 already exists and SHA1 matches.Library org.slf4j:slf4j-api:2.0.7 already exists and SHA1 matches.Checking assets...Launching...Running...[20:23:12] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[20:23:12] [ForkJoinPool-1-worker-2/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR3-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:23:12] [main/INFO]: Loading 94 mods:
	- baritone 1.10.2
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- fabric-api 0.91.3 1.20.4
	   |-- fabric-api-lookup-api-v1 1.6.45 78d798af4f
	   |-- fabric-biome-api-v1 13.0.15 78d798af4f
	   |-- fabric-block-api-v1 1.0.14 78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3 78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45 78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6 78d798af4f
	   |-- fabric-command-api-v1 1.2.40 f71b366f4f
	   |-- fabric-commands-v0 0.2.57 df3654b34f
	   |-- fabric-containers-v0 0.1.81 df3654b34f
	   |-- fabric-content-registries-v0 5.0.9 78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9 78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22 78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17 78d798af4f
	   |-- fabric-dimensions-v1 2.1.60 78d798af4f
	   |-- fabric-entity-events-v1 1.5.28 4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14 78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71 df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45 78d798af4f
	   |-- fabric-item-api-v1 2.1.34 78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20 78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40 78d798af4f
	   |-- fabric-keybindings-v0 0.2.38 df3654b34f
	   |-- fabric-loot-api-v2 2.1.4 78d798af4f
	   |-- fabric-message-api-v1 6.0.4 78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59 78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7 78d798af4f
	   |-- fabric-models-v0 0.4.6 9386d8a74f
	   |-- fabric-object-builder-api-v1 13.0.7 78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15 78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3 78d798af4f
	   |-- fabric-renderer-indigo 1.5.3 78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50 df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41 73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32 78d798af4f
	   |-- fabric-rendering-v0 1.1.53 df3654b34f
	   |-- fabric-rendering-v1 3.0.12 78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13 78d798af4f
	   |-- fabric-screen-api-v1 2.0.16 78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50 78d798af4f
	   |-- fabric-sound-api-v1 1.0.16 78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6 78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13 78d798af4f
	- fabric-language-kotlin 1.9.4 kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- liquidbounce 0.1.0
	- minecraft 1.20.4
	- viafabricplus 3.1.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.10.0
	   |-- com_viaversion_viaversion-common 4.10.0
	   |-- de_florianmichael_classic4j 2.0.2
	   |-- fabric-api-base 0.4.37 78d798af4f
	   |-- fabric-command-api-v2 2.2.21 78d798af4f
	   |-- fabric-lifecycle-events-v1 2.3.1 a67ffb5d4f
	   |-- fabric-networking-api-v1 3.1.8 2e5ac5484f
	   |-- fabric-particles-v1 1.1.8 78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20 ee30b13a4f
	   |-- fabric-resource-loader-v0 0.11.21 ee30b13a4f
	   |-- io_jsonwebtoken_jjwt-api 0.12.5
	   |-- io_jsonwebtoken_jjwt-gson 0.12.5
	   |-- io_jsonwebtoken_jjwt-impl 0.12.5
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_commons_httpclient 1.4.1
	   |-- net_lenni0451_mcping 1.4.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_reflect 1.3.2
	   |-- net_raphimc_minecraftauth 4.0.0
	   |-- net_raphimc_viaaprilfools 2.0.11
	   |-- net_raphimc_viabedrock 0.0.6-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22
	   |-- net_raphimc_vialoader 2.2.13
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR3-SNAPSHOT
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_lz4_lz4-pure-java 1.8.0
	   \-- org_yaml_snakeyaml 2.2
[20:23:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/xaers/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:23:13] [main/INFO]: Compatibility level set to JAVA_17
[20:23:14] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[20:23:14] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[20:23:18] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
[20:23:18] [main/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus->@Redirect::changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity from mod liquidbounce->@Redirect::injectFatigueNoSlow(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;)Z with priority 1337
[20:23:18] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1657 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;Lcom/llamalad7/mixinextras/sugar/ref/LocalFloatRef;)Z in viafabricplus.mixins.json:fixes.minecraft.entity.MixinPlayerEntity from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap ViaFabricPlus-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at com.llamalad7.mixinextras.wrapper.InjectorWrapperImpl.doPostInject(InjectorWrapperImpl.java:79) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.doPostInject(SugarWrapperImpl.java:84) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.postInject(WrapperInjectionInfo.java:78) ~[mixinextras-0.3.1-325a8ab2beea7910.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:178) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	... 2 more
An error occured:

Process exited with non-zero exit code: 1.
```

**Comment by sqlerrorthing** [comment]
`by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeSpeedCalculation(Lnet/minecraft/class_1657;Lnet/minecraft/class_1291;Lcom/llamalad7/mixinextras/sugar/ref/LocalFloatRef;)Z in ==viafabricplus==.mixins.json:fixes.minecraft.entity.MixinPlayerEntity`

try to remove ViaFabricPlus

**Comment by 1zun4** [comment]
You are trying to launch LiquidBounce v0.1.0 for Minecraft 1.20.4, which was released almost 1 year ago... You have to update your client.

If you are looking to change your version on the newest LiquidBounce, this is how to do it: https://liquidbounce.net/docs/Tutorials/Changing%20Version
