### ISSUE TITLE
[BUG] 1.8.9 Not working on Mac 

### ISSUE THREAD

**Issue by cartnels** [CCBlueX/LiquidBounce#4954]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

all 

### Operating System

macOS

### Minecraft Version

1.8.9

### Describe the bug

When I launch 1.8.9 any build it will open for a millisecond then close giving me an error. Other versions such as 1.21.1 works fine.

### Steps to reproduce

Chose any build of 1.8.9 , launch and then the the client will open for a second then close.

### Client Log

```shell
ssLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_432]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_432]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 6 more
Exception in thread "main" 
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:101)
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:987)
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[18:23:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
An error occured:

Process exited with non-zero exit code: 1.
```

**Comment by ghost** [comment]
You need to send us a proper log. This does not help us find anything useful.

**Comment by EclipsesDev** [comment]
try launching without optifine

**Comment by 1zun4** [comment]
"Other versions such as 1.21.1 works fine." - then use that. Don't use Legacy. Nextgen works fine for 1.8 servers - look at: https://liquidbounce.net/docs/Tutorials/Changing%20Version

**Comment by EclipsesDev** [comment]
seems like a optifine issue, nothing we can do

**Comment by EclipsesDev** [comment]
actually you can use it by updating optifine to their preview version
