### ISSUE TITLE
[BUG] ScriptAPI mapping issue with method overloading

### ISSUE THREAD

**Issue by ayaxperson** [CCBlueX/LiquidBounce#4964]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.22.0

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

Hello, I've found out that when calling certain methods in DrawContext, other methods with the same name (but different parameters) are called. 

In the provided script, I try to call method_52706 (with the parameters `Identifier texture, int x, int y, int width, int height`), but method_52709 (with the parameters `Identifier texture, int int2, int int3, int int4, int int5, int x, int y, int z, int width, int height`) gets called instead (I'm presuming this on the amount of expected arguments). 

I used [this version of Yarn JavaDocs for DrawContext](https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/client/gui/DrawContext.html) as my reference for the methods and their parameters. I remember getting the link to this specific version somewhere in the ScriptAPI docs or possibly on the forum, but I can't say for sure as I cannot find it anymore, sorry :/

Here's my script:

```
const script = registerScript({
  name: "IssueExample",
  version: "1.0.0",
  authors: ["Ajax"]
});

script.registerModule({
  name: "IssueExample_drawGuiTexture",
  category: "Client",
  description: "Sausage"
}, (mod) => {

  mod.on("overlayRender", (event) => {
    if (!mc.player || !mc.world)
      return;

    // Should map to method_52706, but (probably) maps to method_52709
    // inb4 some smartass goes "oh this is because of null!1!", no
    event.context.drawGuiTexture(null, 100, 100, 200, 200);    
  })
});

script.registerModule({
  name: "IssueExample_fill",
  category: "Client",
  description: "Sausage"
}, (mod) => {

  mod.on("overlayRender", (event) => {
    if (!mc.player || !mc.world)
      return;

    // Should map to method_25294, but (probably) maps to method_51737
    event.context.fill(100, 100, 200, 200, -1);    
  })
});


```

### Steps to reproduce

- Try and call a method
- Find out there exists a method with the same name but different arguments
- Fail
- Get depressed

### Client Log

```shell
[18:45:05] [Render thread/INFO]: [CHAT] LiquidBounce ▸ Reloaded all scripts.
[18:45:07] [Render thread/INFO]: [CHAT] LiquidBounce ▸ IssueExample_fill has been enabled.
[18:45:07] [Render thread/INFO]: [CHAT] [IssueExample.js] IssueExample::IssueExample_fill::overlayRender threw [PolyglotException]: TypeError: invokeMember (fill) on net.minecraft.class_332 failed due to: Arity error - expected: 6 actual: 5
[18:45:07] [Render thread/ERROR]: IssueExample::IssueExample_fill -> Event Function overlayRender threw an error
org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (fill) on net.minecraft.class_332 failed due to: Arity error - expected: 6 actual: 5
	at <js>.:=>(IssueExample.js:35) ~[?:?]
	at knot/com.oracle.truffle.polyglot.PolyglotFunctionProxyHandler.invoke(PolyglotFunctionProxyHandler.java:151) ~[org_graalvm_truffle_truffle-api-24.0.2-995983b52bfdc5a1.jar:?]
	at knot/jdk.proxy2/jdk.proxy2.$Proxy61.invoke(Unknown Source) ~[?:?]
	at knot/net.ccbluex.liquidbounce.script.bindings.features.ScriptModule.callEvent(ScriptModule.kt:86) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.script.bindings.features.ScriptModule.hookHandler$lambda$2(ScriptModule.kt:126) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:213) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.render.engine.UIRenderer.startUIOverlayDrawing(UIRenderer.kt:70) ~[LiquidBounce.jar:?]
	at knot/net.minecraft.class_329.handler$ccn000$liquidbounce$hookRenderEventStart(class_329.java:3583) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_55805(class_329.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) [client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55809(class_9080.java:29) [client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_1753(class_329.java:218) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

[18:42:45] [Render thread/INFO]: [CHAT] LiquidBounce ▸ Reloaded all scripts.
[18:42:53] [Render thread/INFO]: [CHAT] LiquidBounce ▸ IssueExample has been enabled.
[18:42:53] [Render thread/INFO]: [CHAT] [IssueExample.js] IssueExample::IssueExample::overlayRender threw [PolyglotException]: TypeError: invokeMember (drawGuiTexture) on net.minecraft.class_332 failed due to: Arity error - expected: 10 actual: 5
[18:42:53] [Render thread/ERROR]: IssueExample::IssueExample -> Event Function overlayRender threw an error
org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (drawGuiTexture) on net.minecraft.class_332 failed due to: Arity error - expected: 10 actual: 5
	at <js>.:=>(IssueExample.js:27) ~[?:?]
	at knot/com.oracle.truffle.polyglot.PolyglotFunctionProxyHandler.invoke(PolyglotFunctionProxyHandler.java:151) ~[org_graalvm_truffle_truffle-api-24.0.2-995983b52bfdc5a1.jar:?]
	at knot/jdk.proxy2/jdk.proxy2.$Proxy61.invoke(Unknown Source) ~[?:?]
	at knot/net.ccbluex.liquidbounce.script.bindings.features.ScriptModule.callEvent(ScriptModule.kt:86) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.script.bindings.features.ScriptModule.hookHandler$lambda$2(ScriptModule.kt:126) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:213) ~[LiquidBounce.jar:?]
	at knot/net.ccbluex.liquidbounce.render.engine.UIRenderer.startUIOverlayDrawing(UIRenderer.kt:70) ~[LiquidBounce.jar:?]
	at knot/net.minecraft.class_329.handler$ccn000$liquidbounce$hookRenderEventStart(class_329.java:3583) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_55805(class_329.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55813(class_9080.java:36) [client-intermediary.jar:?]
	at knot/net.minecraft.class_9080.method_55809(class_9080.java:29) [client-intermediary.jar:?]
	at knot/net.minecraft.class_329.method_1753(class_329.java:218) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:896) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

(There is nothing more unexpected in the logs other than these exceptions' stacktraces)
```

### Screenshots

![image](https://github.com/user-attachments/assets/141d626c-f30b-4af5-af7c-e2e08a13c8ec)

**Comment by ayaxperson** [comment]
(I was asked to ping @commandblock2 here)

**Comment by ayaxperson** [comment]
Also, I forgot to mention that it usually seems to "want" the method with most parameters.

**Comment by commandblock2** [comment]
I do remember seeing this a few days ago, [Method Selection for graaljs](https://www.graalvm.org/latest/reference-manual/js/JavaInteroperability/#method-selection). I am not sure if this will help u, because the problem may involve remapping and the error is not found in the following doc. I will try this as soon as I build and run LiquidBounce.

**Comment by ayaxperson** [comment]
> I do remember seeing this a few days ago, [Method Selection for graaljs](https://www.graalvm.org/latest/reference-manual/js/JavaInteroperability/#method-selection). I am not sure if this will help u, because the problem may involve remapping and the error is not found in the following doc. I will try this as soon as I build and run LiquidBounce.

Haha, I can't get this syntax to even work, no matter how many arguments I specify. ¯\\_(ツ)_/¯

![image](https://github.com/user-attachments/assets/90ba9a39-1e31-4833-8350-64f449b1bccc)

**Comment by commandblock2** [comment]
I modified a bit of your script
```ts
    console.log(event);
    console.log(event.context);
    console.log(event.context.drawGuiTexture);
```
and found that the problem cannot be fully reproduced in a **develop envrionment** (LiquidBounce launched with gradle/idea), because the mapping might not be the same as the production environment? not sure at the moment.

For the first `IssueExample_drawGuiTexture` module, I was able to see a white squre on the screen but for the second `IssueExample_fill` I got a different exception.

```log
[00:36:56] [Render thread/INFO] (LiquidBounce) Successfully saved config 'modules'.
net.ccbluex.liquidbounce.event.events.OverlayRenderEvent@5eac67c9
net.minecraft.client.gui.DrawContext@1d86f20b
function () { [native code] }
[00:36:56] [Render thread/INFO] (Minecraft) [System] [CHAT] [method-selecting.js] IssueExample::IssueExample_drawGuiTexture::overlayRender threw [PolyglotException]: 
[00:36:56] [Render thread/ERROR] (LiquidBounce) IssueExample::IssueExample_drawGuiTexture -> Event Function overlayRender threw an error
 org.graalvm.polyglot.PolyglotException: null
```

I will try if I can reproduce this later tomorrow if I launch LB from a normal environment. btw I am using openjdk not the new default graalvm for this one, so not sure what what is happening. Hope this information could be useful for further deep dive.

**Comment by commandblock2** [comment]
Also a bit for the workaround, you can use the reflection api hack to try to call those functions, I have some old scripts, they are not built for the current api but the reflection code should function the same (didn't try tho). For example in this [old script made for script api v1 1.8.9 with out-dated Core.lib](https://github.com/commandblock2/scripts/blob/6d1b5c53c8b05beec82991350e3f5835681af895/misc/repl.js#L78), the code uses `getDeclaredField()` but should also be ok to use `getDeclaredMethod()`

**Comment by CzechHek** [comment]
Core has an utility called [Reflector](https://github.com/CzechHek/Core/blob/master/Core.lib#L424-L448) which remaps calls and calls methods which have matching parameter types, might be useful.

**Comment by ayaxperson** [comment]
Welp, I can see that I can get around this, but isn't it still a bug? So, shall I close the issue?

**Comment by commandblock2** [comment]
Also a correction, for `IssueExample_drawGuiTexture` in development environment I was able to get an Exception and the second `IssueExample_fill` I was able to see a white square on the screen, I thought one was the other and vice versa .

Later now that I can totally reproduce 2/2 of your problems in the production environment with the LBNG I just compiled. And your comment is indeed very right.

![image](https://github.com/user-attachments/assets/ad6ebc12-d4f9-4521-9950-8063d690c493)
![image](https://github.com/user-attachments/assets/3f2a3724-eb79-4313-bae0-9f4f4b51bbcb)

There might be a workaround but I would treat it as a bug or something, if I were u I would keep it open. Going to take a look at the remapper implementation and see if I could do anything.

**Comment by commandblock2** [comment]
Just in these two days I found there is indeed a built-in `RelfectionUtil` just made for scripting right now in LB. Before I was going to suggest using `ReflectionUtil.invokeMethod(event.context, "fill", 100, 100, 200, 200, -1);` I figured out that it's probably not working as indented right now as it
- probably can't match the null value
- filter the overload by parameter as intended

see https://github.com/CCBlueX/LiquidBounce/blob/1199618a72206fe7606a9e92212a5651c4d66876/src/main/kotlin/net/ccbluex/liquidbounce/script/bindings/api/ScriptReflectionUtil.kt#L71-L77
Will open a [separated issue](https://github.com/CCBlueX/LiquidBounce/issues/5030) for that tomorrow and possibly a PR.
