### ISSUE TITLE
[BUG] Implicit dependency on Fabric API

### ISSUE THREAD

**Issue by leumasme** [CCBlueX/LiquidBounce#4983]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.22.0

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

Liquidbounce uses Fabric API in 
https://github.com/CCBlueX/LiquidBounce/blob/e021ac06e8d95c1d55ead45d3cae45a4e7009f24/src/main/kotlin/net/ccbluex/liquidbounce/utils/client/SignTranslationFix.kt#L26
and possibly more places, but does not explicitly declare a dependency on Fabric API. This means that Liquidbounce will launch fine and work fine until code that requires Fabric API is executed, at which point it crashes.
Fabric API should be declared as an explicit dependency so that it will fail on launch and inform the user about the missing dependency, as is already done with Fabric Kotlin Language mod.

### Steps to reproduce

- Launch a liquidbounce instance with only the specified dependency: Fabric Kotlin Language
- Join a server that has a server resource pack
- Crash due to ClassNotFound for `net/fabricmc/fabric/api/resource/ModResourcePack`

### Client Log

```shell
[01:03:02] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/resource/ModResourcePack
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/resource/ModResourcePack
	at knot/net.ccbluex.liquidbounce.utils.client.VanillaTranslationRecognizer.shouldPreventLoad(SignTranslationFix.kt:26) ~[liquidbounce.jar:?]
	at knot/net.minecraft.class_1078.redirect$zbd000$liquidbounce$injectShit(class_1078.java:531) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1078.method_4675(class_1078.java:40) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1076.method_14491(class_1076.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.resource.ModResourcePack
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.ccbluex.liquidbounce.utils.client.VanillaTranslationRecognizer.shouldPreventLoad(SignTranslationFix.kt:26) ~[liquidbounce.jar:?]
	at knot/net.minecraft.class_1078.redirect$zbd000$liquidbounce$injectShit(class_1078.java:531) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1078.method_4675(class_1078.java:40) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1076.method_14491(class_1076.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 15 more
[01:03:02] [Render thread/INFO]: Reloading ResourceManager: vanilla
```

**Comment by 1zun4** [comment]
unlucky

**Comment by 1zun4** [comment]
It also seems that resources that are required will not be loaded without Fabric API present.

![image](https://github.com/user-attachments/assets/24895172-9be0-4e56-9c81-32458ae5b032)
