### ISSUE TITLE
[BUG] liquid bounce crashes while opening and gives me an error message

### ISSUE THREAD

**Issue by thenotpingo** [CCBlueX/LiquidBounce#5032]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.22.1

### Operating System

Windows 11

### Minecraft Version

all of them

### Describe the bug

i had just updatet to version 0.22.2  and simply went to launch liquid bounce but while opening the game crashed and gave me an error message

### Steps to reproduce

this happends every time i try to launch liquid bounce

### Client Log

```shell
Loading minecraft version manifest...Downloading recommended mod LiquidBounceDownloading recommended mod Fabric APIDownloading recommended mod Fabric KotlinLoading version profile...Downloading inherited version 1.21.4...Launching fe2bc6800c0f181e552a56169116ab0801360bd3...Setting up...Determined OS to be windows 10.0.22631Checking for JRE...Java Path: "C:\\Users\\NoahM\\AppData\\Roaming\\CCBlueX\\LiquidLauncher\\data\\runtimes\\temurin_21\\jdk-21.0.5 11-jre\\bin\\javaw.exe"Client JAR local hash: a7e5a6024bfd3cd614625aa05629adf760020304, remote: a7e5a6024bfd3cd614625aa05629adf760020304Checking libraries...Library com.fasterxml.jackson.core:jackson-core:2.13.4 already exists and SHA1 matches.Library com.fasterxml.jackson.core:jackson-annotations:2.13.4 already exists and SHA1 matches.Library org.ow2.asm:asm-analysis:9.7.1 already exists and SHA1 matches.Library org.ow2.asm:asm-tree:9.7.1 already exists and SHA1 matches.Library org.ow2.asm:asm:9.7.1 already exists and SHA1 matches.Library org.ow2.asm:asm-commons:9.7.1 already exists and SHA1 matches.Library org.ow2.asm:asm-util:9.7.1 already exists and SHA1 matches.Library net.fabricmc:fabric-loader:0.16.9 already exists and SHA1 matches.Library net.fabricmc:intermediary:1.21.4 already exists and SHA1 matches.Library net.fabricmc:sponge-mixin:0.15.4 mixin.0.8.7 already exists and SHA1 matches.Library com.fasterxml.jackson.core:jackson-databind:2.13.4.2 already exists and SHA1 matches.Library com.github.stephenc.jcip:jcip-annotations:1.0-1 already exists and SHA1 matches.Library com.google.guava:failureaccess:1.0.2 already exists and SHA1 matches.Library com.mojang:blocklist:1.0.10 already exists and SHA1 matches.Library com.google.guava:guava:33.3.1-jre already exists and SHA1 matches.Library com.github.oshi:oshi-core:6.6.5 already exists and SHA1 matches.Library com.google.code.gson:gson:2.11.0 already exists and SHA1 matches.Library com.ibm.icu:icu4j:76.1 already exists and SHA1 matches.Library com.microsoft.azure:msal4j:1.17.2 already exists and SHA1 matches.Library com.mojang:authlib:6.0.57 already exists and SHA1 matches.Library com.mojang:brigadier:1.3.10 already exists and SHA1 matches.Library com.mojang:logging:1.5.10 already exists and SHA1 matches.Library com.mojang:patchy:2.2.10 already exists and SHA1 matches.Library com.mojang:jtracy:1.0.29 already exists and SHA1 matches.Library com.nimbusds:content-type:2.3 already exists and SHA1 matches.Library com.mojang:jtracy:1.0.29:natives-windows already exists and SHA1 matches.Library com.mojang:text2speech:1.17.9 already exists and SHA1 matches.Library com.mojang:datafixerupper:8.0.16 already exists and SHA1 matches.Library com.nimbusds:nimbus-jose-jwt:9.40 already exists and SHA1 matches.Library com.nimbusds:lang-tag:1.7 already exists and SHA1 matches.Library com.nimbusds:oauth2-oidc-sdk:11.18 already exists and SHA1 matches.Library commons-io:commons-io:2.17.0 already exists and SHA1 matches.Library commons-logging:commons-logging:1.3.4 already exists and SHA1 matches.Library commons-codec:commons-codec:1.17.1 already exists and SHA1 matches.Library io.netty:netty-handler:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-codec:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-resolver:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-transport-classes-epoll:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-common:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-buffer:4.1.115.Final already exists and SHA1 matches.Library io.netty:netty-transport:4.1.115.Final already exists and SHA1 matches.Library it.unimi.dsi:fastutil:8.5.15 already exists and SHA1 matches.Library net.java.dev.jna:jna-platform:5.15.0 already exists and SHA1 matches.Library net.java.dev.jna:jna:5.15.0 already exists and SHA1 matches.Library net.sf.jopt-simple:jopt-simple:5.0.4 already exists and SHA1 matches.Library net.minidev:accessors-smart:2.5.1 already exists and SHA1 matches.Library org.apache.commons:commons-compress:1.27.1 already exists and SHA1 matches.Library org.apache.commons:commons-lang3:3.17.0 already exists and SHA1 matches.Library net.minidev:json-smart:2.5.1 already exists and SHA1 matches.Library io.netty:netty-transport-native-unix-common:4.1.115.Final already exists and SHA1 matches.Library org.apache.httpcomponents:httpclient:4.5.14 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-api:2.24.1 already exists and SHA1 matches.Library org.apache.httpcomponents:httpcore:4.4.16 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-core:2.24.1 already exists and SHA1 matches.Library org.apache.logging.log4j:log4j-slf4j2-impl:2.24.1 already exists and SHA1 matches.Library org.jcraft:jorbis:0.0.17 already exists and SHA1 matches.Library org.joml:joml:1.10.8 already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-freetype:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-glfw:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-jemalloc:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-opengl:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-openal:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-stb:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lz4:lz4-java:1.8.0 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl-tinyfd:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows-arm64 already exists and SHA1 matches.Library org.lwjgl:lwjgl:3.3.3:natives-windows-x86 already exists and SHA1 matches.Library org.ow2.asm:asm:9.6 already exists and SHA1 matches.Library org.slf4j:slf4j-api:2.0.16 already exists and SHA1 matches.Checking assets...Launching...Running...Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/NoahM/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/NoahM/AppData/Roaming/CCBlueX/LiquidLauncher/data/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar!/org/objectweb/asm/ClassReader.class
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
	at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
	... 1 more
An error occured:

Process exited with non-zero exit code: 1.
```

### Screenshots

![image](https://github.com/user-attachments/assets/3fae2815-9fcf-42d5-92a8-e4d79711aabe)

**Comment by 1zun4** [comment]
Do not use Nightly. The faulty 1.21.4 builds were now removed from the launcher and are now back on 1.21.1.

**Comment by 1zun4** [comment]
@superblaubeere27 In the future, please do not merge PRs that change the Minecraft version, for example. These are guaranteed to cause problems if not tested in non-development workspaces...

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidLauncher/releases/tag/v0.4.0
