### ISSUE TITLE
[BUG] Crash on Nightly (BoundedInputStream.builder() missing)

### ISSUE THREAD

**Issue by mcgamer48ft** [CCBlueX/LiquidBounce#5037]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

v0.22.1 (commit #5031)

### Operating System

Linux

### Minecraft Version

1.21.4

### Describe the bug

Liquidbounce crashes when finished downloading "mcef"

### Steps to reproduce

- Use Fedora 41 (Linux)
- Run minecraft with Liquidbounce, Fabric API, Fabric Language Kotlin, ViaFabricPlus
- Start downloading JCEF/MCEF
- Crash when done extracting.

### Client Log

```shell
[21:02:50] [mcef-downloader/INFO]: [Downloading JCEF] Progress 100%
[21:02:50] [mcef-downloader/INFO]: [Comparing Checksum] Started task
[21:02:50] [mcef-downloader/INFO]: [Comparing Checksum] Started task
[21:02:51] [mcef-downloader/INFO]: [Comparing Checksum] Finished task
[21:02:51] [mcef-downloader/INFO]: Extracting JCEF...
[21:02:51] [mcef-downloader/INFO]: [Extracting] Started task
[21:02:51] [mcef-downloader/INFO]: [Extracting] Finished task
[21:02:51] [mcef-downloader/ERROR]: Fatal error
java.lang.NoSuchMethodError: 'org.apache.commons.io.input.BoundedInputStream$Builder org.apache.commons.io.input.BoundedInputStream.builder()'
	at knot/org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:155) ~[commons-compress-1.27.1.jar:?]
	at knot/org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:139) ~[commons-compress-1.27.1.jar:?]
	at knot/net.ccbluex.liquidbounce.mcef.MCEFResourceManager.extractTarGz(MCEFResourceManager.java:276) ~[mcef-1.3.0-1.21.4-21feca4e97183d50.jar:?]
	at knot/net.ccbluex.liquidbounce.mcef.MCEFResourceManager.downloadJcef(MCEFResourceManager.java:147) ~[mcef-1.3.0-1.21.4-21feca4e97183d50.jar:?]
	at knot/net.ccbluex.liquidbounce.integration.browser.supports.JcefBrowser.makeDependenciesAvailable$lambda$4(JcefBrowser.kt:76) ~[liquidbounce.jar:?]
	at knot/kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [org_jetbrains_kotlin_kotlin-stdlib-2.1.0-4bc6dcd88c5d18b9.jar:?]
```

**Comment by 1zun4** [comment]
Do not use Nightly.
