### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by killme990** [CCBlueX/LiquidBounce#537]
**Describe the bug**

**To Reproduce**
1. download viafabric kotlin latest nighty of liquidbounce multiconnect
2. install in mods folder 1.16.5 no other mods
3. fire up fabric 1.16.5

**Additional information:**
 - OS: mac osx 11.1
 - LiquidBounce Build Version fbb9ee1
 - Minecraft Version 1.16.5
log file

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/20/21 10:49 AM
Description: Initializing game

kotlin.UninitializedPropertyAccessException: lateinit property lockedOnThread has not been initialized
	at net.ccbluex.liquidbounce.utils.client.ThreadLock.get(ThreadLock.java:27)
	at net.ccbluex.liquidbounce.render.ultralight.View.<init>(View.java:57)
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.newSplashView(UltralightEngine.java:152)
	at net.minecraft.class_425.handler$zgn000$hookSplashInit(class_425.java:556)
	at net.minecraft.class_425.<init>(class_425.java:53)
	at net.minecraft.class_310.<init>(class_310.java:585)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ccbluex.liquidbounce.utils.client.ThreadLock.get(ThreadLock.java:27)
	at net.ccbluex.liquidbounce.render.ultralight.View.<init>(View.java:57)
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.newSplashView(UltralightEngine.java:152)
	at net.minecraft.class_425.handler$zgn000$hookSplashInit(class_425.java:556)
	at net.minecraft.class_425.<init>(class_425.java:53)
	at net.minecraft.class_310.<init>(class_310.java:585)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1437288920 bytes (1370 MB) / 1879048192 bytes (1792 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Apple M1 GL version 2.1 Metal - 71.0.7, Apple
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Apple M1

**Comment by BobIsMyManager** [comment]
Liquidbounce nextgen only supports windows as of now but will support macOS and Linux before the release

**Comment by killme990** [comment]
assholes java is cross compatable wtf are you talking about bitch???? tryna backdoor my computer fuck you!!!!!!

**Comment by mems01** [comment]
i'd like to see 1zuna shutting this guy's mouth either the respectable way or the worst way possible

**Comment by 1zun4** [comment]
@killme990 Nextgen uses native dependencies, because of our ultralight implemention and the path system is slightly different on macOS and Linux.
You can always review the code yourself, there is no backdoor or anything else.
Using Java doesn't mean every program will work on every OS. That's not how it works.

**Comment by killme990** [comment]
lmao backdoor

**Comment by killme990** [comment]
thats bullshit java is cross compatable with alll systems with java installed

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
i have 2 mil subs
ill expose ur ass
!

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by killme990** [comment]
BACKDOOOOOOOR

**Comment by Teals53** [comment]
wtf

**Comment by mems01** [comment]
yeah he's an idiot don't worry

**Comment by Teals53** [comment]
lmao

**Comment by SenkJu** [comment]
Banned from interacting with this organisation.

**Comment by mems01** [comment]
some people man... they have the audacity to say all that...

**Comment by leumasme** [comment]
```
i have 2 mil subs
ill expose ur ass
!
```

Tell me that's not sarcasm

**Comment by mems01** [comment]
ha, people with 2 mil subs would be way more chill and patient

**Comment by BobIsMyManager** [comment]
Exactly

**Comment by superblaubeere27** [comment]
> 
> 
> BACKDOOOOOOOR

I am worried about @killme990 mental health.

**Comment by BobIsMyManager** [comment]
Lol

**Comment by ENDER1355** [comment]
> > BACKDOOOOOOOR
> 
> I am worried about @killme990 mental health.

me too
