### ISSUE TITLE
[BUG] freeze on game load in NextGen

### ISSUE THREAD

**Issue by TheBlocky** [CCBlueX/LiquidBounce#583]
### LiquidBounce Build/Version

Next-Gen latest nightly build

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

I loaded the game, and it instantly stopped responding. There was no error, just a few warns in logs, it just stopped.

### Steps to reproduce

- Start the game
- Wait until it stops responding

### Client Log

```shell
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/i3/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
Compatibility level set to JAVA_16
@Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
Setting user: BlockMiner008
@Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[Indigo] Registering Indigo renderer!
Invalid floating point value for option textBackgroundOpacity = 
java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:556)
	at net.minecraft.class_315$2.method_33678(class_315.java:408)
	at net.minecraft.class_315.method_33666(class_315.java:286)
	at net.minecraft.class_315.method_1636(class_315.java:366)
	at net.minecraft.class_315.<init>(class_315.java:223)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Narrator library for x64 successfully loaded
Launching LiquidBounce v1.0.0 by CCBlueX
Successfully extracted default theme
Loading heads...
Successfully loaded 956 heads from the database
Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
Loading ultralight...
Checking resources...
Successfully loaded ultralight!
Successfully loaded config 'enemies'.
Successfully loaded config 'modules'.
Successfully loaded config 'commands'.
Successfully loaded config 'friends'.
Successfully loaded config 'proxies'.
Successfully loaded config 'chat'.
Successfully loaded config 'fonts'.
(Chat) §8[§9§lLiquidBounce§8] §7[§a§lChat§7]
(Chat) §8[§9§lLiquidBounce§8] §7[§a§lChat§7]
```

**Comment by ENDER1355** [comment]
https://www.reddit.com/r/minecraftclients/comments/om2omy/jvm_arguments_for_crashing_clients/

**Comment by commandblock2** [comment]
I have the same problem when I was trying to launch LiquidBounce from idea (with an cracked account), in my case, it seemed to stuck at trying to connecting to connecting to the IRC server. After I deleted [that line](https://github.com/CCBlueX/LiquidBounce/blob/264bc4c4bebc7a8a753f5f77bd8df37df84489e0/src/main/kotlin/net/ccbluex/liquidbounce/LiquidBounce.kt#L114) it launched successfully. Idk if this is relevant to your case, but it could be very nice if we can have a timeout for that.

**Comment by ENDER1355** [comment]
> I have the same problem when I was trying to launch LiquidBounce from idea (with an cracked account), in my case, it seemed to stuck at trying to connecting to connecting to the IRC server. After I deleted [that line](https://github.com/CCBlueX/LiquidBounce/blob/264bc4c4bebc7a8a753f5f77bd8df37df84489e0/src/main/kotlin/net/ccbluex/liquidbounce/LiquidBounce.kt#L114) it launched successfully. Idk if this is relevant to your case, but it could be very nice if we can have a timeout for that.

u need a premium account for IRC

**Comment by ghost** [comment]
Should be fixed now, thanks to this [commit.](https://github.com/CCBlueX/LiquidBounce/commit/014ba8689801ec4b137faf497bd7afd3c8203bd6)

**Comment by superblaubeere27** [comment]
Fixed
