### ISSUE TITLE
[BUG] nextgen main menu is closing

### ISSUE THREAD

**Issue by SpoilerRules** [CCBlueX/LiquidBounce#609]
### LiquidBounce Build/Version

Nextgen: 220596c

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

main menu is being reverted to normal 1.17.1 main menu when i press esc in liquidbounce main menu

### Steps to reproduce

1. open liquidbounce main menu
2. press esc

### Client Log

```shell
[15:16:37] [main/INFO]: Loading for game Minecraft 1.17.1
[15:16:37] [main/INFO]: [FabricLoader] Loading 58 mods:
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b446318
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.2+kotlin.1.5.20
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- java@16
	- liquidbounce@1.0.0
	- minecraft@1.17.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.20
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
[15:16:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/MSI/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[15:16:38] [main/INFO]: Compatibility level set to JAVA_16
[15:16:38] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[15:16:41] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:16:42] [Render thread/INFO]: Setting user: no nickname for u
[15:16:42] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:16:42] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[15:16:43] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:16:45] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\MSI\AppData\Roaming\.minecraft\versions\fabric-loader-0.11.6-1.17.1\fabric-loader-0.11.6-1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.args$zee000$setupIcon(class_310.java:5167) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[15:16:46] [Render thread/INFO]: Narrator library for x64 successfully loaded
[15:16:46] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[15:16:46] [Render thread/INFO]: Successfully extracted default theme
[15:16:46] [Render thread/INFO]: Loading heads...
[15:16:47] [Render thread/INFO]: Successfully loaded 956 heads from the database
[15:16:47] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[15:16:47] [Render thread/INFO]: Loading ultralight...
[15:16:47] [Render thread/INFO]: Checking resources...
[15:16:47] [Render thread/INFO]: Successfully loaded ultralight!
[15:16:48] [Render thread/INFO]: Successfully loaded config 'enemies'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'modules'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'commands'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'friends'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'proxies'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'chat'.
[15:16:48] [Render thread/INFO]: Successfully loaded config 'fonts'.
[15:16:48] [Render thread/INFO]: Successfully loaded client!
[15:16:48] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[15:16:48] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, LiquidBounce, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[15:16:48] [Render thread/INFO]: [MainFrame 3 (file:///C:/Users/MSI/AppData/Roaming/LiquidBounceLatest-NextGen/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[15:16:49] [IO-Worker-8/INFO]: Successfully connected to LiquidChat!
[15:16:49] [IO-Worker-8/INFO]: Requesting to login into Mojang...
[15:16:50] [Render thread/INFO]: [MainFrame 5 (file:///C:/Users/MSI/AppData/Roaming/LiquidBounceLatest-NextGen/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[15:16:51] [Render thread/INFO]: OpenAL initialized.
[15:16:51] [Render thread/INFO]: Sound engine started
[15:16:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:16:51] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:16:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:16:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:16:51] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:16:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:16:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:16:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:16:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:16:56] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:16:56] [Render thread/INFO]: [MainFrame 1 (file:///C:/Users/MSI/AppData/Roaming/LiquidBounceLatest-NextGen/LiquidBounce/themes/default/hud/index.html)]: The view finished loading
[15:17:05] [Render thread/INFO]: Shutting down client...
[15:17:05] [Render thread/INFO]: Successfully saved config 'enemies'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'modules'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'commands'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'friends'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'proxies'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'chat'.
[15:17:05] [Render thread/INFO]: Successfully saved config 'fonts'.
[15:17:05] [Render thread/INFO]: Stopping!
```

**Comment by 1zun4secondary** [comment]
Duplicate of https://github.com/CCBlueX/LiquidBounce/issues/471, but I keep this one open and close the old issue.
