### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by f4r2** [CCBlueX/LiquidBounce#613]
### LiquidBounce Build/Version

b73

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

Im try to run LiquidBounce from idea but i get this error:

Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraftforge.gradle.GradleForgeHacks.searchCoremods(GradleForgeHacks.java:87)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:86)
	at GradleStart.main(GradleStart.java:26)

### Steps to reproduce

I im trying to run LiquidBounce with idea
But when it running i get error

### Client Log

```shell
[21:58:55] [main/INFO]: Extra: []
Yes its all log
```

### Screenshots

![Screenshot_20210806_220116](https://user-images.githubusercontent.com/55927996/128559313-e3502208-3faa-4da3-8ad0-7a318455cf4d.png)

**Comment by 1zun4secondary** [comment]
Maybe try to use JDK 1.8, not JDK 16.
