### ISSUE TITLE
[BUG] The background from LiquidBounce in the minecraft menu disappears. 

### ISSUE THREAD

**Issue by majjestro** [CCBlueX/LiquidBounce#618]
### LiquidBounce Build/Version

NextGen - 56158d0

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

When starting minecraft, the custom background of the game menu may not load. This has been seen in earlier builds as well. 
Video in the Minecraft: https://imgur.com/a/vHLQpL8

### Steps to reproduce

- Start minecraft.

### Client Log

```shell
[20:20:10] [main/INFO]: Loading for game Minecraft 1.17.1
[20:20:10] [ForkJoinPool-1-worker-7/WARN]: Non-Fabric mod JAR at "C:\Users\HelloWorld\AppData\Roaming\.minecraft\mods\Infinity-0.14.2.jar", ignoring
[20:20:11] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b446318
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b446313, also found 0.1.5+a02b446318
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b446318, also found 0.1.13+a02b446313
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
[20:20:11] [main/INFO]: [FabricLoader] Loading 62 mods:
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- java@16
	- liquidbounce@1.0.0
	- minecraft@1.17.1
	- modmenu@2.0.4
	- multiconnect@1.4.11
	- multiconnect-api@1.4.11
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- sodium@0.3.0+build.5
[20:20:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/HelloWorld/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[20:20:12] [main/INFO]: Compatibility level set to JAVA_16
[20:20:12] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[20:20:13] [main/WARN]: @Mixin target net/minecraft/class_631$class_3681 is public in sodium.mixins.json:features.chunk_rendering.MixinClientChunkManager$MixinClientChunkMap and should be specified in value
[20:20:13] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[20:20:13] [main/WARN]: @Mixin target net/minecraft/class_5120$class_5121 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[20:20:14] [main/WARN]: @Mixin target net/minecraft/class_702$class_4090 is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[20:20:14] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[20:20:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:20:32] [Render thread/INFO]: Setting user: BlockyBuddha
[20:20:32] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zjp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:20:33] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[20:20:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[20:20:36] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\HelloWorld\AppData\Roaming\.minecraft\versions\fabric-loader-0.11.6-1.17.1\fabric-loader-0.11.6-1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.args$zeh000$setupIcon(class_310.java:4167) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[20:20:38] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:20:38] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[20:20:40] [Render thread/INFO]: Successfully extracted default theme
[20:20:40] [Render thread/INFO]: Loading heads...
[20:20:41] [Render thread/INFO]: Successfully loaded 956 heads from the database
[20:20:43] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[20:20:43] [Render thread/INFO]: Loading ultralight...
[20:20:43] [Render thread/INFO]: Checking resources...
[20:20:43] [Render thread/INFO]: Successfully loaded ultralight!
[20:20:44] [Render thread/INFO]: Successfully loaded config 'enemies'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'modules'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'commands'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'friends'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'proxies'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'chat'.
[20:20:44] [Render thread/INFO]: Successfully loaded config 'fonts'.
[20:20:44] [Render thread/INFO]: Successfully loaded client!
[20:20:44] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[20:20:44] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), MultiConnect API, Fabric Loader, Fabric Structure API (v1), LiquidBounce, Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), MultiConnect, Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Sodium, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0))
[20:20:45] [Thread-97/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[20:20:45] [Thread-97/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[20:20:45] [Render thread/INFO]: [MainFrame 3 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[20:20:46] [IO-Worker-8/INFO]: Successfully connected to LiquidChat!
[20:20:46] [IO-Worker-8/INFO]: Requesting to login into Mojang...
[20:20:47] [Thread-117/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[20:20:47] [Thread-117/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[20:20:47] [Thread-132/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[20:20:47] [Thread-132/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[20:20:47] [Thread-192/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[20:20:47] [Thread-192/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[20:20:49] [Render thread/INFO]: [MainFrame 1 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/hud/index.html)]: The view finished loading
[20:20:49] [Render thread/INFO]: [MainFrame 5 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:20:51] [Render thread/INFO]: OpenAL initialized.
[20:20:51] [Render thread/INFO]: Sound engine started
[20:20:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:20:51] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:20:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:20:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:20:51] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:20:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:20:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:21:02] [Render thread/INFO]: [MainFrame 7 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:21:04] [Render thread/INFO]: View message: [JS/ERROR] file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/build/bundle.js:1:20450: TypeError: minecraft.scheduleStop is not a function. (In 'minecraft.scheduleStop()', 'minecraft.scheduleStop' is undefined)
[20:24:55] [Render thread/INFO]: [MainFrame 9 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[20:25:00] [Render thread/INFO]: View message: [JS/ERROR] file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html:169:36: TypeError: null is not an object (evaluating 'document.getElementById('response').innerText = client.getSessionService().loginCracked(document.getElementById('username').value)')
[20:25:00] [Render thread/INFO]: View message: [JS/ERROR] file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html:169:36: TypeError: null is not an object (evaluating 'document.getElementById('response').innerText = client.getSessionService().loginCracked(document.getElementById('username').value)')
[20:25:01] [Render thread/INFO]: [MainFrame 11 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:08] [Render thread/INFO]: [MainFrame 13 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:09] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.987 ms
[20:25:09] [Render thread/INFO]: [MainFrame 15 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:12] [Render thread/INFO]: [MainFrame 17 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:13] [Render thread/INFO]: [MainFrame 19 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:15] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 221.1 ?s
[20:25:15] [Render thread/INFO]: [MainFrame 21 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:17] [Render thread/INFO]: [MainFrame 23 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:17] [Render thread/INFO]: [MainFrame 25 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:18] [Render thread/INFO]: [MainFrame 27 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:33] [Render thread/INFO]: [MainFrame 29 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:34] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 284.9 ?s
[20:25:35] [Render thread/INFO]: [MainFrame 31 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:41] [Render thread/INFO]: [MainFrame 33 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:54] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 273.2 ?s
[20:25:54] [Render thread/INFO]: [MainFrame 35 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:57] [Render thread/INFO]: [MainFrame 37 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[20:25:59] [Render thread/INFO]: [MainFrame 39 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
```

**Comment by ghost** [comment]
Weird, that does not occur to me at all. Can you show us maybe what video settings have you used?

**Comment by majjestro** [comment]
I was able to cause this bug again by clicking in some areas when loading Minecraft. At the very start, I had the creation of a single world, and when I left there, there was no background in the minecraft menu. 
Video settings: https://imgur.com/a/42vOJ9E

**Comment by ghost** [comment]
Are you using a minecraft launcher like MultiMC or something or are you loading it via Intellij IDEA? Because if I'm not wrong, LiquidBounce Nextgen currently doesn't have this kind of settings. Mine looks like this: 
![Base Profile Screenshot 2021 08 10 - 13 25 31 81](https://user-images.githubusercontent.com/70612656/128851321-eb09fba4-9d61-49c4-88d4-18257b4f8006.png)

**Comment by majjestro** [comment]
It's a Sodium mod.

**Comment by majjestro** [comment]
For launch minecraft i am using original Minecraft Launcher.

**Comment by ghost** [comment]
Can you remove those kind of mods and try again?

**Comment by majjestro** [comment]
I will check this later.
