### ISSUE TITLE
[BUG] Black screen when interacting with Alt Manager

### ISSUE THREAD

**Issue by majjestro** [CCBlueX/LiquidBounce#622]
### LiquidBounce Build/Version

NextGen - 56158d0

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

As usual, I went to minecraft, then to the server, left the server, wanted to change my account, and when I clicked on Alt Manager, a black screen appears instead. To see the screen again, I pressed F11 and everything was displayed, but when exiting Alt Manager, a black screen also appears, which is treated in this way. 

### Steps to reproduce

- Go to Minecraft
- Go to a random server
- Quit from a server
- Click on Alt Manager 

### Client Log

```shell
[09:11:35] [main/INFO]: Loading for game Minecraft 1.17.1
[09:11:36] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b446318
 - Conflicting versions found for fabric-rendering-data-attachment-v1: used 0.1.5+a02b446313, also found 0.1.5+a02b446318
 - Conflicting versions found for fabric-rendering-fluids-v1: used 0.1.13+a02b446318, also found 0.1.13+a02b446313
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
[09:11:36] [main/INFO]: [FabricLoader] Loading 62 mods:
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- java@16
	- liquidbounce@1.0.0
	- minecraft@1.17.1
	- modmenu@2.0.4
	- multiconnect@1.4.11
	- multiconnect-api@1.4.11
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- sodium@0.3.0+build.5
[09:11:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/HelloWorld/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[09:11:36] [main/INFO]: Compatibility level set to JAVA_16
[09:11:36] [main/INFO]: Loaded configuration file for Sodium: 28 options available, 0 override(s) found
[09:11:36] [main/WARN]: @Mixin target net/minecraft/class_631$class_3681 is public in sodium.mixins.json:features.chunk_rendering.MixinClientChunkManager$MixinClientChunkMap and should be specified in value
[09:11:37] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[09:11:37] [main/WARN]: @Mixin target net/minecraft/class_5120$class_5121 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[09:11:37] [main/WARN]: @Mixin target net/minecraft/class_702$class_4090 is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[09:11:37] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[09:11:46] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:11:48] [Render thread/INFO]: Setting user: BlockyBuddha
[09:11:48] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zjp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[09:11:50] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[09:11:50] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[09:11:56] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\HelloWorld\AppData\Roaming\.minecraft\versions\fabric-loader-0.11.6-1.17.1\fabric-loader-0.11.6-1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.args$zeh000$setupIcon(class_310.java:4167) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[09:11:58] [Render thread/INFO]: Narrator library for x64 successfully loaded
[09:11:58] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[09:12:00] [Render thread/INFO]: Successfully extracted default theme
[09:12:00] [Render thread/INFO]: Loading heads...
[09:12:01] [Render thread/INFO]: Successfully loaded 956 heads from the database
[09:12:04] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[09:12:04] [Render thread/INFO]: Loading ultralight...
[09:12:04] [Render thread/INFO]: Checking resources...
[09:12:04] [Render thread/INFO]: Successfully loaded ultralight!
[09:12:05] [Render thread/INFO]: Successfully loaded config 'enemies'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'modules'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'commands'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'friends'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'proxies'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'chat'.
[09:12:05] [Render thread/INFO]: Successfully loaded config 'fonts'.
[09:12:05] [Render thread/INFO]: Successfully loaded client!
[09:12:05] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[09:12:06] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), MultiConnect API, Fabric Loader, LiquidBounce, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), MultiConnect, Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Sodium, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Language Kotlin, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[09:12:06] [Thread-97/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[09:12:06] [Thread-97/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[09:12:06] [Render thread/INFO]: [MainFrame 3 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[09:12:08] [IO-Worker-8/INFO]: Successfully connected to LiquidChat!
[09:12:08] [IO-Worker-8/INFO]: Requesting to login into Mojang...
[09:12:09] [Thread-117/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[09:12:09] [Thread-117/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[09:12:09] [Thread-132/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[09:12:09] [Thread-132/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[09:12:11] [Thread-192/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[09:12:11] [Thread-192/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[09:12:11] [Render thread/INFO]: OpenAL initialized.
[09:12:11] [Render thread/INFO]: Sound engine started
[09:12:12] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[09:12:12] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[09:12:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:12:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:12:12] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:12:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:12:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:12:15] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[09:12:15] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:12:15] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:12:16] [Render thread/INFO]: [MainFrame 1 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/hud/index.html)]: The view finished loading
[09:12:16] [Render thread/INFO]: [MainFrame 5 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:12:30] [Render thread/INFO]: Connecting to 217.106.107.160, 28373
[09:12:31] [Server Connector #1/INFO]: Protocol version forced to 340 (1.12.2)
[09:12:39] [Netty Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 2.442 ms
[09:12:39] [Netty Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.055 ms
[09:12:39] [Netty Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 313.2 ?s
[09:12:40] [Render thread/INFO]: Started 8 worker threads
[09:12:40] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:12:41] [Render thread/INFO]: [CHAT] Welcome back BlockyBuddha this motd supports placeholders from placeholderapi!
[09:12:41] [Render thread/INFO]: [CHAT] [Server] hello BlockyBuddha
[09:12:41] [Render thread/INFO]: [CHAT] Please register using /register <password>
[09:12:43] [Render thread/INFO]: [CHAT] You do not have access to that command.
[09:12:48] [Render thread/INFO]: [CHAT] Please register using /register <password>
[09:12:51] [Render thread/INFO]: [CHAT] Successfully registered, you are now logged in.
[09:13:00] [Render thread/INFO]: Stopping worker threads
[09:13:01] [Render thread/INFO]: [MainFrame 7 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:03] [Render thread/INFO]: [MainFrame 9 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:13:06] [Render thread/INFO]: [MainFrame 11 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:08] [Render thread/INFO]: [MainFrame 13 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:08] [Render thread/INFO]: [MainFrame 15 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:09] [Render thread/INFO]: [MainFrame 17 ()]: The view finished loading
[09:13:09] [Render thread/INFO]: [MainFrame 19 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:13] [Render thread/INFO]: [MainFrame 21 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:13:15] [Render thread/INFO]: [MainFrame 23 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:16] [Render thread/INFO]: [MainFrame 25 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:19] [Render thread/INFO]: [MainFrame 27 ()]: The view finished loading
[09:13:19] [Render thread/INFO]: [MainFrame 29 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:23] [Render thread/INFO]: [MainFrame 31 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:23] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 359.7 ?s
[09:13:24] [Render thread/INFO]: [MainFrame 33 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:28] [Render thread/INFO]: [MainFrame 35 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:29] [Render thread/INFO]: [MainFrame 37 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:13:30] [Render thread/INFO]: [MainFrame 39 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:30] [Render thread/INFO]: [MainFrame 41 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:31] [Render thread/INFO]: [MainFrame 43 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:31] [Render thread/INFO]: [MainFrame 45 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:31] [Render thread/INFO]: [MainFrame 47 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:31] [Render thread/INFO]: [MainFrame 49 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:32] [Render thread/INFO]: [MainFrame 51 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:32] [Render thread/INFO]: [MainFrame 53 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:32] [Render thread/INFO]: [MainFrame 55 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:32] [Render thread/INFO]: [MainFrame 57 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:33] [Render thread/INFO]: [MainFrame 59 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:33] [Render thread/INFO]: [MainFrame 61 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:33] [Render thread/INFO]: [MainFrame 63 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:33] [Render thread/INFO]: [MainFrame 65 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:34] [Render thread/INFO]: [MainFrame 67 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:34] [Render thread/INFO]: [MainFrame 69 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:38] [Render thread/INFO]: [MainFrame 71 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:40] [Render thread/INFO]: [MainFrame 73 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:43] [Render thread/INFO]: [MainFrame 75 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:43] [Render thread/INFO]: [MainFrame 77 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:43] [Render thread/INFO]: [MainFrame 79 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:43] [Render thread/INFO]: [MainFrame 81 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:44] [Render thread/INFO]: [MainFrame 83 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:46] [Render thread/INFO]: [MainFrame 85 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:47] [Render thread/INFO]: [MainFrame 87 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:47] [Render thread/INFO]: [MainFrame 89 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:47] [Render thread/INFO]: [MainFrame 91 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:13:48] [Render thread/INFO]: [MainFrame 93 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:07] [Render thread/INFO]: [MainFrame 95 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:14:08] [Render thread/INFO]: [MainFrame 97 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:08] [Render thread/INFO]: [MainFrame 99 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:13] [Render thread/INFO]: [MainFrame 101 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:13] [Render thread/INFO]: [MainFrame 103 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:14] [Render thread/INFO]: [MainFrame 105 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:14] [Render thread/INFO]: [MainFrame 107 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:14] [Render thread/INFO]: [MainFrame 109 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:14] [Render thread/INFO]: [MainFrame 111 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:14] [Render thread/INFO]: [MainFrame 113 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:22] [Render thread/INFO]: [MainFrame 115 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:22] [Render thread/INFO]: [MainFrame 117 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:22] [Render thread/INFO]: [MainFrame 119 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:22] [Render thread/INFO]: [MainFrame 121 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:22] [Render thread/INFO]: [MainFrame 123 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:26] [Render thread/INFO]: [MainFrame 125 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:14:28] [Render thread/INFO]: [MainFrame 127 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:14:33] [Render thread/INFO]: [MainFrame 129 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:14:33] [Render thread/INFO]: [MainFrame 131 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:16:55] [Render thread/INFO]: [MainFrame 133 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:16:59] [Render thread/INFO]: [MainFrame 135 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:17:07] [Render thread/INFO]: [MainFrame 137 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[09:17:11] [nioEventLoopGroup-2-1/INFO]: [Chat] apokodIstLegit: fuck down syndromers (gaymer)
[09:20:11] [Render thread/INFO]: [MainFrame 139 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/altmanager/index.html)]: The view finished loading
[09:20:13] [Render thread/INFO]: [MainFrame 141 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
```

### Screenshots

Video: https://imgur.com/a/AmJOI8E

**Comment by ghost** [comment]
Have you tried updating your GPU driver? If not, please do it.

**Comment by majjestro** [comment]
This bug appears when installing the mod Sodium 0.3.0 build 5

**Comment by ghost** [comment]
The issue is fixed: https://github.com/CCBlueX/LiquidBounce/commit/3845eeef3e8bc1ea9b242025cd5548c33be15294
