### ISSUE TITLE
[BUG] AutoTool сompatibility with Anti-Cheats.

### ISSUE THREAD

**Issue by majjestro** [CCBlueX/LiquidBounce#630]
### LiquidBounce Build/Version

NextGen - 56158d0

### Operating System

Windows 10

### Minecraft Version

1.12.2

### Describe the bug

When using AutoTool on a server with anti-cheat (for example, NoCheatPlus), it displays the following messages in the console:
[NoCheatPlus] BlockyBuddha failed WrongBlock: broke another block than clicked. VL 30.
[NoCheatPlus] (CONSOLE) Kicked BlockyBuddha: Block breaking out of sync! 

### Steps to reproduce

- Join on server with Anti-Cheat (tested on NoCheatPlus).
- Enable AutoTool.
- Go to mining.

### Client Log

```shell
[11:00:05] [main/INFO]: Loading for game Minecraft 1.17.1
[11:00:05] [ForkJoinPool-1-worker-5/WARN]: Non-Fabric mod JAR at "C:\Users\HelloWorld\AppData\Roaming\.minecraft\mods\antighost-1.17.1-forge37.0.13-1.1.2.jar", ignoring
[11:00:05] [ForkJoinPool-1-worker-9/WARN]: Non-Fabric mod JAR at "C:\Users\HelloWorld\AppData\Roaming\.minecraft\mods\Infinity-0.14.2.jar", ignoring
[11:00:06] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
 - Mod 'BetterF3' (betterf3) recommends version 2.0.0.* of mod 'Mod Menu' (modmenu), but a non-matching version is present: 2.0.4!
	 - You must install version 2.0.0.* of 'Mod Menu' (modmenu).
	 - Mod 'Mod Menu' (modmenu) v2.0.4 is being loaded from the user's mod directory.
[11:00:06] [main/INFO]: [FabricLoader] Loading 76 mods:
	- appleskin@mc1.17-2.1.3
	- architectury@2.3.24
	- betterf3@1.1.5
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- clumps@fabric-1.17.1-7.0.4
	- enchantmentdescriptions@4.0.1
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- horsestatsvanilla@4.1.8
	- inventoryhud@3.3.2
	- itemscroller@0.15.0-dev.20210707.005506
	- jankson@3.0.1+j1.2.0
	- java@16
	- libgui@4.0.0-beta.4+1.17-rc1
	- libninepatch@1.1.0
	- liquidbounce@1.0.0
	- malilib@0.10.0-dev.24
	- minecraft@1.17.1
	- modmenu@2.0.4
	- multiconnect@1.4.12
	- multiconnect-api@1.4.12
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- roughlyenoughitems@6.0.267-alpha
[11:00:06] [main/WARN]: Mod `clumps` (fabric-1.17.1-7.0.4) does not respect SemVer - comparison support is limited.
[11:00:06] [main/WARN]: Mod `appleskin` (mc1.17-2.1.3) does not respect SemVer - comparison support is limited.
[11:00:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/HelloWorld/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[11:00:06] [main/INFO]: Compatibility level set to JAVA_16
[11:00:07] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[11:00:07] [main/WARN]: @Mixin target net/minecraft/class_5120$class_5121 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[11:00:07] [main/WARN]: @Mixin target net/minecraft/class_702$class_4090 is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[11:00:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:00:18] [Render thread/INFO]: Setting user: BlockyBuddha
[11:00:18] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$znc000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[11:00:19] [Render thread/INFO]: Config loaded.
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[11:00:19] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[11:00:20] [Render thread/WARN]: WARNING! Mod horsestatsvanilla is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[11:00:20] [Render thread/WARN]: WARNING! Mod jankson is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[11:00:20] [Render thread/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[11:00:20] [Render thread/WARN]: WARNING! Mod enchantmentdescriptions is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[11:00:20] [Render thread/WARN]: WARNING! Mod architectury is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[11:00:20] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[11:00:20] [Render thread/INFO]: Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIClientPlugin
[11:00:20] [Render thread/INFO]: Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIClientPlugin
[11:00:21] [Render thread/INFO]: [STDOUT]: Inventory HUD + has been initialized!
[11:00:21] [Render thread/INFO]: [BetterF3] Loading...
[11:00:21] [Render thread/INFO]: [BetterF3] All done!
[11:00:21] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity = 
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:556) ~[?:?]
	at net.minecraft.class_315$2.method_33678(class_315.java:408) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_315.method_33666(class_315.java:286) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_315.method_1636(class_315.java:366) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_315.<init>(class_315.java:223) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:459) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[11:00:21] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[11:00:30] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\HelloWorld\AppData\Roaming\.minecraft\versions\fabric-loader-0.11.6-1.17.1\fabric-loader-0.11.6-1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.args$zgj000$setupIcon(class_310.java:5667) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[11:00:31] [Render thread/INFO]: Narrator library for x64 successfully loaded
[11:00:31] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[11:00:32] [Render thread/INFO]: Successfully extracted default theme
[11:00:32] [Render thread/INFO]: Loading heads...
[11:00:44] [Render thread/ERROR]: Unable to load heads database
java.net.UnknownHostException: headdb.org
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
	at java.net.Socket.connect(Socket.java:645) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request(HttpClient.kt:53) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request$default(HttpClient.kt:50) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.get(HttpClient.kt:62) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.tabs.Tabs.<clinit>(Tabs.kt:91) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:96) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:68) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:108) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zgj000$startClient(class_310.java:5609) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:615) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[11:00:46] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[11:00:46] [Render thread/INFO]: Loading ultralight...
[11:00:46] [Render thread/INFO]: Checking resources...
[11:00:46] [Render thread/INFO]: Successfully loaded ultralight!
[11:00:47] [Render thread/INFO]: Successfully loaded config 'enemies'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'modules'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'commands'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'friends'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'proxies'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'chat'.
[11:00:47] [Render thread/INFO]: Successfully loaded config 'fonts'.
[11:00:47] [Render thread/INFO]: Successfully loaded client!
[11:00:47] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[11:00:48] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), MultiConnect API, Fabric Loader, Fabric Structure API (v1), LiquidBounce, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Dimensions API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), MultiConnect, Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Horse Stats Vanilla, Mod Menu, Fabric Command API (v1), Jankson, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Roughly Enough Items, LibGui, Fabric Language Kotlin, Fabric Entity Events (v1), Enchantment Descriptions, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v4, Fabric Resource Loader (v0), Inventory HUD +, MaLiLib, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), AppleSkin, Fabric Registry Sync (v0), Fabric Commands (v0), Item Scroller, Fabric Mining Levels (v0), BetterF3, Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0)), Nikitich_TotemOfImmortality.zip, zubneo-prismarine-dragonnfly.zip
[11:00:48] [Render thread/INFO]: [STDOUT]: InvGUI Initialized
[11:00:49] [Thread-111/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[11:00:49] [Thread-111/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[11:00:49] [IO-Worker-8/INFO]: Successfully connected to LiquidChat!
[11:00:49] [IO-Worker-8/INFO]: Requesting to login into Mojang...
[11:00:50] [Render thread/INFO]: [MainFrame 3 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[11:00:50] [Thread-126/INFO]: [STDERR]: java.lang.NullPointerException: mimeType must not be null
[11:00:50] [Thread-126/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99)
[11:00:52] [Render thread/INFO]: [MainFrame 1 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/hud/index.html)]: The view finished loading
[11:00:52] [Render thread/INFO]: [MainFrame 5 (file:///C:/Users/HelloWorld/AppData/Roaming/.minecraft/LiquidBounce/themes/default/title/index.html)]: The view finished loading
[11:00:53] [Render thread/INFO]: OpenAL initialized.
[11:00:53] [Render thread/INFO]: Sound engine started
[11:00:53] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[11:00:53] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:00:53] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:00:53] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:00:53] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:00:53] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:00:53] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:00:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11:00:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:00:55] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:34:07] [Render thread/INFO]: Connecting to 51.91.61.66, 40543
[12:34:07] [Server Connector #19/INFO]: Discovered server protocol: 340 (1.12.2)
[12:34:10] [Netty Client IO #5/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 119.6 ?s
[12:34:10] [Netty Client IO #5/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 109.7 ?s
[12:34:10] [Netty Client IO #5/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 109.5 ?s
[12:34:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:34:10] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIPlugin], registered 4 plugins: DefaultRuntimePlugin, DefaultClientRuntimePlugin, DefaultPlugin, DefaultClientPlugin
[12:34:10] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 1 fluid support providers in 0ms.
[12:34:10] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIClientPlugin], registered 2 plugins: DefaultClientRuntimePlugin, DefaultClientPlugin
[12:34:10] [Render thread/INFO]: [CHAT]                                      
[12:34:10] [Render thread/INFO]: [CHAT] BlockyBuddha joined the game
[12:34:10] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIClientPlugin] with 1370 entries, 934 displays, 0 display visibility predicates, 16 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Beacon Base, Beacon Payment, Tilling, Pathing, Information), 4 exclusion zones and 4 overlay deciders in 46ms.
[12:34:10] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIServerPlugin], registered 2 plugins: DefaultRuntimePlugin, DefaultPlugin
[12:34:10] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 20ms.
[12:34:10] [Render thread/INFO]: Loaded 45 advancements
```

### Screenshots

Video proof and comparison of AutoTool in Impact 4.9.1 and LiquidBounce 56158d0: https://imgur.com/a/o6Ug8ED

### Other

Since the full log did not fit, I cut it off.

**Comment by ghost** [comment]
@majjestro, the issue with AutoTool is now fixed. You can now close your issue.
