### ISSUE TITLE
[BUG] Liquidbounce not loading

### ISSUE THREAD

**Issue by acepirine** [CCBlueX/LiquidBounce#643]
### LiquidBounce Build/Version

b72

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

Liquidbounce won't load, the minecraft client loads in and then crashes with this error

### Steps to reproduce

![image](https://user-images.githubusercontent.com/18514433/131247037-490634c0-c445-479b-83b5-91710e365a5e.png)

### Client Log

```shell
Picked up _JAVA_OPTIONS: 
[16:16:09] [main/INFO]: Loading for game Minecraft 1.17.1
[16:16:10] [main/INFO]: [FabricLoader] Loading 62 mods:
	- fabric@0.39.2+1.17
	- fabric-api-base@0.3.0+a02b446318
	- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
	- fabric-biome-api-v1@3.2.0+b06cb95b18
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.3.0+211ddf9518
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.2+62e33f4118
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.1+b06cb95b18
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.8.0+b06cb95b18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.1.2+96bf6a7e18
	- fabricloader@0.11.6
	- java@16
	- liquidbounce@1.0.0
	- minecraft@1.17.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- org_yaml_snakeyaml@1.29
	- viafabric@0.4.3+203-main
	- viafabric-mc117@0.4.3+203-main
	- viaversion@4.0.1
[16:16:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/arman/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[16:16:14] [main/INFO]: Compatibility level set to JAVA_16
[16:16:17] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[16:16:28] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[16:16:28] [Render thread/INFO]: Setting user: AspirineTY
[16:16:30] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[16:16:30] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[16:16:30] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[16:16:30] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[16:16:30] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[16:16:31] [Via-Mappingloader-1/INFO]: Loading 1.16 -> 1.16.2 mappings...
[16:16:31] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[16:16:31] [Via-Mappingloader-4/INFO]: Loading 1.16.2 -> 1.17 mappings...
[16:16:31] [ViaFabric-0/INFO]: ViaVersion detected server version: 1.17.1 (756)
[16:16:31] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbc000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[16:16:31] [ViaFabric-0/WARN]: ViaVersion does not have any compatible versions for this server version!
[16:16:31] [ViaFabric-0/WARN]: Please remember that ViaVersion only adds support for versions newer than the server version.
[16:16:31] [ViaFabric-0/WARN]: If you need support for older versions you may need to use one or more ViaVersion addons too.
[16:16:31] [ViaFabric-0/WARN]: In that case please read the ViaVersion resource page carefully or use https://jo0001.github.io/ViaSetup
[16:16:31] [ViaFabric-0/WARN]: and if you're still unsure, feel free to join our Discord-Server for further assistance.
[16:16:31] [ViaFabric-0/INFO]: Finished mapping loading, shutting down loader executor!
[16:16:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[16:16:32] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[16:16:35] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\arman\AppData\Roaming\.minecraft\versions\Fabric 1.17.1\Fabric 1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.args$zek000$setupIcon(class_310.java:5165) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[16:16:38] [Render thread/INFO]: Narrator library for x64 successfully loaded
[16:16:38] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[16:16:39] [Render thread/INFO]: Successfully extracted default theme
[16:16:39] [Render thread/INFO]: Loading heads...
[16:16:39] [Render thread/ERROR]: Unable to load heads database
java.io.IOException: Server returned HTTP response code: 403 for URL: https://cloud.liquidbounce.net/LiquidBounce/heads.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request(HttpClient.kt:53) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.request$default(HttpClient.kt:50) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.get(HttpClient.kt:62) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.features.tabs.Tabs.<clinit>(Tabs.kt:86) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:94) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:67) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zek000$startClient(class_310.java:5107) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:615) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[16:16:40] [Render thread/ERROR]: Unable to load font Roboto-Medium.ttf. Falling back to default.
java.awt.FontFormatException: java.nio.BufferUnderflowException
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:528) ~[?:?]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:217) ~[?:?]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:197) ~[?:?]
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2226) ~[?:?]
	at java.awt.Font.createFont0(Font.java:1168) ~[?:?]
	at java.awt.Font.createFont(Font.java:1073) ~[?:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.getAwtFont(Fonts.kt:96) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.loadFont(Fonts.kt:82) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadFonts(Fonts.kt:68) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.RenderEngine.init(RenderEngine.kt:126) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:98) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:67) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zek000$startClient(class_310.java:5107) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:615) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[16:16:41] [Render thread/ERROR]: Unable to load font Roboto-Bold.ttf. Falling back to default.
java.awt.FontFormatException: java.nio.BufferUnderflowException
	at sun.font.TrueTypeFont.init(TrueTypeFont.java:528) ~[?:?]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:217) ~[?:?]
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:197) ~[?:?]
	at sun.font.SunFontManager.createFont2D(SunFontManager.java:2226) ~[?:?]
	at java.awt.Font.createFont0(Font.java:1168) ~[?:?]
	at java.awt.Font.createFont(Font.java:1073) ~[?:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.getAwtFont(Fonts.kt:96) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts$FontDetail.loadFont(Fonts.kt:82) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.Fonts.loadFonts(Fonts.kt:68) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.engine.RenderEngine.init(RenderEngine.kt:126) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:98) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:67) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zek000$startClient(class_310.java:5107) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:615) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[16:16:43] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[16:16:43] [Render thread/INFO]: Loading ultralight...
[16:16:43] [Render thread/INFO]: Checking resources...
[16:16:43] [Render thread/INFO]: Downloading v0.46 resources... (os: win)
[16:16:43] [Render thread/ERROR]: Unable to download resources
java.io.IOException: Server returned HTTP response code: 403 for URL: https://cloud.liquidbounce.net/LiquidBounce/ultralight_resources/0.46/win-x64.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at net.ccbluex.liquidbounce.utils.io.HttpClient.download(HttpClient.kt:64) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.ultralight.UltralightResources.downloadResources(UltralightResources.kt:84) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.init(UltralightEngine.kt:86) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:101) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:67) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:106) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zek000$startClient(class_310.java:5107) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:615) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

**Comment by hax0r31337** [comment]
i think its your network issues, try use a vpn

**Comment by acepirine** [comment]
> i think its your network issues, try use a vpn

But what I have seen from other issues the individual link https://cloud.liquidbounce.net/LiquidBounce/ultralight_resources/0.46/win-x64.zip
wasn't supposed to work if it were a network issue but i'll try anyways

**Comment by acepirine** [comment]
> i think its your network issues, try use a vpn

Yep works now for some reason... thank you for your response
