### ISSUE TITLE
[BUG] Crashes when using Patcher mod

### ISSUE THREAD

**Issue by litstuffhere** [CCBlueX/LiquidBounce#645]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

Crashing on startup when using [Patcher](https://sk1er.club/mods/patcher) 

### Steps to reproduce

Startup with liquidbounce b73 and patcher mod

### Client Log

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-v1.jar)
  LoadingPlugin (Block_Overlay_4.0.3.jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  MinecraftTweaker (TimeChanger-1.0 (1.8.9).jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/4/21 5:13 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.gui.FontRenderer.handler$drawString$zbm000(FontRenderer.java:1257)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:402)
	at club.sk1er.patcher.Patcher.postInit(Patcher.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.FontRenderer.handler$drawString$zbm000(FontRenderer.java:1257)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:402)
	at club.sk1er.patcher.Patcher.postInit(Patcher.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 429210824 bytes (409 MB) / 1603272704 bytes (1529 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJ	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJ	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHIJ	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCHIJ	keystrokesmod{KMV5} [KeystrokesMod] ([1.8.9] BetterKeystrokes V-1.1.0.jar) 
	UCHIJ	blockoverlay{4.0.3} [Block Overlay] (Block_Overlay_4.0.3.jar) 
	UCHIJ	ChromaHUD{3.0} [Chroma HUD] (ChromaHUD-3.0 (1.8.9).jar) 
	UCHIJ	custom-crosshair-mod{1.3.0-forge} [Custom Crosshair Mod] (custom-crosshair-mod-v1.3.0-forge-mc1.8.9.jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-law-1.8.x.jar) 
	UCHIJ	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (InGameAccountSwitcher-Forge-1.8.9-7.0.1.jar) 
	UCHIJ	inventoryhud{3.2.1} [Inventory HUD+] (InventoryHUD-1.8.9-3.2.1.jar) 
	UCHIJ	ctrlsaved{1.0} [Controls Saved] (No text shadow (Forge 1.8.x).jar) 
	UCHIE	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	UCHIJ	timechanger{1.0} [TimeChanger] (TimeChanger-1.0 (1.8.9).jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPClient-v1.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
LoadingPlugin (Block_Overlay_4.0.3.jar)
  me.aycy.blockoverlay.asm.Transformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
MinecraftTweaker (TimeChanger-1.0 (1.8.9).jar)
  xyz.blowsy.freelook.tweaker.ClassTransformer
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)
  keystrokesmod.tweaker.ASMTransformerClass
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.96, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.16, VanillaTweaks_r867523.zip (incompatible), Default-Dark-Mode-1.8-0.5-000000-(v1.3.0).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 471.96
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by ENDER1355** [comment]
Can confirm this is happening.

**Comment by ghost** [comment]
> TransformerLoader (FDPClient-v1.jar)
  LoadingPlugin (Block_Overlay_4.0.3.jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  MinecraftTweaker (TimeChanger-1.0 (1.8.9).jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)

You’re not only using a heavy modded version of liquidbounce, you re also using a whole other client alongside it so I think that is most likely the problem as I have used liquidbounce with patcher just fine

**Comment by litstuffhere** [comment]
> > TransformerLoader (FDPClient-v1.jar)
> > LoadingPlugin (Block_Overlay_4.0.3.jar)
> > PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
> > MinecraftTweaker (TimeChanger-1.0 (1.8.9).jar)
> > ModTweaker (Patcher-1.5.1 (1.8.9).jar)
> > ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
> > FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)
> 
> You’re not only using a heavy modded version of liquidbounce, you re also using a whole other client alongside it so I think that is most likely the problem as I have used liquidbounce with patcher just fine

Happens with b73, uploaded wrong logs. However, when using just patcher and b73 from [https://dl.ccbluex.net/download/duktXkxezz](https://dl.ccbluex.net/download/duktXkxezz), it instantly crashes on startup,
fml-client-latest.log at the very bottom: `[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:108)
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:973)
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[11:38:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

[latest.log](https://github.com/CCBlueX/LiquidBounce/files/7117541/latest.log)

Does not generate a crash report. Does not happen with b72, it can run fine. I will just use b72 for now.
