### ISSUE TITLE
[BUG] RenderEngine not working at all

### ISSUE THREAD

**Issue by NowPyk** [CCBlueX/LiquidBounce#668]
### LiquidBounce Build/Version

a144a3e / nexgen in general

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

I was trying to use the nametags but when enabled it literally erases all the nametags this also happens with ESP Box mode
ESP Only works some times in outline mode
This seems only to be happening with AMD users and i say this bc one of my friends who also has AMD it's experiencing the same problem
I have rx580 card and it's latest drivers
Is there anything i can do to fix this or should i wait for an update?

### Steps to reproduce

Any server
.t nametags / .t esp
Esp box
Nametags is vanish while Esp box doesn't show

### Client Log

```shell
[11:15:19] [main/INFO]: Loading for game Minecraft 1.17.1
[11:15:19] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:15:26] [main/INFO]: Loading 59 mods:
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018
	- fabric-api-lookup-api-v1 1.3.1+5847535018
	- fabric-biome-api-v1 3.2.2+5847535018
	- fabric-blockrenderlayer-v1 1.1.6+5847535018
	- fabric-command-api-v1 1.1.4+5847535018
	- fabric-commands-v0 0.2.3+5847535018
	- fabric-containers-v0 0.1.13+5847535018
	- fabric-content-registries-v0 0.3.1+5847535018
	- fabric-crash-report-info-v1 0.1.6+5847535018
	- fabric-dimensions-v1 2.0.13+5847535018
	- fabric-entity-events-v1 1.3.1+5847535018
	- fabric-events-interaction-v0 0.4.11+5847535018
	- fabric-events-lifecycle-v0 0.2.2+5847535018
	- fabric-game-rule-api-v1 1.0.8+5847535018
	- fabric-item-api-v1 1.2.5+5847535018
	- fabric-item-groups-v0 0.3.1+5847535018
	- fabric-key-binding-api-v1 1.0.5+5847535018
	- fabric-keybindings-v0 0.2.3+5847535018
	- fabric-language-kotlin 1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1 1.4.5+5847535018
	- fabric-loot-tables-v1 1.0.5+5847535018
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218
	- fabric-mining-levels-v0 0.1.5+6d0fac4218
	- fabric-models-v0 0.3.1+5847535018
	- fabric-networking-api-v1 1.0.14+5847535018
	- fabric-networking-blockentity-v0 0.2.12+5847535018
	- fabric-networking-v0 0.3.3+5847535018
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218
	- fabric-object-builders-v0 0.7.5+6d0fac4218
	- fabric-particles-v1 0.2.5+5847535018
	- fabric-registry-sync-v0 0.7.13+5847535018
	- fabric-renderer-api-v1 0.4.5+5847535018
	- fabric-renderer-indigo 0.4.9+5847535018
	- fabric-renderer-registries-v1 3.2.6+6d0fac4218
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218
	- fabric-rendering-v0 1.1.7+6d0fac4218
	- fabric-rendering-v1 1.10.1+6d0fac4218
	- fabric-resource-loader-v0 0.4.9+5847535018
	- fabric-screen-api-v1 1.0.5+5847535018
	- fabric-screen-handler-api-v1 1.1.9+5847535018
	- fabric-structure-api-v1 1.1.14+5847535018
	- fabric-tag-extensions-v0 1.2.2+5847535018
	- fabric-textures-v0 1.0.7+5847535018
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18
	- fabric-transfer-api-v1 1.5.1+6d0fac4218
	- fabricloader 0.12.5
	- java 16
	- liquidbounce 1.0.0
	- minecraft 1.17.1
	- org_jetbrains_kotlin_kotlin-reflect 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.0
[11:15:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/DP/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.6+mixin.0.8.4/sponge-mixin-0.10.6+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[11:15:26] [main/INFO]: Compatibility level set to JAVA_16
[11:15:33] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:15:33] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:112) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:670) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:429) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:77) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
	... 12 more
[11:15:33] [Render thread/INFO]: Setting user: TyPyPvP
[11:15:34] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdc000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[11:15:34] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[11:15:35] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[11:15:36] [Render thread/ERROR]: Unable to load client icons.
net.minecraft.class_3266: 'assets/liquidbounce/icon_16x16.png' in ResourcePack 'C:\Users\Abraham Tiukm\AppData\Roaming\.minecraft\.fabric\remappedJars\minecraft-1.17.1\intermediary-fabric-loader-0.12.5-1.17.1.jar'
	at net.minecraft.class_3258.method_14391(class_3258.java:44) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14416(class_3268.java:626) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_1065.method_14416(class_1065.java:36) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3268.method_14405(class_3268.java:115) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.args$zin000$setupIcon(class_310.java:6167) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
[11:15:37] [Render thread/INFO]: Narrator library for x64 successfully loaded
[11:15:37] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[11:15:38] [Render thread/INFO]: Successfully extracted default theme
[11:15:38] [Render thread/INFO]: Loading heads...
[11:15:40] [Render thread/INFO]: Successfully loaded 956 heads from the database
[11:15:40] [Render thread/INFO]: Downloading required font Roboto-Medium.ttf...
[11:15:41] [Render thread/INFO]: Downloading required font Roboto-Bold.ttf...
[11:15:42] [Render thread/INFO]: Found out OpenGL version to be 3.2.13596. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[11:15:42] [Render thread/INFO]: Loading ultralight...
[11:15:42] [Render thread/INFO]: Checking resources...
[11:15:42] [Render thread/INFO]: Downloading v0.46 resources... (os: win)
[11:16:05] [Render thread/INFO]: Extracting resources...
[11:16:06] [Render thread/INFO]: Successfully loaded resources.
[11:16:06] [Render thread/INFO]: Successfully loaded ultralight!
[11:16:06] [Render thread/INFO]: Successfully saved config 'Enemies'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'modules'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'Commands'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'Friends'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'Proxies'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'chat'.
[11:16:06] [Render thread/INFO]: Successfully saved config 'Fonts'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'modules'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'Commands'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'Friends'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'Proxies'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'chat'.
[11:16:06] [Render thread/INFO]: Successfully loaded config 'Fonts'.
[11:16:06] [Render thread/INFO]: Successfully loaded client!
[11:16:06] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[11:21:35] [Render thread/WARN]: Received packet for unknown team 13Santino45631dA: team action: REMOVE, player action: null
[11:21:36] [Render thread/WARN]: Received packet for unknown team 13AZKEEA: team action: REMOVE, player action: null
[11:21:41] [Render thread/WARN]: Received packet for unknown team 13GUANBLOOXA: team action: REMOVE, player action: null
[11:21:45] [Render thread/WARN]: Received packet for unknown team 13elbenjas717A: team action: REMOVE, player action: null
[11:21:48] [Render thread/WARN]: Received packet for unknown team 13MambowzA: team action: REMOVE, player action: null
[11:21:49] [Render thread/WARN]: Received packet for unknown team 13tototo1907A: team action: REMOVE, player action: null
[11:21:53] [Render thread/WARN]: Received packet for unknown team 13rikubikA: team action: REMOVE, player action: null
[11:22:04] [Render thread/WARN]: Received packet for unknown team 13sebasxdd1213A: team action: REMOVE, player action: null
[11:22:05] [Render thread/WARN]: Received packet for unknown team 13xroberto_5044A: team action: REMOVE, player action: null
[11:22:06] [Render thread/WARN]: Received packet for unknown team 13NicoGmer693A: team action: REMOVE, player action: null
[11:22:06] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 17 on entity class_1642['Zombi'/657110, l='ClientLevel', x=-91.54, y=105.25, z=628.43]: old=0(class java.lang.Integer), new=false(class java.lang.Boolean)
	at net.minecraft.class_2945.method_12785(class_2945.java:245) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:230) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:459) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:39) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:11) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
```

### Screenshots

![nametags3](https://user-images.githubusercontent.com/94635557/142471862-a3396bec-3825-4d59-8c6a-d20cb759f31a.png)
![nametags4](https://user-images.githubusercontent.com/94635557/142471868-89769b52-411a-4d02-9879-1c0d7b3287d6.png)
![nametags](https://user-images.githubusercontent.com/94635557/142471870-ac764616-c944-441c-b6af-f2994c038c5a.png)
![nametags1](https://user-images.githubusercontent.com/94635557/142471873-24c26bda-cbb3-4175-aba5-81463361d1bb.png)

**Comment by 1zun4secondary** [comment]
Yes, this issue is known for us. The RenderEngine doesn't support AMD drivers at the moment, the actual reason is not fully known because of their poor gpu debugging tools, so it might take some time until we get it fixed. @superblaubeere27 and me already spend some time trying to solve this issue, but all calls do work properly and on NVIDIA drivers they just work, which is a huge issue with supporting AMD graphic cards, because we actually do not know how to figure out the issue.

**Comment by 1zun4secondary** [comment]
Render Engine needs to be reworked or replaced by the Minecraft Render System. @superblaubeere27

**Comment by 1zun4** [comment]
This is currently being addressed by https://github.com/CCBlueX/LiquidBounce/pull/1142 and will replace the whole render engine.
