### ISSUE TITLE
[BUG] Failed to run LiquidBounce, Mod resolution encountered an incompatible mod set

### ISSUE THREAD

**Issue by VenixPLL** [CCBlueX/LiquidBounce#732]
### LiquidBounce Build/Version

nextgen

### Operating System

Windows 11

### Minecraft Version

1.18.1

### Describe the bug

Can't run LiquidBounce nextgen in ide due to lithium version being bad

### Steps to reproduce

Clone project and setup
try to run it

### Client Log

```shell
[23:48:31] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[23:48:31] [main/WARN] (FabricLoader/Resolution) Mod resolution failed
[23:48:31] [main/INFO] (FabricLoader/Resolution) Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED lithium 0.7.9-SNAPSHOT {depends minecraft @ [1.18.2]}, ROOT_FORCELOAD_SINGLE lithium 0.7.9-SNAPSHOT]
[23:48:31] [main/INFO] (FabricLoader/Resolution) Reason: [HARD_DEP lithium 0.7.9-SNAPSHOT {depends minecraft @ [1.18.2]}]
[23:48:31] [main/INFO] (FabricLoader/Resolution) Fix: add [], remove [], replace [[lithium 0.7.9-SNAPSHOT] -> add:lithium 1 ([(-?,?)])]
[23:48:31] [main/ERROR] (FabricLoader) Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Lithium' (lithium) 0.7.9-SNAPSHOT with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod 'Lithium' (lithium) 0.7.9-SNAPSHOT requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by ghost** [comment]
Just remove lithium from `build.gradle` for now. The developers will fix it once they update to 1.18.2, because this error is all about the new Minecraft version.
