### ISSUE TITLE
[BUG] crash on launch

### ISSUE THREAD

**Issue by jyooru** [CCBlueX/LiquidBounce#757]
### LiquidBounce Build/Version

I have tried nexgen 0256417 and b176154

### Operating System

Linux

### Minecraft Version

I have tried 1.18 and 1.18.2

### Describe the bug

Crash

### Steps to reproduce

As said above, I've tried using 0256417 and b176154 as well as 1.18 and 1.18.2. I'm not sure what is causing this crash, so I am opening this issue.

### Client Log

```shell
PolyMC version: 1.1.1


Launched instance in offline mode

Minecraft folder is:
/home/joel/.local/share/polymc/instances/1.18/.minecraft


Java path is:
/nix/store/h6g1yng4gkbqpydqc86k7nc6fnmd4zpy-openjdk-17.0.1+12/lib/openjdk/bin/java


Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from N/A.


Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/joel/.local/share/polymc/instances/1.18/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home/joel/.local/share/polymc/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  /home/joel/.local/share/polymc/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  /home/joel/.local/share/polymc/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  /home/joel/.local/share/polymc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  /home/joel/.local/share/polymc/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/joel/.local/share/polymc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/joel/.local/share/polymc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/joel/.local/share/polymc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/joel/.local/share/polymc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/joel/.local/share/polymc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/joel/.local/share/polymc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/joel/.local/share/polymc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/joel/.local/share/polymc/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  /home/joel/.local/share/polymc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/joel/.local/share/polymc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/joel/.local/share/polymc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/joel/.local/share/polymc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/joel/.local/share/polymc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/intermediary/1.18/intermediary-1.18.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/joel/.local/share/polymc/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  /home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  /home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  /home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  /home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  /home/joel/.local/share/polymc/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/minecraft/1.18/minecraft-1.18-client.jar

Native libraries:
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/joel/.local/share/polymc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [✔️] fabric-language-kotlin-1.7.2+kotlin.1.6.20
  [✔️] liquidbounce

Params:
  --username  --version PolyMC --gameDir /home/joel/.local/share/polymc/instances/1.18/.minecraft --assetsDir /home/joel/.local/share/polymc/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 39815


Using onesix launcher.

[18:38:16] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18 with Fabric Loader 0.13.3
[18:38:16] [main/INFO]: Loading Minecraft 1.18 with Fabric Loader 0.13.3
[18:38:17] [main/INFO]: Loading 14 mods:
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabricloader 0.13.3
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.18
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
[18:38:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/joel/.local/share/polymc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:38:17] [main/ERROR]: liquidbounce.mixins.json:minecraft.client.MixinWorld: Unsupported mixin, liquidbounce.mixins.json:minecraft.client.MixinWorld requires the following unsupported language features: [NESTING], these features require compatibility level JAVA_11
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported mixin, liquidbounce.mixins.json:minecraft.client.MixinWorld requires the following unsupported language features: [NESTING], these features require compatibility level JAVA_11
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validateClassFeatures(MixinInfo.java:366) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:335) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:914) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:803) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:414) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:38:17] [main/ERROR]: liquidbounce.mixins.json:minecraft.network.MixinPlayerListEntry: Unsupported mixin, liquidbounce.mixins.json:minecraft.network.MixinPlayerListEntry requires the following unsupported language features: [NESTING], these features require compatibility level JAVA_11
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported mixin, liquidbounce.mixins.json:minecraft.network.MixinPlayerListEntry requires the following unsupported language features: [NESTING], these features require compatibility level JAVA_11
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validateClassFeatures(MixinInfo.java:366) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:335) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:914) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:803) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:414) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:38:23] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:38:24] [Render thread/INFO]: Setting user: name
[18:38:25] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:38:29] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':
libflite.so.1: cannot open shared object file: No such file or directory
libflite.so.1: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libfliteWrapper.so) not found in resource path (/nix/store/6c2icbbizzpkr1jjvbgc9pk1aaym4fik-polymc-1.1.1/share/jars/NewLaunch.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/joel/.local/share/polymc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/joel/.local/share/polymc/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar:/home/joel/.local/share/polymc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar:/home/joel/.local/share/polymc/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar:/home/joel/.local/share/polymc/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:/home/joel/.local/share/polymc/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar:/home/joel/.local/share/polymc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:/home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar:/home/joel/.local/share/polymc/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar:/home/joel/.local/share/polymc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:/home/joel/.local/share/polymc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/joel/.local/share/polymc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar:/home/joel/.local/share/polymc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/joel/.local/share/polymc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:/home/joel/.local/share/polymc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/joel/.local/share/polymc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/joel/.local/share/polymc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/home/joel/.local/share/polymc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/home/joel/.local/share/polymc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/home/joel/.local/share/polymc/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar:/home/joel/.local/share/polymc/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar:/home/joel/.local/share/polymc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/home/joel/.local/share/polymc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/joel/.local/share/polymc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/joel/.local/share/polymc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:/home/joel/.local/share/polymc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:/home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar:/home/joel/.local/share/polymc/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar:/home/joel/.local/share/polymc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/intermediary/1.18/intermediary-1.18.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar:/home/joel/.local/share/polymc/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar:/home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar:/home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar:/home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar:/home/joel/.local/share/polymc/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar:/home/joel/.local/share/polymc/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar:/home/joel/.local/share/polymc/libraries/com/mojang/minecraft/1.18/minecraft-1.18-client.jar)
[18:38:29] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[18:38:30] [Render thread/INFO]: Successfully extracted default theme
[18:38:30] [Render thread/INFO]: Loading heads...
[18:38:33] [Render thread/INFO]: Successfully loaded 956 heads from the database
[18:38:35] [Render thread/INFO]: Found out OpenGL version to be 4.6. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[18:38:35] [Render thread/INFO]: Loading ultralight...
[18:38:35] [Render thread/INFO]: Checking resources...
OpenJDK 64-Bit Server VM warning: You have loaded library /home/joel/.local/share/polymc/instances/1.18/.minecraft/LiquidBounce/ultralight/bin/libWebCore.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[18:38:36] [Render thread/INFO]: Successfully loaded ultralight!
[18:38:36] [Render thread/INFO]: Successfully loaded config 'Enemies'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'modules'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'Commands'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'Friends'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'Proxies'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'chat'.
[18:38:36] [Render thread/INFO]: Successfully loaded config 'Fonts'.
[18:38:36] [Render thread/INFO]: Successfully loaded client!
[18:38:36] [IO-Worker-8/INFO]: Connecting to LiquidChat...
[18:38:37] [Render thread/INFO]: Reloading ResourceManager: Default
[18:38:37] [Thread-23/ERROR]: Uncaught exception in thread "Thread-23"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
[18:38:37] [Thread-28/ERROR]: Uncaught exception in thread "Thread-28"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
[18:38:37] [Thread-33/ERROR]: Uncaught exception in thread "Thread-33"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
[18:38:37] [Render thread/INFO]: [MainFrame 3 (file:////home/joel/.local/share/polymc/instances/1.18/.minecraft/LiquidBounce/themes/default/splashscreen/index.html)]: The view finished loading
[18:38:38] [Thread-38/ERROR]: Uncaught exception in thread "Thread-38"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
[18:38:38] [Thread-43/ERROR]: Uncaught exception in thread "Thread-43"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
[18:38:38] [Thread-48/ERROR]: Uncaught exception in thread "Thread-48"
java.lang.NullPointerException: mimeType must not be null
	at net.ccbluex.liquidbounce.render.ultralight.filesystem.BrowserFileSystem.getFileMimeType(BrowserFileSystem.kt:99) ~[?:?]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f001e483369, pid=39815, tid=40244
#
# JRE version: OpenJDK Runtime Environment (17.0.1+12) (build 17.0.1+12-nixos)
# Java VM: OpenJDK 64-Bit Server VM (17.0.1+12-nixos, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libWebCore.so+0x1dab369]  SSL_CTX_set_max_proto_version+0x7
#
# Core dump will be written. Default location: Core dumps may be processed with "/nix/store/jp2asqzh2vha5bbkscb7vhsd39bl48ls-systemd-250.4/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/joel/.local/share/polymc/instances/1.18/.minecraft/core.39815)
#
# An error report file with more information is saved as:
# /home/joel/.local/share/polymc/instances/1.18/.minecraft/hs_err_pid39815.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Process crashed with exitcode 6.
```

**Comment by Gyztor** [comment]
also getting this too, for a split second i see it saying "saving world" than it crashes. not sure why nor can i get logs because it keeps not giving me any
