### ISSUE TITLE
[BUG] liquidbounce nextgen crashed

### ISSUE THREAD

**Issue by tzt2020** [CCBlueX/LiquidBounce#851]
### LiquidBounce Build/Version

2fbf004

### Operating System

Windows 11

### Minecraft Version

1.18.2

### Describe the bug

Can not start

### Steps to reproduce

Added the liquidbounce mod and kotlin mod
Start the game
Crashed!

### Client Log

```shell
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod liquidbounce
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more
```

**Comment by 1zun4secondary** [comment]
should be fixed by https://github.com/CCBlueX/LiquidBounce/commit/010a20731c50af407d7a6eb4ca1ca081ed74d136
