### ISSUE TITLE
[BUG] Liquidbounce NG Crash on startup

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce#852]
### LiquidBounce Build/Version

010a207

### Operating System

macOS

### Minecraft Version

1.18.2

### Describe the bug

Game crashes on startup

### Steps to reproduce

Start the game

Current mod list:
```
XaerosWorldMap_1.28.1_Fabric_1.18.2.jar
Xaeros_Minimap_22.16.0_Fabric_1.18.2.jar
baritone-api-fabric-1.8.3.jar
fabric-api-0.58.0+1.18.2.jar
fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
liquidbounce.jar
litematica-fabric-1.18.2-0.11.3.jar
lithium-fabric-mc1.18.2-0.7.10.jar
malilib-fabric-1.18.2-0.12.1.jar
minihud-fabric-1.18.2-0.22.1.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
seedcrackerX-2.12.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.3.jar
```
(but I haven't tried without mods. Wurst starts without any problems with this mods)

### Client Log

```shell
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main.main(Main.java:206)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookFreeCamPreventCreativeFly(Lnet/minecraft/class_1656;)Z in liquidbounce.mixins.json:minecraft.entity.MixinClientPlayerEntity from mod liquidbounce failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap liquidbounce-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 11 more
```

**Comment by ghost** [comment]
Can you try loading the client with just the fabric api and fabric kotlin language? In my case this error did not seem to appear.

**Comment by henrydatei** [comment]
Ok found the problem. Baritone doesn't work with Liquidbounce.
