### ISSUE TITLE
[BUG] enabling ESP crashes game when FabricAPI is not installed

### ISSUE THREAD

**Issue by henrydatei** [CCBlueX/LiquidBounce#856]
### LiquidBounce Build/Version

010a20731c50af407d7a6eb4ca1ca081ed74d136

### Operating System

macOS

### Minecraft Version

1.18.2

### Describe the bug

enabling ESP crashes game

### Steps to reproduce

Join Singleplayer World
enable ESP

### Client Log

```shell
---- Minecraft Crash Report ----
// Oops.

Time: 16.11.22, 12:25
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4597.getBuffer(net.minecraft.class_1921)" because "$$4" is null
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.handler$zlh000$injectOutlineESP(class_761.java:4457)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_922.method_4054(class_922.java:138)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.handler$zlh000$injectOutlineESP(class_761.java:4457)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Entity being rendered --
Details:
	Entity Type: minecraft:salmon (net.minecraft.class_1462)
	Entity ID: 83
	Entity Name: Salmon
	Entity's Exact location: 19.25, 59.97, -93.65
	Entity's Block location: World: (19,59,-94), Section: (at 3,11,2 in 1,3,-6; chunk contains blocks 16,-64,-96 to 31,319,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.03, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.handler$zlh000$injectOutlineESP(class_761.java:4457)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_938@5a3b266e
	Location: 14.84,-24.04,-8.09 - World: (14,-25,-9), Section: (at 14,7,7 in 0,-2,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: -156.15938
	Delta: 0.14000452
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.handler$zlh000$injectOutlineESP(class_761.java:4457)
	at net.minecraft.class_761.method_22977(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['henrydatei'/118, l='ClientLevel', x=4.38, y=82.39, z=-85.56]]
	Chunk stats: 1024, 318
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,72,-256), Section: (at 0,8,0 in -3,4,-16; chunk contains blocks -48,-64,-256 to -33,319,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 10513 game time, 10513 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.6.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 762844280 bytes (727 MiB) / 2046820352 bytes (1952 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: unknown
	Frequency (GHz): 1,80
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel HD Graphics 6000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536,00
	Graphics card #0 deviceId: 0x1626
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 10240,00
	Virtual memory used (MB): 6686,53
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 1176,00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		liquidbounce: LiquidBounce 1.0.0
		litematica: Litematica 0.11.3
		lithium: Lithium 0.7.10
		malilib: MaLiLib 0.12.1
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.1
		phosphor: Phosphor 0.8.1
		seedcrackerx: SeedCrackerX 2.12
			cloth-config: Cloth Config v6 6.2.57
				cloth-basic-math: cloth-basic-math 0.6.0
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 88b246597e0147e37b38d1b33e9526e6c3eb1469
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		tweakeroo: Tweakeroo 0.13.3
		xaerominimap: Xaero's Minimap 22.16.0
		xaeroworldmap: Xaero's World Map 1.28.1
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) HD Graphics 6000 GL version 4.1 INTEL-18.8.5, Intel Inc.
	Window size: 1440x772
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['henrydatei'/118, l='ServerLevel[New World]', x=4.38, y=82.39, z=-85.56]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

**Comment by 1zun4secondary** [comment]
This issue is being caused when FabricAPI is not installed. Since we install FabricAPI in the launcher this is no problem.

We could fix this issue or require FabricAPI to be installed, but it makes sense to require it to be installed, since we rely on a few features of the library.

**Comment by renshengongji** [comment]
还有人用fabric不装fabric api？

**Comment by ghost** [comment]
Fabric API is required.
