### ISSUE TITLE
[BUG] Ultralight file manager unable to understand '#' in paths

### ISSUE THREAD

**Issue by MJMALTE32** [CCBlueX/LiquidBounce#898]
### LiquidBounce Build/Version

b73

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

Its just a blackscreen, I can´t do anything.
(Ihave tried the newest and 1.7.10 fabric kotlin and it doesn´t work)

### Steps to reproduce

-open Curseforge
-Use 1.18.2
-download Liquidbounce and fabric kotlin 
-Start the game
-Blackscreen

### Client Log

```shell
[15:26:25] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.13
[15:26:26] [main/INFO]: Loading 62 mods:
	- fabric-api 0.67.1+1.18.2
	- fabric-api-base 0.4.5+64b7c69360 via fabric-api
	- fabric-api-lookup-api-v1 1.6.3+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.10+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.9+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.24+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.2+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.2+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.3+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.21+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.9+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.20+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.21+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.1+a6f01b2660 via fabric-api
	- fabric-item-groups-v0 0.3.15+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.1+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.1+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.3+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.5+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.7+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.24+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.11+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.4+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.13+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.12+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.16+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.6+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.14+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.8+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.11+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.3+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.13+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.4+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.13
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.18.2
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
[15:26:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Malte%20Illigasch/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:26:26] [main/INFO]: Compatibility level set to JAVA_16
[15:26:26] [main/INFO]: Compatibility level set to JAVA_17
[15:26:28] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[15:27:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:27:02] [Render thread/INFO]: Setting user: WhiskeryCone624
[15:27:04] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[15:27:05] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:27:14] [Render thread/INFO]: Narrator library for x64 successfully loaded
[15:27:14] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[15:27:16] [Render thread/INFO]: Successfully extracted default theme
[15:27:16] [Render thread/INFO]: Loading heads...
[15:27:17] [Render thread/INFO]: Successfully loaded 956 heads from the database
[15:27:20] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[15:27:20] [Render thread/INFO]: Loading ultralight...
[15:27:20] [Render thread/INFO]: Checking resources...
[15:27:20] [Render thread/INFO]: Loading ultralight natives
[15:27:20] [Render thread/INFO]: Native path: C:\Users\Malte Illigasch\curseforge\minecraft\Instances\#Liquidbounce\LiquidBounce\ultralight\bin
[15:27:20] [Render thread/INFO]: Setting up ultralight renderer
[15:27:20] [Render thread/INFO]: Successfully loaded ultralight!
[15:27:22] [Thread-4/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/Malte Illigasch/curseforge/minecraft/Instances/
[15:27:22] [Thread-4/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\Malte Illigasch\curseforge\minecraft\Instances
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[15:27:22] [Thread-4/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.filesystem.BrowserFileSystem.openFile(BrowserFileSystem.kt:128)
[15:27:22] [Render thread/INFO]: Successfully loaded config 'Enemies'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'modules'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'Commands'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'Friends'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'Proxies'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'chat'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'Fonts'.
[15:27:23] [Render thread/INFO]: Successfully loaded config 'ultralight_storage'.
[15:27:23] [Render thread/INFO]: Successfully loaded client!
[15:27:23] [IO-Worker-4/INFO]: Connecting to LiquidChat...
[15:27:23] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, LiquidBounce)
[15:27:24] [Thread-6/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/Malte Illigasch/curseforge/minecraft/Instances/
[15:27:24] [Thread-6/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\Malte Illigasch\curseforge\minecraft\Instances
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[15:27:24] [Thread-6/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.filesystem.BrowserFileSystem.openFile(BrowserFileSystem.kt:128)
[15:27:24] [Thread-7/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/Malte Illigasch/curseforge/minecraft/Instances/
[15:27:24] [Thread-7/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\Malte Illigasch\curseforge\minecraft\Instances
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[15:27:24] [Thread-7/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.filesystem.BrowserFileSystem.openFile(BrowserFileSystem.kt:128)
[15:27:25] [Render thread/ERROR]: [MainFrame 1 (file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html)]: Failed to load file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html, 0(file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html)
[15:27:25] [Render thread/INFO]: [MainFrame 1 ()]: The view finished loading
[15:27:27] [IO-Worker-4/INFO]: Successfully connected to LiquidChat!
[15:27:27] [IO-Worker-4/INFO]: Requesting to login into Mojang...
[15:27:32] [Render thread/ERROR]: [MainFrame 3 (file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\splashscreen\index.html)]: Failed to load file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\splashscreen\index.html, 0(file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\splashscreen\index.html)
[15:27:32] [Render thread/INFO]: [MainFrame 3 ()]: The view finished loading
[15:27:32] [Render thread/ERROR]: [MainFrame 5 (file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html)]: Failed to load file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html, 0(file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html)
[15:27:32] [Render thread/INFO]: [MainFrame 5 ()]: The view finished loading
[15:27:38] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Lautsprecher (Synaptics SmartAudio HD)
[15:27:38] [Render thread/INFO]: Sound engine started
[15:27:38] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:27:39] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:27:39] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:27:39] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:27:39] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:27:39] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:27:39] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:27:48] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:27:48] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:27:48] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:28:40] [Thread-9/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/Malte Illigasch/curseforge/minecraft/Instances/
[15:28:40] [Thread-9/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\Malte Illigasch\curseforge\minecraft\Instances
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[15:28:40] [Thread-9/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.filesystem.BrowserFileSystem.openFile(BrowserFileSystem.kt:128)
[15:28:40] [Render thread/ERROR]: [MainFrame 5 (file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html)]: Failed to load file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html, 0(file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\title\index.html)
[15:28:40] [Render thread/INFO]: [MainFrame 5 ()]: The view finished loading
[15:28:40] [Thread-10/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/Malte Illigasch/curseforge/minecraft/Instances/
[15:28:40] [Thread-10/INFO]: [STDERR]: java.nio.file.AccessDeniedException: C:\Users\Malte Illigasch\curseforge\minecraft\Instances
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[15:28:40] [Thread-10/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.filesystem.BrowserFileSystem.openFile(BrowserFileSystem.kt:128)
[15:28:40] [Render thread/ERROR]: [MainFrame 1 (file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html)]: Failed to load file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html, 0(file:///C:/Users/Malte%20Illigasch/curseforge/minecraft/Instances/#Liquidbounce\LiquidBounce\themes\default\hud\index.html)
[15:28:40] [Render thread/INFO]: [MainFrame 1 ()]: The view finished loading
```

### Screenshots

![image](https://user-images.githubusercontent.com/96497717/216997825-2d66e8ee-1d50-496b-a108-2e091ac98dbd.png)

**Comment by 1zun4secondary** [comment]
It is due to your file path. You stored the client inside a folder which has # in it, which seems to cause the path not pointing to the required files.

Please move the client out of this folder, do not call it #liquidbounce.

**Comment by MJMALTE32** [comment]
thanks it worked, but it would be nice to name it #liquidbounce bc i name all the instances i often use "#Name"

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
