### ISSUE TITLE
[BUG] Natives not being loaded correctly

### ISSUE THREAD

**Issue by NCPUser** [CCBlueX/LiquidBounce#913]
### LiquidBounce Build/Version

nextgen

### Operating System

Windows 7

### Minecraft Version

1.18.2

### Describe the bug

Crashed Minecraft 1.18.2

### Steps to reproduce

Crash

### Client Log

```shell
[13:46:05] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.14
[13:46:05] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[13:46:06] [main/INFO]: Loading 62 mods:
	- fabric-api 0.67.1+1.18.2
	- fabric-api-base 0.4.5+64b7c69360 via fabric-api
	- fabric-api-lookup-api-v1 1.6.3+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.10+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.9+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.24+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.2+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.2+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.3+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.21+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.9+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.20+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.21+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.1+a6f01b2660 via fabric-api
	- fabric-item-groups-v0 0.3.15+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-language-kotlin 1.9.1+kotlin.1.8.10
	- fabric-lifecycle-events-v1 2.1.1+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.1+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.3+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.5+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.7+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.24+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.11+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.4+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.13+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.12+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.16+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.6+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.14+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.8+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.11+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.3+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.13+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.4+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.14
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.18.2
	- org_jetbrains_kotlin_kotlin-reflect 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.19.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
[13:46:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/H:/mi/test/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:46:06] [main/INFO]: Compatibility level set to JAVA_16
[13:46:06] [main/INFO]: Compatibility level set to JAVA_17
[13:46:07] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[13:46:25] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=<null>]
[13:46:25] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[13:46:25] [Render thread/INFO]: Setting user: Bobux5
[13:46:27] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[13:46:29] [Render thread/ERROR]: Failed to load options
java.lang.NumberFormatException: For input string: "-98:SHIFT"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at net.minecraft.class_1201.method_5122(class_1201.java:162) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_1201.method_28236(class_1201.java:183) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_1201.method_28235(class_1201.java:160) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.Typed.lambda$updateCap$9(Typed.java:164) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.util.Pair$Instance.traverse(Pair.java:90) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.optics.profunctors.TraversalP$1.lambda$wander$0(TraversalP.java:50) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.Typed.updateCap(Typed.java:164) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.Typed.update(Typed.java:138) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.Typed.update(Typed.java:133) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_1201.method_5121(class_1201.java:159) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.DataFix.lambda$null$3(DataFix.java:86) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.types.Type.capWrite(Type.java:167) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.types.Type.lambda$readAndWrite$9(Type.java:159) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.types.Type.readAndWrite(Type.java:158) ~[datafixerupper-4.1.27.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_2512.method_10693(class_2512.java:488) ~[client-intermediary.jar:?]
	at net.minecraft.class_2512.method_10688(class_2512.java:484) ~[client-intermediary.jar:?]
	at net.minecraft.class_315.method_1626(class_315.java:506) ~[client-intermediary.jar:?]
	at net.minecraft.class_315.method_1636(class_315.java:376) [client-intermediary.jar:?]
	at net.minecraft.class_315.<init>(class_315.java:236) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:454) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
[13:46:30] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[13:46:39] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:46:40] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[13:46:48] [Render thread/INFO]: Successfully extracted default theme
[13:46:48] [Render thread/INFO]: Loading heads...
[13:46:50] [Render thread/INFO]: Successfully loaded 956 heads from the database
[13:46:53] [Render thread/INFO]: Found out OpenGL version to be 3.2.0. Using backend for OpenGL 3.3+ (VAOs, VBOs, Instancing, Shaders)
[13:46:53] [Render thread/INFO]: Loading ultralight...
[13:46:53] [Render thread/INFO]: Checking resources...
[13:46:53] [Render thread/INFO]: Loading ultralight natives
[13:46:53] [Render thread/INFO]: Native path: H:\mi\test\LiquidBounce\ultralight\bin
[13:46:53] [Render thread/ERROR]: Unable to load client.
java.lang.UnsatisfiedLinkError: H:\mi\test\LiquidBounce\ultralight\bin\gstreamer-full-1.0.dll: Can't find dependent libraries
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1953) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:144) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:70) ~[liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:105) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:70) [liquidbounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:108) [liquidbounce.jar:?]
	at net.minecraft.class_310.handler$zjn000$startClient(class_310.java:6526) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:617) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
```

### Screenshots

![image](https://user-images.githubusercontent.com/86876065/219344868-ec1a40ea-8dcb-4009-8032-fc5d9cbf377a.png)
Mods

**Comment by 1zun4secondary** [comment]
Please try deleting your H:\mi\test\LiquidBounce\ultralight\ folder and try again.

**Comment by 66hh** [comment]
This seems to be caused by gstreamer referencing a DLL that does not exist in win7
![NXLTVSSK5R1 W` 4H4K~XM5](https://github.com/CCBlueX/LiquidBounce/assets/49398720/df7106d9-0c74-44a0-bcce-c3ac34d31f68)
![Y3)I6BLWE6J{B8XYVD27N9S](https://github.com/CCBlueX/LiquidBounce/assets/49398720/e64bdd49-1d38-48da-9db3-f35b8656ede4)

**Comment by 66hh** [comment]
You may need to rebuild gstreamer(https://github.com/ultralight-ux/GStreamer) using the win7sdk to fix this error

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidBounce/commit/a83861f482a2aa3300d378a4f2a82c8daed5cd16
