### ISSUE TITLE
Liquid not running with feather client [BUG]

### ISSUE THREAD

**Issue by Waffle-s** [CCBlueX/LiquidBounce#924]
### LiquidBounce Build/Version

b76-71c7b4a

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

The title says it. I can't run lb with feather. It just crashes. I've tried disabling other mods and stuff like that, and in conclusion, lb is causing it. "Feather crashed or failed to start fully, please try to check added mods for incompatibility. Feather already includes a large set of mods itself." Idk if it's just me but help is very much appreciated :D

### Steps to reproduce

Try running latest ver of lb with feather.

### Client Log

```shell
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:482)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_332, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 118582952 bytes (113 MB) / 469762048 bytes (448 MB) up to 5804916736 bytes (5536 MB)
	JVM Flags: 8 total; -Xmx5525M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre2 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCH	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCH	feather{1.0.0-SNAPSHOT} [Feather Client] (feather-1.8.9-1.0.0-SNAPSHOT.jar) 
	UCH	featheropt{1.0.0-SNAPSHOT} [FeatherOpt] (FeatherOpt-1.0.0-SNAPSHOT.temp.jar) 
	UCH	minecraftcapes{11.0.1} [MinecraftCapes Mod] (MinecraftCapes+Forge+1.8.9-11.0.1.temp.jar) 
	Loaded coremods (and transformers): 
MixinLoader (liquidbounce.temp.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
FeatherOpt (FeatherOpt-1.0.0-SNAPSHOT.temp.jar)
  net.digitalingot.featheropt.FeatherOptAccessTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.1070' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.8.9-feather
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 30.0.101.1070, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Forge'
	Type: Client (map_client.txt)
	Resource Packs: !     �3azura �8[�f16x�8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre2
	OptiFine Build: 20211101-204933
	Render Distance Chunks: 9
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.101.1070
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8
[16:00:54] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\thele\AppData\Roaming\.minecraft\crash-reports\crash-2023-02-26_16.00.53-client.txt
error: AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by 1zun4secondary** [comment]
It is unlikely to be fixed. Especially mods which change so much on the client are unlikely to be supported.
