### ISSUE TITLE
[BUG]The "Fixes" page has no options.

### ISSUE THREAD

**Issue by guosic** [CCBlueX/LiquidBounce#965]
### LiquidBounce Build/Version

legacy-d494e2a

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

The "Fixes" page has no options.

### Steps to reproduce

Opened the 'Fixes' page and didn't do anything else.

### Client Log

```shell
[14:06:42] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:06:42] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:06:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:06:42] [main/INFO]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading
[14:06:42] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_362, running on Windows 11:amd64:10.0, installed at C:\Users\g1361\AppData\Roaming\CCBlueX\LiquidLauncher\data\runtimes\8\jdk8u362-b09-jre
[14:06:42] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from LiquidBounce.jar
[14:06:42] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:06:42] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:06:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/g1361/AppData/Roaming/CCBlueX/LiquidLauncher/data/gameDir/legacy/mods/LiquidBounce.jar Service=LaunchWrapper Env=CLIENT
[14:06:42] [main/DEBUG]: Instantiating coremod class MixinLoader
[14:06:42] [main/WARN]: The coremod net.ccbluex.liquidbounce.injection.forge.MixinLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:06:42] [main/INFO]: [net.ccbluex.liquidbounce.injection.forge.MixinLoader:<init>:20]: [LiquidBounce] Injecting with IFMLLoadingPlugin.
[14:06:42] [main/INFO]: Compatibility level set to JAVA_8
[14:06:42] [main/ERROR]: Mixin config liquidbounce.forge.mixins.json does not specify "minVersion" property
[14:06:42] [main/DEBUG]: Enqueued coremod MixinLoader
[14:06:42] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:06:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:06:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:06:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:06:42] [main/DEBUG]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
[14:06:42] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[14:06:42] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[14:06:42] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[14:06:42] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[14:06:42] [main/DEBUG]: Injection complete
[14:06:42] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin}
[14:06:42] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[14:06:43] [main/DEBUG]: Read 818 binary patches
[14:06:43] [main/DEBUG]: Loading deobfuscation resource /deobfuscation_data-1.8.9.lzma with 27891 records
[14:06:43] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:06:43] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[14:06:43] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[14:06:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:06:43] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[14:06:43] [main/DEBUG]: Injection complete
[14:06:43] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[14:06:43] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[14:06:43] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[14:06:43] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[14:06:43] [main/ERROR]: Mixin config liquidbounce.forge.mixins.json does not specify "minVersion" property
[14:06:43] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@7bd69e82
[14:06:43] [main/DEBUG]: Injecting coremod MixinLoader {net.ccbluex.liquidbounce.injection.forge.MixinLoader} class transformers
[14:06:43] [main/TRACE]: Registering transformer net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
[14:06:43] [main/TRACE]: Registering transformer net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
[14:06:43] [main/DEBUG]: Injection complete
[14:06:43] [main/DEBUG]: Running coremod plugin for MixinLoader {net.ccbluex.liquidbounce.injection.forge.MixinLoader}
[14:06:43] [main/DEBUG]: Running coremod plugin MixinLoader
[14:06:43] [main/DEBUG]: Coremod plugin class MixinLoader run successfully
[14:06:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:06:43] [main/DEBUG]: Loaded 163 rules from AccessTransformer config file forge_at.cfg
[14:06:43] [main/DEBUG]: Loaded 48 rules from AccessTransformer mod jar file C:\Users\g1361\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\legacy\mods\LiquidBounce.jar!META-INF/liquidbounce_at.cfg

[14:06:43] [main/DEBUG]: Validating minecraft
[14:06:44] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:06:44] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:06:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:06:44] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:06:44] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:06:45] [Client thread/INFO]: Setting user: GrandioseSeahog
[14:06:46] [Client thread/INFO]: LWJGL Version: 2.9.4
[14:06:47] [Client thread/WARN]: =============================================================
[14:06:47] [Client thread/WARN]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[14:06:47] [Client thread/WARN]: Offendor: com/sun/jna/Native.main([Ljava/lang/String;)V
[14:06:47] [Client thread/WARN]: Use FMLCommonHandler.exitJava instead
[14:06:47] [Client thread/WARN]: =============================================================
[14:06:47] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (LiquidBounce.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 23-4-1 下午2:06
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_362, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 758138640 bytes (723 MB) / 1073741824 bytes (1024 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5107M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
MixinLoader (LiquidBounce.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 531.41' Renderer: 'NVIDIA GeForce RTX 3050/PCIe/SSE2'
[14:06:47] [Client thread/INFO]: MinecraftForge v11.15.1.1722 Initialized
[14:06:47] [Client thread/INFO]: Replaced 204 ore recipies
[14:06:47] [Thread-6/ERROR]: [FileManager] Failed to save config file: modules.json.
kotlin.UninitializedPropertyAccessException: lateinit property moduleManager has not been initialized
	at net.ccbluex.liquidbounce.LiquidBounce.getModuleManager(LiquidBounce.kt:72) ~[LiquidBounce.class:?]
	at net.ccbluex.liquidbounce.file.configs.ModulesConfig.saveConfig(ModulesConfig.kt:46) ~[ModulesConfig.class:?]
	at net.ccbluex.liquidbounce.file.FileManager.saveConfig(FileManager.kt:156) [FileManager.class:?]
	at net.ccbluex.liquidbounce.file.FileManager.saveConfig(FileManager.kt:143) [FileManager.class:?]
	at net.ccbluex.liquidbounce.features.module.Module.setKeyBind(Module.kt:33) [Module.class:?]
	at net.ccbluex.liquidbounce.features.module.Module.<init>(Module.kt:52) [Module.class:?]
	at net.ccbluex.liquidbounce.features.module.modules.misc.NameProtect.<init>(NameProtect.kt:18) [NameProtect.class:?]
	at net.ccbluex.liquidbounce.features.module.modules.misc.NameProtect.<clinit>(NameProtect.kt) [NameProtect.class:?]
	at net.minecraft.client.gui.FontRenderer.localvar$renderString$zcb000(FontRenderer.java:1011) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:286) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270) [avn.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414) [SplashProgress$3.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327) [SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
[14:06:47] [Thread-6/ERROR]: [FileManager] Failed to save config file: modules.json.
kotlin.UninitializedPropertyAccessException: lateinit property moduleManager has not been initialized
	at net.ccbluex.liquidbounce.LiquidBounce.getModuleManager(LiquidBounce.kt:72) ~[LiquidBounce.class:?]
	at net.ccbluex.liquidbounce.file.configs.ModulesConfig.saveConfig(ModulesConfig.kt:46) ~[ModulesConfig.class:?]
	at net.ccbluex.liquidbounce.file.FileManager.saveConfig(FileManager.kt:156) [FileManager.class:?]
	at net.ccbluex.liquidbounce.file.FileManager.saveConfig(FileManager.kt:143) [FileManager.class:?]
	at net.ccbluex.liquidbounce.features.module.Module.setArray(Module.kt:40) [Module.class:?]
	at net.ccbluex.liquidbounce.features.module.Module.<init>(Module.kt:53) [Module.class:?]
	at net.ccbluex.liquidbounce.features.module.modules.misc.NameProtect.<init>(NameProtect.kt:18) [NameProtect.class:?]
	at net.ccbluex.liquidbounce.features.module.modules.misc.NameProtect.<clinit>(NameProtect.kt) [NameProtect.class:?]
	at net.minecraft.client.gui.FontRenderer.localvar$renderString$zcb000(FontRenderer.java:1011) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:286) [avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270) [avn.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414) [SplashProgress$3.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327) [SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
[14:06:48] [Thread-6/INFO]: [Shader] Successfully loaded: rainbow_font_shader.frag
[14:06:48] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[14:06:48] [Client thread/INFO]: Searching C:\Users\g1361\AppData\Roaming\CCBlueX\LiquidLauncher\data\gameDir\legacy\mods for mods
[14:06:48] [Client thread/INFO]: Forge Mod Loader has identified 3 mods to load
[14:06:48] [Client thread/INFO]: FML has found a non-mod file LiquidBounce.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[14:06:48] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[14:06:48] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:06:49] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, %234Amaranth 32x.zip
[14:06:49] [Client thread/INFO]: Processing ObjectHolder annotations
[14:06:49] [Client thread/INFO]: Found 384 ObjectHolder annotations
[14:06:49] [Client thread/INFO]: Identifying ItemStackHolder annotations
[14:06:49] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[14:06:49] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[14:06:49] [Client thread/INFO]: Applying holder lookups
[14:06:49] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[14:06:49] [Client thread/INFO]: Holder lookups applied
[14:06:49] [Client thread/INFO]: Injecting itemstacks
[14:06:49] [Client thread/INFO]: Itemstack injection complete
[14:06:49] [Client thread/INFO]: [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[14:06:49] [Client thread/ERROR]: Couldn't initialize twitch stream
[14:06:49] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:06:49] [Thread-8/INFO]: Initializing LWJGL OpenAL
[14:06:49] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:06:49] [Thread-8/INFO]: OpenAL initialized.
[14:06:49] [Sound Library Loader/INFO]: Sound engine started
[14:06:51] [Client thread/INFO]: Max texture size: 16384
[14:06:51] [Client thread/INFO]: Created: 16x16 textures-atlas
[14:06:52] [Client thread/INFO]: Injecting itemstacks
[14:06:52] [Client thread/INFO]: Itemstack injection complete
[14:06:52] [Client thread/INFO]: Forge Mod Loader has successfully loaded 3 mods
[14:06:52] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, %234Amaranth 32x.zip
[14:06:52] [Client thread/INFO]: SoundSystem shutting down...
[14:06:52] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[14:06:52] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:06:52] [Thread-10/INFO]: Initializing LWJGL OpenAL
[14:06:52] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:06:52] [Thread-10/INFO]: OpenAL initialized.
[14:06:53] [Sound Library Loader/INFO]: Sound engine started
[14:06:54] [Client thread/INFO]: Max texture size: 16384
[14:06:54] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[14:06:55] [Client thread/INFO]: Starting LiquidBounce b78 git-d494e2a, by CCBlueX
[14:06:55] [Client thread/INFO]: Loading Fonts.
[14:06:55] [Client thread/INFO]: Loaded Fonts. (764ms)
[14:06:55] [Client thread/INFO]: [ModuleManager] Loading modules...
[14:06:56] [Client thread/INFO]: [ModuleManager] Loaded 147 modules.
[14:06:56] [Client thread/INFO]: [Remapper] Loading srg...
[14:06:56] [Client thread/INFO]: [Remapper] Loaded srg.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: modules.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: values.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: accounts.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: friends.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: xray-blocks.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: shortcuts.json.
[14:06:56] [Client thread/INFO]: [FileManager] Loaded config: clickgui.json.
[14:06:56] [Client thread/INFO]: Loading heads...
[14:06:58] [Client thread/ERROR]: Error while reading heads.
java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_362]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_362]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_362]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_362]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_362]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_362]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_362]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:293) ~[?:1.8.0_362]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_362]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_362]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_362]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_362]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_362]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1046) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1044) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1043) ~[?:1.8.0_362]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_362]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[?:1.8.0_362]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_362]
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.request(HttpUtils.kt:52) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.request$default(HttpUtils.kt:48) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.utils.misc.HttpUtils.get(HttpUtils.kt:64) ~[HttpUtils.class:?]
	at net.ccbluex.liquidbounce.tabs.HeadsTab.loadHeads(HeadsTab.kt:39) [HeadsTab.class:?]
	at net.ccbluex.liquidbounce.tabs.HeadsTab.<init>(HeadsTab.kt:29) [HeadsTab.class:?]
	at net.ccbluex.liquidbounce.LiquidBounce.startClient(LiquidBounce.kt:150) [LiquidBounce.class:?]
	at net.minecraft.client.Minecraft.handler$startGame$zzf000(Minecraft.java:3190) [ave.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:06:58] [Client thread/INFO]: [FileManager] Loaded config: hud.json.
[14:06:59] [Thread-14/ERROR]: Failed to setup Discord RPC.
java.lang.RuntimeException: java.io.FileNotFoundException: \\?\pipe\discord-ipc-0 (系统找不到指定的文件。)
	at com.jagrosh.discordipc.entities.pipe.WindowsPipe.<init>(WindowsPipe.java:45) ~[WindowsPipe.class:?]
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:158) ~[Pipe.class:?]
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67) ~[Pipe.class:?]
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116) ~[IPCClient.class:?]
	at net.ccbluex.liquidbounce.features.special.ClientRichPresence.setup(ClientRichPresence.kt:82) [ClientRichPresence.class:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startClient$1.invoke(LiquidBounce.kt:167) [LiquidBounce$startClient$1.class:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startClient$1.invoke(LiquidBounce.kt:165) [LiquidBounce$startClient$1.class:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [ThreadsKt$thread$thread$1.class:?]
Caused by: java.io.FileNotFoundException: \\?\pipe\discord-ipc-0 (系统找不到指定的文件。)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_362]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_362]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_362]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124) ~[?:1.8.0_362]
	at com.jagrosh.discordipc.entities.pipe.WindowsPipe.<init>(WindowsPipe.java:43) ~[WindowsPipe.class:?]
	... 7 more
[14:07:01] [UpdateCarriersTask/ERROR]: Failed to refresh cape carriers due to error.
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_362]
	at net.ccbluex.liquidbounce.cape.CapeService$refreshCapeCarriers$1.invoke(CapeService.kt:85) [CapeService$refreshCapeCarriers$1.class:?]
	at net.ccbluex.liquidbounce.cape.CapeService$refreshCapeCarriers$1.invoke(CapeService.kt:70) [CapeService$refreshCapeCarriers$1.class:?]
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [ThreadsKt$thread$thread$1.class:?]
[14:07:01] [Client thread/INFO]: [Shader] Successfully loaded: background.frag
[14:07:12] [Netty Client IO #1/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:07:12] [Netty Client IO #0/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:07:12] [Netty Client IO #2/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:07:13] [Netty Client IO #7/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:07:14] [Client thread/INFO]: [FileManager] Saved config: values.json.
[14:07:15] [Client thread/INFO]: Stopping!
[14:07:15] [Client thread/INFO]: SoundSystem shutting down...
[14:07:16] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
```

### Screenshots

![屏幕截图 2023-04-01 140844](https://user-images.githubusercontent.com/101028480/229269052-bf6a73db-bb74-47cd-a037-cce750cdc4e2.png)

**Comment by CzechHek** [comment]
My bad, will fix the fixes in next pull request.
