### ISSUE TITLE
theAltening not working

### ISSUE THREAD

**Issue by notKnownn** [CCBlueX/LiquidBounce#968]
### LiquidBounce Build/Version

b77

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

When I enter the token from thealtening it says: Failed to login: Cannot contact authentication server.

I already checked internet connection, restarted MC, reinstalled liquidbounce...

![imagen](https://user-images.githubusercontent.com/118249487/229504215-0c1ffaa6-dadd-45ab-8042-eccf3950f199.png)
I removed the token before taking the screenshot (because I don't know if I can show it or not, idk)

### Steps to reproduce

Go to altmanager
theAltening
check it

### Client Log

```shell
[13:57:49] [Client thread/INFO]: Successfully loaded 194 cape carriers.
[13:57:54] [Netty Client IO #1/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[14:00:03] [Thread-18/INFO]: Logging in with username & password
[14:00:18] [Thread-18/ERROR]: Failed to login.
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:71) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logInWithPassword(YggdrasilUserAuthentication.java:74) ~[YggdrasilUserAuthentication.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logIn(YggdrasilUserAuthentication.java:57) ~[YggdrasilUserAuthentication.class:?]
	at net.ccbluex.liquidbounce.ui.client.altmanager.menus.altgenerator.GuiTheAltening.actionPerformed$lambda-3(GuiTheAltening.kt:188) ~[GuiTheAltening.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_352]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_352]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_352]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_352]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:743) ~[?:1.8.0_352]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1595) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[?:1.8.0_352]
	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:83) ~[HttpAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54) ~[YggdrasilAuthenticationService.class:?]
	... 4 more
[14:01:47] [Thread-19/INFO]: Logging in with username & password
[14:02:02] [Thread-19/ERROR]: Failed to login.
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:71) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logInWithPassword(YggdrasilUserAuthentication.java:74) ~[YggdrasilUserAuthentication.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.logIn(YggdrasilUserAuthentication.java:57) ~[YggdrasilUserAuthentication.class:?]
	at net.ccbluex.liquidbounce.ui.client.altmanager.menus.altgenerator.GuiTheAltening.actionPerformed$lambda-3(GuiTheAltening.kt:188) ~[GuiTheAltening.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_352]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_352]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_352]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_352]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_352]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:743) ~[?:1.8.0_352]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1595) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784) ~[?:1.8.0_352]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[?:1.8.0_352]
	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:83) ~[HttpAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54) ~[YggdrasilAuthenticationService.class:?]
	... 4 more
```

**Comment by CzechHek** [comment]
I suppose that the api got changed, since you can't login with mojang alts anymore... How does even altening work rn?

**Comment by 1zun4secondary** [comment]
![grafik](https://user-images.githubusercontent.com/69533520/230728642-1a1fa259-79bf-4697-b6d6-0794ece69ffd.png)

Still works for me.
