### ISSUE TITLE
[BUG] Exception while opening theme

### ISSUE THREAD

**Issue by notaLonelyDay** [CCBlueX/LiquidBounce#991]
### LiquidBounce Build/Version

bbbd95cb

### Operating System

Windows 10

### Minecraft Version

1.19.4

### Describe the bug

Building LB from sources, when opening minecraft, freezes on start screen

### Steps to reproduce

- Build using `./gradlew build`
- Took jar from `build/libs`

### Client Log

```shell
[19:45:31] [Thread-55/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/user/Desktop/prismlauncher/instances/Liquid bounce bbbd95cb/.minecraft/LiquidBounce/themes/default/title/build/bundle.css
[19:45:31] [Thread-55/INFO]: [STDERR]: java.nio.file.NoSuchFileException: C:\Users\user\Desktop\prismlauncher\instances\Liquid bounce bbbd95cb\.minecraft\LiquidBounce\themes\default\title\build\bundle.css
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[19:45:31] [Thread-55/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
[19:45:31] [Thread-56/ERROR]: [ERROR/FileSystem] Exception while opening C:/Users/user/Desktop/prismlauncher/instances/Liquid bounce bbbd95cb/.minecraft/LiquidBounce/themes/default/title/build/bundle.js
[19:45:31] [Thread-56/INFO]: [STDERR]: java.nio.file.NoSuchFileException: C:\Users\user\Desktop\prismlauncher\instances\Liquid bounce bbbd95cb\.minecraft\LiquidBounce\themes\default\title\build\bundle.js
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:121)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
[19:45:31] [Thread-56/INFO]: [STDERR]: 	at net.ccbluex.liquidbounce.base.ultralight.impl.BrowserFileSystem.openFile(BrowserFileSystem.kt:132)
```

### Screenshots

![image](https://user-images.githubusercontent.com/33029221/232106855-6c7c7961-3d65-451a-9a11-356a02c06a43.png)

**Comment by 1zun4secondary** [comment]
You have not successfully run the building process of the themes. You need to have npm and python installed and make sure :makeTheme is working.

**Comment by notaLonelyDay** [comment]
Maybe we should add some requirements or/and instructions for build to readme.md??

**Comment by notaLonelyDay** [comment]
> You have not successfully run the building process of the themes. You need to have npm and python installed and make sure :makeTheme is working.


Maybe we should add some requirements or/and instructions for build to readme.md??
